### ISSUE TITLE
Update the testing docs

### ISSUE THREAD

**Issue by RohitRox** [phstc/shoryuken#100]
In the testing section (https://github.com/phstc/shoryuken/wiki/Testing)
AWS::SQS::ReceivedMessage doesn't work with latest aws-sdk-core (~> 2.0.21) because it has been removed. Please update new guides for testing.

**Comment by phstc** [comment]
Great call. Done :beers:

**Comment by RohitRox** [comment]
That was fast! :+1: :beer: Thanks.
