### ISSUE TITLE
Set auto_visibility_timeout for ActiveJob wrapper

### ISSUE THREAD

**Issue by gshutler** [phstc/shoryuken#103]
I'm looking at using Shoryuken as part of switching to SQS but I'm interested in using it via ActiveJob so things can be run locally more easily.

I was wondering if there was a reason the [ActiveJob wrapper](https://github.com/phstc/shoryuken/blob/fcaf6f694aa9d92ee9082aed23b2a1c86dbfc5f0/lib/shoryuken/extensions/active_job_adapter.rb#L62) doesn't set [auto_visibility_timeout](https://github.com/phstc/shoryuken/wiki/Worker-options#auto_visibility_timeout) to `true` as it seems like it would be a reasonable default for the wrapper.

In case some context helps, we'll probably have 3 queues (ignoring DLQs) for high, medium, and low priority jobs. Tasks within those queues take anything from sub-second to 1-2 minutes to process therefore a blanket timeout (which we'll have to have if using ActiveJob unless I've missed something) will always be a compromise. Having `auto_visibility_timeout` set and a timeout on the queue of ~30 seconds feels like it would be the best compromise for our situation and I can't think of any significant downsides for other ActiveJob users in having `auto_visibility_timeout` set.

**Comment by gshutler** [comment]
From following the source code I think I've found that it is possible to configure this with an initializer along the lines of:

```ruby
Shoryuken.configure_server do |config|
  config. default_worker_options['auto_visibility_timeout'] = true
end
```

Does that sound right?

**Comment by phstc** [comment]
> I was wondering if there was a reason the ActiveJob wrapper doesn't set auto_visibility_timeout to true as it seems like it would be a reasonable default for the wrapper.

We don't do that by default just to keep Shoryuken as transparent as possible to SQS. Auto visibility timeout isn't a SQS feature, it's a feature implemented by Shoryuken only.

> Shoryuken.configure_server do |config|
>   config.default_worker_options['auto_visibility_timeout'] = true
> end

This will work :+1: 

But I strongly recommend you to set higher visibilitiy timeouts in your queues. If your worker can take 1 minute AVG to process, set the visibility timeout to 5 or 10 minutes. In most cases it's better to have the message taking longer to be re-processed in case of failures than to be processed twice or more.

wdyt?

**Comment by gshutler** [comment]
Yeah, I understand where you're coming from.

In my case it's the mix of processing times that's a problem. For many of the tasks that are sub-second it isn't desirable to wait potentially 5 minutes for them to be reattempted, but that would be fine for the tasks that can take 1-2 minutes.

I perhaps need to think about separating those into separate queues, utilising `ExponentialBackoffRetry` through `default_worker_options`, or perhaps creating a custom middleware that works in a similar way to that.

Thanks for the prompt response.

**Comment by phstc** [comment]
:smile: 

My advice when using SQS is to create queues per jobs (unless you have a ton of them) instead of super generic ones: high, medium and low. At least as granular as possible (doable). It helps with prioritization, troubleshooting, specific config etc.

> For many of the tasks that are sub-second it isn't desirable to wait potentially 5 minutes for them to be reattempted

If they fail you can update their `visiblity_timeout` to something more desirable, letting only the others to use the default `visibility_timeout`. But again, I recommend to create more specific queues.
