### ISSUE TITLE
shoryuken_options queue and queues option in config file

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [phstc/shoryuken#107]
I'm not sure what's exactly the difference between these two things. Currently, I would like to fetch messages from two different queues in a single worker, so I added both queues to the configuration file.

Is it possible to do the same through the shoryuken_options ?

If not, is ok if I call shoryuken options only with auto_delete, like: `shoryuken_options auto_delete: false` ?

Thanks a lot, couldn't find any information about this in the documentation

**Comment by phstc** [comment]
Hi @Fire-Dragon-DoL 

I'm not sure if I understood your question. Do you want a single worker class, consuming message from two different queues? If so, you can probably do that by hacking the [shoryuken_class](https://github.com/phstc/shoryuken/blob/af126a190a161aea77c9e30d1996f0796e5135d1/lib/shoryuken/default_worker_registry.rb#L17-L19). But I would not recommend that.

Maybe you could have two worker classes and one inheriting from the other.

```ruby
class Worker1
  include Shoryuken::Worker

  shoryuken_options queue: 'my_queue1'

  def perform(sqs_msg, body)
    # ...
  end
end

class Worker2 < Worker1
  shoryuken_options queue: 'my_queue2'
end
```

**Comment by phstc** [comment]
> shoryuken_options queue and queues option in config file

Might help too:

- [Shoryuken options](https://github.com/phstc/shoryuken/wiki/Shoryuken-options)
- [Worker options](https://github.com/phstc/shoryuken/wiki/Worker-options)

**Comment by Fire-Dragon-DoL** [comment]
I read the documentation quite thorughly, "A single Shoryuken process can handle multiple queues"

I'm not sure what does it mean so, I thought it would pick by itself messages from two queues (not two messages at same time, one message but it will prioritize a queue over another, will still pick messages from both)

Otherwise, can you explain a bit more what's the purpose of the `queues` key in `shoryuken.yml`?

**Comment by phstc** [comment]
> Otherwise, can you explain a bit more what's the purpose of the queues key in shoryuken.yml?

The `queues` are the queue names in AWS SQS that Shoryuken will poll messages.

**Comment by phstc** [comment]
A single process means: if you run `shoryuken` it will be a single process, but even being a single process, it can consume messages from multiple queues defined in the `shoryuken.yml`.

**Comment by Fire-Dragon-DoL** [comment]
@phstc great, thanks. Last point, how this queue relates to `shoryuken_options queue:` key? (the queue key).

If I don't specify the `queue` key, will it use shoryuken.yml `queues` ? If that's the case, it's perfectly fine

**Comment by phstc** [comment]
Hey @Fire-Dragon-DoL 

The `queues` in the `shoryuken.yml` tells Shoryuken which queues should be polled in AWS SQS, the `queue` in the `shoryuken_options` tells Shoryuken which class (worker) should be used to consume messages from a given queue.

So on one config you define the `queues` that needs to be polled, on the other you associate a worker with a `queue`.


The config below tells Shoryuken to poll messages from `queue1` and `queue2`.
```yml
queues:
  - [queue1, 1]
  - [queue2, 1]
```

The workers below [register themselves](https://github.com/phstc/shoryuken/blob/fcaf6f694aa9d92ee9082aed23b2a1c86dbfc5f0/lib/shoryuken/worker.rb#L49) to consume messages from `queue1` and `queue2`.

```ruby
class Worker1
  include Shoryuken::Worker

  shoryuken_options queue: 'queue1'

  def perform(sqs_msg, body); end
end

class Worker2
  include Shoryuken::Worker

  shoryuken_options queue: 'queue2'

  def perform(sqs_msg, body); end
end
```

**Comment by Fire-Dragon-DoL** [comment]
Thank @phstc now it's clear. One last question, if in the file I require I have two worker classes, will shoryuken start using both? O suppose yes by your example

**Comment by phstc** [comment]
@Fire-Dragon-DoL np

> if in the file I require I have two worker classes, will shoryuken start using both?

Correct. But Shoryuken supports only one worker per queue, you can't define multiple workers per queue.

Did you try to play with Shoryuken? I think testing it locally will help you to understand how it works better :wink:

**Comment by Fire-Dragon-DoL** [comment]
@phstc perfect, it's ok I needed 1 worker for 2 queues, I can definitely use 2 workers for 2 queues (1 for each), as long as shoryuken prioritize one over the other, it's still doing what I want.

I tried running shoryuken, it turns on the process and wait for messages, but I suppose I'll need to be on a AWS instance to actually send a message through it, right?

I wrote tests for my worker to ensure functionality is correct, but can't really say I found a way to test it manually, so until I hit AWS the result is unknown

**Comment by phstc** [comment]
> I tried running shoryuken, it turns on the process and wait for messages, but I suppose I'll need to be on a AWS instance to actually send a message through it, right?

You can send messages from any host you want as long as you have the AWS credentials in place. It does not need to be AWS.

**Comment by Fire-Dragon-DoL** [comment]
@phstc oh, that's fantastic, ok I'll start playing!
