### ISSUE TITLE
Support multiple queues per worker

### ISSUE THREAD

**Issue by jshthornton** [phstc/shoryuken#110]
Let's say I have 15 queues which need to have the same operations performed on them.
It would be great that instead of having 15 worker classes which all inherit from one base just to be able to define that one worker can manage multiple queues.

Now I know you are thinking why not put everything in one queue? Because other software might want to manage each queue independently, also allows for tighter IAM security, and we are also able to set priorities per queue.

**Comment by jshthornton** [comment]
Look what animal I have become:
```
require 'shoryuken'

class EmailWorkerBase
	include Shoryuken::Worker

	def perform(sqs_msg, body)
	end
end

email_map = {
	'Test' => 'queue1',
	'Tester' => 'queue2'
}

email_map.each do |key, value|
	klass = Class.new(EmailWorkerBase) do
		shoryuken_options queue: value, auto_delete: true
	end
	Object.const_set key + 'Worker', klass
end
```

**Comment by gshutler** [comment]
Just to be clear, you want to be able to queue the same job onto different queues programmatically?

If so, I think this can be done by sending the message to the queue directly in the [same way Shoryuken does](https://github.com/phstc/shoryuken/blob/3d1e044f60b340724347d324f044370578b9d18f/lib/shoryuken/worker.rb#L8-19):

```ruby
options = {
  message_attributes: {
    'shoryuken_class' => {
      string_value: EmailWorker.to_s,
      data_type: 'String'
    },
  },
  message_body: body,
}

Shoryuken::Client.queues('whatever-queue').send_message(options)
```

The `shoryuken_class` attribute is needed for Shoryuken to know which class to use to process the message on the other side.

If a more general solution is required, I think it's to allow the queue to be overridden by the `options` hash in `#perform_async` like this:

```ruby
def perform_async(body, options = {})
  options ||= {}
  options[:message_attributes] ||= {}
  options[:message_attributes]['shoryuken_class'] = {
    string_value: self.to_s,
    data_type: 'String'
  }

  options[:message_body] = body

  queue_name = options.delete(:queue) || get_shoryuken_options['queue']

  Shoryuken::Client.queues(queue_name).send_message(options)
end
```

What do you think @phstc?

**Comment by jshthornton** [comment]
No that is not the case.
Let's say I have 15 different queue, which each have different jobs, but how I handle them is pretty much the same regardless of which queue they are in.
Think of it like McDonalds. There can be 15 queues one for each cash register, each with their own customer and own request. I am just asking that one worker (cashier) is able to run between each queue and serve each.

**Comment by leemhenson** [comment]
You'll be able to do this by providing your own ```WorkerRegistry``` implementation:

https://github.com/phstc/shoryuken/blob/fcaf6f694aa9d92ee9082aed23b2a1c86dbfc5f0/lib/shoryuken.rb#L33

Shoryuken comes with only a single implementation out of the box: ```DefaultWorkerRegistry```. It obtains the appropriate worker for a given message & queue:

https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/default_worker_registry.rb#L15

**Comment by gshutler** [comment]
Workers are already able to *consume* a task, regardless of what queue it is taken from, so long as it is queued via `perform_async` so that the `shoryuken_class` attribute is set.

What isn't possible right now, apart from how I've described, is *sending* messages to different queues.

**Comment by jshthornton** [comment]
I think it will need a lot more work that just creating a new worker registry right?
I would need to change how the registry is set, how the core takes the workers then adds them to the registry.

**Comment by gshutler** [comment]
@leemhenson, I think `DefaultWorkerRegistry` will provide the functionality @jshthornton is looking for as the [left-hand `constantize` branch](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/default_worker_registry.rb#L21) will resolve the correct class so long as `perform_async` is used.

**Comment by leemhenson** [comment]
Yeah if he's in control of enqueuing the message and can set the message attributes for each one.

**Comment by phstc** [comment]
Great answers :beers: 

@jshthornton if I understood correctly, if you can control the messages enqueuing you can set the `shoryuken_class` as @gshutler said, otherwise you will probably need to create your own worker registry as @leemhenson is suggesting.

It's hard to judge code without a context, but both solution in theory are simple to implement, but they totally depend on your environment.
