### ISSUE TITLE
Sequential Queue Priority  

### ISSUE THREAD

**Issue by geekguy** [phstc/shoryuken#112]
Lets say I have 3 (Q1, Q2, and Q3) queues. 

Is it possible to give priority such that all the messages in Q1 will be processed first, then Q2 and then Q3?

What will happen If I give this config ?
```
concurrency: 1
queues:
  - [high_priority, 3]
  - [default, 2]
  - [low_priority, 1]
```

**Comment by gshutler** [comment]
At the moment, no it isn't. However, I also want the behaviour you've described so I created #106 to make it easier to change how prioritisation works.

With the default prioritisation your configuration effectively creates a queue along the lines of:

 1. `high_priority`
 2. `high_priority`
 3. `high_priority`
 4. `default`
 5. `default`
 6. `low_priority`

So what happens is that `high_priority` is checked 3 times every loop around the queues, `default` is checked twice each time, and `low_priority` is checked once. In reality it's a bit more complicated than that but that's the easiest way to explain it.

**Comment by geekguy** [comment]
Thanks @gshutler. 

For now, If I increase weight for `high_priority`, will it help ?

```
concurrency: 1
queues:
  - [high_priority, 100]
  - [default, 20]
  - [low_priority, 1]
```

Will It have performance impact if the weights are high?

**Comment by gshutler** [comment]
I would be wary of putting them too high, with the figures there you'd have 121 queues to check over. If you had nothing in high priority, in the worst case you'd be checking it 100 times before finding a message in another queue.

As with all these things there's no substitute for measuring and observing, but before I went with a strict prioritisation I was using this which was ok:

```
queues:
  - [high_priority, 4]
  - [default, 2]
  - [low_priority, 1]
```

Also, I'd recommend a concurrency greater than 1 (the default is 25), you'll get a much better throughput by utilising concurrency.

**Comment by geekguy** [comment]
In my case workers are doing cpu intensive jobs. CPU went to 100% when I changed concurrency to 2. So I don't think I can increase concurrency.

Thanks for the information. I 'll try your configuration. 

Closing the issue as your pull request takes care of same thing.
