### ISSUE TITLE
Send Messages in batch

### ISSUE THREAD

**Issue by marc-agas** [phstc/shoryuken#115]
Hi Guys,

I would like to verify if you have provided a method that processes sending of batch messages in sqs. I belive you already have a method in the Queue class, however it seems like you didn't provide an interface to be used by worker. Is there a purpose for not providing in the worker module? 

Thanks,
Marc

**Comment by magnocosta** [comment]
Hi @marc-agas I am implementing this feature, but there is a problem with AWS SDK. he limit in 10 messages by request, because this I dont create pull request.
Att,

**Comment by phstc** [comment]
@marc-agas I added an example on how you can send messages in batch here: https://github.com/phstc/shoryuken/wiki/Sending-a-message

But what @magnocosta said, is correctly, AWS has some limitation with batching, check out their documentation  https://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#send_message_batch-instance_method

**Comment by marc-agas** [comment]
@magnocosta Even if they limit by 10, I think it's still a good idea to support sending of batch messages. We can still leverage on this feature especially if we're going to send approximately millions of request per week. Currently we have a feature that queues millions of messages in sqs on a weekly basis, so we have to really take advantage of this feature. 

@phstc Thanks for these tips.
