### ISSUE TITLE
activejob adapter async enqueue

### ISSUE THREAD

**Issue by trungpham** [phstc/shoryuken#119]
Hi,
Do you know if the ActiveJob adapter send the job to SQS asynchronously? Or is it a blocking SQS call? Thanks.

**Comment by phstc** [comment]
It's a blocking a call. But it's a simpleHTTP Request to SQS, which is usually fast.

**Comment by trungpham** [comment]
Even then, won't the outbound http call add an additional 100ms to the web request? Since you're already using celluloid, why not leverage it to submit the job asynchronously?

**Comment by phstc** [comment]
Indeed, it adds ms to the request. But if we send it in background and it fails for some reason how can we control that? Maybe it's better to do it synchronously and failing the entire request by throwing up the exception than failing in background.

Have a look at https://github.com/brandonhilkert/sucker_punch, maybe you can use it in your app to send the messages asynchronously. wdyt?

**Comment by trungpham** [comment]
Yup. I currently use suckerpunch in combination with activejob to submit the job asynchronously. If there is a failure in submitting the job, then we can log it to a file, then resubmit it later. It's safe to do this because the web request does not care about the output of the job.

**Comment by phstc** [comment]
I see, and it's great idea. But it's something that might be "complex" for most of the users. They need to be aware on how to deal with it, in case it fails.

Maybe it could an option:  `perform_async({ ... }, { block: true })`, but not by default.
