### ISSUE TITLE
Outdated Amazon SDK

### ISSUE THREAD

**Issue by johncblandii** [phstc/shoryuken#123]
I was going to give this a run but ran into an SDK clash. It would be good to see an update to at least `2.1`.

```
  In Gemfile:
    refile-s3 (>= 0) ruby depends on
      aws-sdk (~> 2.0) ruby depends on
        aws-sdk-resources (= 2.1.11) ruby depends on
          aws-sdk-core (= 2.1.11) ruby

    shoryuken (~> 1.0.3) ruby depends on
      aws-sdk-core (~> 2.0.21) ruby
```

**Comment by phstc** [comment]
@johncblandii what's new on 2.1? Could you link the release the notes?

**Comment by johncblandii** [comment]
The API changed. I thought it would be a quick update but it wasn't so I had to table this for productivity purposes.

Have you looked into it? http://docs.aws.amazon.com/sdkforruby/api/index.html

**Comment by RobertoSchneiders** [comment]
I noticed some random `AWS::SQS::Errors::NonExistentQueue` errors, so, I contacted the aws support. They asked me what version of the sdk I was using...

they reply: 
> Ouch. A full point release behind.
> 2.0.21 is from January 2015. Hardly ancient, but it was also not a stable release. The first stable release in the .0.2X was 2.0.22
> I've found many reports of the issue but most of these ended up being issues with referencing a deleted queue

So, I think it is a good idea update the sdk.

**Comment by phstc** [comment]
@RobertoSchneiders I can try to play with @johncblandii on his PR #124. 

We tried to keep in track with the SDK updates, but that was super complicated, because they were removing and adding major stuff, weekly release etc. We ended up having to add classes that were supposed to be in the SDK, but they weren't, for example https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/message.rb

Are you guys having problems with the SDK version on Shoryuken or it's just to keep in track with the sdk updates, which is also fair enough?

**Comment by johncblandii** [comment]
I can't use Shoryuken because I have a gem (Refile) with an updated requirement Shoryuken cannot meet. I'd rather not use background processing or go with Sidekiq than get rid of Refile.

**Comment by phstc** [comment]
@johncblandii gotcha. Tks! How is #124 going? Did you find some issues?

**Comment by johncblandii** [comment]
Yes, the API has changed so it had quite a few problems.

**Comment by trevorrowe** [comment]
Hey everyone. I thought I'd jump in here to help clear up some confusion. The AWS SDK for Ruby is built as two main gems, `aws-sdk-core` and `aws-sdk-resources`. The core gem provides client classes for all AWS services. The resources gem provides resource/object oriented interfaces over the client classes.

* The `aws-sdk-core` gem went stable with version 2.0 back in September of 2014.
* The `aws-sdk` and `aws-sdk-resources` kept the preview flags on until version 2.0.22, which was in January of this year (2015).

**Comment by phstc** [comment]
Hey @trevorrowe, thanks for the heads up. @yoshinorisano update the aws-sdk-core for us :beers: 

> When possible, we will re-introduce them

Alright, so for now we will keep using our own implementation of [queue](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/queue.rb) and [message](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/message.rb).

> You should be able to have a dependency on the SDK for ~> 2 once you've move off the preview release code that was removed.

[Done](https://github.com/phstc/shoryuken/blob/master/shoryuken.gemspec#L27)! Thanks.

**Comment by phstc** [comment]
Shoryuken v2.0.1 is out, running `SDK for ~> 2`

Thank you all :beers:

**Comment by johncblandii** [comment]
Awesome!
