### ISSUE TITLE
Allow workers to be registered at some point at runtime, instead or load time.

### ISSUE THREAD

**Issue by Senjai** [phstc/shoryuken#125]
It's currently difficult to wrap this up in another class due to the fact the configuration needs to be known at load time, instead of run time. It takes a proc to define the queue name, but that doesn't do anything because it still calls the proc at load time.

```ruby
    def shoryuken_options(opts = {})
      @shoryuken_options = get_shoryuken_options.merge(stringify_keys(opts || {}))
      queue = @shoryuken_options['queue']
      if queue.respond_to? :call
        queue = queue.call
        @shoryuken_options['queue'] = queue
      end

      Shoryuken.register_worker(queue, self)
    end
```

Is there a way we could register workers later? Perhaps by keeping track of every class that includes `Shoryuken::Worker` via the included hook, and simply register all of them with their configured queue before booting up the worker. For this specifically, I -must- load configuration before requiring worker classes. I'd like to remove that dependency.

**Comment by phstc** [comment]
hi @Senjai 

Not sure if I understood the problem that's happening. Is Shoryuken failing to start? Did you try to call  `Shoryuken.worker_registry.register_worker` at runtime to dynamically add workers?

**Comment by Senjai** [comment]
No, the problem isn't that it's starting. The problem I have surrounds having to call shoryuken_options at load time which I'm not sure can be circumvented.

```ruby
require 'my_configuration'

class MyWorker
  include Shoryuken::Worker
  shoryuken_options MyConfiguration[:worker_options]
end
```
Will fail (understandably) if you load MyWorker, before MyConfiguration. What I wanted to look for was if there was a way I could delay calling `shoryuken_options` until my entire environment was loaded. This isn't a dealbreaker, just an inquiry.

**Comment by phstc** [comment]
hm... that's a good inquiry. Currently `shoryuken_options` also [registers the workers](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/worker.rb#L49), so it needs to `eval` the options right the way. We can't do something like lazy loading, to only parse it when it's needed. _is thinking out load_.

Maybe what you could do is to load the workers only at the end of `MyConfiguration`:

```ruby
Dir.glob(File.join(core_dir, 'workers/**/*.rb')).each(&method(:require))
```

wdyt?

**Comment by jtoy** [comment]
can shoryuken do hot swapping of the workers? I have workers that are running for weeks at a time and I dont want to wait for that worker to finish while the other workers are just sitting there idle.

**Comment by phstc** [comment]
@jtoy I'm not sure if I could follow your use case. Could you clarify more your question?

**Comment by jtoy** [comment]
I want my workers to check if  there is a newer version of working code,
and if so load that up to run.
I'm using shoryuken for long jobs (days to weeks) and have ~4 workers per
machine.  I currently have to wait for all jobs to finish to update the
code, so even if one job is working, I have to wait until it finishes so i
can restart the workers. I'd like to not have to wait that long.

**Comment by Senjai** [comment]
@jtoy Elixir is better for that use case than ruby is. This is not a shoryuken thing.

**Comment by phstc** [comment]
Hey @jtoy 

> I'm using shoryuken for long jobs (days to weeks) and have ~4 workers per
machine

How are you doing that with SQS, didn't the messages get back to the queue because of the invisibility timeout?

```ruby
class MyWorker
# my_worker.rb
  include Shoryuken::Worker

  shoryuken_options queue: 'my_queue'

  def perform(sqs_msg, body)
    load('other-worker.rb')
    other_worker_perform(sqs_msg, body)
  end
end

# other-worker.rb
def other_worker_perform(sqs_msg, body)
end
```

[load](http://ruby-doc.org/core-2.3.0/Kernel.html#method-i-load) can do what you want, but I agree with @Senjai, Shoryuken/SQS does not seem to be the best solution for super long running workers. Perhaps I didn't get your use case completely.

**Comment by phstc** [comment]
@Senjai did [this](https://github.com/phstc/shoryuken/issues/125#issuecomment-138099666) work for you? Can I close this issue?

**Comment by jtoy** [comment]
I manually delete the job. I set auto_delete to false.
I looked at elixir a bit, it seems like it might be overkill since I wrote
a lot of code in ruby already and I dont know elixir.    I'll try with load
first. I'm using sqs to manage building machine learning models and the
jobs can take a very long time.  In the meantime I am constantly improving
the workers code.
Is there a way I can dynamically change the amount of workers listening on
a queue?

I want to change that number often times also.

**Comment by phstc** [comment]
> Is there a way I can dynamically change the amount of workers listening on

You can try to change the concurrency or queue priorities at runtime level, but you will need to dig into the code to hack, as it isn't something expected in Shoryuken.

**Comment by cavi21** [comment]
@jtoy I know that this is way to late, but something like https://github.com/sschepens/toiler maybe helps you, or I completely missed the point
