### ISSUE TITLE
add a good changelog?

### ISSUE THREAD

**Issue by ivan-kolmychek** [phstc/shoryuken#126]
> Why can’t people just use a git log diff?
>
> Because log diffs are full of noise — by nature. They could not make a suitable change log even in a  hypothetical project run by perfect humans who never make typos, never forget to commit new files, never miss  any part of a refactoring. The purpose of a commit is to document one atomic step in the process by which the code evolves from one state to another. The purpose of a change log is to document the noteworthy differences between these states.

http://keepachangelog.com/

**Comment by phstc** [comment]
@ivan-kolmychek thanks for the reminder :heart:  https://github.com/phstc/shoryuken/issues/94#issuecomment-93851578

I will add an entry on my TODO list for that. Meanwhile, if you can start the initial CHANGELOG and PR, that would be awesome.
