### ISSUE TITLE
Sending from Rails

### ISSUE THREAD

**Issue by waynerobinson** [phstc/shoryuken#129]
Is there some officially expected way to send messages from within a Rails app to be processed by a Shoryuken app somewhere else?

It seems that Shoryuken doesn't get auto-configured when Rails starts with the shoryuken.yml config file and it seems a little strange to create proxy Workers to send `perform_async` messages to.

**Comment by phstc** [comment]
Hi @waynerobinson 

Shoryuken can be integrated with Rails via ActiveJob, check the documentation [here](https://github.com/phstc/shoryuken#rails-integration). Is that what you are asking for?

**Comment by waynerobinson** [comment]
Sorry, not really talking about ActiveJob in particular, but rather if there is a Shoryuken-standard way to queue up messages within Rails for processing by an external Shoryuken process. Or whether we should publish manually with the AWS library and set the correct worker header?

**Comment by phstc** [comment]
Hi @waynerobinson 

You don't need to integrate with ActiveJob (Shoryuken is not Rails dependent), you can just write a [worker](https://github.com/phstc/shoryuken/wiki/Worker-options) and [send messages using it](https://github.com/phstc/shoryuken/wiki/Sending-a-message): `MyWorker.perform_async(...)`.

**Comment by waynerobinson** [comment]
But the worker is in a different microservice app to the one that needs the work done.

**Comment by phstc** [comment]
You want to enqueue messages to be consumed by a Shoryuken process, but not using Shoryuken to enqueue them?

**Comment by waynerobinson** [comment]
Yes, basically. The application that is enqueuing messages is not the same one that has the workers for consuming them.

**Comment by phstc** [comment]
But if it's a Ruby application, why not adding `shoryuken` as a gem in this application. If you add it to your application, it will be a client/producer only.

**Comment by waynerobinson** [comment]
I can, but the worker classes won't be available. Can I just create empty proxies?

**Comment by phstc** [comment]
You can duplicate the workers code, if you can't share them. To share them you could create a third app as a gem with all workers and having app1 and app2 adding it as a gem, so both will share the same workers.

Anyway you can also enqueue messages using aws-sdk directly, Shoryuken does not enforce any special message format. The only exception is if you have more than one worker listening to the same queue, in this case you need to enqueue with [a special header](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/worker.rb#L9-L14).

**Comment by waynerobinson** [comment]
Thank you for your help.

**Comment by phstc** [comment]
do any of that options work for you?

**Comment by waynerobinson** [comment]
I most likely will create empty proxy-classes (as it doesn't need to actually perform anything itself).

**Comment by phstc** [comment]
Awesome. I'm glad it helped you. 

BTW I use a lot that third project approach to share code as a gem. You don't need to publish these projects as official gems, you can reference them as git dependencies in your Gemfile.

`gem 'my-shared-project', github: 'secret/secret'`  - it does not need to be a public repo.

**Comment by tombeynon** [comment]
@waynerobinson This issue might help anyone with a similar problem - it explains how to implement a WorkerRegistry to determine which worker to pass an SQS message to https://github.com/phstc/shoryuken/issues/110
