### ISSUE TITLE
Middleware for handling non Shoryuken messages

### ISSUE THREAD

**Issue by jacksonh** [phstc/shoryuken#132]
Have you considered adding a middleware step that would receive the raw sqs message before `Processor::process` is invoked? (or is there already a mechanism for this?)

I have a scenario where I'd like to intercept and re-route some messages that were added to an SQS queue but don't contain the `shoryuken_class` message attribute.

**Comment by phstc** [comment]
Hi @jacksonh have a look at [Rejecting messages with middleware](https://github.com/phstc/shoryuken/wiki/Middleware#rejecting-messages-with-middleware), is that what you are looking for?
