### ISSUE TITLE
Integration testing

### ISSUE THREAD

**Issue by stevehodgkiss** [phstc/shoryuken#133]
Does Shoryuken have something similar to Sidekiq's `require 'sidekiq/inline'` for testing purposes? What's the recommended approach for integration testing and development environments with Shoryuken (where you don't want to connect to an SQS queue, but rather stub it out)?

**Comment by phstc** [comment]
Hi @stevehodgkiss 

I recommend using doubles to test it locally. Check out [Testing workers with RSpec](https://github.com/phstc/shoryuken/wiki/Testing).

> development environments

For development I use AWS SQS for real. I prefix the queues with `ENV['USER']`, so each dev gets exclusive queues.

**Comment by phstc** [comment]
btw have a look at #131, @nritholtz is using [fake_sqs](https://github.com/iain/fake_sqs).
