### ISSUE TITLE
Is it possible to clear failed jobs in queue?

### ISSUE THREAD

**Issue by rusllonrails** [phstc/shoryuken#134]
Hey guys,

I know how to clear RetrySet of failed jobs in sidekiq:
```
Sidekiq::RetrySet.new.clear
```

Is it possible to clear failed jobs in queue in shoryuken?

Thanks :beers:

**Comment by phstc** [comment]
Hi @rusllonrails 

Are you using [dead letter queues](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/SQSDeadLetterQueue.html) for failed jobs in SQS?

Shoryuken does not provide a explicit mechanism to purge your dead letter queues. But you can do that via AWS console.

**Comment by rusllonrails** [comment]
Hey @phstc 

Thanks for answer. 
Gonna take a look at "SQS Dead Letter Queues".
For time being will clean up failed jobs via AWS console.

:beers:
