### ISSUE TITLE
Data loss when exceptions are raised in Shoryuken while using auto delete.

### ISSUE THREAD

**Issue by Senjai** [phstc/shoryuken#135]
https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/processor.rb#L91-L93 should re raise the error. If you have auto delete turned on, this action simply acts as if it was completed, causing the auto delete to delete the message which causes lost data as your worker was never able to process it. I believe this also can occur in the auto extend helper as well. 

Could we re raise the exception and submit a new release? I don't think we should be catching this.

**Comment by phstc** [comment]
Hi @Senjai 

It's returning `nil` because in theory the worker should fail if the message is nil, it shouldn't be nil in any case other than having issues while parsing. I see your point, but the decision is to make it a responsibility of the worker. wdyt?

**Comment by Senjai** [comment]
I'm not sure I understand. If the body parser raises an exception, the worker should crash hard, just as if the worker itself raised an exception. 

Here, if the body is nil OR if the body is not nil, but fails to be parsed, we simply replace the body with `nil` and pass it along to the worker which is misleading. The message had a body, it just couldn't run the body through the parser because the parser broke in some unexpected way. 

I don't see a way for the worker to feasibly expect and interpret this result, I would expect it to crash. Would you agree or do you see a case where this shouldn't raise?

**Comment by Senjai** [comment]
@phstc ^

**Comment by phstc** [comment]
That was an initial design choice. Having the `body_parser` just as a helper that tries to parse the messages and that returns `nil` in case it fails. Returning `nil` instead of exceptions is very common in the Ruby ecosystem in general. 

But I'm open to change it, could you submit a PR? :heart:

**Comment by Senjai** [comment]
@phstc For sure. Incoming.
