### ISSUE TITLE
Expose SQS message to ActiveJob workers

### ISSUE THREAD

**Issue by bobbrez** [phstc/shoryuken#137]
It would be nice to have access to the SQS message from within an ActiveJob. Specifically I'd like to get the message's ID but exposing the full message may be useful.

It seems like it could be fairly straight forward, but is there a reason this wasn't included initially? Was there a design consideration that I'm missing?

Would it make sense to make a PR for this?

**Comment by phstc** [comment]
@bobbrez I'm sure how can we expose that using `ActiveJob` as it receives a single object and it's expected to be the message itself. If you use Shoryuken without `ActiveJob` the raw message is the first parameter. 

>  Would it make sense to make a PR for this?

Totally as long as it does not break the `ActiveJob` contracts.
