### ISSUE TITLE
Celluloid 0.17

### ISSUE THREAD

**Issue by farski** [phstc/shoryuken#142]
Are there any known issues updating the Celluloid dependency to `~> 0.17`?

**Comment by mrsweaters** [comment]
@farski The only one I see is that shoryuken forces us to use `0.16.0` as celluloid `0.16.1` was pulled.

**Comment by farski** [comment]
@mrsweaters Yeah, I'm wondering if there are any code-related issues with updating that dependency to `0.17`

**Comment by phstc** [comment]
@farski @mrsweaters @vemv I couldn't test Shoryuken with `~> 0.17` yet, could you guys test it? I'm super ok with upgrading it in case it's working. Is there a specific change in Celulloid that you guys are looking for?

**Comment by vemv** [comment]
I've been using my fork of shoryuken (which uses ~> 0.17) since I opened #149, that is 2 weeks ago.

Works absolutely fine! (my app is not in the wild though... only in staging)

The thing I'm looking for is compatibility with sidekiq.

**Comment by farski** [comment]
@phstc Compatibility with other gems is the main reason I want it also.

**Comment by phstc** [comment]
Could you guys submit a PR? :heart:

**Comment by vemv** [comment]
Alright, lock acquired!

**Comment by vemv** [comment]
Done!

**Comment by azisaka** [comment]
Hi, what about this warning https://github.com/celluloid/celluloid/wiki/DEPRECATION-WARNING ?
Will you not upgrade the require statements?

**Comment by phstc** [comment]
Hi @azisaka 

Good catch, I can check that, but I can't give you an ETA. Meanwhile, if you can submit a PR, I will be more than happy to review it 🍻
