### ISSUE TITLE
Shoryuken is inflexible if a there is a requirement to deal with multiple aws accounts.

### ISSUE THREAD

**Issue by Senjai** [phstc/shoryuken#143]
Because `Shoryuken::Client` is not really a class, and behaves more like a module with methods, we cannot easily store a series of clients for separate AWS accounts. 

We can instantiate instances of `Aws::SQS::Client` with specific credentials and regions. Within the current Shoryuken implementation, I do not know how we could easily implement this feature without breaking existing API's. 

I know I can hack around this by removing the memoization here: https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/client.rb#L20 and making it private because nothing uses the sqs method directly, all interfaces go through `Shoryuken::Client.queues`. 

As a temporary fix I would allow the queues method to take an optional client_override hash, that is passed to the sqs method for instantiation of its own client for that queue, as each queue stores its' own client. The catch is that because we still need the queue to be memoized for performance, we have to make sure we pass in the override on the first call to the queues method which is _super_ hacky. I also haven't looked into how this might work on the `Shoryuken::Worker` level just yet either.

I would like to suggest an overhaul here, even if we just made `Client` a normal class, and stored a default client instance in the configuration, with the option to override the client for specific queues. I would be happy to put effort into making that a reality, but it would be a sizeable refactoring, especially if we wanted to support backwards compatible interfaces. If @phstc et al. agree I could work on that front, right now we might just have to work around the current environment with the hacks suggested.

**Comment by farski** [comment]
How would this work with something like Active Job? All each worker class knows about is a queue name, sometimes which doesn't even exactly match the name of the underlying resource queue. There would need to be a change with Active Job to be able to support multiple endpoints for different workers, and that seems unlikely to happen.

**Comment by Senjai** [comment]
@farski in the case with ActiveJob it would just fall back to the default client in the scenario I mentioned (which is configured with `Aws.config` or the environment), while still allowing us to be granular for other use cases. 

In the case where additional queue configuration is required for active job, we could simply add that functionality into the active job adapter or define an active job class that extends `ActiveJob::Base` to add the required functionality. But we should be able to add this to the system without affecting ActiveJob unless I'm missing something.

**Comment by farski** [comment]
@Senjai Hm, okay. I guess I'm wondering what the benefit of retrofitting Shoryuken to do this, which seems like it's uncommon, when just running multiple instances with different configs gets most of the way there. If the answer to enqueueing is still going to be writing custom adapters, doing that now to get things into different queues wouldn't actually be that much work.

**Comment by Senjai** [comment]
@farski We don't use the active job adapter, just regular workers. 

In our use case we have this scenario:

SQS is used as a data store for a message processing and broker system. It is the only data store we use.

One integration, must work from a SQS queue we do not control, hosted by a third party's AWS account. We must take messages off of this queue, possibly manipulate them, and insert them on the appropriate queue within our ecosystem.

This approach is not possible in the current setup. One could argue that we could have a seperate worker instance to listen to the one queue, place the message in a shared datastore like redis or a rdbms, and have another worker which listens to redis or runs a cron on the database to then put those messages on our queue.

We would like to avoid a setup like that and prefer changing the current implementation to work with multiple AWS accounts if that helps define the problem for us :)

**Comment by farski** [comment]
@Senjai I guess I'm not understanding why two separate Shoryuken processors isn't the right option here. 

Each processor just have it's own config with different AWS credentials, which is already supported.

The only minor oddity with the setup you described is the the worker handling jobs coming off the third-party queue need to enqueue things to your first party queue. That should be fairly trivial to do with a standard `Shoryuken::Worker`. Just use explicit `Shoryuken::Queue` instances to enqueue them where you'd like. There's no real need for the different account/queues to all co-exist within the processor just to accomplish that. Is the benefit just eliminating the small overhead of having to run two processors?

**Comment by phstc** [comment]
> Each processor just have it's own config with different AWS credentials, which is already supported.

:+1: If I understood correctly, I would be in favor of two processes using different creds.

@Senjai How about [SNS - SQS](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqssubscribe.html)?

**Comment by Senjai** [comment]
@phstc If a worker for a queue we control needs to send data to a queue we dont control, this is not a thing. The SQS client

**Comment by phstc** [comment]
> The Aws::SQS::Client has to be used directly at the lowest level

I see, :+1: on that ^

**Comment by kwokster10** [comment]
Is there support for multiple AWS accounts yet? I was also wondering if it would be feasible to add `queue_owner_aws_account_id` as another option into [queue.rb](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/queue.rb#L9). With the correct permissions, it would allow the worker to perform jobs on queues owned by different AWS accounts.

**Comment by phstc** [comment]
@kwokster10 multiple accounts per Shoryuken isn't supported. If you need multiple accounts only for enqueuing messages, that might be easier, as you can change the `Aws.config` before enqueuing messages, but to consume messages, that would introduce more work. Another option, if you want multiple accounts, is to have a process and shoryuken.yml per account, so you can keep using Shoryuken as is.

**Comment by kwokster10** [comment]
Unfortunately, I need it for reading from queues. Thanks for the response.

**Comment by phstc** [comment]
@kwokster10 it isn't the Rails process that reads messages, it's a Shoryuken process.

You can start two processes with different `shoryuken.yml` files.

```
bundle exec shoryuken -r worker.rb -C shoryuken-account1.yml
bundle exec shoryuken -r worker.rb -C shoryuken-account2.yml
```

**Comment by kwokster10** [comment]
oh got it, but how does that work if you have a class setup that are executed by Heroku dynos?

**Comment by phstc** [comment]
@kwokster10 Not sure if I could follow you. You can start Shoryuken in Heroku:

```
# Procfile
worker: bundle exec shoryuken ...
```

Is that what you asked for?

**Comment by kwokster10** [comment]
Yep, I don't get to see the setup for our Heroku account so I didn't think about editing the worker directly, but that makes a lot more sense. Thanks for the responses!
