### ISSUE TITLE
Document `Rails.application.config.active_job.queue_adapter = :shoryuken`

### ISSUE THREAD

**Issue by vemv** [phstc/shoryuken#148]
I see in the code that one can use

```
Rails.application.config.active_job.queue_adapter = :shoryuken
```

But such possibility is not mentioned in the wiki!

**Comment by farski** [comment]
@vemv I added a note about this in the wiki https://github.com/phstc/shoryuken/wiki/Rails-Integration-Active-Job

**Comment by vemv** [comment]
Alrighty!
