### ISSUE TITLE
Outdated / overly pessimistic celluloid constraint

### ISSUE THREAD

**Issue by vemv** [phstc/shoryuken#149]
Hi,

I cannot have sidekiq and shoryuken at the same time because of the following line.

`spec.add_dependency 'celluloid', '~> 0.16.0'`

Surely if sidekiq can use 0.17 we are safe to upgrade too!

Additionally, are you aware that with such a constraint (as opposed to just `'~> 0.16'`) you only get bugfixes (and for a limited time), and no non-breaking new features?

I'd change it to either `'~> 0.16'` or `'~> 0.17.2'`.

Cheers - Victor

**Comment by farski** [comment]
See #142. Also wort noting that the newest version of Sidekiq does not have a Celluloid dependency.

**Comment by vemv** [comment]
@phstc could you please give a resolution on this?

Cheers - Victor

**Comment by phstc** [comment]
@vemv I replied you in #142 :smile:

**Comment by phstc** [comment]
duplicated #142
