### ISSUE TITLE
Rescue Aws::SQS::Errors::NonExistentQueue

### ISSUE THREAD

**Issue by vemv** [phstc/shoryuken#150]
Aws::SQS::Errors::NonExistentQueue (which btw looks like it's an automatically generated class - not defined in aws-sdk) errors could be handled, or at the very least re-thrown with a more useful message than the AWS default.

![screen shot 2015-10-29 at 09 02 13](https://cloud.githubusercontent.com/assets/1162994/10813027/081eb93a-7e1c-11e5-804d-a0412dd1b295.png)

I'd do

```ruby
begin
    self.url    = client.get_queue_url(queue_name: name).queue_url
rescue Aws::SQS::Errors::NonExistentQueue => e
  raise StandardError.new "Non existing queue: #{name}. Please create it in advance in SQS."
end
```

Cheers - Victor

**Comment by vemv** [comment]
(I don't know if it'd be correct to create automatically a queue based on the name. Would you do that?)

**Comment by phstc** [comment]
I wouldn't create a queue automatically, maybe the creds supplied don't have permissions for that or the queue was typoed, creating it automatically can cause other issues.

I try to keep Shoryuken as transparent as possible to SQS, so I usually don't mind re-raising AWS exceptions, but I will check #152 carefully.

**Comment by vemv** [comment]
:+1:

**Comment by phstc** [comment]
@vemv wdyt https://github.com/phstc/shoryuken/pull/152#issuecomment-172382789?

**Comment by vemv** [comment]
Closing this issue since it got merged!
