### ISSUE TITLE
Clarify lack of stopping/restarting capabilities

### ISSUE THREAD

**Issue by vemv** [phstc/shoryuken#151]
Hi again!

It looks like shoryuken offers no way to cleanly:

- stop the execution (i.e. gracefully terminate the workers)
- restart the execution (i.e. let the currently-working workers finish, then perform a code reload and give the workers work again)

I consider the former ability critical for many systems - all servers shutdown at some point, and Ruby must respond in a predictable way, avoiding duplicated actions at all costs (my workers sure are idempotent, but as a user receiving e.g. 2 emails instead of 1 sucks)

The latter is less important, but most devs like deploying things by restarting stuff (personally I do not, but I'm minority)

As long hanging fruit, it would be very nice to say in the README what the current capabilities are, and why.

Lastly, if you can tell me in advance that implementing stop/restart is definitely something that shoryuken could support, I'll give it a shot (I have the time!). Not sure if there are any obstacles I should be aware of.

Cheers - Victor

**Comment by andrewyoo** [comment]
In the wiki, you can read the Signals section which talks about the graceful shutdown:
https://github.com/phstc/shoryuken/wiki/Signals

I don't know yet about the restart, but that is something this lazy developer would like to do on deploys.

**Comment by vemv** [comment]
Ahahaha ohhh damn, I completely ommitted the wiki and also the misread lib/shoryuken/cli.rb code - I thought no signals were supported at all.

My bad!

Maybe the link to the wiki in the README could be a little more noticeable. e.g:

> For more information on advanced topics such as shutdown, ______, and ______, please refer to the wiki.

Else it's really easy to skip when quickly scanning the text!

**Comment by phstc** [comment]
@vemv I agree! Could you submit a PR? :heart:

**Comment by phstc** [comment]
@andrewyoo :star:

**Comment by vemv** [comment]
Alright, closing this one and hoping my PR is ok!
