### ISSUE TITLE
Not able to send messages using shoryuken client

### ISSUE THREAD

**Issue by alfredolopez-kantox** [phstc/shoryuken#154]
I have a config file (in `rails_app/config/shoryuken.yml`) that I use for the shoryuken standalone server. I would like to use that same config file (instead of relying on AWS shell environment variables) for when sending messages to an SQS queue from Rails application code.

I got the following error after trying to send a message to a queue:
```
missing region; use :region option or export region name to ENV['AWS_REGION']
/xx/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.35/lib/aws-sdk-core/plugins/regional_endpoint.rb:32:in `after_initialize'
/xx/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.35/lib/seahorse/client/base.rb:84:in `block in after_initialize'
/xx/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.35/lib/seahorse/client/base.rb:83:in `each'
/xx/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.35/lib/seahorse/client/base.rb:83:in `after_initialize'
/xx/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.35/lib/seahorse/client/base.rb:21:in `initialize'
/xx/.rvm/gems/ruby-2.1.1/gems/aws-sdk-core-2.1.35/lib/seahorse/client/base.rb:105:in `new'
/xx/.rvm/gems/ruby-2.1.1/gems/shoryuken-2.0.2/lib/shoryuken/client.rb:20:in `sqs'
...
```
I thought this was due to the configuration file not being loaded so I decided to create the following initializer:

```ruby
# config/initializers/shoryuken.rb
Shoryuken.configure_client do |config|
  config_file = Rails.root.join('config', 'shoryuken.yml')
  config_options = YAML.load(ERB.new(IO.read(config_file)).result).deep_symbolize_keys
  config.options.merge!(config_options)
end
```

However, I was still getting the same issue. I decided then to set the AWS environment variables there instead of using the options hash:

```ruby
Shoryuken.configure_client do |config|
  config_file = Rails.root.join('config', 'shoryuken.yml')
  config_options = YAML.load(ERB.new(IO.read(config_file)).result).deep_symbolize_keys
  # config.options.merge!(config_options)
  # The above doesnt seem to work, I'll populate ENV variables from settings in config yml file.
  ENV['AWS_ACCESS_KEY_ID']     = config_options[:aws][:access_key_id]
  ENV['AWS_SECRET_ACCESS_KEY'] = config_options[:aws][:secret_access_key]
  ENV['AWS_REGION']            = config_options[:aws][:region]
end
```

With this I was able to connect to SQS and send messages. 

My question is, am I doing it right or is there any better / more elegant way for reusing config settings for shoryuken client and server? I could not find much information in the wiki.

Thanks!

**Comment by farski** [comment]
If you look at how the AWS SDK is being configured, https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/environment_loader.rb#L47, what should be happening is that it's sanitizing some values that may be configured in the yaml under `aws`, like `sns_endpoint` and `receive_message`. Then it builds the `Credentials` with the key and secret. Anything left over from the yaml file should get passed into `Aws.config`, so if you have a region in the config file it should get set as the default for the SDK. Without seeing the shoryuken.yml you're using I don't see anything obvious that would make that not work.

**Comment by alfredolopez-kantox** [comment]
I see `EnvironmentLoader.load(options)` is called upon start of the Shoryuken server, inside `Shoryuken::CLI`. However, that doesnt happen when using Shoryuken as client inside Rails code isn't? I think in that case the `config/shoryuken.yml` is not parsed (that's why I had to create the rails initializer).

My `config/shoryuken.yml` looks like:
```
aws:
  access_key_id: ACCESS_KEY
  secret_access_key: SECRET_KEY
  sqs_endpoint: sqs.eu-central-1.amazonaws.com
  region: eu-central-1
  receive_message:
    wait_time_seconds: 10
concurrency: 5
delay: 25      
queues:
  - [default, 1]
```

Maybe there was something I misunderstood since it is the first time I use `shoryuken` (I used `activemessaging` gem before but it has poor support of Amazon SQS).

**Comment by farski** [comment]
Yeah, my bad. I misread your first sentence and got confused. As far as a better or more elegant way of reusing that config, I think environment variables are the answer there. Baking an AWS secret key into the config is very unusual, so parsing that for the client usually isn't a good solution. If you really need to avoid environment variables, what you have is probably as good an option as any.

**Comment by alfredolopez-kantox** [comment]
true, I'll better use environment variables then. Thanks!

**Comment by iurifq** [comment]
I'm experiencing the same problem. However, in my case, I can't set the environment variables because I use distinct access keys for S3 and SQS. Is there any workaround for this?

**Comment by iurifq** [comment]
I could load the credentials successfully. I modified the initializer to look like the following.

```ruby
config_file = if Rails.env.development?
                Rails.root.join('config', 'shoryuken.dev.yml')
              else
                Rails.root.join('config', 'shoryuken.yml')
              end

unless Rails.env.test?
  Shoryuken::EnvironmentLoader.load(config_file: config_file)
  Rails.logger.info "Shoryuken loaded with options #{Shoryuken.options}"
end
```

I have different shoryuken config files for the development environment. Inside config files I load the desired environment variables. I avoid loading it for the test environment as I test the workers separately.
