### ISSUE TITLE
Doesn't seem to pick up Instance Profile credentials

### ISSUE THREAD

**Issue by vemv** [phstc/shoryuken#155]
I deleted these two lines in my  shoryuken.yml:

```
  access_key_id:
  secret_access_key:
```

...because I store no credentials in my EC2s, they're provided by AWS' Instance Profile optional mechanism.

However that causes authentication to fail:

```
2015-11-09T18:02:05Z 1043 TID-owy21ivmg WARN: AWS Queue 'mailers' does not exist
2015-11-09T18:02:05Z 1043 TID-owy21ivmg WARN: AWS Queue 'default' does not exist
```

The queues do exist and used to work, back when I provided access_key_id and secret_access_key.

Probably Shoryuken configures the SQS client in a not-flexible-enough way?

**Comment by farski** [comment]
You're sure `ENV['AWS_ACCESS_KEY_ID']` and `ENV['AWS_SECRET_ACCESS_KEY']` exist, and are correct for an IAM user with access to those particular queues?

**Comment by vemv** [comment]
> You're sure ENV['AWS_ACCESS_KEY_ID'] and ENV['AWS_SECRET_ACCESS_KEY'] exist

They don't have to, that's what Instance Profiles consists of.

I figured out my issue - the IAM role of my machine hadn't had any SQS Policy assigned yet. Now Shoryuken picked it up without hassle!

Closing, sorry for the noise.
