### ISSUE TITLE
Is enqueueing multithreaded?

### ISSUE THREAD

**Issue by vemv** [phstc/shoryuken#158]
> Like many other AWS services, SQS is accessed through HTTP request-response, and a typical SQS request-response takes a bit less than 20ms from EC2. This means that from a single thread you can, on average, issue 50+ API requests / sec.

https://aws.amazon.com/blogs/aws/scaling-with-amazon-sqs/

As of today how many items/sec can Shoryuken enqueue - only ~50, or more?

Aws::SQS::Client uses Seahorse which seems to use a connection pool.

Anyone can confirm?

**Comment by vemv** [comment]
So, I asked here https://github.com/aws/aws-sdk-ruby/issues/1001 and enqueueing with the SDK is not parallel, but the client is thread safe. One client can be shared across threads, and concurrent calls will result in HTTP request parallelism.

Shoryuken already uses celluloid - maybe its thread pools can do the job? https://github.com/celluloid/celluloid/wiki/Pools

**Comment by Senjai** [comment]
If you use workers, yes, it's multi threaded. However because of the GIL on MRI ruby, only one thread will run at any given time, so it's concurrent, but not paralell. IO takes a long time, so another thread will run while a message is getting queued. I was unable to get Shoryuken to work with jruby on an initial pass (which would allow you to have paralell processing).

**Comment by vemv** [comment]
@Senjai you seem to be misguided, I was asking about enqueueing parallelism, not processing (worker) parallelism.

IO can be concurrent and parallel with Ruby threads.

**Comment by Senjai** [comment]
Apologies! as in en queueing multiple items in the same worker? Or using Shoryuken::Client directly?

**Comment by vemv** [comment]
My use case is: whenever I call `MyJob.perform_later`, that enqueueing should use parallel HTTP requests.

Example:

```ruby
clients.each do |client|
  ClientMailer.perform(client).deliver_later
end
```

Here for a `clients` size of 1000, it would to Shoryuken about 1000 * 20ms to enqueue all the items. Parallel enqueueing could divide this amount by e.g. 4.

Another strategy would be to leverage SQS batches but I'm not sure that would be easy to integrate with ActiveJob...

**Comment by Senjai** [comment]
Oh okay, with active job this is your logic right? Wouldn't it be your job to parallel-ize the calls to `ClientMailer.perform(client).deliver_later`?

If you're suggesting that deliver_later not block, I would disagree. It should block until it is successfully enqueued.

Sorry if I don't properly understand. I'm not too familiar with SQS batches, and I don't use the ActiveJob part of Shoryuken, but let me know if you find a better solution.

**Comment by vemv** [comment]
> Oh okay, with active job this is your logic right?

Not necessarily, but yes in my case.

> Wouldn't it be your job to parallel-ize the calls to ClientMailer.perform(client).deliver_later?

I could, but it would be better to have a reusable, safe abstraction.

**Comment by Senjai** [comment]
In that case It would be something like: `ParalellListExecutor.new(clients).process { |client| do_something_with_client(client) }`. 

This is domain code, and I don't see how an abstraction could be performed in Shoryuken, or that it should be. You're just taking a list of things, and doing something to those things, and wish to do them in paralell. This could be within a job or outside of a job, but it's still application specific. I'm sure there are libraries that accomplish the above, though, and it wouldn't be hard to implement. I'm sure you could use a celluloid actor here as well with celluloid futures.

**Comment by vemv** [comment]
Putting an item in a queue is not "domain code", it's a low-level operation. Enqueueing with SQS is 25 times slower than with Redis (http://www.pablocantero.com/blog/2015/03/14/sidekiq-redis-vs-shoryuken-aws-sqs ) so it seems to me that Shroryuken could use threads to compensate.

**Comment by phstc** [comment]
Shoryuken also suports batch sending:

```ruby
# https://github.com/phstc/shoryuken/wiki/Sending-a-message

Shoryuken::Client.queues('my_queue').send_messages(['msg 1', 'msg 2']) # up to 10 messages
```
I see you point about parallelism, but I believe that might be a little bit more complicated, for example if a thread fails, what should it do? 

Maybe if your `ClientMailer.perform` is done via a user interaction and you want to speed it up, you could do it in background: 

```ruby
ClientMailerEnqueuer.perform(clients.map(&:id)).deliver_later
```

wdyt?

**Comment by vemv** [comment]
> Shoryuken also suports batch sending:

I don't think that's an option for me - I'm quite sold on ActiveJob, using Sidekiq in development, 'inline' running in test, etc.

> `ClientMailerEnqueuer.perform(clients.map(&:id))` 

Mailers can only send one email at a time, so that wouldn't work.

> If a thread fails, what should it do?

If one uses a good thread-pool implementation, and only runs thread-safe components (as `Aws::SQS::Client `) from it, things are just as likely to fail in a thread pool than in a single thread, aren't they?

**Comment by vemv** [comment]
(whoops I misread something, so I deleted that specific reply)

**Comment by vemv** [comment]
> ClientMailerEnqueuer
An `Enqueuer` class seems interesting. But maybe Shoryuken could provide that? Consumer projects shouldn't have to worry about keeping thread pools, etc.

How about: shoryuken doesn't make multi-threaded enqueueing the default, **but** it provides an optional `Enqueuer` class? I can imagine it being implemented with very little code (i.e. it wouldn't be a pain to maintain).

It would kind of overlap in goals with batching, but batching has its limitations, both in batch size and ActiveJob compatibility.

**Comment by phstc** [comment]
> How about: shoryuken doesn't make multi-threaded enqueueing the default, but it provides an optional Enqueuer class? I can imagine it being implemented with very little code (i.e. it wouldn't be a pain to maintain).

I would prefer to have it implemented outside Shoryuken, as it would require an internal queue for that, worker and monitoring etc, and also giving a lot of room for unexpected behaviour.

**Comment by vemv** [comment]
No worries, I probably agree. Probably very few people will have a real need for high-performance enqueueing.
