### ISSUE TITLE
Transactional enqueueing?

### ISSUE THREAD

**Issue by vemv** [phstc/shoryuken#159]
I was thinking of implementing the following feature when I have the time, maybe somebody can comment since I haven't seen it in any queue library I know of.

Sometimes one enqueues multiple items, and the process of queueing itself can fail because the items are processed in some way before being enqueued. Example:

```ruby
company.clients.each do |client|
  ClientMailer.perform(client.id).deliver_later
end
```

Here each `.perform` call is subject to failure since rendering an email involves a few things.

So the scenario to avoid is e.g. when the enqueueing for the first 3 `company.clients` have succeeded, but the fourth fails, resulting in an inconsisting emailing. If I retry the job, the first 3 clients will receive duplicated emails.

So what I'd like to have is:

```ruby
Shoryuken.transactionally_enqueue do
  # the enqueueing loop...
end
```

Inside the block, any enqueued items would be retained in-memory, and only if the block completes without failure, the retained messages are passed to SQS.

Sounds like this could be achieved with thread locals. The only disadvantage I can imagine, is that potentially one could run out of memory if too many items are retained.

Thoughts? Anyone has used something similar in production?

**Comment by phstc** [comment]
Hi @vemv

I totally see the use case, but if I understood it correctly, I wouldn't add it to Shoryuken, as I believe we can use standard Ruby for it:

```ruby
if company.clients.all?(&:do_some_processing)
  company.clients.each(&:enqueue)
end

def do_some_processing(client)
 # do something and return true or false if succeed or not respectively
end

def enqueue(client)
  ClientMailer.perform(client.id).deliver_later
end
```

wdyt?

**Comment by vemv** [comment]
@phstc actually sounds good! Maybe just a little tedious to separate the work from the enqueueing, as a user it'd be great to have this abstraction.

I implemented/tested the functionality last night https://github.com/vemv/shoryuken/commit/a4bd480f34a4bb1245815afed0a84eeca46db881 , will be trying it out.

**Comment by phstc** [comment]
The implementation seems interesting, but I'm not sure how reliable it's, for example if the process crashes, will it lose all references that were persisted in memory?

**Comment by vemv** [comment]
Certainly.

I already consider creating e.g. 1000 jobs (for sending 1000 emais) a process subject to failure, so I wrap that in a job (which of course can be retried).

I mean, enqueueing 1000 items directly from a model/controller is an antipattern already, probably lots of folks write job-creating-jobs already.

In short, so far I see no disadvantages, provided the programmer knows what he's doing!
