### ISSUE TITLE
Rake tasks for creating/deleting SQS queues

### ISSUE THREAD

**Issue by elsurudo** [phstc/shoryuken#16]
Since everyone will pretty much need this, I think it's worth adding to shoryuken itself.

I've created these for my own project, but they only handle the config options that I had an immediate use for. This ticket is mainly a reminder for myself to abstract it out and create a PR eventually.

If someone wants to take a stab at it before I can find the time, that is welcome (I can share my current rake tasks).

**Comment by kookster** [comment]
@elsurudo I also have rake tasks for this.
Couple of questions:

I name space queues based on env, is that something others do?
e.g. I prefix all my queue names "developement_" for my dev env.

How about dead letter queues?
Assume I have 3 different regular queues, should the rake tasks create a DLQ for each, or one DLQ for all?

**Comment by farski** [comment]
This doesn't actually work entirely, but it's the direction I took
https://gist.github.com/farski/26e94cf30c5dc2a1a9b1
