### ISSUE TITLE
Process Limits?

### ISSUE THREAD

**Issue by timscott** [phstc/shoryuken#161]
I'm migrating from sidekiq, and I use [sidekiq-limit_fetch](https://github.com/brainopia/sidekiq-limit_fetch) to set process limits. The reason is that certain queues serve jobs that take a lot of memory. I could dial down concurrency, but then jobs with a smaller footprint lose the advantage of higher concurrency.

Is there any thing like this with Shoryokun?

**Comment by vemv** [comment]
Mind to explain your problem a bit more clearly? Exact problem experienced / exact solution expected?

Anyway, I find it likely that this kind of problem can be solved with good ops, instead of with more code.

**Comment by vemv** [comment]
> I could dial down concurrency, but then jobs with a smaller footprint lose the advantage of higher concurrency.

Specifically, I think that you could have separate worker machines depending on the job type to be run.

A mature app can have dozens of different job types - having them mixed up in the same machine calls for problems. They have different business priorities, CPU/Memory/HTTP footprints, etc.

**Comment by phstc** [comment]
> Is there any thing like this with Shoryokun?

@timscott there isn't. You can try to play with `delay`, `concurrency` and queues priorities, but there isn't something similar to `sidekiq-limit_fetch` for Shoryuken.
