### ISSUE TITLE
Two workers with different concurrency

### ISSUE THREAD

**Issue by RajatGoyal** [phstc/shoryuken#162]
```
class Worker1
  include Shoryuken::Worker
  shoryuken_options queue: ->{ "twitter_queue_#{ENV['RAILS_ENV']||'development'}" }, auto_delete: true, body_parser: :json, retry_intervals: [360, 1200, 3600]
```

```
class Worker2
  include Shoryuken::Worker
  shoryuken_options queue: ->{ "search_queue_#{ENV['RAILS_ENV']||'development'}" }, auto_delete: true, body_parser: :json, retry_intervals: [360, 1200, 3600]
```

I want to run ```Worker2``` as single thread because it is a rate limited api and ```Worker1``` as 25 concurrent threads.

my configuration file looks like this:

```
  aws:
    access_key_id:  XXX
    secret_access_key:  XXX
    region:             us-east-1
  concurrency: 25
  delay: 1
  queues:
    - [twitter_queue_development, 10]
    - [search_queue_development, 1]
```

And I start shoryuken like this:

```RAILS_ENV=development bundle exec shoryuken -R```

How can i define different concurrency for different workers?

**Comment by phstc** [comment]
@RajatGoyal there's no way of defining different concurrencies for the same worker using shoryuken. Maybe you could use a single shoryuken process for this specific worker.

```yaml
aws:
  concurrency: 1
  delay: 1
  queues:
    - [search_queue_development, 1]
```

BTW Maybe [batching](https://github.com/phstc/shoryuken/wiki/Worker-options#batch) can help you with your rate limit problem.
