### ISSUE TITLE
license

### ISSUE THREAD

**Issue by ngordon17** [phstc/shoryuken#163]
Just want to say that I think this gem is awesome and I would really love to be able to use this in my new project. Unfortunately, I am not allowed to use gems that are licensed under LGPLv3. 

Any chance you would consider changing the license of this to something such as a standard MIT license?

**Comment by ngordon17** [comment]
ping.

**Comment by phstc** [comment]
Hi @ngordon17 

Unfortunately I can't. Some of the code in Shoryuken was based (and also copied) from Sidekiq, so I need to keep the same [license that Sidekiq uses](https://github.com/mperham/sidekiq/blob/master/LICENSE).
