### ISSUE TITLE
Question with ActiveJob

### ISSUE THREAD

**Issue by kntmrkm** [phstc/shoryuken#170]
Hi.

I read README. so, I know how to set `retry_intervals` like below.

```
class MyWorker
  include Shoryuken::Worker

  shoryuken_options retry_intervals: [10.minutes, 30.minutes, 1.hour, 6.hours, 12.hours]
end
```

But, I don't know when using ActiveJob that where sholud I set options...

Like this?

```
class CommonToJob < ActiveJob::Base
  shoryuken_options queue: 'default', retry_intervals: [360, 1200, 3600] # 5.minutes, 20.minutes and 1.hour
  rescue_from ActiveJob::DeserializationError do |e|
    ExceptionNotifier.notify_exception(e)
  end
end
```

If I want to set default options to all job. Where is it? shoryuken.yml? `config/initializers/shoryuken.rb`?

thanks.

**Comment by phstc** [comment]
Hi @kntmrkm 

I've never tried this and it seems very hacky, but you can try:

```ruby
JobWrapper.shoryuken_options(retry_intervals: [10.minutes, 30.minutes, 1.hour, 6.hours, 12.hours])
```

[JobWrapper](https://github.com/phstc/shoryuken/blob/c65638f1748ad90c35bb2198d43955d6c20a715c/lib/shoryuken/extensions/active_job_adapter.rb#L59) is the worker that `ActiveJob` uses.

**Comment by kntmrkm** [comment]
Thanks @phstc .

I tried with below setting.

`in config/initializers/shoryuken.rb`

```
ActiveJob::QueueAdapters::ShoryukenAdapter::JobWrapper
    .shoryuken_options(retry_intervals: [10.minutes, 30.minutes, 1.hour, 6.hours, 12.hours])
```

And, I invoke `raise` manually.

```
class OneJob < ActiveJob::Base
  queue_as :default

  def perform(something)
    do_ something

    raise
  end
rescue => e
  ExceptionNotifier.notify_exception(e)
  raise e
end
```

so, result is ...

<img width="264" alt="_ _admin_tasca_io 33_" src="https://cloud.githubusercontent.com/assets/2703486/12371179/456785b6-bc6e-11e5-96d3-eff036128f30.png">

I think that it works well with original `retry_intervals`.

If you know more smart setting, tell me. 
Thanks a lot.

**Comment by phstc** [comment]
hi @kntmrkm 

Did that work? Or is it failing? The screenshot is too cut out, I can't see the full error.

**Comment by kntmrkm** [comment]
@phstc

That setting works well. I have wrote `raise` to confirm retry interval.
The error is correct. and setting was correct.

The screenshot say that a job works by setting interval as intended.
There are no problem to accomplish my purpuse.

I just seem that the setting code is ugly.
I expected there are more smart code.

I am sorry my misleading comment.
