### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by andrea-spoldi** [phstc/shoryuken#171]
Hi, 
I have a tool deployed with shoryuken, today it went really bad and started logging this sort of thing : 

2016-01-13T13:42:28Z 489 TID-4p5zg ERROR: Error fetching message: Too many open files - getaddrinfo
2016-01-13T13:42:28Z 489 TID-4p5zg ERROR: /usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize'

I thought it was related to my code, and still can be like that 'cause I have that sort of error also within parts of my worker's code, but that "error fetching message" looks a bit too specific to me

my bundle is using "shoryuken (1.0.2) from git://github.com/phstc/shoryuken.git (at master) " with ruby 2.0.0

Did that happened to others ? what other info do you need ? 

Thanks

A

**Comment by Senjai** [comment]
What is your concurrency

**Comment by andrea-spoldi** [comment]
Hi, 25 (default)

ty

**Comment by Senjai** [comment]
Not sure, given the information provided it's not very possible to guess. I would expect your system is reaching the file descriptor limit. Other applications probably have too many descriptors, or they aren't being closed properly. This isn't a shoryuken issue though, this is a ulimit issue on your box.

**Comment by Senjai** [comment]
See http://unix.stackexchange.com/questions/36841/why-is-number-of-open-files-limited-in-linux
