### ISSUE TITLE
Running Shoryuken without any YAML configs

### ISSUE THREAD

**Issue by julik** [phstc/shoryuken#173]
Is there a way to start Shoryuken from my own code (using `Shoryuken::CLI`) without having to have any yaml files for configuration? I have `SQS_QUEUE_URL` already set in the environment and I won't be using more queues in the future, so I would like to grab that envvar and set is as the queue for Shoryuken to process.

**Comment by phstc** [comment]
Hi @julik 

You can use Shoryuken without the YAML, if you pass all the options when you start it, have a look at [this](https://github.com/phstc/shoryuken#start-shoryuken) to a get list of options. Is that what you want or do you want to start Shoryuken inside another process?

**Comment by julik** [comment]
It is close, but how would I handle submission to the queue? Is there a way to configure the Worker class with just the queue URL and that's it? (because it contains the endpoint by itself AFAIK)

**Comment by phstc** [comment]
@julik not sure if I could follow you. Have you tried something like this `bundle exec shoryuken -r worker.rb -q myqueue`?

**Comment by julik** [comment]
@phstc if I need to submit jobs, this won't necessarily happen from within the worker process. I might need to submit from an external process, from a web handling Rack app for example. Where would the queue configuration come from in that case, if I got no config files? How would Shoryuken know what queue to submit to? For instance, to talk to SQS it is actually sufficient to have the queue URL. The documentation says that you need to supply the queue name and the endpoint URL instead - is that really required? To explain it in a different way, the README says (for a runtime queue configuration for a worker):

    shoryuken_options queue: ->{ "#{ENV['environment']}_default" }

What is "default"? I have an arbitrarily named SQS queue, and I have it's URL and that's pretty much it (is also what `Aws::SQS::Client` accepts for most resource calls). How do I hook this URL into the worker?

**Comment by phstc** [comment]
@julik you can name the queue with the name you want, check [this wiki entry](https://github.com/phstc/shoryuken/wiki/Worker-options). Basically require `shoryuken` in your external process, configure the queue as the example above, make sure that you have AWS credentials available in your env (unless you use IAM permissions) and that's it, it should be able to enqueue messages from your external process.

**Comment by phstc** [comment]
BTW if you want, you can also enqueue messages using [aws-sdk-ruby](https://github.com/aws/aws-sdk-ruby) directly without Shoryuken. 

Shoryuken does not mutate the messages, it enqueues exactly what you send. So you can enqueue the messages from external process, and have a Shoryuken process to listen the messages from the queues you enqueued in.
