### ISSUE TITLE
Bugsnag Integration

### ISSUE THREAD

**Issue by camhine** [phstc/shoryuken#179]
I'm using Bugsnag to track exceptions in a rails app (https://bugsnag.com).

I'd like to be able to send exceptions coming out of a shoryuken worker's perform method to Bugsnag.

At the moment I'm rescuing exceptions as they occur in the perform method, notifying Bugsnag, and re-raising them.

```
class MyWorker
  include Shoryuken::Worker

  shoryuken_options auto_delete: true, body_parser: :json, queue: ->{ "#{ENV['DEFAULT_QUEUE_PREFIX']}_application" }

  def perform(sqs_msg, json_body)
    # code that might raise an exception
  rescue AnException => e
    error = AnotherException.new(sqs_msg.message_id)
    Bugsnag.notify(error)
    raise error
  end
```

Is there a better way to do this?

**Comment by vemv** [comment]
I use shoryuken with ActiveJob (the integration is great!). By using AJ you can leverage `rescue_from`, defined just once in the base ApplicationJob.

**Comment by phstc** [comment]
Hey @camhine 

I believe they way you did is the best one. 

In case you have a ton of workers, and you need that for all of them, maybe you can try implementing a [template method](https://en.wikipedia.org/wiki/Template_method_pattern).

```ruby
class BaseWorker
  include Shoryuken::Worker

  def perform(sqs_msg, json_body)
    _perform(sqs_msg, json_body)
  rescue AnException => e
    error = AnotherException.new(sqs_msg.message_id)
    Bugsnag.notify(error)
    raise error
  end
  
  def _perform(sqs_msg, json_body)
    raise NotImplementedError
  end
end

class MyWorker < BaseWorker
  def _perform(sqs_msg, json_body)
    # code that might raise an exception
  end
end
```

BTW if you do this:

```ruby
rescue AnException => e
  error = AnotherException.new(sqs_msg.message_id)
  Bugsnag.notify(error)
  raise error
end
```

You will lose `e.backtrace` - to keep it, you can try instead:

```ruby
class AnException < StandardError
  def initialize(msg, backtrace = nil)
    set_backtrace(backtrace) if backtrace
    super(msg)
  end
end

rescue AnException => e
  error = AnotherException.new(sqs_msg.message_id, e.backtrace)
  Bugsnag.notify(error)
  raise error
end
```
