### ISSUE TITLE
Concurrent-ruby support

### ISSUE THREAD

**Issue by rainerborene** [phstc/shoryuken#185]
any plans to replace celluloid with concurrent-ruby?

**Comment by phstc** [comment]
Hi @rainerborene 

It seems to be an interesting idea, it was also commented [here](https://github.com/phstc/shoryuken/issues/88#issuecomment-173562649). Unfortunately I can't work on this now, but a pull request would be very appreciated.

**Comment by gwincr11** [comment]
I am interested in using this gem, but I just removed the .16 version of celluloid that you require to get rid of a memory leak. It is a known leaky gem https://github.com/ASoftCo/leaky-gem. 

Can Shoryuken at least be updated to the non-leaky version?

**Comment by phstc** [comment]
> TIL: https://github.com/ASoftCo/leaky-gems

@gwincr11 yay! Changed [here](https://github.com/phstc/shoryuken/blob/feature/185-bump-celluloid-non-leaky-version/shoryuken.gemspec#L28).

@rainerborene @gwincr11 can you guys help with testing the change above? 🙏 

```ruby
gem 'shoryuken', github: 'phstc/shoryuken', branch: 'feature/185-bump-celluloid-non-leaky-version'
```

**Comment by gwincr11** [comment]
Oh nice, thank you! 
I can try to test. I have actually never used this gem before so I have some setup to figure out.

**Comment by geun** [comment]
+1

**Comment by phstc** [comment]
Just a heads up... I'm very excited with the changes in #291 so far. I'm thinking on releasing Shoryuken 3.0.0, with that change. It's basically removing Celluloid, in favor of [a thread pool](https://github.com/phstc/shoryuken/pull/291/files#diff-9fdc6bf30b3f5b4078e1e4d4720765b7R22) and [a heartbeat](https://github.com/phstc/shoryuken/pull/291/files#diff-9fdc6bf30b3f5b4078e1e4d4720765b7R18), both from concurrent-ruby. No more actors, and the issues with messages, having to trap died actors etc. Super simple, as it should be.
