### ISSUE TITLE
Documentation - SQS Queue Policy

### ISSUE THREAD

**Issue by camhine** [phstc/shoryuken#186]
I had a look for some documentation on what the SQS queue policy should be set to for shoryuken but couldn't find any.

Referring to: http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/acp-overview.html

I'm assuming it needs DeleteMessage, SendMessage and ReceiveMessage to operate the queue. But does it also need GetQueueAttributes and/or GetQueueUrl to initialise the queue when it boots?

It would be great if there was an example policy in the README or wiki.

**Comment by camhine** [comment]
Now I've looked at the code. (Sorry I should have done that first). I can see that it needs all (*) SQS permissions.

Still it might be nice to have that explicitly in the documentation.

Here is an example queue policy that will work with shoryuken for anyone interested:
```
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS":  "<insert account ARN or role ARN here>"
      },
      "Action": "sqs:*",
      "Resource": "<insert queue arn here>"
    }
  ]
}
```

**Comment by Senjai** [comment]
It does not need all privs. Get queue attributes is the only necessary one if I remember correctly. The rest depend on what you use it for. If its a worker you need receive and delete. If it just sends you only need send message.

**Comment by camhine** [comment]
Ahh cool. Thanks for the clarification.

Are you sure it doesn't need GetQueueUrl as well? It looks like `get_queue_url` is called when the Queue is initialized:

```
def initialize(client, name)
  self.name   = name
  self.client = client
  begin
    self.url = client.get_queue_url(queue_name: name).queue_url
  rescue Aws::SQS::Errors::NonExistentQueue => e
    raise e, "The specified queue '#{name}' does not exist"
  end
end
```

**Comment by camhine** [comment]
GetQueueUrl and GetQueueAttributes are required to allow shoryuken to initialize the queues.

DeleteMessage and ReceiveMessage are required to allow a shoryuken ***worker*** to process items on the queue: receive the message, process it, delete the message if processing succeeds.

Example SQS Policy for a Shoryuken worker:

```
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "<insert account ARN or role ARN here>"
      },
      "Action": [
        "sqs:DeleteMessage",
        "sqs:GetQueueAttributes",
        "sqs:GetQueueUrl",
        "sqs:ReceiveMessage"
      ],
      "Resource": "<insert queue arn here>"
    }
  ]
}
```

**Comment by phstc** [comment]
Thanks @camhine! I added to the wiki :beers: 

https://github.com/phstc/shoryuken/wiki/Amazon-SQS-Policy-for-Shoryuken
