### ISSUE TITLE
Job timeout option

### ISSUE THREAD

**Issue by mariokostelac** [phstc/shoryuken#187]
Is there any option to define a timeout on job itself?
If not, is there any reason why we do not want to have that option?

I know visibility timeout helps here, but it does not kill the job. If we have N workers, visibility timeout T and job that lasts for (N + 1) * T, after T we have the whole fleet running the same task.
Of course, a task could run forever, too.

**Comment by mariokostelac** [comment]
And yes, I am willing to take this one.

**Comment by phstc** [comment]
@mariokostelac can a very high visibility timeout solve you problem? I usually recommend for any SQS setup, to set the visibility timeout to something like 20x or more times than the AVG message consumption time.

**Comment by mariokostelac** [comment]
It would kind of solve my problem, but generally it's good to have an option to have hard timeout on everything. 
Very long visibility timeout could solve my problem, but actually we are just covering underlying problem that way. If I know that every job execution should last for x with dispersion of let's say x and I set visibility timeout to 30x, I could actually just be covering underlying problems. Also, it could be that somebody wrote infinite loop and our job never finishes. We have to protect the platform from such things at the platform level.
Having hard timeout would allow to investigate and fix things like that.
Of course, that'd be opt-in thing.
What do you say? :)

**Comment by phstc** [comment]
I'm still not 100% confident with the idea. That seems to be something similar to have a hard timeout on Rails controller actions implemented by Rails. I'm not sure it's a responsibility of Shoryuken to implement that.

Shoryuken has a similar option for the opposite, it can auto extend the visibility timeout: https://github.com/phstc/shoryuken/wiki/Worker-options#auto_visibility_timeout

Maybe what you can do, in case you need that, is to implement a Middleware and add to your Shoryuken setup. If you do so, as you will have the code, you can also submit a PR, so other users can also review the idea.

**Comment by mariokostelac** [comment]
That would also work. Thanks :)

**Comment by mariokostelac** [comment]
Actually middleware is not an option here.
Middleware do not have access to actor as far as I can see, which means it can't stop it.
Logic should be part of https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/processor.rb#L14-L32. :S

**Comment by jrgns** [comment]
I won't mind having a hard timeout on a job as well, but it is relatively easy to add it on a per worker basis:

```ruby
require 'shoryuken'
require 'timeout'

class Worker
  include Shoryuken::Worker

  def perform
    Timeout::timeout(30) {
      # Perform potentially long running code here
    }
  end
end
```

**Comment by mariokostelac** [comment]
@jrgns yes, but that's completely detached from SQS/Shoryuken config, which is antipattern.

**Comment by mariokostelac** [comment]
I can't say I agree with you @phstc. Is timeout responsibility of http client library? I would say yes. A good client provides ways to protect you from cascading failures, hanging client etc.
The same way processor library should allow protection from one message congesting the whole fleet (caused by any reason).
I am happy to implement that and submit PR to discuss with you about integration, if solution is going to be nice and elegant.
If you can't think about situation where you would merge it, please say that :).

**Comment by jrgns** [comment]
@mariokostelac I'm not sure how you'd want to attach this to SQS? I think if you whip up a PR with the proposed code I'll have a better understanding of it :)

The timeout should be easy to configure using the current shoryuken confuiguration codebase, so that shouldn't be an issue.

I use the the snippet I've posted above specifically to prevent runaway tasks from keeping my worker fleet from processing properly.

**Comment by phstc** [comment]
We could implement something like `shoryuken_options hard_timeout: true`, which fetches the queue/message timeout and hard timeouts based on it. But before getting into the implementation, I would like to understand more the use case.

If a job takes longer than the queue/message visibility timeout, the message will return to the queue, becoming available to processed again, but a very important concept of using SQS/Shoryuken is to have idempotent workers, so re-processing the message should not have any collateral effect. How hard timing out would help? What's the use case?

**Comment by jrgns** [comment]
I don't think shoryuken should determine if the outcome is idempotent. Here's what I have:

I have workers that create documents in a document store. If the document is already there, it just skips it, and goes on to the next document. That ensures idempotency.

My problem is that due to some issue in the preprocessing, the worker gets stuck on a particular document, causing the worker to stop taking items from the queue. So even though the original message goes back onto the queue after the timeout, I know have a worker running in an infinite loop.

Having a hard timeout allows the worker to recover from this and continue processing. After enough timeouts the message(s) causing the issue are moved to the dead letter queue, where I can then analyze the problem messages.

At the end of the day I want a totally autonomous queue that will run indefinitely, even if problem messages arrive.

**Comment by phstc** [comment]
@jrgns thanks for clarifying it.

Timeout in a middleware would work, but check [this Sidekiq thread](https://github.com/mperham/sidekiq/issues/862), they had to remove it. 

The middleware they used to have: https://github.com/mperham/sidekiq/blob/v2.10.0/lib/sidekiq/middleware/server/timeout.rb

**Comment by mariokostelac** [comment]
If that is not thread safe, extending message timeout is not thread safe, too. It should use the same logic actually.

**Comment by phstc** [comment]
> extending message timeout is not thread safe

Hi @mariokostelac, why it isn't thread safe? BTW The [extender](https://github.com/phstc/shoryuken/blob/bf65b6e90bd6648279c89eeaafeb3f21cbbfd1c1/lib/shoryuken/processor.rb#L43) uses [Celluloid timers](https://github.com/celluloid/timers), not `Timeout`.

**Comment by phstc** [comment]
Thinking more on it, the extender could be converted into a middleware as well simplifying the processor.

I'm open to a PR for harding timeout using Celluloid timers, if you guys are up to it 🍻 

Thanks for following up this discussion.

**Comment by mariokostelac** [comment]
Sorry if I was not totally clear :). I imagine that logic for extending the timeout and killing the process is very similar so my thought is that they have to share the same nature regarding being thread safe or not.
Will try to cut a PR today :).
