### ISSUE TITLE
Synchronised perform for dev environement

### ISSUE THREAD

**Issue by Plippe** [phstc/shoryuken#189]
Hi,

We have extended Shoryuken to execute our perform method synchronously. This, of course, is active only on our dev environment. It permits us to have a much faster feedback loop and avoid paying for or mocking SQS.

Would you be interested in a PR for that feature or is this a route you are trying to avoid ?

**Comment by phstc** [comment]
Hi @Plippe 

Are you using the ActiveJob adapter? If so, you can configure the [inline adapter](http://api.rubyonrails.org/classes/ActiveJob/QueueAdapters/InlineAdapter.html) locally. WDYT?

I don't have options yet on have something sync or not in Shoryuken. Initially, I would recommend the ActiveJob "trick", but I know that for standalone Shoryuken it isn't an option. If a PR wouldn't take much of your time, I would love to see it.

**Comment by Plippe** [comment]
Hey,

No, we aren't using inline adapter. I had never heard of it, and it seems to do what we want. Will dig more into that.

We have just added a hook to `perform_async`. This hook tests the environment and calls `perform` directly in dev. There is a little more to it, but not much more.

After seeing Active Jobs, I am not sure the PR has a lot of value for Rails users, but I don't mind cleaning it up anyways. Are you still interested ?

**Comment by phstc** [comment]
Hi @Plippe 

If the ActiveJob solution works, I would prefer to use it instead of adding more code to Shoryuken.
