### ISSUE TITLE
Logfile location in shoryuken.yml

### ISSUE THREAD

**Issue by VarunNatraaj** [phstc/shoryuken#190]
@phstc I have provided log file path in shoryuken.yml file, but it is not picked at all. Could it be because [initialize_logger](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/environment_loader.rb#L18) comes before shoryuken options are merged with config_file_options? Or is that intentional? Also is there a list of attributes that can be provided and configured in shoryuken.yml?

**Comment by phstc** [comment]
Hi @VarunNatraaj 

> Also is there a list of attributes that can be provided and configured in shoryuken.yml?

Unfortunately, it's spread in the README and Wiki entries. But it would be awesome to have wiki entry for that, if you research on that, would you mind to add a wiki entry with all options?

> @phstc I have provided log file path in shoryuken.yml file, but it is not picked at all. Could it be because initialize_logger comes before shoryuken options are merged with config_file_options? 

There's a PR #181 to fix that, could you test it? If it works, let's merged it. I didn't have a chance to test it yet.

**Comment by VarunNatraaj** [comment]
@phstc I'd say moving [this line](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/environment_loader.rb#L20) to first should solve problems and have no impact as you're invoking logger only in [load_rails](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/environment_loader.rb#L100)

Also, wrt the wiki entry, I'll try 😄
