### ISSUE TITLE
Error processing messages not in ActiveJob format

### ISSUE THREAD

**Issue by reinaldob** [phstc/shoryuken#192]
If you send a message to a queue without any format, like this:

`Shoryuken::Client.queues('reinaldo_clover').send_message('msg 1')`

But try to consume using an ActiveJob worker you will have a message like this:

```
2016-04-13T12:22:02Z 91861 TID-ov7242yec INFO: Found 1 messages for 'reinaldo_clover'
2016-04-13T12:22:02Z 91861 TID-ov71hffh8 ERROR: Process died, reason: undefined method `new' for nil:NilClass
```

Maybe check if the message is in the right format, as the message from `ActiveJob` has a peculiar format:

```
{"job_class":"ProcessClover","job_id":"55b2b57b-93a3-4403-8b08-d0cfb00394a6","queue_name":"reinaldo_clover","arguments":["msg 1"],"locale":"en"}
```

**Comment by mariokostelac** [comment]
Actually wait a second, does your message translated to the payload you've noted in your comment?
