### ISSUE TITLE
Automatic Rails worker queue registration

### ISSUE THREAD

**Issue by hlascelles** [phstc/shoryuken#198]
Just started using Shoryuken and it seems great, but I had an issue when integrating it with Rails. 
I added workers in the `jobs` folder as described, used the `--rails` switch, and everything started fine, but nothing was being processed. I had not specified a config file, as I thought I didn't need one.

Example worker:

```
class EmailRequestsWorker
  include Shoryuken::Worker

  shoryuken_options queue: "#{::Rails.env}-email-requests", auto_delete: true

  def perform(_sqs_msg, body)
    puts body
  end
end
```

I expected that as all the workers were loaded automatically, they would all start processing automatically, as they all had queues defined. I finally tracked it to the fact that Shoryuken needs to be told explicitly what queues to process (which makes sense). 

Since I did not want to specify the queues twice (once in the worker, once in the config), I added this initializer:

```
require_all 'app/jobs'

Shoryuken.configure_server do |config|
  Shoryuken.options.merge!(
    queues: (Shoryuken.worker_registry.queues - ['default']).map { |name| [name, 1] }
  )
end
```

Now I just call `bundle exec shoryuken --rails`, and all the worker/queue config is "self starting".

From my experience I was wondering if any of the following would be good additions:

1) A log line that warns if no queues are specified after initialization (since that implies something is wrong with your config).
2) A CLI switch for `--auto-add-worker-queues` or similar...
3) ... and/or some more explicit documentation that specifies that queues will not be picked up automatically from workers.

**Comment by phstc** [comment]
Thanks for the very detailed issue. I would say that 3 option is the way to go for now.

Regarding to 1, Shoryuken logs out a warning message: https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/environment_loader.rb#L165
