### ISSUE TITLE
Code Review request; evaluate my middleware

### ISSUE THREAD

**Issue by stijnster** [phstc/shoryuken#201]
Hi,

first of all; thank you for an excellent job with this gem! I've been only using it for a few months now, but it's awesome!

I'm creating a middleware to integrate Shoryuken into Appsignal (a gem to collect error and performance data); see the pull request here; https://github.com/appsignal/appsignal-ruby/pull/105.

Since I'm relatively new to the gem (as I am to writing hooks in Appsignal), I'm wondering if someone could be so kind to do code review on my implementation and maybe suggest some improvements?

Thanks,

Stijn

**Comment by mariokostelac** [comment]
I took a look, code does not look bad. Since it's already merged, I am going to close this one to keep issues clean. Feel free to reopen if you have some questions/doubts :).
