### ISSUE TITLE
How to test worker option :auto_delete?

### ISSUE THREAD

**Issue by mekf** [phstc/shoryuken#202]
hi there,

I see that the auto delete logic is handled in the [auto_delete](https://github.com/phstc/shoryuken/blob/bf65b6e90bd6648279c89eeaafeb3f21cbbfd1c1/lib/shoryuken/middleware/server/auto_delete.rb#L15) middleware.

How do verify that after successfully executing`#perform` that the message will be deleted?

Thanks

**Comment by phstc** [comment]
Hi @mekf 

WDYM by verify? Well, I would say to believe in the framework? But you can always disable it and instead call `sqs_msg.delete` manually in your `perform` method.

BTW `auto_delete` is only performed if your worker does not raise any exception.
