### ISSUE TITLE
Changing visibility timeout on SIGTERM

### ISSUE THREAD

**Issue by meskallito** [phstc/shoryuken#203]
Hi there,

We are deploying our app to ECS and during deployments it sends SIGTERM with a grace period 30 seconds to all containers. 

I am wondering if there is a way to use exponential back off or manually set visibility timeout for jobs that are not gonna make it within this grace period.

We are using a single queue and have a bunch of tasks that range from very fast to long running ones.
That's why we started to use auto_visibility_timeout. In addition we want to set default visibility timeout for the queue to a large number and rely purely on exponential backoff in order to override it in case of failure (reduce waiting period).

In the same time we don't want to end up having a message in flight for a long time when process was killed by ecs.

How would you recommend to deal with it?

**Comment by mariokostelac** [comment]
Hi @meskallito,

auto extend visibility is actually considered harmful. It disables you from having any expectation from your fleet power (it fluctuates a lot), number of messages in the Q etc.

I've been working with queued jobs a little bit in Intercom and figured out something that makes it far easier for you: **group similar jobs together**. Similar could mean different things, but I am thinking about nature of resource utilisation (CPU bound, network bound, RAM bound...) and duration.
The more you do that, the easier it is to operate with.

- Once you have similar (resource-utilisation wise) jobs grouped together, you can adjust instance type that's the best fit for your jobs, correct number of processed (or threads) running per machine etc.
- Once you have jobs of similar duration in same queue, it becomes easy to reason about expected time to process the same q, set auto-scaling policies based on Q depth and generally, you can start even setting internal SLAs for expected time to process a job. Also, once you have this property in your queueing system, you know what timeout to set for graceful shutdown, you can implement hard timeout for jobs that take longer than expected to protect your platform from poison pills etc.

However, default timeout is set to 5 seconds, which means you process should die by itself in less than 10 seconds.
Dying actually raises `Shoryuken::Shutdown` error so you could implement a middleware to do whatever you want with a message.

**Comment by mariokostelac** [comment]
I am going to close this one. @meskallito if you need more help with implementing that catches `Shoryuken::Shutdown` and does some back-off, ping me somewhere or reopen.
