### ISSUE TITLE
possible to do regex for queue listening?

### ISSUE THREAD

**Issue by jtoy** [phstc/shoryuken#207]
I have a bunch of queues that are dynamically added.  I have queues in the format of production_training_NUMBER  where NUMBER can be 2-1000.  Is it possible to have the worker listen with this format.

**Comment by phstc** [comment]
Hi @jtoy 

It is if you implement a custom Worker Registry, the default one does not support it. Check the [default one](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/default_worker_registry.rb) for some guidance. If you do that, would you mind adding a Wiki entry about Worker Registries, so other people can have some guidance too? ❤️

Kudos to @leemhenson for that ^  #26

**Comment by jtoy** [comment]
Ok, I can write code for this. With a Regex will the worker be able to grab items from new queues that become available?

-- Sent from my mobile

**Comment by phstc** [comment]
> will the worker be able to grab items from new queues that become available?

Oops. I guess I missed that part ^. The worker registry part is still valid for linking workers and queues. But to add new queues to be fetched at runtime, you will need to explicit call `Shoryuken.queues << 'queue_name'` inside a worker. I've never tried it, but it should work.

Do you use a worker to dynamically create queues, if so, it could also `Shoryuken.queues << ...` after creating them. WDYT?

**Comment by jtoy** [comment]
@phstc I dont use a worker to create queues. I have another service creates queues.
so can I program this situation:
1 queue   hello_a and hello_b are created
2 worker_a registers to listen on hello_*
3 new queue is created at hello_c
4 worker_a listens on hello_c

**Comment by phstc** [comment]
I believe it can work. Please, let me know how it goes 🍻
