### ISSUE TITLE
message attribute options

### ISSUE THREAD

**Issue by wstaples** [phstc/shoryuken#227]
is there a way to have a worker filter messages using sqs message attributes?

**Comment by phstc** [comment]
Hey @wstaples 

You can probably write a middleware for that:

```ruby
class FilterMessages
  def call(worker_instance, queue, sqs_msg, body)
    if sqs_msg. message_attributes['something'] == 'somethingelse'
      yield
    else
      # in case you want to ignore forever
      sqs_msg.delete
    end
  end
end
```

Middleware docs: https://github.com/phstc/shoryuken/wiki/Middleware

I don't think AWS SQS natively allows filtering while receiving them.
