### ISSUE TITLE
Question: "too many open files" from LogStash-Event

### ISSUE THREAD

**Issue by mr-deamon** [phstc/shoryuken#228]
Hi there
I am using shoryuken to process files as soon they appear on the S3. So far so good. But because i wanted some kind of "frontend"/"monitoring", i added the following code just above "class MyWorker"
```
scheduler = Rufus::Scheduler.new
scheduler.every '30s' do
  LogStashLogger.new(port: 5228).debug LogStash::Event.new(message: "Heartbeat, App alive!",app:"stitcher",action:"heartbeat")
end
```

It is working, but i run into "too many open files" problems. Is it because the block itself is misplaced, or could you think of another problem?

Thank you!
Chris

**Comment by mariokostelac** [comment]
Open it once:
```ruby
scheduler = Rufus::Scheduler.new
logger = LogStashLogger.new(port: 5228) #opens just one connection, hence one file descriptor
scheduler.every '30s' do
 logger.debug LogStash::Event.new(message: "Heartbeat, App alive!",app:"stitcher",action:"heartbeat")
end
```

**Comment by mariokostelac** [comment]
Since issue is not shoryuken related and you get some help, I am going to close this one :)

**Comment by mr-deamon** [comment]
Thank you, @mariokostelac, i was completely on the wrong track... i thought that the workers are opening the descriptors, that's why i posted this here!
Thanks for your hint!
Chris
