### ISSUE TITLE
Massive IO wait from Shoryuken

### ISSUE THREAD

**Issue by jellybob** [phstc/shoryuken#231]
We're seeing some issues with a Shoryuken based system generating lots of IO wait - is that normal? To put this in context, we're routinely seeing 90%+ IO wait on the servers running Shoryuken. I'm not certain on this respect, but I think its causing our processors to run much slower than they should be, and generally making queue consumption incredibly slow.

Configuration currently has us listening to 7 separate queues, which doesn't seem like a crazy number, but maybe I'm wrong.

**Comment by laCour** [comment]
We've noticed the same issue in production, 90% IO wait on several servers. This has happened occasionally some weekends, precisely right after we have a maintenance job run (which completes successfully). We're using OpsWorks/EC2.

We've had to force restart shoryuken when this happens, afterwards things go back to normal.

**Comment by phstc** [comment]
@jellybob @laCour blocking operations or high number of processors `concurrency` can cause IO wait.

For example, if you have 25 processors, and each of them perform a blocking operation, when the queues are full, most likely you will get IO wait.

We have this [`sleep`](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/manager.rb#L137), that may also cause some waits, but I can't confirm that yet, it still needs a deeper investigation. But this is most likely for low concurrencies, for example 1.

Could you guys give more insights when it happens, how are the queues and how many processors do you have configure?

**Comment by jellybob** [comment]
We've got the default 25 processors, listening to 7 queues. Running strace
on one the worker processors showed it making a lot FUTEX_WAIT calls (I'll
be honest, I have no idea what that means). Another was blocking on a
select call, which makes me think it was waiting on network IO. iostat
seems to back that up as there was minimal disk activity.

What else would help? I can start up a test environment tomorrow morning
and have a poke at it.

**Comment by phstc** [comment]
> What else would help? I can start up a test environment tomorrow morning
and have a poke at it.

That's helpful, thanks 🍻  

How are your workers, fast or slow? In an AVG, how long do they take to finish?

What do you have configure in `delay`?  We also `sleep` in case the queues get empty.

**Comment by jellybob** [comment]
Typically our jobs average about 200-500ms, although looking at our New Relic graphs I'm seeing some huge spikes on external requests which take things up to 8 seconds. Delay is set to whatever the default value is.

I've got an instance exhibiting these symptoms at the moment, and the Shoryuken worker process is just blocking on a select call indefinitely - I've been attached to one for the past 10 minutes or so and it hasn't gone anywhere:

```
[ec2-user@ip-172-31-43-14 ~]$ sudo strace -p 5951
Process 5951 attached
select(16, [15], NULL, NULL, NULL
```

**Comment by jellybob** [comment]
We're continuing to see these issues. After turning up the log level, and introducing a delay of 250ms for empty queues I'm seeing a gradual but increasing latency on queue updates - they start at ~90ms, and 20 minutes after restarting the worker process they're now taking about 4 seconds. Interestingly I'm seeing even larger results within our processors - they also hit AWS services, so I wonder if its something at the network level, however other applications running on the same instance and making AWS requests aren't seeing any significant variability in response times.

At this point queue consumption has for all intents and purposes ceased. IO wait is at 95.8%, at external requests from processors are taking anything up to a minute.

**Comment by laCour** [comment]
This happened again for us this past weekend. We ran `strace` on the processes and got the same result as jellybob, everything was hanging on a select call. We might want to run `lsof` on the process when this happens to determine what the file descriptor is doing for some extra insight (i.e. `lsof -p <pid> -ad <descriptors>`, in jellybob's case: `lsof -p 5951 -ad 15`). I'm not able to easily reproduce this though so I can't check any time soon.

**Comment by jellybob** [comment]
Hmm, not getting much of use out of that I'm afraid:

```
[ec2-user@ip-172-31-35-199 ~]$ sudo strace -p 15994
Process 15994 attached
select(16, [15], NULL, NULL, NULL^CProcess 15994 detached
 <detached ...>
[ec2-user@ip-172-31-35-199 ~]$ sudo strace -p 4309
Process 4309 attached
select(16, [15], NULL, NULL, NULL^CProcess 4309 detached
 <detached ...>
[ec2-user@ip-172-31-35-199 ~]$ sudo lsof -p 15994 -ad 15
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
ruby    15994 root   15r  FIFO   0,10      0t0 977792 pipe
[ec2-user@ip-172-31-35-199 ~]$ sudo lsof -p 4309 -ad 15
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF  NODE NAME
ruby    4309 root   15r  FIFO   0,10      0t0 15982 pipe
```

Also relevant is that my worker is still processing jobs, but very slowly. I've managed to get to a point where I can consistently reproduce the problem at least. If I push enough traffic to a processor which makes a lot of calls to our REST API then it will consistently bog down, quite quickly getting to a point where all network IO done by the worker becomes unviable.

**Comment by mariokostelac** [comment]
@jellybob can you make sure that you do not have some problems of boxes OOM-ing or having something weird in your code?
The best way to reproduce that would be creating a noop worker that just gets the job and see if the same thing appears with workers like that.

Related to FUTEX calls, it's a synchronisation mechanism provided by OS (FUTEXT = Fast mUTEX) and it's expected that some processes at certain point could be in that call (especially if you have a lot of small jobs). It is caused by celluloid, dependency shoryuken uses.

Select calls are quite usual and it is possible that sqs is using that.

**Comment by laCour** [comment]
After investigating, this does not seem to be an issue with shoryuken. This seems to be caused by hypervisors limiting IO.

This can be determined by running `vmstat 1`. If you frequently see values higher than 0 in the blocked queue column (i.e. "b"), you have processes (e.g. shoryuken) being placed in a waiting queue. Along with this, you'll likely see high IO wait.

A system health monitor could be implemented on the application's job level which responds to such situations by bouncing the message back to the queue if unfit for processing. This prevents tying system resources up and making things worse, allowing other servers to process the job instead.

**Comment by phstc** [comment]
Thanks for the update @laCour.
