### ISSUE TITLE
Get the current amount of pending SQS messages

### ISSUE THREAD

**Issue by eyalrosen** [phstc/shoryuken#233]
Hi,

Is there a way to get the current amount of pending and/or processed SQS messages in queue?

Thanks!

**Comment by phstc** [comment]
Hey @eyalrosen 

Only via AWS SQS Console.

There's also this dashboard mentioned in [Asynchronous processing using SQS and Shoryuken](https://medium.com/@WoloxEngineering/asynchronous-processing-using-sqs-and-shoryuken-2596aec19b4c#.3jqnynuff), posted by @epintos, but I've never tried it.
