### ISSUE TITLE
ActiveJob wait & wait_until params are not working

### ISSUE THREAD

**Issue by syntaxTerr0r** [phstc/shoryuken#234]
When I schedule a job this way:

```ruby
WatchDogJob.set(wait: 10.minutes).perform_later(message)
```

The job is enqueued and processed immediately by SQS, not after the required 10 minutes.

My `WatchDogJob` class is basic though.

```ruby
class WatchDogJob < ActiveJob::Base
  queue_as :mailbot
  include SlackNotifier

  rescue_from ActiveJob::DeserializationError do |ex|
    Shoryuken.logger.error ex
    Shoryuken.logger.error ex.backtrace.join("\n")
  end if Rails.env.production?

  def perform(message)
    slack_notify(message)
  end
end
```

**Comment by phstc** [comment]
Hi @syntaxTerr0r 

Is this `wait`something new? I'm not that familiar with `ActiveJob`, but I would expect `ActiveJob` to call `enqueue_at` internally.

The Shoryuken adapter: https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/extensions/active_job_adapter.rb#L17

I don't see anything calling `wait` in the Sidekiq one: https://github.com/rails/rails/blob/52ce6ece8c8f74064bb64e0a0b1ddd83092718e1/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb

hm I need to investigate that. Any thoughts?

**Comment by syntaxTerr0r** [comment]
Hi @phstc

He's what I know.

ActiveJob's jobs can be enqueued this way: 
http://guides.rubyonrails.org/active_job_basics.html#enqueue-the-job

The `wait` & `wait_until` params are processed internally by ActiveJob to finally call `enqueue` or `enqueue_at` of the adapter (so you are right):
https://github.com/rails/rails/blob/4-2-stable/activejob/lib/active_job/enqueuing.rb

The problem might be happening after that, while providing those params to SQS?

**Comment by kaninfod** [comment]
You need to run resque-scheduler for the delayed jobs to work

**Comment by syntaxTerr0r** [comment]
I'm closing the issue, this is working now.
