### ISSUE TITLE
IAM Policy revision

### ISSUE THREAD

**Issue by Trimakas** [phstc/shoryuken#239]
Amazon did not like the policy currently in the Wiki.. I updated it here to a policy that is valid:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ShoryukenAccess",
            "Effect": "Allow",
            "Action": [
                "sqs:ChangeMessageVisibility",
                "sqs:ChangeMessageVisibilityBatch",
                "sqs:DeleteMessage",
                "sqs:DeleteMessageBatch",
                "sqs:GetQueueAttributes",
                "sqs:GetQueueUrl",
                "sqs:ReceiveMessage",
                "sqs:SendMessage",
                "sqs:SendMessageBatch"
            ],
            "Resource": "arn:aws:REGION:ID:QUEUE_NAME"
        }
    ]
}

**Comment by phstc** [comment]
Thanks @Trimakas 🍻 

Updated version: https://github.com/phstc/shoryuken/wiki/Amazon-SQS-IAM-Policy-for-Shoryuken
