### ISSUE TITLE
Is there any "clean" way to remove default logs ?

### ISSUE THREAD

**Issue by Sof31t** [phstc/shoryuken#242]
i am formatting logs in a specific way and i need to remove default logs like "started at 2016-09-05 15:11:59 +0000" any help ?

**Comment by phstc** [comment]
Hi @Sof31t 

You can remove the timing middleware to get rid of those messages:

```
Shoryuken.configure_server do |config|
  config.server_middleware do |chain|
    chain.remove Middleware::Server::Timing
  end
end
```
It's added by default [here](https://github.com/phstc/shoryuken/blob/a87887247e0ee09c2bd47c7167d9d8c843f58613/lib/shoryuken.rb#L143).

**Comment by Sof31t** [comment]
Hi @phstc, thank you very much ! 👍 
But i still have another issue with another log i need to remove:
In the following file: `/lib/shoryuken/fetcher.rb`
Is there any clean way to remove it ?
`logger.info { "Found #{sqs_msgs.size} messages for '#{queue}'" }`
Actually i did a monkey patch

**Comment by phstc** [comment]
@Sof31t which log do you need log? Maybe you can change the log level to `ERROR`, or maybe write your own logger `Shoryuken.logger = YourLogger` skipping the log you don't want to.
