### ISSUE TITLE
Load multiple workers

### ISSUE THREAD

**Issue by rubemz** [phstc/shoryuken#245]
How can I load multiple works using shoryuken?

The shoryuken `-r` option seems to be designed to load just one worker.

Thanks

**Comment by rubemz** [comment]
nm, misread the docs. closing

**Comment by greggilbert** [comment]
@rubemz What was your solution to this?

**Comment by rubemz** [comment]
@geekguy the ```-r``` option should be working now, per https://github.com/phstc/shoryuken/pull/248

**Comment by greggilbert** [comment]
@rubemz Ah, the issue was that I was running 2.0.11 locally rather than 2.1.x. Thanks.

For anyone else who isn't good at reading like me, `-r DIR` will work; e.g. `bundle exec shoryuken -r ./lib/workers/ -C ./config/shoryuken.yml`

**Comment by phstc** [comment]
@greggilbert 🍻 

Another option, I usually use is to `-r workers.rb` and in this file I `require` the workers I need.
