### ISSUE TITLE
Forward logging to STDOUT

### ISSUE THREAD

**Issue by pmint93** [phstc/shoryuken#246]
Hi there !
I want to running shoryuken workers in a docker container and forward logging out to STDOUT.
As i found in the source: https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/logging.rb#L26
If there are no log_target params passed, default log_target would be STDOUT.
But, initialize_logger method was called at https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/environment_loader.rb#L78
will be not called if i do not passing logfile option.

 How do i forward logging to STDOUT instead of logfile ? Thanks so much !

**Comment by phstc** [comment]
Hey @pmint93, you can try to re-initialize it `Shoryuken::Logging.initialize_logger` after it starts, without passing the `log_target`.

If you have some spare time, I'm open for a PR to fix `def initialize_logger` to use `STDOUT` when `logfile` isn't supplied.

**Comment by pmint93** [comment]
Hi @phstc ,

Sorry for late reply and thanks for replied me.

I'm just digging in to the source, and i found that: the method `initialize_logger` in `logging.rb` isn't get called by environment_loader on initial.

But fortunately, it get called by [logger](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/logging.rb#L33) method when shoryuken want to log something out, and of course it's get called without parameters so STDOUT is the default log_target. Everything working as i expected.

**Comment by phstc** [comment]
@pmint93 thanks for the follow up.
