### ISSUE TITLE
Exponential-Backoff Retry with Active Job Integration

### ISSUE THREAD

**Issue by nritholtz** [phstc/shoryuken#247]
I know how to do backoff with a regular Worker class based off the [WIKI](https://github.com/phstc/shoryuken/wiki/Worker-options#retry_intervals).

However, I am using [Active Job integration with Shoryuken](https://github.com/phstc/shoryuken/wiki/Rails-Integration-Active-Job).

How do I implement the retry_intervals within the Active Job integration implementation?

**Comment by nritholtz** [comment]
I believe this a duplicate of #170

**Comment by phstc** [comment]
@nritholtz thanks for checking #170. [This](https://github.com/phstc/shoryuken/issues/170#issuecomment-172085598) should do, but it isn't going to be on a worker basis, that is going to be applied for all workers using `ActiveJob`. Does that work for you?

**Comment by sunil-sadasivan** [comment]
@phstc, is there a way at the moment to override the retry logic on a per active job basis?

Thanks!

**Comment by phstc** [comment]
Hi @sunil-sadasivan 

I don't think there is. I believe for making that happening, [this](https://github.com/phstc/shoryuken/blob/d7fa44c924822487d2ec9920f158e5b207599076/lib/shoryuken/middleware/server/exponential_backoff_retry.rb#L34) would need to be changed to pass the body as well: `retry_intervals.call(attempts, body)`, then you would be able to do something like this:

```ruby
JobWrapper.shoryuken_options(
retry_intervals: Proc.new do |attempts, body|
  if body['job_class']
    # ...
  else
    # ...
  end
end
)

```
