### ISSUE TITLE
Scheduled jobs

### ISSUE THREAD

**Issue by oyeanuj** [phstc/shoryuken#251]
Hi @phstc, I was wondering if it is possible to have scheduled jobs run on shoryuken - like sending nightly emails. With Sidekiq, it seems that using sidetiq or sidetiq-scheduler achieves it, or that clockwork gem would work with Sideqik possibly.

Any thoughts on best way to achieve it with Shoryuken?

Thank you for open sourcing this library!

**Comment by phstc** [comment]
Hi @oyeanuj 

You can check [shoryuken-later](https://github.com/joekhoobyar/shoryuken-later) from @joekhoobyar. 

But also recommend to have a look at [Using AWS Lambda with Scheduled Events](https://docs.aws.amazon.com/lambda/latest/dg/with-scheduled-events.html). You can use AWS for "cron jobs" like, it will trigger a lambda and this lambda can enqueue a SQS message.

**Comment by tjsingleton** [comment]
@phstc It may be worth adding this to the wiki. Note too that you don't need the lambda with SQS targets https://aws.amazon.com/about-aws/whats-new/2016/03/cloudwatch-events-now-supports-amazon-sqs-queue-targets/

**Comment by phstc** [comment]
@tjsingleton interesting. Just added https://github.com/phstc/shoryuken/wiki/Scheduled-Jobs thanks 🍻

**Comment by scottfromsf** [comment]
The cloudwatch_scheduler gem makes using CloudWatch to kick off Shoryuken jobs via cron a piece of cake: https://github.com/paul/cloudwatch_scheduler
