### ISSUE TITLE
multiple queue declerations?

### ISSUE THREAD

**Issue by jtoy** [phstc/shoryuken#254]
is it correct that I must declare the queues twice if i need priorities?

once from the queue or command line and then once in the ruby code with shoryuken_options?

so:

shoryuken -r worker.rb -q test_queue|1

and
 
shoryuken_options queue: 'test_queue'

isnt that redundant?

**Comment by phstc** [comment]
@jtoy that is necessary to map the relation between workers and queues. In one (Ruby) you tell which queue, and in another you configure the queues and priorities.

`-q test_queue|1` can be also configured in the `shoryuken.yml`. 

Shoryuken could read the queues and priorities from the workers, but that isn't the way it works.
