### ISSUE TITLE
Inlining with Shoryuken

### ISSUE THREAD

**Issue by Petesta** [phstc/shoryuken#256]
Hi, I was wondering if there was a way to inline Shoryuken like you can with ActiveJob inside of your environment configuration for testing purposes like this.

``` ruby
# ActiveJob
config.active_job.queue_adapter = :inline
```

As far as I can tell, Shoryuken doesn't allow us to do this. I have some integration tests that I would like to run but when kicking off the worker there is no way for me to block that call or force that queue to drain itself. Assuming the queue can be drained then I can make assertions on whatever work was being performed inside of that worker during integration tests.

I found a similar [issue](https://github.com/phstc/shoryuken/issues/133). One of the responses is `Testing workers with RSpec` but I'm not looking to isolate workers in this case.

Are we having to write middleware to force the async calls to be performed immediately?

**Comment by phstc** [comment]
Hi @Petesta 

Shoryuken does not support `inline`. Unfortunately, a middleware won't help with that, as it's only triggered after receiving messages from SQS.

One option could be monkey patching [`perform_async`](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/worker.rb#L8) to call `perform` right the way. [Sidekiq testing](https://github.com/mperham/sidekiq/wiki/Testing) can give you some ideas. 

I can't work on that at moment, but I'm happy to review/accept pull requests for that.

**Comment by Petesta** [comment]
As of right now, it's probably easier to just switch back to `Sidekiq` as I'm very familiar with its setup. My fault for not realizing sooner that there is no clean way of doing integration testing.

I'd like to avoid monkey patching but if you can point me in the right direction for adding this testing functionality into `Shoryuken` then I can look into adding it in.

**Comment by phstc** [comment]
@Petesta IMO choosing between Sidekiq and Shoryuken should go further than just testing helpers. I have [a post](http://www.pablocantero.com/blog/2015/03/14/sidekiq-redis-vs-shoryuken-aws-sqs/) comparing them, in case you want some ideas. I'm not advocating in favor Shoryuken or Sidekiq, both have pros and cons, just saying that the testing helpers may be not the biggest decision factor.

> I'd like to avoid monkey patching

If I'm not missing something in [here](https://github.com/mperham/sidekiq/blob/8c53356fc8e6ff24ba739fed70a81d3c0ad0d907/lib/sidekiq/testing.rb), that's what Sidekiq does.

> but if you can point me in the right direction for adding this testing functionality into Shoryuken then I can look into adding it in.

Sure thing! 🍻 

I think that idea would be to monkey patch [`Shoryuken::Worker`](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/worker.rb), if `Shoryuken.inline?` is set to true, call the worker, otherwise call `original_perform_async`.

Something like that:

```ruby
module Shoryuken
  module Worker
    def self.included(base)
      base.extend(ClassMethods)
    end

    module ClassMethods
      alias_method :original_perform_async, :perform_async

      def perform_async(body, options = {})
         if Shoryuken.testing?
           fake_sqs = generate_fake_sqs_msg(body, options)
           new.perform(fake_sqs_msg, body)
         else
           original_perform_async(body, options)
         end
      end
```

But TBH, if you want to test just a single worker, you can also patch it on top of your test:

```ruby
class MyWorker
   def self.perform_async(body, options = {})
     new.perform(fake_sqs_msg, body)
   end
end
```

**Comment by mariokostelac** [comment]
@phstc could we support that from our side?

**Comment by phstc** [comment]
@mariokostelac like `perform_now` for testing purposes? If it does not require super complex code. I think we could 👍 

We need to make sure we don't break the compatibility with ActiveJob `perform_now`.

**Comment by vemv** [comment]
I think some people are unaware that Shoryuken implements the ActiveJob interface, and are using Shoryuken directly, which would be a mistake if later they want 'inline' capabilities.

Why not just...

```ruby
  if Rails.env.production?
    config.active_job.queue_adapter = :shoryuken
  else
    config.active_job.queue_adapter = :inline
  end
```

...and be done with it?

Cheers - Victor

**Comment by phstc** [comment]
@vemv the motivation for `perform_now` is for people that don't use it with `ActiveJob` for testing and also to run it locally. Thinking more on it, `perform_now` does not seem to be a good idea for running it locally (not test), people would need `if` in their code.

For the developers who want to test something locally, they don't need SQS, they could use something `Shoryuken.adapter = :inline` locally. I understand it's given by `ActiveJob`, but a lot of people use it without `ActiveJob`, at least, I do.

WDYT?

**Comment by samneely** [comment]
@phstc @Petesta For clarification, does this mean we can inline background jobs with ActiveJob/Rails to perform those synchronously while still using `shoryuken`?

**Comment by phstc** [comment]
@samneely correct in somehow, you need to change the ActiveJob adapter to `:inline`. I do that in my `{test,development}.rb`.

So in production you set the adapter to `:shoryuken` and in places you want it to be synchronously, you set it to `:inline`. 

It should work just fine with the exception of delaying message, if you use `wait time in seconds`, it isn't supported in the `:inline` adapter.

**Comment by jakehow** [comment]
If you are using the library directly, but RSpec, you can do the following:

`allow(MyJob).to receive(:perform_async) {|arg| MyJob.new.perform(arg) }`

and very easily make a spec helper that lets you write it like `inline(MyJob)`

**Comment by phstc** [comment]
@jakehow great example, I like it ⭐️

**Comment by phstc** [comment]
hi @Petesta 

I have a WIP #448 for the inline worker, the idea is to enable inline by setting a `worker_executor` attribute.

```ruby
Shoryuken.worker_executor = Shoryuken::Worker::InlineExecutor
```

`Shoryuken::Worker::DefaultExecutor` would be the default value, which is the one that goes to SQS.

The only one difference so far is that the `inline` does not perform middleware. But I believe I can make them to work with some hackery, if it's needed.

WDYT?

**Comment by phstc** [comment]
Wiki updated:

- [Shoryuken Inline adapter
](https://github.com/phstc/shoryuken/wiki/Shoryuken-Inline-adapter)
- [Testing](https://github.com/phstc/shoryuken/wiki/Testing)
