### ISSUE TITLE
SQS "at-least-once" delivery

### ISSUE THREAD

**Issue by ifightcrime** [phstc/shoryuken#257]
Does shoryuken already handle locking, or do you have a recommended method for handling multiple deliveries? Thinking about pulling in something like redis-lock, but was hoping you might already have a suggestion or potentially solved this.

http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/DistributedQueues.html

**Comment by phstc** [comment]
Hey @ifightcrime there isn't a built in solution for that in Shoryuken.

I usually recommend:

> You must design your applications to be idempotent (they must not be affected adversely when processing the same message more than once).

But I understand that it's something we can't achieve depending on the process. In case you strongly need that, I would say that a middleware and something like Redis would do.
