### ISSUE TITLE
Understanding Shoryuken's queue balancing

### ISSUE THREAD

**Issue by atyndall** [phstc/shoryuken#258]
Hi there,

I have a question related to how Shoryuken load balances jobs that I found hard to figure out in the docs. If I have the following config:

```
concurrency: 2
queues:
  - [type_A_job, 1]
  - [type_B_job, 1]
```

Will there be any circumstances where 2 type A jobs or 2 type B  jobs will be executed simultaneously, or does the weighting place a maximum on how many jobs of that type can be in flight at once? It is important due to rate limiting reasons that simultaneous execution of the same type of jobs not occur.

If this config doesn't work, is there any other way besides running another Shoryuken process that would allow that constraint to be enforced?

In the same vein, if I had a situation like this;

```
concurrency: ?
queues:
  - [type_A_job_high_priority, 4]
  - [type_A_job_medium_priority, 2]
  - [type_A_job_low_priority, 1]

  - [type_B_job_high_priority, 4]
  - [type_B_job_medium_priority, 2]
  - [type_B_job_low_priority, 1]
```

I'm fine with any type A job and any type B job executing together, but I would never want two type A or two type B jobs executing simultaneously. Is making this work possible? 

Much appreciated,
Ash

**Comment by phstc** [comment]
hi @atyndall 

```
concurrency: 2
queues:
  - [type_A_job, 1]
  - [type_B_job, 1]
```

`concurrency` is the number of available processors (workers, actors, threads) that will be triggered in "parallel". With that setup, it will cause Shoryuken to [try to fetch 2 messages from SQS](https://github.com/phstc/shoryuken/blob/a40e6b26e2dfbc4a78a36198d02010dce66a977e/lib/shoryuken/fetcher.rb#L32) for `type_A_job`, and then [once one or more processors are available again](https://github.com/phstc/shoryuken/blob/a40e6b26e2dfbc4a78a36198d02010dce66a977e/lib/shoryuken/manager.rb#L142-L143), Shoryuken will try to fetch messages for `type_B_job`. It's hard to deterministic say it's going to process 2 for `type_A_job` then 2 for `type_B_job`.

The queue load balancing is more to tell Shoryuken to try to process the maximum it can (based on the concurrency, and of course up to 10 messages due the SQS limit) one time for `type_A_job` and another for `type_B_job`.

> Will there be any circumstances where 2 type A jobs or 2 type B jobs will be executed simultaneously

If `A` receives two messages, two processors get busy, then one become available before another, Shoryuken will try to use it to consume a message for `B`. 

>  It is important due to rate limiting reasons that simultaneous execution of the same type of jobs not occur.

The only way you can guarantee that `B` is processed only after `A` is using `concurrency: 1` .

```
  - [type_A_job_high_priority, 4]
  - [type_A_job_medium_priority, 2]
  - [type_A_job_low_priority, 1]

  - [type_B_job_high_priority, 4]
  - [type_B_job_medium_priority, 2]
  - [type_B_job_low_priority, 1]
```

That only means, fetch the maximum Shoryuken can 4 times for `type_A_job_high_priority`, 2 times for `type_A_job_medium_priority` and so on in that particular order.

**Comment by atyndall** [comment]
Thanks for the explanation! So as it stands the easiest way to get what I want would be to run two seperate Shoryuken processes, one for type A jobs, and one for type B?

**Comment by phstc** [comment]
@atyndall I'm not sure if I completely followed what you really want. Could you clarify your use case?

If you want to start consuming messages from `B` only after consuming all messages in `A`, there's no guarantee for that in Shoryuken. Having two Shoryuken processes will cause the two queues to be consumed in simultaneously.

**Comment by atyndall** [comment]
What I mean is if I run the following configs

```
# process 1
concurrency: 1
queues:
  - [type_A_job_high_priority, 4]
  - [type_A_job_medium_priority, 2]
  - [type_A_job_low_priority, 1]
```

```
# process 2
concurrency: 1
queues:
  - [type_B_job_high_priority, 4]
  - [type_B_job_medium_priority, 2]
  - [type_B_job_low_priority, 1]
```

I should get the guarantees that no two type A jobs or type B jobs run simultaneously, but still be able to run 1 type A and 1 type B job simultaneously.

**Comment by phstc** [comment]
> I should get the guarantees that no two type A jobs or type B jobs run simultaneously, but still be able to run 1 type A and 1 type B job simultaneously.

Confirmed and guaranteed.

**Comment by phstc** [comment]
Hi @atyndall 

Have you seen the new FIFO queue from AWS? It can guarantee the message processing order. Does that work for you?

https://github.com/phstc/shoryuken/wiki/FIFO-Queues

**Comment by atyndall** [comment]
@phstc I don't think so?

My situation is something like this, I have an "important_jobs" queue and a "unimportant_jobs" queue. Different agents can add to these queues at any time.

I want Shoryuken to always choose an important job if one is available, but if there isn't one, it can choose an unimportant job instead. As far as I understand, with the FIFO queues you need to make sure you're ordering your jobs how you want them executed at the time you insert them, whereas in my case a more important job could appear at any time, and I would want it to execute next.

**Comment by phstc** [comment]
@atyndall thanks for checking it. I got too excited too soon. You are right, I don't think it fits for your use case.

I'm planning to use a FIFO queue for a specific webhook setup I have. The controller that handles the webhook requests would enqueue messages to a FIFO queue, so "guaranteeing" the order.
