### ISSUE TITLE
Memory leak in auto_visibility_timeout

### ISSUE THREAD

**Issue by rkr090** [phstc/shoryuken#266]
The ```@visibility_extender``` instance variable is always nil due to which a new ```MessageVisibilityExtender``` object is created for every message processed. This object is never garbage collected due to which the threads/memory of the worker grows with the number of messages processed.

https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/middleware/server/auto_extend_visibility.rb#L48

We didn't face this issue when not using auto_visibility_timeout, adding ```@visibility_extender.terminate``` as the last line in ```auto_visibility_timer``` method fixes the issue.

**Comment by mariokostelac** [comment]
@rkr090 if we terminate the extender before the whole thing is done, it actually does not work, does it?
I think it'd be good to terminate the extender in ensure block https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/middleware/server/auto_extend_visibility.rb#L13-L15.
Could you create  a PR?

**Comment by rkr090** [comment]
@mariokostelac Yep, the ensure block is the right place to terminate the extender. I have created a PR #267, please review.

**Comment by phstc** [comment]
If we always terminate it, do we need `||=`? 

```ruby
@visibility_extender ||= MessageVisibilityExtender.new_link
```

I think the initial idea was to have `visibility_extender` as a class variable and to use it for every message.
