### ISSUE TITLE
middleware improvements

### ISSUE THREAD

**Issue by leemhenson** [phstc/shoryuken#27]
Some of my workers need to have middleware X invoked each time they handle a message, and some don't. At the moment I can only configure the ```server_middleware``` chain that is run for every worker. I'm thinking that ```Shoryuken::Worker``` should offer a hook for modifying the default chain on a per-worker basis. For example:

```ruby
class FooWorker
  include Shoryuken::Worker

  shoryuken_options queue: 'foo_queue', airbrake_data: 'some string'

  shoryuken_middleware do |chain|
    chain.insert_before Shoryuken::Middleware::Server::Timing, MyAirbrakeMiddleware
  end
end
```

I guess when the worker is registering itself with Shoryuken it can cache a new chain if ```shoryuken_middleware``` was called, and then the processor would need to pick that up here:

https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/processor.rb#L21

**Comment by leemhenson** [comment]
Yeah, so it looks like the only things we need are:

- [ ] a ```shoryuken_middleware``` method to partner ```shoryuken_options``` in worker definitions
- [ ] patching ```Processor``` to run global and then per-worker middlewares

**Comment by phstc** [comment]
+1 for the checklist :smile: 

_hm having an idea..._

The processor could get all (global + specific) middleware from the worker class:

```ruby
worker.class.get_server_middleware.invoke(worker, queue, sqs_msg, body) do
    worker.perform(sqs_msg, body)
end
```

which by default returns the global middleware, but if someone define `server_middleware` inside the worker:

```ruby
class FooWorker
  include Shoryuken::Worker

  shoryuken_options queue: 'foo_queue', airbrake_data: 'some string'

  server_middleware do |chain|
    chain.add Shoryuken::Middleware::Server::Timing 
    chain.add MyAirbrakeMiddleware
  end
end
```

The worker will return a new chain with all global middleware along with the worker specific ones.

So we will be able skip the global ones if we want:

```ruby
server_middleware do |chain|
  chain.clear
  # chain.delete GlobalXXX
  chain.add Shoryuken::Middleware::Server::Timing 
  chain.add MyAirbrakeMiddleware
end
```

**Comment by leemhenson** [comment]
- [x] :+1:

**Comment by leemhenson** [comment]
See: https://github.com/musicglue/shoryuken/tree/per-worker-middlewares

**Comment by leemhenson** [comment]
https://github.com/musicglue/shoryuken/commit/10ec2438474f4a32573c2cffd5be42a8a1111717
