### ISSUE TITLE
Pull log level from rails environment configuration

### ISSUE THREAD

**Issue by Startouf** [phstc/shoryuken#270]
I am running Shoryuken and I'd like to have a logger with the same level as declared in my environment configuration

Currently the logger seems to be initialized like this

def self.initialize_logger(log_target = STDOUT)
      @logger = Logger.new(log_target)
      @logger.level = Logger::INFO
      @logger.formatter = Pretty.new
      @logger
end

So for the Rails WIki / initializer I suggest the following changes

```
# Original
Rails.logger = Shoryuken::Logging.logger 

# New
Rails.logger = Shoryuken::Logging.logger
Rails.logger.level = Rails.application.config.log_level
```

**Comment by phstc** [comment]
@Startouf wiki updated, thanks 🍻 

https://github.com/phstc/shoryuken/wiki/Rails-Integration-Active-Job
