### ISSUE TITLE
Support deliver_later wait/wait_until options

### ISSUE THREAD

**Issue by vemv** [phstc/shoryuken#271]
As per https://github.com/phstc/shoryuken/wiki/Sending-a-message#delaying-a-message, one can delay a message up to 15 minutes.

Support of this feature for the ActiveJob interface seems to be lacking though. It would be a matter of observing the `:wait` and `:wait_until` options (http://edgeapi.rubyonrails.org/classes/ActiveJob/Core/ClassMethods.html) and forwarding them to the tight place

Of course, we should ensure that we delay 15 minutes max.

This looks like fairly low-hanging fruit. I could volunteer for it!

Any initial feedback? I assume there's no big reason why this isn't implemented already.

Cheers - Victor

**Comment by gshutler** [comment]
I believe it is already implemented. See the [ActiveJob adapter](https://github.com/phstc/shoryuken/blob/cea4f5f475b2e756f82e367152db831f9e2cc6f5/lib/shoryuken/extensions/active_job_adapter.rb#L40-L48).

**Comment by vemv** [comment]
Good catch!

However I don't see it covered by specs. There are no occurrences of wait/wait_until in the codebase. I woulnd't want to use something that only accidentally works

**Comment by phstc** [comment]
@vemv `wait` and `wait_until` are implemented in ActiveJob. Shoryuken adapter implements only `enqueue` and `enqueue_at` which ActiveJob calls when `wait` or `wait_until` are supplied.  That's the why you don't find any occurrence of `wait` and `wait_until`, Shoryuken does not know about them, as ActiveJob calls only `enqueue` and `enqueue_at`.

Does that make sense?

**Comment by vemv** [comment]
Sorry for leaving this hanging on, I had postponed using Shoryuken in a specific new project for a few months, so the question became non-urgent.

So, my impression is that even if this works OOTB, it should be explicitly documented and tested.

We can go back at this later!

Victor

**Comment by phstc** [comment]
Hi @vemv

**Comment by phstc** [comment]
Hi @vemv 

Thanks for getting back. I'm reopening it, as a placeholder for adding a test to the [active job adapter](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/extensions/active_job_adapter.rb). About the documentation, I think [this](https://github.com/phstc/shoryuken/wiki/Rails-Integration-Active-Job) is enough, we only need to implement the ActiveJob interface, how it's integrated with Rails `wait` and `wait_until` isn't a responsibility of the adapter, actually Shoryuken does not know about those methods. For further documentation, [ActiveJob docs](http://edgeguides.rubyonrails.org/active_job_basics.html) is place to go.

**Comment by vemv** [comment]
Hi Pablo, great to hear!

> how it's integrated with Rails wait and wait_until isn't a responsibility of the adapter.

This might be true, but doesn't it seem worthwhile to add an integration test actually running over SQS, and asserting that the job was actually delayed by N minutes? You never know how SQS and AJ might change over time.

So someone should be responsible for testing that feature - and I'm pretty sure the Rails or Amazon guys won't be the ones coding this test.

> For further documentation, ActiveJob docs is place to go.

Fair enough. I'd just expect that the FAQ _can shoryuken execute delayed jobs through AJ?_ is answered, visible, and links to http://edgeguides.rubyonrails.org/active_job_basics.html.

Hope it sounds reasonable!

Victor

**Comment by phstc** [comment]
> This might be true, but doesn't it seem worthwhile to add an integration test actually running over SQS, and asserting that the job was actually delayed by N minutes? You never know how SQS and AJ might change over time.

I understand your point, but I don't think it's. I think it's worthwhile adding unit tests in [here](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/extensions/active_job_adapter.rb). 

> So someone should be responsible for testing that feature - and I'm pretty sure the Rails or Amazon guys won't be the ones coding this test.

ActiveJob specifies an interface. Shoryuken implements this interface.

> Fair enough. I'd just expect that the FAQ can shoryuken execute delayed jobs through AJ? is answered, visible, and links to http://edgeguides.rubyonrails.org/active_job_basics.html.

Any contribution is very welcome through pull requests or updates in the wiki. Shoryuken supports delayed jobs natively without AJ, why wouldn't it not support it with AJ? There's a link to ActiveJob basis in the wiki.

**Comment by phstc** [comment]
> Note: When queueing jobs to be performed in the future (e.g when setting the wait or wait_until Active Job options), SQS limits the amount of time to 15 minutes. Shoryuken will raise an exception if you attempt to schedule a job further into the future than this limit.

@vemv there's also that ^ in the docs.
