### ISSUE TITLE
Disable "DEBUG: Looking for new messages" logs

### ISSUE THREAD

**Issue by eni9889** [phstc/shoryuken#275]
I cannot seem to find any documentation for turning these logs off. I have made sure to not use the -v option as well. Is there something I am missing?

**Comment by phstc** [comment]
Hi @eni9889 

Any chance you are setting `Shoryuken::Logging.logger.log_level` to `DEBUG` in your code?

**Comment by eni9889** [comment]
This is what I have in the initializer:

```
Rails.logger.level = (Rails.env.production? ? Logger::WARN : Logger::DEBUG)
```

**Comment by phstc** [comment]
If you are `Shoryuken::Logging.logger = Rails.logger` then you will have `debug`, which is the same as `verbose` in non `Rails.env.production?` environments.

**Comment by eni9889** [comment]
I am running the app in production or at least i thought i was:

```
RAILS_ENV=#{RAILS_ENV} bundle exec shoryuken -R -C ./config/shoryuken/#{APP_NAME}.yml -L ./log/#{APP_NAME}.log -P ./tmp/pids/#{APP_NAME}.pid -d
```

**Comment by phstc** [comment]
@eni9889 try this `Shoryuken::Logging.logger = Logger::ERROR` in an initializer.

**Comment by eni9889** [comment]
This is my initializer:
```
Shoryuken.configure_server do |config|
  Rails.logger = Shoryuken::Logging.logger
  Rails.logger.level = (Rails.env.production? ? Logger::WARN : Logger::DEBUG)
  Rails.logger.formatter = Logger::Formatter.new
  Shoryuken.active_job_queue_name_prefixing = false
end
```

Thanks for the help BTW

**Comment by phstc** [comment]
@eni9889 try to `Rails.logger.level = Logger::ERROR` to see if that helps. Maybe for some reason Rails isn't being set to prod mode.

**Comment by eni9889** [comment]
I'll take a look thank you.

**Comment by eni9889** [comment]
I ended up logging the ENV and Rails is being loaded in production

```
Shoryuken.configure_server do |config|
  puts "SHORYUKEN ENV: #{Rails.env}"
```

results in : 'production'

**Comment by eni9889** [comment]
I also logged the logger level and it is set to WARN:

```
SHORYUKEN ENV: production
SHORYUKEN Rails.logger.level: 2
```

**Comment by eni9889** [comment]
@phstc any ideas whats happening?

**Comment by eni9889** [comment]
Putting the following in the initializer seems to work:
```
Shoryuken.configure_server do |config|
  Rails.logger = Shoryuken::Logging.logger
  Shoryuken.active_job_queue_name_prefixing = false
end

module Shoryuken
  module Logging
    def self.initialize_logger(log_target = STDOUT)
      @logger = Logger.new(log_target)
      @logger.level = (Rails.env.production? ? Logger::WARN : Logger::DEBUG)
      @logger.formatter = Pretty.new
      @logger
    end
  end
end
```
