### ISSUE TITLE
workers know what queue they are in?

### ISSUE THREAD

**Issue by jtoy** [phstc/shoryuken#285]
can a worker know what queue it is processing the current message in?

I have code defined as so:
 shoryuken_options queue: ->{ ["#{ENV['APP_ENV']}_training","#{ENV['APP_ENV']}_inference","#{ENV['APP_ENV']}_inference"] }

like:

if @queue == "production"
  email_me
end

I want to change some of the logic depending on what queue is being processed. Is this possible? I did not see this in any of the documentation.

**Comment by phstc** [comment]
Hey @jtoy 

I don't think it's possible, the workers receives `body` and `sqs_message`, but the aws sdk does not provide anything queue information for the message, see [this](https://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Types/Message.html).

**Comment by jtoy** [comment]
@phstc that is unfortunate. What if I split the queues being watched into separate workers, could I have code to know what queue im using?

I need the ability to somehow have 1 code base be able to switch between queues. The reason is have resource constrained hardware and each of my queues does a different type of processing. I want my machine to be able to process both types of jobs, but not concurrently,hence the need for another meta worker that watches 2 queues and alternates between pulling jobs off of them.

**Comment by mariokostelac** [comment]
@jtoy could you just include that information in the message itself? I know it's not the cleanest solution, but it would work :).

**Comment by jtoy** [comment]
@mariokostelac good idea, I will try that as a last resort. I want to try one more method, Is it possible for me to write a meta job that runs a worker on a queue for a minute, stops and then switches to another worker on another queue?

**Comment by mariokostelac** [comment]
@jtoy I read your problem again and I believe you actually need just two different workers :).

I believe you want to use ActiveJob integration https://github.com/phstc/shoryuken/wiki/Rails-Integration-Active-Job, create `SlowProcessor` and `FastProcessor`, tie them to the same queue `versatile-queue` and choose what you want to do when enqueueing the message. `SlowProcessor.perform_async` or `FastProcessor.perform_async`. Shoryuken will know which processor to run when the message come in (there is some metadata attached to the message).
