### ISSUE TITLE
Listen to multiple queues per process

### ISSUE THREAD

**Issue by vdaubry** [phstc/shoryuken#29]
Hi,

First of all thanks a lot for the great work ! 
From what i understand the gem is currently designed to handle one queue per process, so if i want to listen to n queues i need do start n shoryuken process (right ?)

On our app workers are mainly doing IO intensive job, like database operations. Listening to all queues on a single process would reduce RAM usage a lot and also means fewer process to monitor.
I'm willing to contribute if you're interested in.

**Comment by elsurudo** [comment]
Nope, it can monitor as many queues as you like on a single process. Check out the readme (especially the configuration file section) for more details.
