### ISSUE TITLE
Create threads within a job

### ISSUE THREAD

**Issue by chinshr** [phstc/shoryuken#290]
Is it recommendable to create new threads within a worker? 

```ruby
class ThreadedWorker
  include ::Shoryuken::Worker

  def perform
    1..10.times.map {|i| Thread.new { do_something} }.join
  end

end
```

**Comment by phstc** [comment]
@chinshr What's your use case? What do you want to do with `do_something`? You can also use `perform` to enqueue other messages, so you don't need to do `Thread.new` to get some "parallelism".

**Comment by chinshr** [comment]
@phstc thanks. `do_something` stores, converts, uploads, etc. and is considered thread save. I have noticed that my shoryuken process went down, and just wanted to know if creating threads inside a worker perform is considered ok.

Correct, I could enqueue more messages from within `perform`, but it will be more coding overhead breaking out the code and data. What other ways did you suggest other than threads?

**Comment by phstc** [comment]
@chinshr I would suggest to do it sequentially without threads, or to enqueue messages in place of your threads.

**Comment by chinshr** [comment]
Got it, thanks.
