### ISSUE TITLE
 Is it possible to run in a separate thread instead of process?

### ISSUE THREAD

**Issue by thomas07vt** [phstc/shoryuken#292]
The readme shows this example for starting up shoryuken

```bash
bundle exec shoryuken -r worker.rb -C shoryuken.yml
```

Is there a way to spawn this from an existing process? Like my web server? I am using JRuby with true threads, so I would like have this run on it's own thread inside the JVM, rather than spin up another JVM.

Is that possible?

**Comment by phstc** [comment]
@thomas07vt I'm not that familiar with JRuby, but wouldn't `Thread.new` be a real OS thread, when running Shoryuken with using JRuby?

Anyway feels wrong to me to spawn Shoryuken from an existing process.

**Comment by mariokostelac** [comment]
@thomas07vt we are not officially supporting JRuby, but I'd say we're ready to accept contributions pushing us in that direction.

**Comment by tjsingleton** [comment]
Sounds what you want is something like https://github.com/brandonhilkert/sucker_punch but with shoryuken's durability.

**Comment by thomas07vt** [comment]
yep, exactly @tjsingleton

**Comment by algorist** [comment]
One use case that I'm struggling with is writing functional tests that send messages which the worker then works. I'd like to programmatically start and stop the worker and use a mocked SQS, all of which seems easiest to do if it's all in the same process. Is there a way to do this, or a better approach?

**Comment by phstc** [comment]
@algorist can't you unit test your workers `YourWorker.new.perform(...)` directly?

**Comment by algorist** [comment]
That's fine for unit tests, but I'm writing an overarching functional/quasi-integration test to ensure that everything is working as expected, including that message producer produces the right message, puts it into the right queue, and the worker is working that queue and correctly processing the message.

**Comment by phstc** [comment]
@algorist Makes sense! Have a look at [this](https://github.com/phstc/shoryuken/blob/master/spec/integration/launcher_spec.rb#L5), I used it for real end-to-end testing with Shoryuken.  If that works, maybe we could add it as an example [here](https://github.com/phstc/shoryuken/wiki/Testing), WDYT?

**Comment by algorist** [comment]
Ah, thanks @phstc! I'll give that a look and see if I can get something similar working in my system. If I can, I'll see if I can write up an illustrative example for the Testing guide if you'd like.

**Comment by phstc** [comment]
>  I'll see if I can write up an illustrative example for the Testing guide if you'd like.

@algorist I would love that!
