### ISSUE TITLE
Remove Aws.config

### ISSUE THREAD

**Issue by phstc** [phstc/shoryuken#293]
We should drop any AWS credentials setup from Shoryuken, like this:

```ruby
Shoryuken.configure_client do |config|
  config.aws = {
```

In favor of leveraging [`Aws.config`](https://docs.aws.amazon.com/sdkforruby/api/index.html#Configuration). 

aws-sdk is very powerful and supports a few different ways to configure it, we shouldn't duplicate this logic in Shoryuken. This would also "resolve" the problem about people complaining that they've configured the creds in `shoryuken.yml`, but it isn't picked up in client mode (Rails), they would know that they need to configure that by themselves. 

- [x] Drop https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/aws_config.rb
- [x] Update README and Wiki references related to the Aws credentials/config setup. Explaining how to use the `Aws.config`
  - Add a link to [Aws.config](https://docs.aws.amazon.com/sdkforruby/api/index.html#Configuration) for more details
  - Explain that it should be configured using an initializer or ENV variables or IAM roles or any other way described in aws-sdk that's more convenient for them. As long as it's properly configured, Shoryuken will use it.
- [x] Remove SNS references in the code. Shoryuken does not use SNS, people must refer to aws-sdk instead

The maximum we can provide is a setter `sqs=` to allow people to set the  [SQS Client](https://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html), in case the have a specific need, such as `sqs_endpoint` or they want to have different credentials other than the ones in `Aws.config`. I'm not totally convinced about this setter yet, but that is the maximum we can provide.

We currently support `receive_message` in the `shoryuken.yml`, but I think people only use it to for attributes, and because of the FIFO queue, we [ask for all by default](https://github.com/phstc/shoryuken/blob/thread-pool/lib/shoryuken/queue.rb#L52).

**Comment by phstc** [comment]
@mariokostelac WDYT? This should be part of the next version 3.0.0, all together which would also include #291.

If ok with that and if you have a spare time, could you work on that?

**Comment by mariokostelac** [comment]
@phstc give me few days to take a look, probably end of the week.

**Comment by mbriggs** [comment]
I have most of my AWS resources in a different region from my SQS queues, since amazon only supports FIFO in a few regions. If you go this way, please provide a way to override region ONLY for shoryuken :)

**Comment by phstc** [comment]
@mbriggs would `Shoryuken.sqs= ...` expecting a `Aws::SQS::Client.new` work for you?

**Comment by mbriggs** [comment]
yeah, totally :) just need _some_ kind of way to configure stuff outside of the global sdk configuration
