### ISSUE TITLE
Is there a way to get the worker's instance id?

### ISSUE THREAD

**Issue by chinshr** [phstc/shoryuken#298]
Inside a perform, I would like to do something with the current worker's "instance id", e.g. my service requires must verify that a state transition has actually been done using this worker.

```ruby
class MyWorker
  include ::Shoryuken::Worker

  def perform
    save_worker_info(worker_id)
  end
end
```

Is there anything I have access to inside my worker, like a current worker's id (worker_id)? If so, whites the scope, how unique is it?

**Comment by phstc** [comment]
@chinshr not sure, if I understood your needs, but if you want a unique ID, you can get it from the `sqs_msg`.

```ruby
class MyWorker
  include Shoryuken::Worker

  shoryuken_options queue: 'my_queue'

  def perform(sqs_msg, body)
    sqs_msg.id
  end
end
```

Your worker does not have any special id, it's just a class that a processor calls it `YourWorker.new.perform(...)`.

**Comment by chinshr** [comment]
Thanks @phstc. I see, I think, the message id does not work in my use case. Sorry, for not explaining in more detail: I have a long running worker, and until it finishes, the message is still available on SQS, so Shoryuken attempts to reschedule the message. Since, that is not desired (unless the process fails), I really want the worker finish the work before carrying and no other worker instance (it would have the same message id) be scheduled with the same message.

```ruby
class LongRunningWorker
  include Shoryuken::Worker

  shoryuken_options queue: -> { queue_name },
    auto_delete: true, body_parser: :json

  def perform(sqs_msg, body)
    lock! do
       do_long_running_stuff
    end
  end

  ...
end
```

The question is, how to I prevent Shoryuken to reschedule the message or provide a safe `lock!` mechanism? I could delete the message the very first thing inside `lock!` (set `auto_delete` false) and re-create the message in case I get a "perform error". Is that the right approach?

**Comment by phstc** [comment]
@chinshr maybe you could bump the [visibility timeout](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html) to something higher preventing the message to become available too quickly. Inflight messages are not available for consumption in SQS.

Another option is to use the option [auto_visibility_timeout](https://github.com/phstc/shoryuken/wiki/Worker-options#auto_visibility_timeout.

WDYT?

**Comment by chinshr** [comment]
@phstc What do you mean by "Inflight messages are not available for consuption in SQS"? 

The reason why I haven't used [`visibility_timeout`](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html) earlier was that the time for consumption is extremely variable, so it could be between 30 seconds and 60+ minutes, maybe longer (you mention those cases). So [`auto_visibility_timeout`](https://github.com/phstc/shoryuken/wiki/Worker-options#auto_visibility_timeout) is probably the better choice.

**Comment by phstc** [comment]
> What do you mean by ...

@chinshr I think, it was just a misunderstanding. I was just reviewing the SQS life cycle: 

- message available -> 
- inflight (until visibility timeout does not expire or you delete the message -> 
- message available (in case the visibility timeout expired)

**Comment by chinshr** [comment]
Thanks. Makes sense.
