### ISSUE TITLE
retry_intervals - option to support a lambda?

### ISSUE THREAD

**Issue by tjsingleton** [phstc/shoryuken#303]
I noticed that the ExponentialBackoffRetry middleware doesn't add any randomness which is common in backoff algorithms to spread out the retries. With the way the code is structured I you'd just need to do something like: 

```ruby
interval = if attempts < retry_intervals.size
               retry_intervals[attempts]
             else
               retry_intervals.last
             end

# Addition: call if callable
interval = interval.call(attempts) if interval.respond_to?(:call)
```

Note this is speculative and nice to have. Users can swap out the existing middleware for another now. I'm happy to implement it and add tests if it's desirable.

**Comment by phstc** [comment]
Hi @tjsingleton 

Great idea.

>  I'm happy to implement it and add tests if it's desirable.

Could you? <3

**Comment by tjsingleton** [comment]
Sure thing. :)

**Comment by felixbuenemann** [comment]
It would also be nice if it would call `to_i` if it does not respond to `call`, because I had my intervals set from an environment var and got a hard to debug error like `ERROR: Process died, reason: comparison of String with 43168 failed`. The problem was easy enough to fix adding a `.map(&:to_i)` in my code that parsed the ENV var, but still it would be nice.

**Comment by phstc** [comment]
hi @felixbuenemann 

Not sure if we can `to_i`, as `retry_intervals` is supposed to be an Array. If you have that in a ENV as a string, I guess you need to `ENV['RETRY_INTERVALS'].split(',').map(&:to_i)` as it seems you are doing already. How could Shoryuken auto `to_i`?

**Comment by phstc** [comment]
@tjsingleton could you review #329? The PR adds the lambda support you asked for. Basically, if it `responds_to?(:call)`, the `ExponentialBackoffRetry` middleware will call it, and use the returned value as the interval. If the lambda returns `nil`, it does not auto retry, it just raise up the exception.

```ruby
class MyWorker
  include Shoryuken::Worker

  shoryuken_options queue: 'default', retry_intervals: ->(attempts) { do_something }
  # shoryuken_options queue: 'default', retry_intervals: [360, 1200, 3600] 

  def perform(sqs_msg, body); end
end
```

**Comment by felixbuenemann** [comment]
> Not sure if we can to_i, as retry_intervals is supposed to be an Array. If you have that in a ENV as a string, I guess you need to ENV['RETRY_INTERVALS'].split(',').map(&:to_i) as it seems you are doing already. 

I was talking about handling the conversion of the single value to int when used, not converting the values in the array stored in the options.

> How could Shoryuken auto to_i?

You just did it in 589bd02 so I guess you figured it out :smile:

**Comment by phstc** [comment]
Wiki updated https://github.com/phstc/shoryuken/wiki/Worker-options#retry_intervals
