### ISSUE TITLE
Excessive logging when 0 messages found.

### ISSUE THREAD

**Issue by tigris** [phstc/shoryuken#306]
Similar to https://github.com/phstc/shoryuken/issues/9 I found that I was seeing a log message for "Found 0 messages" every second.

I investigated some alternatives, such as adding a `delay` option or decreasing my log level from `INFO` to something more production ready, like `WARN` for example.

However, during my investigation, I came across the following commit: https://github.com/phstc/shoryuken/commit/ef73e173c3c4624d278baf5088a330cffcc5a5b2#diff-3ad4c83632b5d7b72e1a4afa76344726L22

Which, if you check closer on that commit, it is removing an `if` block that was surrounding the noisy log message. Prior to this commit, the `Found "#{count}" messages` log would only happen when there were `> 0` messages. However, now we are seeing this log every single fetch.

For now I am going to just decrease my log level, but I am curious if this change was intended. If not, would you consider making it be a bit quieter or is it not really much of an issue?

**Comment by phstc** [comment]
Hi @tigris 

I agree, it's noisy. I'm removing it again [here](https://github.com/phstc/shoryuken/pull/291/commits/93bb04174aa0417ce2e49b01766646bc194f40ba) - @tjsingleton [raised that up too](https://github.com/phstc/shoryuken/pull/291#discussion_r95239873). That PR may take a while to be merged, as it's part of major change removing Celluloid.

If you can submit a PR only changing that, I would be happy to merge 🍻

**Comment by phstc** [comment]
@tigris @tjsingleton it's fixed in 2.1.3.
