### ISSUE TITLE
Auto prefixing queue does not work on non ActiveJob worker

### ISSUE THREAD

**Issue by knightq** [phstc/shoryuken#309]
... or at least, I think so!

I have a `Rails 4.2.7.1` project on `ruby 2.3.3` and `shoryken 2.1.2` with  the following config:

```ruby
# /config/initializers/00_shoryuken.rb
Shoryuken.configure_client do |config|
  config.aws = {
    secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
    access_key_id:     ENV['AWS_ACCESS_KEY_ID'],
    region:            ENV['AWS_REGION'],
    receive_message: {              # See http://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#receive_message-instance_method
      # wait_time_seconds: N,       # The number of seconds to wait for new messages when polling. Defaults to the #wait_time_seconds defined on the queue
      attribute_names: [
        "ApproximateReceiveCount",
        "SentTimestamp"
      ]
    }
  }
end

Shoryuken.configure_server do |config|
  # Replace Rails logger so messages are logged wherever Shoryuken is logging
  # Note: this entire block is only run by the processor, so we don't overwrite
  #       the logger when the app is running as usual.

  Rails.logger = Shoryuken::Logging.logger
  Rails.logger.level = Rails.application.config.log_level

  config.aws = {
    secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
    access_key_id:     ENV['AWS_ACCESS_KEY_ID'],
    region:            ENV['AWS_REGION']
  }
end

Shoryuken.active_job_queue_name_prefixing = true

```

Here is also the `config/shoryuken.yml`:
```yaml
concurrency: 25  # The number of allocated threads to process messages. Default 25
delay: 5         # The delay in seconds to pause a queue when it's empty. Default 0
queues:
  - [default, 3]
  - [report, 3]
  - [critical_report, 2]
  - [export, 1]
  - [mailer, 1]
  - [analytic, 1]
```

I've already created (since otherwise the process that runs shoryuken gets upset) the following queues on SQS (prefixed, as you can see):

  - `development_default`
  - `development_report`
  - `development_critical_report`
  - `development_export`
  - `development_mailer`
  - `development_analytic`

I have even added (even if I'm not sure it is necessary) in the `application.rb`:

```ruby
# config/application.rb
module MyApplication
  class Application < Rails::Application
    # ...
    config.active_job.queue_name_prefix = Rails.env
    # ...
end
```

So far, so good.
The ActiveJob worker works fine and uses the right (prefixed) queues.

The problems come when I use an 'old-fashion' (non ActiveJob) worker:
I.E., I also have a worker `MyWonderfulWorker` so made:

```ruby
class MyWonderfulWorker
  include Shoryuken::Worker

  def perform(sqs_msg, a_record_id)
    # do some wonderful stuff...
  end
end
```

Each time I try - from a Rails controller - to invoke:
```ruby
MyWonderfulWorker.perform_async(an_id)
```

I get this error:

```ruby
Aws::SQS::Errors::NonExistentQueue (The specified queue 'default' does not exist.)
```

It looks like shoryuken does not consider the auto prefix.

Does it works only for ActiveJob workers?
Shall I explicitly set the queue name on each worker, by manually prefixing the env? (like this: `  shoryuken_options queue: "#{Rails.env}_export", auto_delete: true`)

Thank you

**Comment by knightq** [comment]
I guess that my answer may be [this one](https://github.com/phstc/shoryuken/issues/168#issuecomment-166974429)....

**Comment by phstc** [comment]
Hi @knightq 

How did you solve that? [I think it's only works for AJ](https://github.com/phstc/shoryuken/blob/a3d9238adc669214e91e321439cc3f44bcca3ad4/lib/shoryuken/environment_loader.rb#L97). As I don't use it, I'm not that familiar. But I would be happy to help.

In development, I current use [the `inline` adapter from AJ](http://edgeapi.rubyonrails.org/classes/ActiveJob/QueueAdapters/InlineAdapter.html). But before, I've used to get the queues names from `ENV`, so each dev would have their queue names in a `.env` file. Other option is also a `shoryuken.yml` per dev, like git ignoring it from the repo.
