### ISSUE TITLE
how to disable logging of message body?

### ISSUE THREAD

**Issue by wilsonch** [phstc/shoryuken#310]
Is it possible to disable logging of the message body? I'm using version 2.1.3 and Rails 5.
Thanks in advance.

**Comment by phstc** [comment]
hi @wilsonch 

Shoryuken does not log the message body. Is there any chance you have a worker or custom middleware doing that?

**Comment by wilsonch** [comment]
Hi thanks for the response!

I don't believe I have any middlewares.  How can I check for sure?

shoryuken.yml
```
concurrency: 25
delay: 0
queues:
  - [mailers, 5]
```

FWIW, the log message comes out as:

`App 144 stdout: I, [2017-01-30T22:25:37.868634 #144] INFO -- : [a9d73b90-7dbf-400f-ac70-461478d931ff] [ActiveJob] [Aws::SQS::Client 200 0.038227 0 retries] send_message(message_body:"{\"job_class\":\"ActionMailer::DeliveryJob\",\"job_id\":\"2bd002fa-c881-48af-91f2-1527bddd5bbe\",\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"EnquiryMailer\",\"enquiry_email\",\"deliver_now\",{\"_aj_globalid\":\"gid://abc/dev/123\"},{\"email\":\"sss@sss.ss\",\"message\":\"sss\",\"validation_context\":null,\"errors\":{\"_aj_symbol_keys\":[]},\"_aj_symbol_keys\":[]}],\"locale\":\"en\"}",message_attributes:{"shoryuken_class"=>{string_value:"ActiveJob::QueueAdapters::ShoryukenAdapter::JobWrapper",data_type:"String"}},queue_url:"https://sqs.ap-southeast-2.amazonaws.com/12345/mailers") `

**Comment by phstc** [comment]
@wilsonch that does not seem a log from Shoryuken. Any chance you've enabled aws-sdk debug logging?

https://aws.amazon.com/pt/blogs/developer/logging-requests/

**Comment by wilsonch** [comment]
Yea, must have somehow; it's good to know that shoryuken is not logging it.  Thanks for answering my queries.

**Comment by phstc** [comment]
@wilsonch thanks for letting me know! 🍻

**Comment by phstc** [comment]
Hi @wilsonch 

Another possibility for silencing the the SQS: https://github.com/phstc/shoryuken/issues/353#issuecomment-294315486.

(thanks @pedros007 for linking the issues 🍻 )
