### ISSUE TITLE
Erro when process a worker

### ISSUE THREAD

**Issue by adimircolen** [phstc/shoryuken#313]
I have a error when process the job

`ERROR: Process died, reason: undefined method `new' for nil:NilClass`
I send a message to SQS like this
`Shoryuken::Client.queues("#{Rails.env}_default").send_message(@params[:gcm])`

on Shoryuken::DefaultWorkerRegistry.fetch_worker at line 27 `worker_class.new` and `worker_class` is nil, 

```
class CreateEndpointJob < ActiveJob::Base
  queue_as :default

  rescue_from ActiveJob::DeserializationError do |ex|
    Shoryuken.logger.error ex
    Shoryuken.logger.error ex.backtrace.join("\n")
  end

  def perform(sqs_msg, body)
    ...
  end
end
```

**Comment by phstc** [comment]
hi @adimircolen 

Which version of Shoryuken are you using? For me the live 27 seems to be different than yours https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/default_worker_registry.rb#L27

You can try this in your worker:

```ruby
  def perform(data)
    ...
  rescue e
    Shoryuken.logger.error e
    Shoryuken.logger.error e.backtrace.join("\n")
  end
```

BTW the `perform` signature for ActiveJob does not have `sqs_msg`, see this https://github.com/phstc/shoryuken/wiki/Rails-Integration-Active-Job#active-job-support

**Comment by adimircolen** [comment]
`shoryuken (2.1.3)`
https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/default_worker_registry.rb#L23

**Comment by phstc** [comment]
@adimircolen is there any chance you have messages in that queue that were enqueued not using Shoryuken? That would cause that error.

**Comment by adimircolen** [comment]
No my sqs is empty.
Now it's working, but when I use the Shoryuken client on default_register https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/default_worker_registry.rb#L23
worker_class is nil

`Shoryuken::Client.queues('development_default').send_message(message_body: { gcm: @params[:gcm] })`
I use `CreateEndpointJob.perform_later({ gcm: @params[:gcm], resource: @resource.class.to_s, id: @resource.id })` to enqueue 
I think is related to param `message_attributes['shoryuken_class'][:string_value]`
