### ISSUE TITLE
Using local SQS

### ISSUE THREAD

**Issue by AaronBetterOfficeApps** [phstc/shoryuken#314]
I'm trying to use shoryuken on localhost with localstack for a development, but I getting a number of errors. I have the following setup that I'm using to test the usage. 

`config/initializers/shoryuken.rb`

```
Shoryuken.configure_client do |config|
  config.aws = {
    secret_access_key: "ask",       # or ENV["AWS_SECRET_ACCESS_KEY"]
    access_key_id:     "akid",      # or ENV["AWS_ACCESS_KEY_ID"]
    region:            "region",    # or ENV["AWS_REGION"]
    sqs_endpoint:      "http://localhost:4576",
    receive_message: {              # See http://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#receive_message-instance_method
      # wait_time_seconds: N,       # The number of seconds to wait for new messages when polling. Defaults to the #wait_time_seconds defined on the queue
      attribute_names: [
        "ApproximateReceiveCount",
        "SentTimestamp"
      ]
    }
  }
end
```

`app\jobs\test_job.rb`

```
  class TestJob
    include Shoryuken::Worker

    shoryuken_options queue: 'default', auto_delete: true
    # shoryuken_options queue: ->{ "#{ENV['environment']}_default" }

    # shoryuken_options body_parser: :json
    # shoryuken_options body_parser: ->(sqs_msg){ REXML::Document.new(sqs_msg.body) }
    # shoryuken_options body_parser: JSON

    def perform(sqs_msg, body)
      puts body
    end
  end
```

If I use `shoryuken -R -q default` to start shoryuken I get the following error:

`missing region; use :region option or export region name to ENV['AWS_REGION']`

Then

`AWS_REGION=region  shoryuken -R -q default`

produces

```
Encountered a `SocketError` while attempting to connect to:

  https://sqs.region.amazonaws.com

This is typically the result of an invalid `:region` option or a
poorly formatted `:endpoint` option.

* Avoid configuring the `:endpoint` option directly. Endpoints are constructed
  from the `:region`. The `:endpoint` option is reserved for connecting to
  non-standard test endpoints.

* Not every service is available in every region.

* Never suffix region names with availability zones.
  Use "us-east-1", not "us-east-1a"

Known AWS regions include (not specific to this service):

ap-northeast-1
ap-northeast-2
ap-south-1
ap-southeast-1
ap-southeast-2
eu-central-1
eu-west-1
sa-east-1
us-east-1
us-east-2
us-west-1
us-west-2
us-gov-west-1
cn-north-1
```

Then with `AWS_REGION=sa-east-1 shoryuken -R -q default`

produces

 `The specified queue(s) ["default"] do not exist`

but I have created that queue on the localstack service

I can get this to work directly with the `aws-sdk` with the following 

```
Aws::SQS::Client.remove_plugin(Aws::Plugins::SQSQueueUrls)
sqs = Aws::SQS::Client.new(endpoint: 'http://localhost:4576', region: 'region')
queue_url = sqs.create_queue(queue_name: "default")[:queue_url]

sqs.send_message(
    queue_url: queue_url,
    message_body:"Test Message"
)



sqs.send_message({
  queue_url: queue_url, # required
  message_body: "String", # required
  delay_seconds: 1,
  message_attributes: {
    "String" => {
      string_value: "String",
      binary_value: "data",
      string_list_values: ["String"],
      binary_list_values: ["data"],
      data_type: "String", # required
    },
  }
})

resp = sqs.receive_message({
  queue_url: queue_url
  })
```

`Aws::SQS::Client.remove_plugin(Aws::Plugins::SQSQueueUrls)` is required to allow for the local endpoint work in place of the official aws endpoints.

I had tried to use this by adding `Aws::SQS::Client.remove_plugin(Aws::Plugins::SQSQueueUrls)` to the shoryuken initializer.  

I was hopping my first example would be enough to get this to work with a local SQS. 
Can you let me know if this is possible and if so how can I get it to work.

Cheers

**Comment by phstc** [comment]
@AaronBetterOfficeApps I've never used `localstack`, but if this `Aws::SQS::Client.remove_plugin(Aws::Plugins::SQSQueueUrls)` is required, you may try to make patch [this](https://github.com/phstc/shoryuken/blob/cea4f5f475b2e756f82e367152db831f9e2cc6f5/lib/shoryuken/aws_config.rb#L49).

**Comment by cjlarose** [comment]
Calling `Aws::SQS::Client.remove_plugin(Aws::Plugins::SQSQueueUrls)` should no longer be necessary. See https://github.com/aws/aws-sdk-ruby/pull/1075.

**Comment by phstc** [comment]
@cjlarose Thanks a lot of the update 🍻  Would you mind to write a wiki entry covering this configuration to help others facing this issue?

**Comment by cjlarose** [comment]
@phstc I can add a wiki page. I'll probably wait, though, until my change is merged to moto. That'll make the setup easier for anyone trying to do it.

**Comment by cjlarose** [comment]
My PR for `moto` was merged! I added a wiki page with instructions on using local SQS queues.

https://github.com/phstc/shoryuken/wiki/Using-a-local-mock-SQS-server

**Comment by phstc** [comment]
@cjlarose awesome, thanks! 🍻

**Comment by gbxl** [comment]
I'm using straight moto and with a yml like
```
aws:
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: <%= ENV['AWS_REGION'] %>
concurrency: <%= ENV['WORKER_CONCURRENCY'] || 10 %>
endpoint: http://localhost:4576
verify_checksums: false
queues:
  - [<%= ENV['RAILS_ENV'] %>_urgent_priority, 10]
  - [<%= ENV['RAILS_ENV'] %>_high_priority, 6]
  - [<%= ENV['RAILS_ENV'] %>_medium_priority, 2]
  - [<%= ENV['RAILS_ENV'] %>_low_priority, 1]
```
I cannot get shoryuken to find the queues. If I run a curl agains't my localhost I do get the queues
```
➜  ~ curl -X POST http://localhost:4576/\?Action\=ListQueues
<ListQueuesResponse>
    <ListQueuesResult>
            <QueueUrl>http://localhost:4576/123456789012/development_high_priority</QueueUrl>
            <QueueUrl>http://localhost:4576/123456789012/development_medium_priority</QueueUrl>
            <QueueUrl>http://localhost:4576/123456789012/development_low_priority</QueueUrl>
    </ListQueuesResult>
    <ResponseMetadata>
        <RequestId></RequestId>
    </ResponseMetadata>
</ListQueuesResponse>%```

Any clue?
