### ISSUE TITLE
Multiple Fetchers

### ISSUE THREAD

**Issue by mbriggs** [phstc/shoryuken#316]
First off, thanks for this project :) it is currently massively helping a move from rabbit to sqs.

We use SQS both for internal worker queues in a rails app, as well as inter-app communication queues, so to keep costs down we use long polling. The rails app has two queues, normal and high priority, but the current strategy + long polling adds 20s to the response time to all message processing.

Is the only answer here "stop using long polling"? Or can we specify somehow to use one fetcher per queue, so they can concurrently long poll?

**Comment by phstc** [comment]
@mbriggs Shoryuken does not support multiple fetchers. Maybe you could try two Shoryuken processes in parallel to reduce the delays.

``` 
# shoryuken.a.yml
queues:
  - [high, 10]
  - [normal, 1]

# shoryuken.b.yml
queues:
  - [high, 1]
  - [normal, 10]
```

I don't particularly use long polling. Are you using it to save some requests?

**Comment by mbriggs** [comment]
yeah, using it to save requests. only one service uses shoryuken, thinking maybe ill just do a 1 second poll on that one, which isnt the end of the world by any means.

**Comment by phstc** [comment]
@mbriggs if the idea is only to save requests, you could try to remove the long poll and increase the delay. The delay is used to pause queues when they are empty.

**Comment by mbriggs** [comment]
Just in case anyone googles this later, this is my final reasoning: on most of our services, single threaded-ness is actually a feature, so using something home grown for them. If everything was constantly polling would be a very significant amount of "junk" requests, but shoryuken is only deployed in one place. So some napkin math for a full month of 1 junk request per second * 2 got me to 2.08$. REALLY not a big deal, only gets significant when you have hundreds of pollers (which we can have at times)
