### ISSUE TITLE
Easy way to check whether we are in the server (consumer) process?

### ISSUE THREAD

**Issue by elsurudo** [phstc/shoryuken#319]
I think this would be useful to have. Thoughts?

If this already exists (or there is a simple way to satisfy the requirement), then I apologize (let me know!).

**Comment by phstc** [comment]
hey @elsurudo 😄  

There's no flag for that currently. But it's something straightforward to add. What's the use case on that?

**Comment by elsurudo** [comment]
Hi Pablo :)

Essentially, I would like to handle errors that happen within shoryuken in a specific way in development mode only, for testing purposes. I want them to be big and loud, so that I know that they are occurring.

But I don't want exceptions to be handled the same way _outside_ shoryuken, because those exceptions are already obvious (I see them in the browser when they occur).

**Comment by phstc** [comment]
@elsurudo can you use a different logger in development mode?

Just to clarify, do you want to distinguish dev vs prod modes or consumer vs producer?

**Comment by elsurudo** [comment]
Actually, both :)

I actually want errors on the _consumer_ in _dev_ only to be sent as emails (which actually open in my browser because of the letter_opener gem), so I instantly know that the occurred.

Heh, I do realize it may be a bit of a convoluted and niche use-case.

**Comment by phstc** [comment]
@elsurudo can't you `LOG_EMAIL=true shoryuken ...` in development, then in the place you log, do an `if` based on `ENV['LOG_EMAIL']`? Are you locking through a middleware?
