### ISSUE TITLE
 systemd integration

### ISSUE THREAD

**Issue by dimidd** [phstc/shoryuken#320]
Hi, I'd like to restart shoryuken after a restart and after a deploy (preferably with [capistrano-shoryuken](https://github.com/joekhoobyar/capistrano-shoryuken)). Is there an equivalent for [the sidekiq systemd unit file](https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service)?

**Comment by phstc** [comment]
Hi @dimidd 

There's not. But I guess it's just a matter of `s/sidekiq/shoryuken/g` in the systemd unit file you linked.

Besides the search and replace, you may need to change [this line](https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service#L31) as well, for something like `ExecStart=/usr/local/bin/bundle exec shoryuken -C /path/shoryuken.yml ...`.

Please let me know if you create a system unit file, so I can update [this wiki](https://github.com/phstc/shoryuken/wiki/Deployment) with the instructions.

**Comment by dimidd** [comment]
Thanks, I'm using this one, which seems to work, but I still have to test it thoroughly.
https://gist.github.com/dimidd/2cd37e171ca4cb2dbd12133da4cd877e

**Comment by phstc** [comment]
@dimidd nice! I linked your gist in [here](https://github.com/phstc/shoryuken/wiki/Deployment#systemd-integration).

**Comment by aivils** [comment]
FYI
foreman will export Procfile to systemd for You!
I used foreman 0.84.0 out of the box
I added to my capistrano deploy.rb some lines:
```
namespace :foreman do
  desc "Export the Procfile to Ubuntu's systemd scripts"
  task :export do
    on roles(:app) do
      within release_path do
        with rails_env: fetch(:stage) do
          execute :sudo, '/home/boss/.rvm/bin/rvm 2.4.2 do bundle exec foreman export systemd /etc/systemd/system ' +
        "-f Procfile.#{fetch(:stage)} -a #{fetch(:application)}-#{fetch(:stage)} -u #{fetch(:user)} -l #{shared_path}/log -e #{shared_path}/.env --root #{current_path}"
        end
      end
    end
  end
end
```

Where #{shared_path}/.env have entries with standard KEY=value syntax 

Content of Procfile.staging
```
web: /home/boss/.rvm/bin/rvm 2.4.2 do bundle exec unicorn -c ./config/unicorn.rb
worker: /home/boss/.rvm/bin/rvm 2.4.2 do bundle exec shoryuken --rails -C config/shoryuken.yml
```

This command will create all files for systemd:
```
cap staging foreman:export
```

What we have in the sytemd
```
ls -1 /etc/systemd/system/boss*
/etc/systemd/system/boss-staging.target
/etc/systemd/system/boss-staging-web@.service
/etc/systemd/system/boss-staging-web.target
/etc/systemd/system/boss-staging-worker@.service
/etc/systemd/system/boss-staging-worker.target

/etc/systemd/system/boss-staging-web.target.wants:
boss-staging-web@3010.service

/etc/systemd/system/boss-staging-worker.target.wants:
boss-staging-worker@3110.service

```
