### ISSUE TITLE
Shoyuken still leaking memory

### ISSUE THREAD

**Issue by paul** [phstc/shoryuken#324]
I've been following the various issues regarding memory leaks in shoryuken, they seem to be closed and merged, but I'm still running into some pretty horrendous memory leaks.

I'm using the ActiveJob adapter in Rails 5.0.1, Shoryuken 2.1.3, and Celluloid 0.17.3.

I added some instrumentation to my jobs to record the memory usage at the start of my job, and at the end before & after a `GC.start`.

![2017-03-01 at 4 58 pm](https://cloud.githubusercontent.com/assets/184/23487014/bd621afc-fea0-11e6-9872-fd0949db59c7.png)

The graphs in this screenshot are of my 2 production servers, in order:

1. shoryuken process memory usage as reported by collectd. 
2. memory usage at the beginning of each job as reported by the `get_memory_info` gem
3. delta of memory used between start and end of the `#perform`, before GC
4. delta of memory used between start and end of the `#perform`, after GC
5. number of jobs performed per minute

As you can see, I'm not performing very many jobs, and my job code seems to mostly clean up after itself, the delta is right around 0mb, occasionally there's an increase of 16MB or so. As there's not much traffic, shoryuken is mostly just polling empty queues. However, it seems to have leaked 8GB of memory in about 6 hours. About 4 hours later, the OOM killer nukes the process. 

"Production" in this case is 2 `m4.large` AWS instances running Centos 7.2. This seems to be relevant, because I've left my OSX machine running against queues with 0 jobs, and while it seems to leak 4kb (an OS page maybe?) every 20-30 seconds, I certainly don't see the runaway memory usage exhibited on linux. I'm going to try updating to Shoryuken 3.0 and see if that fixes it, but I wanted to record this memory issue first.

**Comment by paul** [comment]
![2017-03-01 at 10 51 pm](https://cloud.githubusercontent.com/assets/184/23494721/b6335878-fed1-11e6-97d7-d5e86839da9f.png)

Here's the memory usage (orange line) of Shoryuken v3 branch vs 2.1.3 (blue line).

Feel free to close this issue, or I'm happy to help debug further if there's any interest.

**Comment by phstc** [comment]
@paul awesome debugging! Thanks for sharing ❤️ 

I'm happy to see that v3 isn't using as much memory as v2. Did you get any other insights from v3? 

v3 is almost ready, I will start using it in a production app this week. If everything goes well, I'm planning to release it late next week.

**Comment by phstc** [comment]
@paul v3 is out 🎉  based on [this](https://github.com/phstc/shoryuken/issues/324#issuecomment-283563590) feedback, I believe we can safely close this issue 🙏

**Comment by rodolfoburla** [comment]
It seems that memory leak problem returns on version 3.1.3. I downgraded to version 3.0.11 and the problem ended.

**Comment by phstc** [comment]
@rodolfoburla thanks for reporting that, there's a new issue for memory leak related to 3.1 #401

**Comment by rodolfoburla** [comment]
Thanks, I hadn't find it.
