### ISSUE TITLE
Serial Queue

### ISSUE THREAD

**Issue by sammyd** [phstc/shoryuken#337]
Hi,

Apologies for raising an issue to just ask a question, but I'm not sure whether there is somewhere more appropriate.

We are using shorkyuken to great effect on several rails sites, and I was wondering whether it's possible to set the concurrency on a per-queue basis? I know I can set it for the overall worker process, but I'd really like to make a serial queue, as a trivial way to prevent race conditions with particular jobs.

I'd still want to retain the other concurrent queues, using relative weights as specified in the config file.

If it's not currently possible, is this something that you think would be a useful feature of shoryuken? I'd be happy to put some development effort towards it if you think it is, but I could do with some pointers as to the best way to approach it. No worries if not, I'll investigate alternatives, or create my own fork.

Thanks again for the great work!

**Comment by phstc** [comment]
Hi @sammyd 

> Apologies for raising an issue to just ask a question, but I'm not sure whether there is somewhere more appropriate.

It's totally fine asking in here 🍻 

> We are using shorkyuken to great effect on several rails sites

❤️ 

Shoryuken support custom polling strategies (pending docs #294), you might be able to control a specific queue concurrency through a custom polling strategy. 

I can help you with the a custom polling strategy if that works for you. I can try to push #294, feel free to contribute to it as well, if you feel like, it's always welcome.

**Comment by sammyd** [comment]
Thanks @phstc,

I think that a custom polling strategy might do the trick. I'll have a dig around and see what I come up with.

:+1:

**Comment by rmharrison** [comment]
@sammyd Did you ever implement a custom polling strategy? The wiki is light on documentation and I haven't yet found an example.

**Comment by sammyd** [comment]
Hey @rmharrison—I didn't in the end, no. Instead we ended up switching to sidekiq for this process, since it solved both this issue (as far as I can remember), and also provided the long-term delayed scheduling functionality we needed. Sorry I can't help further :(
