### ISSUE TITLE
Thread exhaustion

### ISSUE THREAD

**Issue by waynerobinson** [phstc/shoryuken#338]
I'm not sure how to describe this in a replicatable way. :(

But we have a Rails and a non-Rails app that we're using v3 of Shoryuken with. 

After processing a number of requests (on a Mac) we are starting to see `Error fetching message: can't create Thread: Resource temporarily unavailable` errors.

Macs only allow a pretty small number of threads per process (I believe its 2048) and it is usually a pretty hard limit.

However, we only have concurrency set to 10 and no pool size configured for the DB.

I'm not sure how we're exhausting threads. :(

**Comment by waynerobinson** [comment]
And I get a feeling it might be time-based rather than job-based.

**Comment by waynerobinson** [comment]
Reviewing further, this might be my issue. 

It's only the non-Rails app and it only seems to be effected when I'm running it with foreman (which is the strangest part of all this).

**Comment by waynerobinson** [comment]
I couldn't find anything specific in the foreman changelogs, but updating the latest version (was only one behind) has resolved this issue.

**Comment by phstc** [comment]
Thanks @waynerobinson for giving all the details 🍻 

I'm happy with it's working fine with the latest foreman. Would you mind to send me the foreman version you were using, and the new one? Just in case someone else face the same.

**Comment by waynerobinson** [comment]
Yeah, I think I've boiled the problem down to something in one of my apps. Neither seems like Foreman or Shoryuken's fault. My early guess is a connection pooling problem with our DB. It was probably an unwise decision to use the mysql2 gem directly. 😅

**Comment by phstc** [comment]
@waynerobinson hm. Not sure if it's the case, but you need to set your database pool as the same size as your concurrency.

**Comment by waynerobinson** [comment]
Yup. It is. And it works for a while. Then something goes out of control and starts spawning a bunch of threads. Sigh.

**Comment by phstc** [comment]
It's been a while since last time I used mysql, but please let me know if I can help with debugging.

**Comment by waynerobinson** [comment]
Thanks. :-)

**Comment by waynerobinson** [comment]
Turns out this issue was caused by an uncaught exception in a library making HTTP calls via Faraday.

I'm unsure as to why this uncaught exception ended up causing this runaway thread problem though. Shouldn't a thread that ends up throwing an exception just get killed off and move on?

I'll see if I can replicate the issue with a simpler setup.

**Comment by phstc** [comment]
> Shouldn't a thread that ends up throwing an exception just get killed off and move on?

It should: 

> Should a thread crash for any reason the thread will immediately be removed from the pool and replaced.
> https://ruby-concurrency.github.io/concurrent-ruby/Concurrent/FixedThreadPool.html

> I'll see if I can replicate the issue with a simpler setup.

that will help 🍻

**Comment by waynerobinson** [comment]
OK, turns out all my attempted problem-solving hasn't managed to solve this issue.

However, I think I have managed to replicate it.

Basically, it seems that when Shoryuken is running against an empty queue it starts to leak threads. Any time the queue is empty, it leaks threads. Whilst it is processing data, it will sometimes stop.

My suspicion is that it has something to do with the heartbeat timer task not getting cleaned up properly when the queue is actually empty and causing a deadlock somewhere, rather than being properly cleaned up.

I can replicate this on Ruby 2.3.1 with the following:
```ruby
Shoryuken.sqs_client_receive_message_opts = {
  wait_time_seconds: 5,
  attribute_names: %w(
    ApproximateReceiveCount
    SentTimestamp
  )
}

class EchoWorker
  include Shoryuken::Worker
  shoryuken_options(
    queue:                    "cashdeck-dev-wayne-leaker",
    auto_delete:              true,
    body_parser:              :json
  )

  def perform(sqs_message, message)
    puts "HI #{Time.now}"
  end
end
```

With the following shoryuken.yml file:
```yaml
verbose: true
concurrency: 10  # The number of allocated threads to process messages. Default 25
delay: 0        # The delay in seconds to pause a queue when it's empty. Default 0
queues:
  - [cashdeck-dev-wayne-leaker, 1]
```

Obviously, you'll need to change the queue.

Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    aws-sdk-core (2.8.8)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sigv4 (1.0.0)
    concurrent-ruby (1.0.5)
    jmespath (1.3.1)
    shoryuken (3.0.3)
      aws-sdk-core (~> 2)
      concurrent-ruby
      thor
    thor (0.19.4)

PLATFORMS
  ruby

DEPENDENCIES
  shoryuken

BUNDLED WITH
   1.14.3
```

**Comment by waynerobinson** [comment]
Also, removing the Receive Message Wait Time from the queue makes this problem go away altogether.

**Comment by waynerobinson** [comment]
Any thoughts on using http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/Actor.html for the main dispatcher loop?

Using TimerTask seems like a bit of a hack (not to mention the implementation is broken). Shouldn't there just be a supervised main loop of requests for new messages?

I know `Concurrent::Actor` is listed as an edge-feature right now, but it seems to be the best fit.

The only other option I can think of is rolling this ourselves either with the dispatch loop on the main thread or via a couple of asynchronous methods watching each other.

The quick and dirty fix to the above would be to just use `Concurrent::ScheduledTask` directly, scheduling a new event at the end of either successfully or unsuccessfully processing the previous one as we don't really need to requests messages every `x` seconds, nor do we need timeout handling in the dispatcher on top of the timeouts already baked into the AWS/HTTP library.

**Comment by phstc** [comment]
Hi @waynerobinson 

Great investigation. I need more time to investigate it better. 

I did an initial implementation with `Concurrent::Actor`, but TBH, I only like the mailbox thing, I have mixed feelings on the messaging across actors. Besides being an edge feature as you pointed out.

`heartbeat` is kinda common for this type of solution, not sure if I would call it hacky.

```ruby
def processor_done
  dispatch
end

def dispatch
  # return if no-queue or worker available and try again in 1 sec
  if no_processor && no_queue
    dispatch_later
    return
  end

  # after finishing requesting
  # call dispatch again
  dispatch
end

def dispatch_later
  @pool.post do
    sleep 1
    dispatch
  end

  # or even sleep in the main thread
  # sleep 1
  # dispatch
end
```

WDYT?

**Comment by waynerobinson** [comment]
Sorry, didn't mean to imply that a heartbeat is hacky, just the use of a periodically running task to manage it.

Ideally you'd have a thread (supervisor) that's responsible for keeping the dispatcher running and restarting it if it crashes. And the dispatcher can just run in a loop.

But given the main loop of Shoryuken is just a dispatch loop anyway, I don't see any specific problem with putting this on the main thread, unless you want to implement a pool of dispatchers at a later date.

I don't think the above code would work in Ruby as it doesn't like deep recursion (unlike Erlang/Elixir) and you'll get a stack level too deep issue.

But something like:

```ruby
def processor_done
  dispatch_loop
end

def dispatch_loop
  loop
    if no_processor && no_queue
      sleep 1
    else
      dispatch
    end
  end
end

def dispatch
  # Actual dispatch code
end
```

**Comment by phstc** [comment]
> Sorry, didn't mean to imply that a heartbeat is hacky, just the use of a periodically running task to manage it.

No need for sorry. I got your point 😄 

Cool, I will play with it.

**Comment by waynerobinson** [comment]
No problem.

Also, didn't quite understand what `processor_done` was for but I don't think the above code makes sense to put in there.

Basically, we just need to find somewhere at the end of booting everything the dispatch loop can start in. Or run it in its own thread somewhere.

**Comment by phstc** [comment]
@waynerobinson for how long did you have to keep it running to replicate the issue?

**Comment by waynerobinson** [comment]
It happens very quickly on an empty queue. 

Make sure the Receive Wait Time on the queue is set quite high (like 20 seconds) to make it worse. It increases at hundreds of threads per receive cycle. 

Add another TimerTask that just prints out `Thread.list.size` to see the threads in use. 

This was specifically with MRI, not sure if other rubies have lower thread limits on the default pools, but you should still experience a memory leak as the pool's queue size would grow.

**Comment by waynerobinson** [comment]
It basically doesn't occur if there are messages in a queue to process or the Receive Wait Time is set to 0.

**Comment by waynerobinson** [comment]
Changed `run.rb` to the following:

```ruby
Shoryuken.sqs_client_receive_message_opts = {
  wait_time_seconds: 20
}

class EchoWorker
  include Shoryuken::Worker
  shoryuken_options(
    queue:                    "cashdeck-dev-wayne-leaker",
    auto_delete:              true,
    body_parser:              :json
  )

  def perform(sqs_message, message)
    puts "HI #{Time.now}"
  end
end

task = Concurrent::TimerTask.new(execution_interval: 1) do
  Shoryuken.logger.debug "Threads: #{Thread.list.size}"
end
task.execute
```

And the output of a few cycles: https://gist.github.com/waynerobinson/20362b034694664bc87395032393a8fd

**Comment by phstc** [comment]
@waynerobinson awesome, I could reproduce that. I'm on it.

**Comment by waynerobinson** [comment]
Cheers. 👍

**Comment by phstc** [comment]
@waynerobinson 3.0.4 is out with your fix! 🍻 

https://github.com/phstc/shoryuken/blob/master/CHANGELOG.md
