### ISSUE TITLE
Default queues

### ISSUE THREAD

**Issue by waynerobinson** [phstc/shoryuken#346]
Stupid question I should probably already know the answer to.

But if I don't specify a queue in `shoryuken_options` does it just use the complete, default list specified in `shoryuken.yml`?

**Comment by phstc** [comment]
@waynerobinson if you don't specify a queue in the `shoryuken_options`, Shoryuken won't match the worker with any queue, so the worker will be useless.

**Comment by waynerobinson** [comment]
Ahh, that's what I thought. 

I've always specified queues, but then got confused as to how to make things using priority queues, etc work. Then I saw that there was a `"default"` value specified in the codebase and wondered if there was something special about this that caused the default to be everything.

Cheers. 👍
