### ISSUE TITLE
Default exception and its backtrace logging

### ISSUE THREAD

**Issue by unijewski** [phstc/shoryuken#352]
Hello. So far I used Sidekiq with ActiveJob where all exceptions were logging with their backtrace, regardless of using `rescue_from` and raising errors. After migrating to Shoryuken by default I'm getting only a short status information, e.g. 
```
2017-04-07T16:36:04Z 4163 TID-oxciegseg ActiveJob/ExampleJob/my_queue/9623e444-9216-4be3-b4a6-6f85ed3bcfe6 INFO: failed in: 1317.8410000000001 ms
```
unless I perform explicitly:
```
Shoryuken.logger.error exception
Shoryuken.logger.error exception.backtrace.join("\n")
```
 in a `rescue_from` block. Is there a way to log that everywhere by default?

**Comment by phstc** [comment]
Hi @unijewski 

Good catch. It seems it got mistakenly dropped in v3.

I'm adding it back here #355.

It will be back in v3.0.5 (soon this week).

**Comment by unijewski** [comment]
Cool, thanks! 👍
