### ISSUE TITLE
Silence receive_message from log

### ISSUE THREAD

**Issue by pedros007** [phstc/shoryuken#353]
I start Shoryuken v2.1.3 like this

    shoryuken -R -C config/shoryuken.yml

and it generates log messages every 20 seconds like this
```
[Aws::SQS::Client 200 0.452184 0 retries] receive_message(max_number_of_messages:1,message_attribute_names:["All"],attribute_names:["All"],queue_url:"https://sqs.us-east-1.amazonaws.com/000011112222/my-queue-Queue-K1AB9G02OU8S")
```

How can I silence these messages?  

```
ruby --version
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
rails --version
Rails 4.2.8
```

Snippet from Gemfile.lock:
```
...
    aws-sdk-core (2.9.5)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-rails (1.0.1)
      aws-sdk-resources (~> 2)
      railties (>= 3)
    aws-sdk-resources (2.9.5)
      aws-sdk-core (= 2.9.5)
    aws-sigv4 (1.0.0)
...
    shoryuken (2.1.3)
      aws-sdk-core (~> 2)
      celluloid (~> 0.17)
...
    rails_stdout_logging (0.0.5)
...
```

config/shoryuken.yml

```concurrency: 1
delay: 20
queues:
  - https://sqs.us-east-1.amazonaws.com/000011112222/my-queue-Queue-K1AB9G02OU8S
```
config/initializers/shoryuken.rb

```
Shoryuken.configure_client do |config|
  config.aws = {
    # See http://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#receive_message-instance_method
    receive_message: {
      visibility_timeout: 1
    }
  }
end
```

**Comment by phstc** [comment]
Hi @pedros007 

> [Aws::SQS::Client 200 0.452184 0 retries] receive_message(max_number_of_messages:1,message_attribute_names:["All"],attribute_names:["All"],queue_url:"https://sqs.us-east-1.amazonaws.com/000011112222/my-queue-Queue-K1AB9G02OU8S")

☝️ that feels like a log from `aws-sdk` itself, not from Shoryuken, could you check [this](https://github.com/phstc/shoryuken/issues/310#issuecomment-276269598). Maybe you got the `aws-sdk` debugging logging.

**Comment by pedros007** [comment]
Thanks for the tip, @phstc.  My code does not modify the global AWS config.  I did not see any AWS logging with Sheryuken 2.0.11.  I only see the extra aws-sdk logs when running Sheryuken >= 2.1.0 and <= 2.1.3.  I have not had a chance to test with version >= 3 yet.

**Comment by phstc** [comment]
@pedros007 any chance you have other gem settings `AWS.config(log_level: :debug)`?

> version >= 3 yet.

**Comment by pedros007** [comment]
I tried the just-released v 3.0.5, and I still see `Aws::SQS::Client` methods logged.  Just ran `grep -i aws $(find / -name \*.rb) | grep -i config` to find the only place the default logging config is overridden, [here in aws-sdk-rails](https://github.com/aws/aws-sdk-rails/blob/master/lib/aws-sdk-rails.rb#L33). I tried logging `Aws.config.keys` in my Shoryuken initializer and the only key that exists is `logger`.  [This forum exchange](https://forums.aws.amazon.com/thread.jspa?threadID=88460) suggests `Aws.config` only sets the defaults.

I'm confused because if I set `gem 'shoryuken', '=2.0.11'` in my Gemfile, I see no AWS logging.  However, when I set the version to `'>2.0.11'`, `Aws::SQS::Client` seems to log its public methods (`receive_message`, `get_queue_url`, etc.)

**Comment by phstc** [comment]
Hi @pedros007 

You can try to to use a specific client in Shoryuken instead of the default one:

```ruby
# https://github.com/phstc/shoryuken/wiki/Configure-the-AWS-Client
Shoryuken.sqs_client = Aws::SQS::Client.new(logger: :info)
```

> I'm confused because if I set gem 'shoryuken', '=2.0.11' in my Gemfile, I see no AWS logging. However, when I set the version to '>2.0.11', Aws::SQS::Client seems to log its public methods (receive_message, get_queue_url, etc.)

That version is kind of old, I would need to spend some time on it to understand what's happening. I would rather encourage you to upgrade to the latest one.

> only place the default logging config is overridden, here in aws-sdk-rails

Based on that, you are probably seeing those messages because your Rails is also set to `:debug`, right?

**Comment by pedros007** [comment]
>> only place the default logging config is overridden, here in aws-sdk-rails

> Based on that, you are probably seeing those messages because your Rails is also set to :debug, right?

🎉   Yes, that's it:  [aws-sdk-rails](https://github.com/aws/aws-sdk-rails/blob/master/lib/aws-sdk-rails.rb#L33) sets `Aws.config[:logger]` to the current Rails logger.  The AWS logger seems to inherit `log_level` from the Rails logger.

Strange that I didn't see Aws::SQS::Client messages with shoryuken <= 2.0.11.  Thanks for your help & a great gem, @phstc !

**Comment by pedros007** [comment]
One more update: I can remove all Aws::SQS::Client log messages by swapping the `aws-sdk-rails` gem for `aws-sdk`.  

[The aws-sdk-rails announcement](https://aws.amazon.com/blogs/developer/announcing-the-aws-sdk-rails-gem/) says this of logging:

> It is important to understand that **all SDK log messages are logged at the same log level**. Why is this important? When you set the Rails log level, you’re muting all log messages below that log level. So, if you want to, for example, only see SDK log messages in development, you might set the SDK log level to :debug as shown above, and set the Rails logger to show debug in development.

I wonder if this is why others (ie. #259, #310) were seeing `Aws::SQS::Client` lines in their logs.

**Comment by phstc** [comment]
Hi @pedros007 

Thanks for sharing that. TBH I've never used `aws-sdk-rails`. Maybe you could keep it, if you initialize the `sqs_client` changing the `log_level`. 

```ruby
Shoryuken.configure_server do |config|
  # https://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#initialize-instance_method
  config.sqs_client = Aws::SQS::Client.new(log_level: :info)
end
```

It seems that `aws-sdk-rails` changing the global logging level, but you can still set it at the level client.

WDYT?
