### ISSUE TITLE
[Wiki] Local SQS server

### ISSUE THREAD

**Issue by unijewski** [phstc/shoryuken#357]
Hi, after [this PR](https://github.com/phstc/shoryuken/pull/317) [the wiki page](https://github.com/phstc/shoryuken/wiki/Using-a-local-mock-SQS-server) of Shoryuken configuration for local SQS server seems to be outdated. `Configure Client` section should look like:
```ruby
Shoryuken.sqs_client = Aws::SQS::Client.new(
  region: ENV["AWS_REGION"],
  access_key_id: ENV["AWS_ACCESS_KEY_ID"],
  secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
  endpoint: 'http://localhost:4576',
  verify_checksums: false
)
```
and in my opinion `Configure Server` section is useless now.

Also it's worth mentioning about an alternative of `moto`, namely [ElasticMQ](https://github.com/adamw/elasticmq) which works a bit faster in my case.

**Comment by phstc** [comment]
Thanks @unijewski. Great catch. I've just updated the [wiki](https://github.com/phstc/shoryuken/wiki/Using-a-local-mock-SQS-server#configure-client), could you check it? I kept `client` and `server` for now.

> Also it's worth mentioning about an alternative of moto, namely ElasticMQ which works a bit faster in my case.

Cool, does it work well with Shoryuken? Are you using for development or prod as well?
