### ISSUE TITLE
Auto visibility timeout and ActiveJob

### ISSUE THREAD

**Issue by unijewski** [phstc/shoryuken#358]
Hi, I've been using Shoryuken with ActiveJob for a few days and I noticed that I need to do something around visibility timeout. According to [worker options](https://github.com/phstc/shoryuken/wiki/Worker-options) using `auto_visibility_timeout` looks to be super useful for cases when processing a message takes more time than we expect. However, it seems to be something wrong with the option and ActiveJob. The wiki page says:
> When it's enabled, 5 seconds before the default visibility timeout expires, Shoryuken will reset it to its original value again.

But if I set 
``` 
Shoryuken.default_worker_options = { auto_visibility_timeout: true }
```
in my initializer then it doesn't work. I checked out the options of `JobWrapper` and here are the results:
```
[1] pry(main)> ActiveJob::QueueAdapters::ShoryukenAdapter::JobWrapper.auto_visibility_timeout?
=> false
[2] pry(main)> ActiveJob::QueueAdapters::ShoryukenAdapter::JobWrapper.get_shoryuken_options
=> {"queue"=>"default",
 "delete"=>false,
 "auto_delete"=>true,
 "auto_visibility_timeout"=>false,
 "retry_intervals"=>nil,
 "batch"=>false,
 "body_parser"=>:json}
```
They are unchanged, thus the question is: am I doing it wrong or is there no way to set the option when ActiveJob enabled so far?

**Comment by phstc** [comment]
Hi @unijewski 

I haven't tried `auto_visibility_timeout` with ActiveJob before. But I tested it out , like you did with an initializer + a few `binding.pry`, and I noticed that [this](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/worker.rb#L43) gets called before the initializer, so your setting does not get propagate to your workers.

I think a possible fix would be to try to set it:

```ruby
require 'shoryuken'
Shoryuken.default_worker_options = { auto_visibility_timeout: true }
```

before your workers being required. Perhaps in the top of your `application.rb`.

But... I'm not sure if it's a good thing to have `auto_visibility_timeout` enabled for all workers.

Unfortunately, the ActiveJob API does not support extra options. I have to admit that I thought about add something exclusively in the Shoryuken Adapter for allowing it, but thinking more on it, I believe it should be changed in ActiveJob itself. Most of the queue adapters support per worker options, and sadly it isn't reflected in ActiveJob.

One alternative would be to use Shoryuken Workers directly without ActiveJob, similar approach suggested [here](http://stackoverflow.com/a/33160275/464685) for sidekiq.

WDYT?

**Comment by unijewski** [comment]
@phstc I agree, it would be better to have `auto_visibility_timeout` enabled in specific workers. I think if someone has tiny workers using ActiveJob and doesn't require any additional configuration then `JobWrapper` does the work. Otherwise it's getting more painful so due to that it's more convenient to migrate to Shoryuken workers. Anyway, thanks for clarifying. 

BTW, regarding [this](https://github.com/phstc/shoryuken/issues/357) issue (which is already closed 😛) I tested ElasticMQ only locally, no idea how it would work in production.

**Comment by oyeanuj** [comment]
@phstc Is it still the case that `auto_visibility_timeout` can't be used with ActiveJob? And if so, is the recommendation to use the snippet that you posted above?

**Comment by phstc** [comment]
@oyeanuj correct, it is still the case. The snippet above should do, but it will enable auto visibility timeout for all workers.
