### ISSUE TITLE
DB Timeout

### ISSUE THREAD

**Issue by juggy** [phstc/shoryuken#359]
Hello,

I have this error and it only pops up in shoryuken threads:
```ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds```

Now I know this means that AR is waiting for a connection so I first increased the pool to 30 in the database.yml and changed the concurrency to 5 in the shoryuken.yml.

I still get the error and I am not sure why. Did you experience the same thing and how can this be solved? 

The message fails and is sent back into the queue, but I would prefer to handle it cleanly instead.

Thanks,
Julien.

**Comment by phstc** [comment]
> Did you experience the same thing and how can this be solved?

@juggy I did not. The only thing that comes to mind is the `concurrency` vs `database pool`.  But you've already tested that. Any chance you've misconfigured the pool or concurrency?

A similar issue https://stackoverflow.com/questions/25968728/sidekiq-could-not-obtain-a-database-connection-within-5-000-seconds

**Comment by phstc** [comment]
Hey @juggy 

Did you figure out the problem?
