### ISSUE TITLE
Optionally specify full url instead of just queue name

### ISSUE THREAD

**Issue by dolan** [phstc/shoryuken#361]
When we want to interact with different accounts, we have granted permission across them to access each others queues/topics etc, we have to specify the full url or arn of the queue (either one will work, really,) to access them, but shoryuken only exposes the ability to look for queues by name (and thus assumes they're in the same account as the credentials.)  Should the queue: attribute on the worker detect whether or not it's a URL and just use the url, instead of fetching it by name?  What effect would that have on the shoryuken.yml file and the specification of the queues there?  I may even be able to do a PR for this if we can agree on a solution that accommodates both the "queue" attribute of the worker (and thus the initializer of Queue class) and the specification of the queues to listen to in the config file...  Thoughts?

**Comment by phstc** [comment]
Hi @dolan 

I see the use case, not sure how common it's, but I see it. As a side effect, we may be able to save a request for searching a queue based on the supplied name, as we will have the URL.

I don't have anything against it, if you can work on a PR I will be happy to guide you and review your changes. If you can't, I can try to do something, but no ETA for now.

**Comment by dolan** [comment]
Alright! I'll take a look!

**Comment by phstc** [comment]
Hi @dolan 

I'm adding support to queue URL in #378, should be merged soon.

For using it:

```yaml
# shoryuken.yml
concurrency: 25
delay: 10
queues:
  - ['https://sqs.us-east-1.amazonaws.com/account-id/queue-name', 1]
```

```shell
# In case you want to supply the queue URL (or name) directly as a CLI arg
shoryuken -r ./workers.rb -q https://sqs.us-east-1.amazonaws.com/account-id/queue-name
```

```ruby
class Worker
  include Shoryuken::Worker

  shoryuken_options queue: 'https://sqs.us-east-1.amazonaws.com/account-id/queue-name'

  def perform(sqs, body)
    # ...
  end
end
```

Will that work for you?

**Comment by dolan** [comment]
Thanks! Very cool!  (I did actually mean to put in a PR myself, but hadn't gotten to it.  This is very much appreciated!)

**Comment by phstc** [comment]
Hi @dolan 

No worries! Thanks for reporting and reviewing the PR, that was awesome! Team work 🍻

**Comment by maschwenk** [comment]
@dolan is this working for you in production currently? Trying to setup the same and having a lot of silent permissions errors. Can't tell if its my permissions or sharing a single SQS client object that's supposed to connect to two different AWS accounts is the problem?

**Comment by phstc** [comment]
@maschwenk I don't see the problem with a shared SQS client, as long as it has [valid permissions for the supplied queues/URLs](https://github.com/phstc/shoryuken/wiki/Amazon-SQS-IAM-Policy-for-Shoryuken).

Is it failing for you? If so, could you share your backtrace? Feel free to share that in #412.
