### ISSUE TITLE
Active Support Instrumentation

### ISSUE THREAD

**Issue by Erol** [phstc/shoryuken#363]
Hi @phstc. What are your thoughts of supporting Active Support Instrumentation? Do you think that is worth commiting to core or is it better to spin off as an external library?

**Comment by phstc** [comment]
Hi @Erol 

How would that work? You mean like [this instrumentation](http://edgeguides.rubyonrails.org/active_support_instrumentation.html#active-job) or something more specific?

**Comment by phstc** [comment]
Hi @Erol 

What I found so far, is that [this](http://edgeguides.rubyonrails.org/active_support_instrumentation.html#active-job) is supported by default when using Active Job. 

If you are not using Active job, you can use [the built-in Lifecycle Events](https://github.com/phstc/shoryuken/wiki/Lifecycle-Events).
