### ISSUE TITLE
ActiveJob with SNS support?

### ISSUE THREAD

**Issue by rwadstein** [phstc/shoryuken#367]
This is not so much an issue, but more of a question of having it support SQS via SNS with ActiveJob.
We currently have our own message system that uses SNS/SQS.  But it does *no*t have an ActiveJob adapter for SQS, which is the primary reason we are using the shoryuken gem.

The question I have for you is would you find it useful that your ActiveJob adapter support SNS?  There would be some assumptions to be made like the SNS topic is driven by the queue name for SQS.  This would allow us to post messages via SNS and process them from SQS all from the Shoryuken gem.

The reason I ask is because you did remove all references to SNS with your recent major release, and I didn't want to spend time making it work when you may want to keep this pure SQS.

**Comment by phstc** [comment]
Hi @rwadstein 

hm it feels like SNS would might deserve its own adapter, I'm not super excited on making the Shoryuken adapter deciding to enqueue either to SQS or SNS. But I understand you can configure only one adapter per Rails setup, so we can't use both in parallel.

What would be the advantage on having a SNS adapter over just having a abstraction to publish messages?

**Comment by rwadstein** [comment]
With Rails 5 you can specify an adapter per job.  We had to borrow code temporarily for our Rails 4 app to allow us to do so.  Currently we have ActiveJobs using DelayedJob and some others using Shoryuken.
The main reason we use SNS is because of the ability of having things being pushed to other systems simulataneously aside from only SQS.  

But I completely understand your concern.  It makes the purity of your app potentially get complicated all because of my selfish needs.  :-)  As well as have some sort of instructions of making sure how an SNS topic message can be sent to SQS properly.
