### ISSUE TITLE
Look into / Update payment queue to use FIFO queue

### ISSUE THREAD

**Issue by andrewyoo** [phstc/shoryuken#372]
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html#FIFO-queues-exactly-once-processing

> If you have an existing application that uses standard queues and you want to take advantage of the ordering or exactly-once processing features of FIFO queues, you need to configure the queue and your application correctly.

**Comment by andrewyoo** [comment]
oops, meant to add to my own repo issues. sry

**Comment by phstc** [comment]
@andrewyoo BTW [Shoryuken supports FIFO queues](https://github.com/phstc/shoryuken/wiki/FIFO-Queues), but I think it's still not support in us-east-1,  not sure if it's an issue for you.
