### ISSUE TITLE
batch processing

### ISSUE THREAD

**Issue by tjgillies** [phstc/shoryuken#377]
It looks like the worker grabs up to 10 records from queue at a time. I'm used to the paradigm of having one worker per message. Is there a way to make it so workers only pop one message from the queue? 

It would also be helpful if someone could explain how to process multiple records in tandem in a worker if this is the idiomatic way to do things.

**Comment by phstc** [comment]
Hi @tjgillies 

Shoryuken tries to grab 10 messages at time (max allowed by SQS), but it calls a worker per message, unless you enable [batch](https://github.com/phstc/shoryuken/wiki/Worker-options#batch).

**Comment by tjgillies** [comment]
@phstc Oh wonderful, thank you
