### ISSUE TITLE
ActiveJob 15 minutes delay versus SQS 12 hours max visibility timeout

### ISSUE THREAD

**Issue by smennesson** [phstc/shoryuken#379]
Hello

in the Shoryuken documentation, "Rails Integration Active Job" part, we can read the following:

> When queueing jobs to be performed in the future (e.g when setting the wait or wait_until Active Job options), SQS limits the amount of time to 15 minutes. Shoryuken will raise an exception if you attempt to schedule a job further into the future than this limit.

This is implemented in the `active_job_adapter.rb` file:
```
    def enqueue_at(job, timestamp) #:nodoc:
        register_worker!(job)

        delay = (timestamp - Time.current.to_f).round
        raise 'The maximum allowed delay is 15 minutes' if delay > 15.minutes
```

We can also read in the "Worker options":

> Keep in mind that AWS SQS does not officially support exponential backoff, it's something implemented in Shoryuken using the Visibility Timeout, which can extended to a maximum of 12 hours.

This is confirmed by the [SQS official documentation](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ChangeMessageVisibility.html).

So I'm wondering where the 15 minutes limit for the active job adapter comes from? Is it another limitation I'm not aware of? Or maybe was it a SQS limitation in the past and not the current limitation (if so, I guess the gem should be updated to allow 12 hours max).

Kind regards,
Stéphane

**Comment by phstc** [comment]
Hi @smennesson 

Basically, you can change the visibility up to 15 min at time, that's the maximum supported by  `ChangeMessageVisiblity` and besides that, if you call `ChangeMessageVisiblity` multiple times, total maximum visibility can't max out 12 hours. That's the relation with exponential backoff, since it may trigger `ChangeMessageVisiblity` multiple times. 

I'm open to update the documentation. Any ideas?

The Amazon SQS doc:

> For example, you have a message with a visibility timeout of 5 minutes. After 3 minutes, you call ChangeMessageVisiblity with a timeout of 10 minutes. At that time, the timeout for the message is extended by 10 minutes beyond the time of the ChangeMessageVisibility action. This results in a total visibility timeout of 13 minutes. You can continue to call the ChangeMessageVisibility to extend the visibility timeout to a maximum of 12 hours. If you try to extend the visibility timeout beyond 12 hours, your request is rejected.
> https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ChangeMessageVisibility.html

**Comment by smennesson** [comment]
Thanks for your quick feedback.

I can't find this information on AWS SQS documentation. Couldn't it be a past rule that is no longer true?

In `ChangeMessageVisiblity` documentation, we can read this:
```
VisibilityTimeout
The new value for the message's visibility timeout (in seconds). Values values: 0 to 43200. Maximum: 12 hours.

Type: Integer

Required: Yes
```

It seems the new value can be set up to 43200 seconds. Could it be wrong in SQS documentation ?

Kind regards,
Stéphane

**Comment by phstc** [comment]
> Basically, you can change the visibility up to 15 min at time

@smennesson sorry, that ☝️ isn't true. I got confused with `delay_seconds`.

This `enqueue_at` is for enqueuing a message to be processed later, like check this message only in X seconds, and in order to do it, Shoryuken uses [`delay_seconds`](https://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#send_message-instance_method), which supports max of 15 mins.

Whereas the exponential backoff uses [`change_message_visiblity`](https://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#change_message_visibility-instance_method) which supports 12 hours in total. Does that make sense?

**Comment by smennesson** [comment]
Ok thanks I guess this makes sense, the 15 minutes limit is when a new job is created, and the 12 hours limit is for a job already created.

Actually we're using ActiveJob::Retry (https://github.com/isaacseymour/activejob-retry) instead of Shoryuken exponential backoff.

So I guess that SQS VisibilityTimeout isn't used with ActiveJob::Retry when there is a failure. I guess the job is consumed and created again, being subject to the 15 minutes limit again.

**Comment by phstc** [comment]
@smennesson is there any specific reason for using `activejob-retry` instead of the native Shoryuken impl?

**Comment by smennesson** [comment]
Actually I think we failed to use the native shoryuken implementation with ActiveJob. I don't remember the exact reason why sorry.

**Comment by phstc** [comment]
@smennesson hm actually you can't use Shoryuken exponential backoff with ActiveJob, it's a native worker option. The ActiveJob interface does not offer a way to configure queue adapter specific options. 

[This](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/extensions/active_job_adapter.rb#L75) is all you get with ActiveJob. Unless you extend that adapter, you can't use native options.

**Comment by smennesson** [comment]
Yes ok that makes sense, so this is why ActiveJob::Retry is a good option for us as we do want to keep the ActiveJob layer for our jobs.

Thanks very much for your time and clarifications.
