### ISSUE TITLE
Logging lograge, remote_syslog

### ISSUE THREAD

**Issue by nicpillinger** [phstc/shoryuken#382]
Hello again! We use remote_syslog_logger and papertrail for logging in production and I'm wondering if theres a way to hook into the logging in Shoryuken? Can we replace the logger in use or even mess with the formatting? thanks

**Comment by nicpillinger** [comment]
OK this appears to work

`Shoryuken::Logging.logger= RemoteSyslogLogger.new('pt_url',id,'logname')`

so if I put that in a Shoryuken startup event - I think that has me covered?

**Comment by nicpillinger** [comment]
I need to add additional info to the formatter. Again I assume I can override this somehow?

**Comment by phstc** [comment]
> `Shoryuken::Logging.logger = RemoteSyslogLogger.new('pt_url',id,'logname')`

Yup. That should do.
