### ISSUE TITLE
Error handling, raygun

### ISSUE THREAD

**Issue by nicpillinger** [phstc/shoryuken#383]
Hi there, me again. We use Raygun to track our errors in production environments. In Rails their gem inserts a global handler so if a controller raises an error it gets notified. I'm looking to do something similar with Shoryuken so if a message cannot be processed/an error occurs during processing we get notified. Any ideas on where to start with this one? cheers NIc

**Comment by phstc** [comment]
Hi @nicpillinger 

You can use a [middleware](https://github.com/phstc/shoryuken/wiki/Middleware) for that.  

Some examples:
- https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/middleware/server/exponential_backoff_retry.rb#L18
- https://github.com/honeybadger-io/honeybadger-ruby/blob/master/lib/honeybadger/plugins/shoryuken.rb#L47
- https://github.com/airbrake/airbrake/blob/master/lib/airbrake/shoryuken.rb#L38
