### ISSUE TITLE
A tons of messages in workers.log is it okay? How to turn it off? 

### ISSUE THREAD

**Issue by likitung** [phstc/shoryuken#391]
Hello, on my development enviroment everything is OK, but on my production server I got a tons of records in my workers.rb file.... like this https://monosnap.com/file/R1s9Bj6fXAdwMSdEERzdsZLqhoTAM8  is it normal? Can I not save this messages to the log file?

**Comment by phstc** [comment]
Hi @likitung 

Check #353, those messages aren't from Shoryuken. It's most likely you've (or another gem) enabled `debug: true` in the AWS SDK.

**Comment by likitung** [comment]
Thx!

**Comment by phstc** [comment]
@likitung I added this as a reference: https://github.com/phstc/shoryuken/wiki/Too-many-%22receive_message(...)%22-in-the-log-file%3F 🍻
