### ISSUE TITLE
How to use shoryuken to listen to a SQS queue with Rails

### ISSUE THREAD

**Issue by pmvilaca** [phstc/shoryuken#394]
Hi @phstc 

First of all, congrats for your project!

I've a rails application running that needs to listen to a SQS queue to react to some messages and trigger some operations.

I found your project and it looks like it covers my use case, although I was trying to get it working and I didn't succeed until now.

Can you please point me what I need to do?

I need to use the ([Rails integration](https://github.com/phstc/shoryuken/wiki/Rails-Integration-Active-Job) because while processing the messages I will need to write to the database and do some more stuff. So, I was assuming that I would just need to create the worker, put it under app/jobs (and a shoryuken.yml to define the name of my sqs queue?). The AWS credentials are already there because I'm using aws-sdk to transfer some files to S3.

Thanks in advance for your help!

Pedro

**Comment by phstc** [comment]
>  I was assuming that I would just need to create the worker, put it under app/jobs (and a shoryuken.yml to define the name of my sqs queue?). The AWS credentials are already there because I'm using aws-sdk to transfer some files to S3.

Hey @pmvilaca 

That sounds right. Didn't that work?

**Comment by pmvilaca** [comment]
It's working now. I wasn't passing the config file to the execution because I thought that it would be automatically used.

So, I was executing `bundle exec shoryuken -R`

If I pass the config file, it is now working.

**Comment by phstc** [comment]
@pmvilaca I added some comments in [here](https://github.com/phstc/shoryuken/wiki/Shoryuken-options) for clarifying the `shoryuken.yml` usage. Thanks for the feedback 🍻

**Comment by pmvilaca** [comment]
thanks @phstc 

Looks good!
