### ISSUE TITLE
activejob support

### ISSUE THREAD

**Issue by juggy** [phstc/shoryuken#4]
Is that in the plans?

**Comment by elsurudo** [comment]
This is working for me in dev, in case someone needs it before it's merged: https://github.com/elsurudo/shoryuken/tree/active-job

**Comment by phstc** [comment]
Added [ActiveJob Support](https://github.com/phstc/shoryuken#activejob-support) :smile:

**Comment by renanmzmendes** [comment]
For the main ruby process to be able to save the job to the queue, Shoryuken must know about the main AWS configuration. It would be nice to have a generator that would create a loader of `shoryuken.yml` on the initializers folder.

Maybe refactor a `Shoryuken::CLI` method so it can also be used in the initializer?

Mine was something like this:

```ruby
def parse_config(config_file)
  if File.exist?(config_file)
    YAML.load(ERB.new(IO.read(config_file)).result)
  else
    raise ArgumentError, "Config file #{config_file} does not exist"
  end
end

config = parse_config([Dir.pwd, 'config/shoryuken.yml'].join('/')).deep_symbolize_keys
Shoryuken.options.merge!(config)

AWS.config Shoryuken.options[:aws]
```

Cheers

**Comment by phstc** [comment]
you would to extract https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/environment_loader.rb#L46 and call it a in rails initializer?

**Comment by renanmzmendes** [comment]
Actually, one would actually need to load `shoryuken.yml` so that `Shoryuken.options[:aws]` wasn't empty when `initialize_aws` was called.

P.S.: my previous post was based on the 0.0.5 gem version

**Comment by phstc** [comment]
I agree!

Can you update to the master version? If so, maybe something like that would work:

```ruby
options = Shoryuken.load_config_file 'shoryuken.yml'
Shoryuken.initialize_aws(options)
```

The we would need to update [here](https://github.com/phstc/shoryuken/blob/36150d3ffc98c92bddb59e4bd0a7c8c0499699e1/lib/shoryuken/environment_loader.rb#L20) and [here](https://github.com/phstc/shoryuken/blob/36150d3ffc98c92bddb59e4bd0a7c8c0499699e1/lib/shoryuken/environment_loader.rb#L46) to use these new methods.

wdyt?

**Comment by claudia-beas** [comment]
Hi,
so how exactly would I use Shoryuken with ActiveJob? Because I need to set  queuing backend, but I don't know what I'm supposed to write for Shoryuken.
Or is there a possibility to use something like perform_later with Shoryuken without an extra Active Job?

**Comment by phstc** [comment]
hi @claudia-beas 

You can use Shoryuken without Rails (or ActiveJob) as a standalone process.

Please have a look at the documentation and related wiki pages:

* https://github.com/phstc/shoryuken#usage
* https://github.com/phstc/shoryuken#activejob-support

**Comment by claudia-beas** [comment]
hi @phstc , thanks for your quick answer. I've been using Shoryuken workers so far, but without delay. I know there's a delay option I can set inside the worker, but I'm not sure how. As I said, the ideal result would be something like perform_later but with the limit not set to fifteen minutes, but also several days possible.

**Comment by phstc** [comment]
The fifteen minutes delay is a restriction in SQS :disappointed: So the options in Shoryuken https://github.com/phstc/shoryuken/wiki/Sending-a-message#delaying-a-message are limited to that.

Have a look at this post, it might help you: http://www.pablocantero.com/blog/2014/11/29/sqs-to-the-rescue/#delaying-a-message-perform_in

**Comment by claudia-beas** [comment]
Thank you (for the help and for answering my questions super-awesomely fast^^)! I'll look into it!

**Comment by joekhoobyar** [comment]
@claudia-beas - If you need to delay a message longer than 15 minutes, you could also try this: https://github.com/joekhoobyar/shoryuken-later

**Comment by claudia-beas** [comment]
Cool, thanks.

**Comment by shqear93** [comment]
@phstc how to change message group id or duplication id using shoryuken with activejob ??

**Comment by phstc** [comment]
@shqear93 Unfortunately, the Active Job spec does not support custom parameters. 

I would love if we could set adapter-specific parameters using [`set`](https://apidock.com/rails/ActiveJob/Core/ClassMethods/set), for example `MyJob.set(message_group_id:  some_id).perform_later(something)` but custom options don't seem to be supported.

Unless I'm missing something with the adapter spec, we can't use extra params.

So for using FIFO with a custom message group id and duplication id (Shoryuken has default values for those) you would need to use standard workers. 
`

**Comment by phstc** [comment]
Active Job does not pass the options to the adapters https://github.com/rails/rails/blob/efbab359290d73fc7270599f4e05a59862f8080a/activejob/lib/active_job/enqueuing.rb#L55-L57 😢

**Comment by shqear93** [comment]
@phstc You right! I had to override this methode as well :

```
require "active_job/arguments"

module ActiveJob
  # Provides behavior for enqueuing jobs.
  module Enqueuing
    extend ActiveSupport::Concern

    def enqueue(options = {})
      self.scheduled_at = options.delete(:wait).seconds.from_now.to_f if options[:wait]
      self.scheduled_at = options.delete(:wait_until).to_f if options[:wait_until]
      self.queue_name   = self.class.queue_name_from_part(options.delete(:queue)) if options[:queue]
      self.priority     = options.delete(:priority).to_i if options[:priority]
      run_callbacks :enqueue do
        if scheduled_at
          self.class.queue_adapter.enqueue_at self, scheduled_at
        else
          self.class.queue_adapter.enqueue self, options
        end
      end
      self
    end
  end
end

```

**Comment by DharmaPriya-V** [comment]
can we have shorukyen's auto_visbility_timeout in active job as well.. As i know we can't have as we don't know the receipt handle 
Currently my application is fully based on active jobs...Can I use active job module like logging and exceptions in worker?
