### ISSUE TITLE
Documentation to fully describe shoryuken.yml

### ISSUE THREAD

**Issue by greggilbert** [phstc/shoryuken#404]
The ability to use a separate YML config file is mentioned here and there in the docs, but it's not fully documented. The structure of the file isn't clear either. For example, nowhere in the docs does it clearly state that you can have an `aws:` section to override values, and even then, what the keys would be.

It'd be nice to have some kind of concrete documentation about all the options available through it.

**Comment by phstc** [comment]
Hi @greggilbert is there still any reference for `aws:` I thought I had removed them all.

This https://github.com/phstc/shoryuken/wiki/Shoryuken-options is probably the main article for `shoryuken.yml`.

But I hear you on not having a full list of options.

**Comment by greggilbert** [comment]
Wait, is `aws` deprecated or removed? What's the alternative? On Jul 10, 2017 5:35 PM, Pablo Cantero <notifications@github.com> wrote:Hi @greggilbert is there still any reference for aws: I thought I had removed them all.
This https://github.com/phstc/shoryuken/wiki/Shoryuken-options is probably the main article for shoryuken.yml.
But I hear you on not having a full list of options.

**Comment by phstc** [comment]
@greggilbert check [this](https://github.com/phstc/shoryuken/wiki/Configure-the-AWS-Client).
