### ISSUE TITLE
Cannot use --config with sqs create

### ISSUE THREAD

**Issue by bnolan** [phstc/shoryuken#406]
I was trying to create a sqs queue against `moto` locally and it's not possible to specify a config with the sqs create task.

```
$ bundle exec shoryuken sqs create hello -C shoryuken.yml 
ERROR: "shoryuken create" was called with arguments ["hello", "-C", "shoryuken.yml"]
Usage: "shoryuken create QUEUE-NAME"
```

**Comment by phstc** [comment]
hi @bnolan 

I don't use a config for creating a queue, I just export my AWS keys. Why do you need a config?

**Comment by bnolan** [comment]
I'm trying to use it against `moto sqs` locally, so I send an `endpoint`. I'm actually having trouble conncting `shoryuken` against the moto sqs using any of the config options (.yml, AWS_ENDPOINT_URI or config/initializers/shoryuken.rb).

**Comment by bnolan** [comment]
This is my problem:

```
$ AWS_SQS_ENDPOINT=http://localhost:5000/ bundle exec shoryuken start -q hello-beep-boop-robot
/Users/ben/.rvm/gems/ruby-2.4.0/gems/shoryuken-3.1.3/lib/shoryuken/environment_loader.rb:165:in `validate_queues': The specified queue(s) hello-beep-boop-robot do not exist. (ArgumentError)
Try 'shoryuken sqs create QUEUE-NAME' for creating a queue with default settings
```

But...

```
$ aws --endpoint-url=http://localhost:5000 sqs list-queues
{
    "QueueUrls": [
        "http://localhost:5000/123456789012/hello-beep-boop-robot", 
        "http://localhost:5000/123456789012/hello-beep-boop", 
        "http://localhost:5000/123456789012/hello"
    ]
}
```

**Comment by bnolan** [comment]
I created the queue using the `aws` cli, but I Can't get shoryuken to connect to it for the life of me.

**Comment by phstc** [comment]
@bnolan could you try that?

```shell
bundle exec shoryuken start -q http://localhost:5000/123456789012/hello-beep-boop-robot
```

**Comment by phstc** [comment]
You can also set a specific SQS client with your endpoint in an initializer.

```ruby
Shoryuken.sqs_client = Aws::SQS::Client.new(...)
```

See https://github.com/phstc/shoryuken/wiki/Configure-the-AWS-Client

Currently the `shoryuken sqs` CLI does not support passing an `ENDPOINT`: https://github.com/phstc/shoryuken/blob/master/bin/cli/sqs.rb#L20, but it's doable to make `endpoint` a global option.

**Comment by bnolan** [comment]
Thanks for your help, that didn't work though.

```
$ bundle exec shoryuken start -q http://localhost:5000/123456789012/hello-beep-boop-robot
/Users/ben/.rvm/gems/ruby-2.4.0/gems/shoryuken-3.1.3/lib/shoryuken/environment_loader.rb:165:in `validate_queues': The specified queue(s) http://localhost:5000/123456789012/hello-beep-boop-robot do not exist. (ArgumentError)
Try 'shoryuken sqs create QUEUE-NAME' for creating a queue with default settings
```

**Comment by bnolan** [comment]
This is my gemfile.lock:

```
$ cat Gemfile.lock | grep shoryuken
    shoryuken (3.1.3)
  shoryuken
$ cat Gemfile.lock | grep aws
    aws-sdk (2.10.7)
      aws-sdk-resources (= 2.10.7)
    aws-sdk-core (2.10.7)
      aws-sigv4 (~> 1.0)
    aws-sdk-resources (2.10.7)
      aws-sdk-core (= 2.10.7)
    aws-sigv4 (1.0.0)
      aws-sdk-core (> 2)
  aws-sdk (~> 2)
```

**Comment by bnolan** [comment]
I'm running moto server like so:

`moto_server sqs`

**Comment by phstc** [comment]
@bnolan could you try [these steps](https://github.com/phstc/shoryuken/wiki/Using-a-local-mock-SQS-server#download-and-install-moto) from @cjlarose ⭐️  then try to start it with only the queue name: `bundle exec shoryuken start -q hello-beep-boop-robot`?

**Comment by bnolan** [comment]
Got it going in rails mode with:

```bundle exec shoryuken -q hello -R ```
