### ISSUE TITLE
Worker Daemon: configure queues through code instead of arguments

### ISSUE THREAD

**Issue by rbroemeling** [phstc/shoryuken#407]
Hi,

So I am trying to upgrade a local application (non-rails, standalone ruby) from v2.0.11 to v3.1.3.

The way that we configure our queues for the workers is through ruby code (not via an argument or anything like that). Our configuration code, which worked in v2.0.11, looks like this:

```ruby
unless App.config['SQS_QUEUE_NAME']
  raise 'App configuration variable SQS_QUEUE_NAME is not set, but is required.'
end
Shoryuken::Logging.logger = SemanticLogger[Shoryuken]
Shoryuken.options[:delay] = 5
Shoryuken.options[:queues] << App.config['SQS_QUEUE_NAME']
```

Then we actually run the application like this:
```
bundle exec shoryuken --concurrency 1 --require app "$@"
```

This doesn't work in v3.1.3, and I've been trying to modify the approach to work in v3.1.3, but have been failing horribly -- I can't seem to make it work. Whatever I try, Shoryuken logs `Shoryuken -- No queues supplied` when the workers start up. There doesn't seem to be any good way to configure the queues for the workers via ruby code (instead of via a command-line argument).

I realize that I could reach into the guts of Shoryuken and monkey-patch in the behaviour that I want, but I'm really trying to resist that because it's really breaky in terms of further Shoryuken upgrades.

The reason that we want to configure it via ruby code is because the queue name comes from AWS EC2 instance metadata. I could parse this in the init script and then pass the queue name as a command-line argument, but it is both easier to read and more reliable to do it in ruby code (where it is easier to catch exceptions, handle them gracefully, and so on).

What am I missing? Or is this really not easily possible? How do I configure Shoryuken queues not from a command-line argument, but from ruby code that generally speaking executes _after_ `Shoryuken::EnvironmentLoader#parse_queues` has executed?

**Comment by rbroemeling** [comment]
So actually, I forgot to mention -- I did figure out how to get it to work by putting this code in our initializer:

```ruby 
Shoryuken.add_group('default', Shoryuken.options.fetch(:concurrency, 25))
Shoryuken.add_queue(App.config['SQS_QUEUE_NAME'], 1, 'default')
```

Basically this just replicates the code that runs in `Shoryuken::EnvironmentLoader#parse_queues`, but it again feels very wrong to do this because it's the opposite of DRY, and those bits of code/that behaviour feels like an internal implementation detail of Shoryuken that shouldn't be called from outside of the gem itself.

For `Shoryuken::EnvironmentLoader#load`, would it be possible to reverse the order of the calls to `parse_queues` and `require_workers`, so that `require_workers` has a chance to implement initialization code (and add queues) before `parse_queues` is ever called?

The changeset would look like this:

```ruby
def load
  puts "Shoryuken::EnvironmentLoader#load"
  load_rails if Shoryuken.options[:rails]
  prefix_active_job_queue_names
+ require_workers
  parse_queues
- require_workers
  validate_queues
  validate_workers
end
```

With this change, I _think_ that simple additions to Shoryuken.options[:queues] could be done in initialization code again, and they would be picked up automatically by `Shoryuken::EnvironmentLoader#parse_queues`.

**Comment by phstc** [comment]
Hi @rbroemeling 

I'm glad you figured that out 🤘 

> but it again feels very wrong to do this because it's the opposite of DRY, and those bits of code/that behaviour feels like an internal implementation detail of Shoryuken that shouldn't be called from outside of the gem itself.

Actually, TBH I think it's the other way around, with `add_group` and `add_queue` you are using methods/accessors for adding [processing groups](https://github.com/phstc/shoryuken/wiki/Processing-Groups).

```ruby
Shoryuken.add_group('default', Shoryuken.options.fetch(:concurrency, 25))
Shoryuken.add_queue(App.config['SQS_QUEUE_NAME'], 1, 'default')
```

`Shoryuken.options[:queues]` was the way to go before, but it was exposing internal options, without any accessor on top of it.

So an initializer adding the queues, I think it would be the way to go. I don't see any problem with that.

WDYT?

**Comment by phstc** [comment]
Please let me know how 3.1 goes for you. Are you planning to use multiple processing groups?

**Comment by rbroemeling** [comment]
@phstc We have 3.1.x out right now and it is mostly working, but are seeing some memory growth problems. I don't have any evidence that it is necessarily tied to Shoryuken though -- I'll let you know if I can pin it to a specific cause.

Hum. OK. Well, I'm not sure -- all that I know is that it took me a really long time to figure out how to do it. If that is the "approved" way, maybe it could get added to the README documentation or similar in order to make it clearer how to programatically add queues?

In general the README/WIKI does well at showing configuration files, and the command-line parameters of the daemon are also well-documented, but how to use Shoryuken programmatically is not entirely clearly to me.

It legitimately felt like I was doing something wrong when I was doing this; if it is explicitly part of the interface that Shoryuken exposes then that's fine.

**Comment by phstc** [comment]
@rbroemeling good point on the README, I can work on that. TBH programmatically adding queue was always something like internal, but since there are people using that, +1 on documenting it.

> @phstc We have 3.1.x out right now and it is mostly working, but are seeing some memory growth problems

Some people reported that too #401, but I'm still trying to reproduce it. If you can add more details on #401, that would be great.

> all that I know is that it took me a really long time to figure out how to do it

I hear you, sorry for that. But it was hard to keep that `options[:queues]`. I guess at least now, might be easier for changes, since it's a method, I can encapsulate whatever I want to change.

**Comment by rbroemeling** [comment]
Yep, that sounds great @phstc -- thanks. For now I'll close this. I am currently working on the memory growth issue, if I can find anything that actually ties it to Shoryuken then I will make sure to update #401 with any details that I can suss out.

Thanks!
