### ISSUE TITLE
Setting up shuryken with Rails: No worker found

### ISSUE THREAD

**Issue by skozz** [phstc/shoryuken#410]
Hi! I'm setting the gem with Rails (Rails 4.2.7, Ruby 2.1.7) following the docs 
- https://github.com/phstc/shoryuken/wiki/Getting-Started
- https://github.com/phstc/shoryuken/wiki/Rails-Integration-Active-Job

But I can't make it work completely, I'm receiving the same message all time and I tried everything without success: 

```
2017-07-13T20:10:18Z 63209 TID-oujidbdn4 INFO: Found 1 messages for hello
2017-07-13T20:10:18Z 63209 TID-oujidbopg ERROR: No worker found for hello
```

The problem is the same running the worker from Procfile or with bundle directly: 

```
# Procfile
web: bundle exec unicorn -p $PORT -c ./config/unicorn.rb
worker: bundle exec shoryuken -q hello
```

Any suggestion of what I'm doing wrong? I had `resque` before setting shuryken, but It's removed from the app configuration and from the Procfile, too. 

Thank you and sorry for the hassle.

**Comment by phstc** [comment]
Hi @skozz 

Are you using ActiveJob? If you so, you need to start with `-R` or `--rails` for loading Rails.

```
worker: bundle exec shoryuken -q hello -R
```
 
Please let me know if that works.

**Comment by skozz** [comment]
Hi @phstc, thanks for the fast answer! Ok I just did it but it's still failing: 

From the Procfile: 
```
web: bundle exec unicorn -p $PORT -c ./config/unicorn.rb
worker: bundle exec shoryuken -q hello -R
scheduler: env DYNAMIC_SCHEDULE=true bundle exec rake environment resque:scheduler
```
And only running the command `bundle exec shoryuken -q hello -R`, with both methods the output is the same: 

```
> foreman start
22:45:09 worker.1    | 2017-07-16T20:45:09Z 88434 TID-ov2xytr6o INFO: Found 1 messages for hello
22:45:09 worker.1    | 2017-07-16T20:45:09Z 88434 TID-ov2xyt7eg ERROR: No worker found for hello
22:46:45 worker.1    | 2017-07-16T20:46:45Z 88434 TID-ov2xytr6o INFO: Found 1 messages for hello
22:46:45 worker.1    | 2017-07-16T20:46:45Z 88434 TID-ov2xytng8 ERROR: No worker found for hello

```

Thank you

**Comment by skozz** [comment]
Btw, I forgot to mention that ideally I want to do it [using the yml file](https://github.com/phstc/shoryuken/wiki/Shoryuken-options) because I need to use different queues, but I'm stuck in the current step/problem but, just in case, I mention it now if it can help. 

Thank you for your time, 
Angel

**Comment by phstc** [comment]
@skozz did you configure your ActiveJob job `queue_as :hello`? You need to associate workers (if standalone) or jobs (ActiveJob) with queues.

```ruby
# Standalone
class HelloWorker
  shoryuken_options queue: 'hello'

  def perform(sqs_msg, body)
    # ...
  end
end

# ActiveJob
class HelloJob < ActiveJob::Base
  queue_as :hello

  def perform(something)
    # ...
  end
end
```

**Comment by phstc** [comment]
BTW how are you enqueuing messages to `hello`? Better to enqueue using your worker or job, otherwise you may face some issues with the format enqueued.

**Comment by skozz** [comment]
@phstc it works! well, almost 😅  finally the issue was your second suggestion (your last message: sending the message through ActiveJob, too). Looks like an issue related to the format as you said. 

But there is a little problem: what about the services or microservices communication? for example a rails app (Service A) and another service in Go (Service B) and you are looking for an asynchronous communication using a queue (in this case, SQS). So, you cannot send a message through ActiveJob from Go (it does not exist of course hehe). 

There is any way to do this kind of communication with ActiveJob? if not I'll to suppose that a possible way is without ActiveJob and run a pure ruby worker. 

Thank you so much for your time,
Angel.

**Comment by phstc** [comment]
I'm glad it worked.

> So, you cannot send a message through ActiveJob from Go (it does not exist of course hehe).

For that is better you to check what's the message body enqueued by ActiveJob and send the same when enqueueing from other services. For facilitating debugging, you can try to stop Shoryuken and any other possible consumers, enqueue a message using ActiveJob `perform_later` and inspect the message body and attributes in the queue (you can use AWS Console for that). That's what you will need to enqueue from other services if you want to use ActiveJob.

Shoryuken only [enqueues whatever format ActiveJob passes](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/extensions/active_job_adapter.rb#L53)

If you use Shoryuken workers instead, you can enqueue any message format you want, as long as you have associate the worker with the queue, all should work.
