### ISSUE TITLE
How to hook into thread initialization?

### ISSUE THREAD

**Issue by rbroemeling** [phstc/shoryuken#411]
More a question than an outright issue: is it possible to hook into the thread initialization process (i.e., similar to a "before fork" or "after fork" hook for a forking library) to allow for reopening file descriptors or taking explicit action to prevent sharing of resources across threads?

What I'm looking for here is some way to implement things such that just before the worker threads are created, logging FDs and sockets are closed so as to protect against contention. The idea is to work around/protect from issues that may be caused by non-threadsafe libraries.

Is there any ability to do this built into Shoryuken? I've looked through the source briefly, but I didn't see any obvious point to hook into the Shoryuken processes in a way that would let me do this.

**Comment by phstc** [comment]
Hi @rbroemeling 

Shoryuken uses [`Concurrent.global_io_executor `](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/launcher.rb#L39) and [`Promise`](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/manager.rb#L68) for executing workers. All the thread initialization process is through [concurrent-ruby](https://github.com/ruby-concurrency/concurrent-ruby), better to check if this is supported in there.

Can't you use a `Mutex` for the non-thread-safe code?

**Comment by rbroemeling** [comment]
@phstc: sure, I could Mutex every possible non-threadsafe bit of code, but I'd really prefer not to have to do that. My primary concern is inclusion of non-threadsafe libraries (such as dogstatsd) -- it would be a significant amount of pain to Mutex every individual metrics call, especially since some of them take blocks of executable code (which makes the Mutex long/expensive instead of short/cheap).

Contention would be threatened.

I'd _much_ rather simply force them to reconnect their sockets immediately post-thread instantiation, because then you don't have to Mutex anything, and everything will still keep working.

I noticed the infrastructure that Shoryuken offers around lifecycle events. What I would really like is a lifecycle event that executes code immediately after the creation of each thread. That's what the ideal would be -- it would allow reopening of files/sockets as necessary, at which point non-threadsafe libraries can be used in a much more straightforward way.

**Comment by phstc** [comment]
@rbroemeling not sure if it's supported in `concurrent-ruby`, maybe with a custom executor. Shoryuken does not `Thread.new`, as it uses abstractions `Promise` and `Future` for that. 

Not sure if I totally followed your use case, why do you need:

> executes code immediately after the creation of each thread

How would that help?

Shoryuken also supports batch processing, maybe you could have concurrency 1, but with batch processing.

**Comment by rbroemeling** [comment]
@phstc I think that I was unclear -- by "after the creation of each thread", I mean "within each thread". The intent is to execute code immediately at the start of each thread so that each thread can forge its own FDs and sockets.

It doesn't sound like there is an officially supported way of doing this -- would it be possible to implement a Shoryuken lifecycle event for this?

**Comment by phstc** [comment]
@rbroemeling can't you use a [middleware](https://github.com/phstc/shoryuken/wiki/Middleware) for that then? You can do code around the`perform` of each worker execution, which probably translates for your "thread" need.

```ruby
class MyMiddleware
  def call(worker_instance, queue, sqs_msg, body)
    # do your thing with FDs and sockets
    # can also manipulate to the body to pass extra info to worker/thread
    # body[something] = something
    yield
    # do your thing with FDs and sockets
  end
end
```

**Comment by rbroemeling** [comment]
@phstc Yes, I can do that, but that makes it a lot more expensive -- unless I am badly misunderstanding something, that will happen once per TASK, rather than once per THREAD. That sort of redundant repetition makes even cheap things expensive.

**Comment by phstc** [comment]
@rbroemeling yup. the middleware is per worker execution. Could share some code (even pseudo-code is fine) for clarifying what you are trying to do?

Another option (I'm just guessing, since it's still not clear for me what you want to achieve) might be some sort of pool for what needs to be isolated and call that pool in your workers.

**Comment by rbroemeling** [comment]
Example pseudo-code for what I want to do:

```ruby
Shoryuken.at_start_of_thread do
  Statsd.close()
end
```

**Comment by phstc** [comment]
@rbroemeling threads can be created and replaced all the time, also they can be created in parallel, how would that make it thread-safe?

```ruby
Shoryuken.at_start_of_thread do
  Statsd.close()
end
```

If you have `concurrency: 25`, this `at_start_of_thread` might be called ~25 times, once for each message you receive. Since `Statsd.close()` seems to be a global non-thread-safe thing, what's the purpose of calling it more than once at the start?

**Comment by phstc** [comment]
Basically, Shoryuken uses a thread pool, and each message received is executed using a thread of this pool. Supposing you have concurrency 10, and you receive 10 messages in a single fetch, Shoryuken will use 10 threads of the pool for processing all these 10 messages in parallel, so in your example `at_start_of_thread` would be called 10 times for the first the pool is loaded.

**Comment by rbroemeling** [comment]
@phstc Yes, but what happens behind the scenes of that Statsd call is the closing of an instance variable. Which would result in each of the threads "closing" the instance variable and spinning up their own copies of it, correct? That would be the intent of the snippet.

**Comment by phstc** [comment]
> Which would result in each of the threads "closing" the instance variable and spinning up their own copies of it, correct?

That isn't what it looks like for me. 

For me `Statsd.close()`, feels more like something with a class variable (most likely not thread safe). If so, it would basically closing the same thing over and over again, for each thread being created (= concurrency).
