### ISSUE TITLE
Minimal verification on URL-defined queue

### ISSUE THREAD

**Issue by maschwenk** [phstc/shoryuken#412]
In the queue initialization there is no verification done on the queue if it is supplied as a URL. Is there some basic verification that could be done here to align it more with the `name` verification?

Perhaps just check a queue attribute? Or some other minimal operation that can verify this is valid?

https://github.com/phstc/shoryuken/blame/master/lib/shoryuken/queue.rb#L61
```ruby
def set_name(name)
  self.name = name
  self.url  = client.get_queue_url(queue_name: name).queue_url
rescue Aws::Errors::NoSuchEndpointError, Aws::SQS::Errors::NonExistentQueue => ex
  raise ex, "The specified queue #{name} does not exist."
end

def set_url(url)
  self.name = url.split('/').last
  self.url  = url
end
```

**Comment by phstc** [comment]
@maschwenk it could anticipate [this `queue_attributes `](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/queue.rb#L68), which would test the URL.

Could you share your use case for validating user-supplied URLs?

**Comment by maschwenk** [comment]
@phstc if you boot Shoryuken with an invalid URL (i.e. `https://sqs.us-east-1.amazonaws.com/18290711111/my-dog-is-a-cat`), you'll notice that Shoryuken doesn't complain at all, it silently sits idly. Whereas, if you supply a bad queue name, as you can see it immediately calls `get_queue_url` and that fails fast.

**Comment by phstc** [comment]
@maschwenk I think something like this:

```ruby
def set_name(name)
  self.name = name
  self.url  = client.get_queue_url(queue_name: name).queue_url
end

def set_url(url)
  self.name = url.split('/').last
  self.url  = url
end

def set_name_and_url(name_or_url)
  if name_or_url.start_with?('https://sqs.')
    set_url(name_or_url)
    
    # anticipate the fifo? checker for validating the queue URL 
    return fifo?
  end
  
  set_name(name_or_url)
rescue Aws::Errors::NoSuchEndpointError, Aws::SQS::Errors::NonExistentQueue => ex
  raise ex, "The specified queue #{name_or_url} does not exist."
end
```

Would do.

If you are willing to submit a PR that would great, otherwise I can work on that.

**Comment by maschwenk** [comment]
@phstc I'd be happy to open a PR
