### ISSUE TITLE
shoryuken not polling from SQS

### ISSUE THREAD

**Issue by ACATTAN** [phstc/shoryuken#415]
Hey guys,

I just tried out version 3.1.5. When launching shoryuken it reads SQS messages in the queue just fine. However, subsequent messages arriving to the queue are not read any more.
The delay set in my yml config file is 30 (sec).
Trying with version 2.1.3 - works well (same configuration exactly). Also worked well in version 1.x.
Any idea?

Thanks!
Ariel

**Comment by phstc** [comment]
@ACATTAN thanks for reporting this! Fixed in 3.1.6. Could you give it another try?

**Comment by ACATTAN** [comment]
Yes of course. I'll test it tomorrow and update.

**Comment by ACATTAN** [comment]
Just checked it and it seems to work fine in 3.1.6, thanks!
