### ISSUE TITLE
ActiveJob adapter does not auto delete messages

### ISSUE THREAD

**Issue by juggy** [phstc/shoryuken#43]
I use the active job adapter and it seems that the messages are not deleted from the queue after completion. 

The auto_delete option is set here, but for some reasons it does not work locally:
https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/extensions/active_job_adapter.rb#L55

I do use 
```config.active_job.queue_name_prefix = Rails.application.secrets.APP_NAME```

in the shoryuken.yml config:
```
queues:
  - [<%=Rails.application.secrets.APP_NAME + "_default"%>, 1]
```

and in the job itself:
```queue_as :default```

(I believe this last of should not have the prefix, otherwise what would the config be good for?)

Thanks,
Julien.

**Comment by phstc** [comment]
Hi @juggy 

I'm not currently using it with Rails, but shouldn't `queue_as :default` use the same prefix? 

`queue_as: "#{Rails.application.secrets.APP_NAME}_default"`

Are you sure that the message from this queue are being consumed? Aren't the `perform` raising an exception? The `auto_delete` doesn't delete messages if the `perform` raises an exception.

**Comment by juggy** [comment]
My bad I was enqueing on save and was saving within the worker. Nevermind.
