### ISSUE TITLE
aws-sdk-sqs is required

### ISSUE THREAD

**Issue by pyromaniac** [phstc/shoryuken#430]
Hey, seems like for `aws-sdk-core` V3, `aws-sdk-sqs` dependency is required. Probably it worth to add this at least to readme.

**Comment by phstc** [comment]
@pyromaniac v3 shouldn't be required. What's the error are you getting?

**Comment by pyromaniac** [comment]
This one: https://travis-ci.org/toptal/chewy/jobs/270283525
https://github.com/toptal/chewy/commit/3c68a231a48f94e9679a9a2a169ea8923d7ee50d - this patch helped

**Comment by phstc** [comment]
@pyromaniac Alright, how about [this](https://github.com/phstc/shoryuken/pull/432/files#r136324286)?

**Comment by pyromaniac** [comment]
the patch will help simply by falling back to v2. But I this it is the right direction chosen right now, we want to use > 2 or >=2 (and probably run travis for both of the versions in this case), but v3 still requires an additional gem to be installed and required.

**Comment by phstc** [comment]
@pyromaniac thanks! 3.1.10 is out with the compatibility fixes! 🎉
