### ISSUE TITLE
Send/receive messages across multiple apps using single SQS Queue

### ISSUE THREAD

**Issue by lysender** [phstc/shoryuken#434]
Is it possible to use `shoryuken` to send message from an app then receive it from another app? I'm trying to send messages to a billing app coming from events from multiple apps instead of calling them directly.

Can I use the same SQS Queue URL for multiple apps and the receiver will be able to receive them normally?

**Comment by phstc** [comment]
Hi @lysender 

Yes, [you can](https://github.com/phstc/shoryuken/wiki/Shoryuken-options) as long as you have permissions for the queues.

**Comment by lysender** [comment]
Great! That's all I need.

Thanks!
