### ISSUE TITLE
Prevent useless logs in production

### ISSUE THREAD

**Issue by Sof31t** [phstc/shoryuken#435]
Hello, i actually opened a PR (https://github.com/phstc/shoryuken/pull/243) and changed log verbosity but it seems that the change has been deprecated by this commit (https://github.com/phstc/shoryuken/commit/ef73e173c3c4624d278baf5088a330cffcc5a5b2#diff-3ad4c83632b5d7b72e1a4afa76344726R25)

Why does this happened ?

**Comment by phstc** [comment]
Hi @Sof31t 

Right, TBH I don't remember if the `info` change was intentionally or not, but I'm happy to add `debug` back.

**Comment by Sof31t** [comment]
Ok thanks @phstc ! I have opened this PR to rollback this change => https://github.com/phstc/shoryuken/pull/436
