### ISSUE TITLE
How to query a queue without fetching messages?

### ISSUE THREAD

**Issue by benhoxie** [phstc/shoryuken#437]
I'm new so sorry if this is dumb. Migrating from Sidekiq and trying to replace code that was checking if a job was already enqueued with specific args. For example, I have some overlapping jobs and don't want to run one if another is already queued.

In sidekiq I can do:

```ruby
Sidekiq::Queue.new("refresh").select{|j| j['class']=='myWorker' && j['args'][0] == special_id}
```

I didn't see anything similar in the Shoryuken queue class / sqs client, but maybe I missed it.

**Comment by phstc** [comment]
Hi @benhoxie 

For reading messages in SQS you need to pull with `receive_messages`.

Alternatively, you can go to the AWS Console/SQS, it let's you inspect messages.

But keep in mind that every time you receive messages, SQS bumps their `receive_count` which can cause messages going to a dead letter queue if you have any configured.

**Comment by phstc** [comment]
>  For example, I have some overlapping jobs and don't want to run one if another is already queued

For preventing that, you can try FIFO queues:

- https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html
- https://github.com/phstc/shoryuken/wiki/FIFO-Queues

**Comment by benhoxie** [comment]
@phstc thanks much for the help, pointers and the disclaimer about the `receive_count`, appreciate it!
