### ISSUE TITLE
Shoryuken Worker not picking up messages from the queue

### ISSUE THREAD

**Issue by asampatoor** [phstc/shoryuken#440]
Probably this might be an old issue. 

When I send messages to the queue, the Shoryuken worker isn't picking up the messages as soon as the message arrives in the queue. (This has been happening **intermittently**)

shoryuken.yml:
concurrency: 1
delay: 0
pidfile: tmp/pids/shoryuken.pid

I start my Shoryuken worker with the command
**"bundle exec shoryuken -q #{queue_name} -R -C ./config/shoryuken.yml"**

This has been happening on my local.

**Comment by phstc** [comment]
@asampatoor `concurrency: 1` causes Shoryuken to process one message at the time, if you receive multiple times at once, only one will be processed at time. Could you confirm if that's the case?

You can try to start Shoryuken with `-v` for a verbose log, and follow what's happening.

**Comment by asampatoor** [comment]
@phstc yes I need the worker to process only 1 message at a time(as of now). 

I have also added -v for a verbose log but nothing productive. 
it says the following:

> Looking for new messages in ta_sab_dev
> [DEBUG] Fetcher for ta_sab_dev completed in 58.86 ms
> [DEBUG] Paused ta_sab_dev
> [DEBUG] Unpaused ta_sab_dev
> [DEBUG] Firing 'dispatch' lifecycle event
> [DEBUG] Shoryuken fetching messages ...
> [DEBUG] Ready: 1, Busy: 0, Active Queues: [["ta_sab_dev", 1]]

**Comment by phstc** [comment]
> If the number of messages in the queue is extremely small, you might not receive any messages in a particular ReceiveMessage response. If this happens, repeat the request.
> https://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#receive_message-instance_method

@asampatoor can that be your case? 

The concurrency I just wanted to clarify that if concurrency is 1, Shoryuken will only fetch new messages, once the worker finishes processing the previous one.

**Comment by phstc** [comment]
@asampatoor every time you see `[DEBUG] Firing 'dispatch' lifecycle event` in the logs means that Shoryuken tried to retrieve messages from SQS. Shoryuken probably trying to retrieve messages and it's not getting any. Did you see my last message about the "small volume of messages"?

**Comment by asampatoor** [comment]
@phstc Yes, I have seen your previous message about the small volume of messages. 
So you mean to use the visibility timeout?

**Comment by asampatoor** [comment]
@phstc Can you give me your email ID so that I can email you/connect which prevents this thread go up to 50 msgs.

**Comment by phstc** [comment]
> So you mean to use the visibility timeout?

@asampatoor I did not mean to say anything related to visibility timeout. I'm not sure how visibility timeout would apply for this. Shoryuken just uses the AWS SDK for retrieving messages, and the `receive_messages` method linked in the previous comment says that if the queue has just a few messages, `receive_messages` may not return any message.

As long as you see `[DEBUG] Firing 'dispatch' lifecycle event` often in the logs, it means that Shoryuken is trying to receive message, if SQS is not returning messages, it's with SQS, not with Shoryuken.

**Comment by asampatoor** [comment]
@phstc Ahhh! Thanks.

I will try to debug it from SQS side.

**Comment by phstc** [comment]
@asampatoor you can try [Long-polling](https://github.com/phstc/shoryuken/wiki/Long-Polling) for waiting longer when receiving messages, that may help if your issue is related to a queue with a very few messages.

**Comment by asampatoor** [comment]
@phstc Sure. I will let you know what I end up with. 

Thank you

**Comment by asampatoor** [comment]
@phstc Hello,

Long-Polling did the magic. Thank you very much.
