### ISSUE TITLE
how to slow down polling process?

### ISSUE THREAD

**Issue by icy** [phstc/shoryuken#441]
Hi,

Is there any option to slow down polling process? (e.g, reduce number the workers, and/or delay between fetches) It's important to control the number of API calls because they may be very expensive.

Thanks

**Comment by phstc** [comment]
Hi @icy 

You can add a [delay](https://github.com/phstc/shoryuken/wiki/Shoryuken-options#delay) for pausing empty queues, and also enable [long polling](https://github.com/phstc/shoryuken/wiki/Long-Polling). That can reduce the number of requests against SQS. 

Does that work for you?

> API calls because they may be very expensive.

Usually SQS isn't expensive ([pricing](https://aws.amazon.com/sqs/pricing/)). How many Shoryuken processes are you running?

**Comment by icy** [comment]
Thank @phstc for your reply. And thank you for your great software 💯 

I think `long polling` would help (however `delay` option is not suitable in my case). I used the default setting (25 workers?) and now I change to a lower value (4). I also add some `sleep` to `dispatch` configuration:

```
Shoryuken.configure_server do |config|
  config.on(:dispatch) do
    # called every time it tries to fetch messages from SQS
    sleep(1)
  end
end
```
You're right SQS isn't expensive. (I thought it's expensive as I have had some bad experience with AWS cloudwatch API calls.) Simple calculation: If my system generates 1 message/1sec, then the price is about

```
(24 * 3600 * 30 * 2 - 1000000) / 1000000 * 0.4 = $1.6 / month
```

(`2` =  1 receive api request + 1 delete api request)

**Comment by phstc** [comment]
@icy keep in mind that the fetch is per Shoryuken process/[processing group](https://github.com/phstc/shoryuken/wiki/Processing-Groups). Reducing the number of workers wouldn't impact much on the number of requests, since the delete (request) is in batch, it would mostly only slow down your processing.

**Comment by icy** [comment]
@phstc Agreed. After some tries I now understand much how SQS and your software work :)

I may miss something in my first post. My point is to control the number of api calls (it may be too many or not, but I need to control them). This is because `shoryuken` would help to dispatch SQS messages and store them to my backend storage (in my case, it's simple `sqlite`, and in another project of my team, it's DynamoDB). If `shoryuken` is too fast, it requires more engineering work at back-end side, and/or to increase the cost there

* For DynamoDB, it's writing capacity which is expensive (really :D)
* For SQLite, it's about locking if I want to deploy exactly-one semantic by using `MessageId` as primary key (and `UPSERT` query.) Only is the message stored successfully to database I would fire a delete event (that means I have to disable `auto_delete` option). If there are too many workers, they only cause locking states and [retries].

**Comment by icy** [comment]
btw, do you think it's useful if `perform` should have its return code to work with `auto_delete` option? Some kind of

```
shoryuken_options auto_delete: true

def perform(sqs, sqsBodyJson)
  if my_own_worker_return_true
    return true # ok, put this message to AutoDelete batch 
 else
   return false # no, don't put this message in AutoDelete batch, we will retry next time.
 end
end
```

Maybe this is possible within current `shoryuken` but I haven't figured out.

**Comment by phstc** [comment]
@icy 

> For DynamoDB, it's writing capacity which is expensive (really :D)

For DynamoDB you can try some alternatives, you can use [`batch`](https://github.com/phstc/shoryuken/wiki/Worker-options#batch), and read and write from DynamoDB in batches as well.

Another alternative is to just let it fail `ProvisionedThroughput`, and [exponential backoff](https://github.com/phstc/shoryuken/wiki/Worker-options#retry_intervals), or a [dead letter queue](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html) and process at the speed you want:

```shell 
shoryuken sqs mv [your-dl-queue] [main-queue] --number [number of messages to requeue]
```

You can also try [Processing groups](https://github.com/phstc/shoryuken/wiki/Processing-Groups) for configuring the concurrency per "job capability".


> btw, do you think it's useful if perform should have its return code to work with auto_delete option? Some kind of

I think might be easier to just `auto_delete: false` and programatically delete the messages.

```ruby
def perform(sqs, body)
  if my_own_worker_return_true
    sqs.delete
 end
end
```

But keep in mind, that not deleting the messages, will cause them to go back to the queue once their visibility timeout expires. I believe the exponential backoff or DL queue are probably better alternatives for retrying.
