### ISSUE TITLE
AWS SQS IAM Policy

### ISSUE THREAD

**Issue by andreayng** [phstc/shoryuken#446]
Adding the sqs:ListQueues action in the IAM Policy shown in the [IAM Policy docs](https://github.com/phstc/shoryuken/wiki/Amazon-SQS-IAM-Policy-for-Shoryuken) is not valid for the queue resource itself - when this action is attached, AWS gives a "This action does not support resource-level permissions. This requires a wildcard (*) for the resource." error. Can you update the policy to show the ListQueues action on the correct resource level?

**Comment by phstc** [comment]
hi @andreayng 

Great catch 🍻  Are you suggesting to use `"Resource": "arn:aws:sqs:::*"` in the doc example?

**Comment by andreayng** [comment]
According to the AWS docs, you can specify down to `"Resource:" "arn:aws:sqs:REGION:ACCOUNT:*"` for ListQueues so I think that would be sufficient.

**Comment by phstc** [comment]
@andreayng thanks! updated.  BTW `ListQueues` is necessary only for the CLI `shoryuken sqs ls` it isn't needed for sending and consuming messages `shoryuken start ...`.

**Comment by andreayng** [comment]
Alternatively, to narrow permissions, you could specify two separate policies - one with all the queue-specific permissions granted to the specific queue resources, and one with only the ListQueues permission granted to the top-level resource.

**Comment by phstc** [comment]
@andreayng Good point. I added [a note in the wiki](https://github.com/phstc/shoryuken/wiki/Amazon-SQS-IAM-Policy-for-Shoryuken) explaining `ListQueues`.

**Comment by andreayng** [comment]
Looks good - thanks!
