### ISSUE TITLE
Worker options are not inherited

### ISSUE THREAD

**Issue by fabiokr** [phstc/shoryuken#450]
Say I have a base worker class that my other workers inherit from, and I have this on it:

```ruby
class BaseWorker
  include Shoryuken::Worker

  shoryuken_options body_parser: :json, auto_delete: true
end

class ChildWorker < BaseWorker
end
```

The child workers are not preserving the config from the parent class. Is that expected behavior?

**Comment by phstc** [comment]
Hi @fabiokr 

Good point. I guess it needs some hackery like [this](https://github.com/mperham/sidekiq/pull/246) ([newer version](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/worker.rb)).
