### ISSUE TITLE
Shoryuken with Fake SQS and Rails: No worker found

### ISSUE THREAD

**Issue by shiroyu** [phstc/shoryuken#452]
Hi. I'm setting the gem with Ruby on Rails 5.1 (Ruby 2.4.1) and [fake_sqs](https://github.com/iain/fake_sqs) following the way.

1. following docs https://github.com/phstc/shoryuken/wiki/Getting-Started and https://github.com/phstc/shoryuken/wiki/Rails-Integration-Active-Job
2. add "fake_sqs" gem
3. create "default.fifo" for "fake_sqs"
4. run Shoryuken and "fake_sqs"
5. enqueue a job using ActiveJob (run `SampleJob.perform_later("sample")` )

It is possible to enqueue, but I can't make it work completely. I'm receiving the same messages all time...

```
2017-12-29T21:17:58Z 1 TID-xy8ws ERROR: No worker found for default.fifo
2017-12-29T21:18:03Z 1 TID-xy8ws ERROR: No worker found for default.fifo
2017-12-29T21:18:24Z 1 TID-xy8ws ERROR: No worker found for default.fifo
2017-12-29T21:18:34Z 1 TID-xy8ws ERROR: No worker found for default.fifo
2017-12-29T21:18:34Z 1 TID-xxtpk ERROR: No worker found for default.fifo
2017-12-29T21:18:34Z 1 TID-y1o1k ERROR: No worker found for default.fifo
```

Of course, use `-R` option to run Shoryuken like the following and use `queue_as` in job files (already read #410), also try to use a standalone worker instead of Active Job, but it does not work.

```bash
$ bundle e shoryuken -R -C config/shoryuken.yml
```

```ruby
class SampleJob < ActiveJob::Base
  queue_as "default.fifo"

  def perform(arg)
    ...
  end
end
```

Any suggestion of what what I'm doing wrong?

**Comment by phstc** [comment]
hi @shiroyu 

hm... have you tried a non `.fifo` queue? Like just `queue_as 'default'`. I'm wondering if there's an issue with `.fifo` and `fake_sqs`.

Could you also share your `shoryuken.yml` and Shoryuken version?

**Comment by shiroyu** [comment]
Hi @phstc! Yes, the jobs are located at `app/jobs` .

As it turns out, it works fine! 😄 
I set a prefix to queue names using `Rails.application.config.active_job.queue_name_prefix=` (also set `Shoryuken.active_job_queue_name_prefixing=`) and append a suffix `.fifo` to queue names.
We need to remove these prefix and suffix to work, but removing only one of these, it does not work
 🤔 

When switching to use from "fake_sqs" to actual AWS SQS, it does work fine. So I'm wondering there's an issue in "fake_sqs" as you say.

Thank you so much for your time!
