### ISSUE TITLE
Consider using 'squash and merge'

### ISSUE THREAD

**Issue by maschwenk** [phstc/shoryuken#453]
First of all, I'm a 2 time contributor and really appreciate your work here.

I just have a minor suggestion for you. Looking at the commit history on master, I see a lot of `WIP`/`git revert` style commits. While I think these can be valuable in the PR timeline like here (https://github.com/phstc/shoryuken/pull/448), I think you may make it easier for you to follow the commit history by using the `Squash and merge` button when you merge PR's. We've done this in my org/personal projects and it's really great. If you want to look at why you abandoned a certain approach in the life of a PR, you always have the PR link to go back to, but when you look long term at changes to the repo, it'll be a more coherent linear changelog.

Just a thought. It also helps contributors coming from the outside have a more concise picture of how single files changed through history/blame

![image](https://user-images.githubusercontent.com/1264305/34528468-07b094e4-f077-11e7-9c61-88b165cc92eb.png)

**Comment by phstc** [comment]
@maschwenk you are right, it's a great idea. I will start doing more `squash` from now on.
