### ISSUE TITLE
How do I get shoryuken to reopen log files in daemon mode

### ISSUE THREAD

**Issue by calvincorreli** [phstc/shoryuken#455]
This is more of a question than an issue, but I can't figure out how to tell shoryuken to reopen log files after logrotate does its thing.

With unicorn or other processes I'm running, I'd send a signal to tell it to reopen log files.

What's the solution here? I'm sure it's something you've come up with a solution for.

Searched all over the repo and came up empty-handed, hence the issue here.

Thank you so much!

–Calvin

:pushpin: #458

**Comment by phstc** [comment]
Hi @calvincorreli 

Actually, there's no option for re-opening log files. Maybe Shoryuken could use `USR2` like [Sidekiq does](https://github.com/mperham/sidekiq/blob/e447dae961ebc894f12848d9f33446a07ffc67dc/lib/sidekiq/cli.rb#L155-L158), WDYT?

I don't usually use Shoryuken logs in production, most of the times I monitor errors on error trackers and performance through CloudWatch etc.

**Comment by calvincorreli** [comment]
I think that USR2 would be excellent. I actually ended up moving away from Shoryuken. I only needed a fraction of what it does, and I don't like the lack of visibility into SQS. I don't have a ton of throughput, so I went with something much simpler. And it knows how to reopen its logs :)

Thanks for considering.

**Comment by phstc** [comment]
@calvincorreli thanks for the update! I opened a PR for the USR2 #458

**Comment by phstc** [comment]
I'm closing this for now due to the inactivity.

**Comment by jef-abraham** [comment]
I believe this is required. If at any time the log file is missing or rotated, the runner should create a new file.
