### ISSUE TITLE
Configurable launcher executor

### ISSUE THREAD

**Issue by brennana** [phstc/shoryuken#456]
Using shoryuken in JRuby, I noticed that job processing was limited to two jobs at a time, and realized this was due to the behavior of the `Concurrent.global_io_executor` used as the executor for the shoryuken `Launcher` class. To solve this on my own end, I had to change the code of the `Launcher#executor` method to hardcode a thread pool with different settings.

It would be very helpful if it were possible to directly configure the executor used by `Launcher` by supplying a different thread pool. The settings of the `global_io_executor` aren't always appropriate given the platform.

**Comment by phstc** [comment]
Hi @brennana 

> I had to change the code of the Launcher#executor method to hardcode a thread pool with different settings.

hm Did you monkey patch the launcher in an initializer? 

```ruby
module Shoryuken
  class Launcher
    private

    def executor
      # custom executor
    end
  end
end
```

> thread pool with different settings.

Could you share your custom executor? 🤔 

We can always make it configurable through an option:

```ruby
def executor
  Shoryuken.launcher_executor || Concurrent.global_io_executor
end
```

I'm just trying to get more details on the use case. Since no one has asked for it before.

Thanks

**Comment by brennana** [comment]
Yes, I monkey-patched the shoryuken launcher executor method to the following:

```ruby
    def executor
      @_executor ||= Concurrent::ThreadPoolExecutor.new(
        min_threads:     4,
        max_threads:     Concurrent::ThreadPoolExecutor::DEFAULT_MAX_POOL_SIZE,
        auto_terminate: true,
        idletime:        60,
        max_queue:       0,
        fallback_policy: :abort
      )
    end
```

Concurrent Ruby's global IO executor is [configured](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/configuration.rb) so that min_threads is the larger of 2 or the processor count of the machine.

I noticed in JRuby that the executor would not spawn more than 2 threads on a machine with only two processors, so we wanted to raise the min_thread count to 4 to force the executor to create 4 threads for processing jobs.

The max_threads config option is ignored by the [Java implementation](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html) of the executor
when using pools with max_queue of 0, as is the case for the global IO executor. This is why I am forced to use a different executor under JRuby to achieve the level of concurrency I desire.

**Comment by phstc** [comment]
Hi @brennana 

I'm down for the change:

```ruby
def executor
  @_executor ||= Shoryuken.launcher_executor || Concurrent.global_io_executor
end
```

Are you available for making a PR?

**Comment by brennana** [comment]
Not at the moment, but perhaps at the end of the week I can make a PR if nothing comes up.
