### ISSUE TITLE
Exclude job_id from the message body when calculating message_deduplication_id for ActiveJob

### ISSUE THREAD

**Issue by nathanpalmer** [phstc/shoryuken#457]
I tested out a FIFO queue with deduplication enabled it didn't prevent duplicate jobs from getting submitted. This is while using ActiveJob which assigns a unique job_id to each message and thus makes the body different. 

Has there been any discussion about removing the `job_id` when processing the `message_deduplication_id` while using ActiveJob?

**Comment by phstc** [comment]
hi @nathanpalmer 

Good point on the `job_id`. Removing the `job_id` from the `message_deduplication_id` seems to make sense.

`job_id` is supposed to be unique per `perform_later`, right?

**Comment by nathanpalmer** [comment]
Yeah, that's right. Simply a uuid that gets generated upon initialization, changes for each `perform_later` like you said.

https://github.com/rails/rails/blob/0f8568f58d36a543f9eb423171f42731784b34af/activejob/lib/active_job/core.rb#L73
