### ISSUE TITLE
Move to modular aws sdk version

### ISSUE THREAD

**Issue by ckgagan** [phstc/shoryuken#463]
Hi,
Currently this gem use the aws-sdk-core gem as dependency which has all the AWS service gems.
AWS has moved its gem to modular gems.
Can this gem use the module aws-sdk-sqs as dependency?

**Comment by phstc** [comment]
Hi @ckgagan

Unless I'm missing something, [`aws-sdk-core` only contains shared utilities, not all service gems](https://github.com/aws/aws-sdk-ruby#upgrade-from-version-2). Also, any other service, such as [`aws-sdk-sqs` require it](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-sqs/aws-sdk-sqs.gemspec#L26) as well.

**Comment by ckgagan** [comment]
@phstc I thought aws-sdk-core contains all service gems. But I was wrong.
Closing the issue :).
