### ISSUE TITLE
Gem Load Error is occurred about aws-sdk-sqs

### ISSUE THREAD

**Issue by muryoimpl** [phstc/shoryuken#464]
Hi.
(related to #463 ?) Today I had a error below when starting shoryuken. 
```
There was an error while trying to load the gem 'shoryuken'.                                                                                              
Gem Load Error is: AWS SDK 3 requires aws-sdk-sqs to be installed separately. Please add gem 'aws-sdk-sqs' to your Gemfile                
Backtrace for gem load error is:  ...
```

this problem is [shoryuken.gemspec](https://github.com/phstc/shoryuken/blob/master/shoryuken.gemspec#L26) only has "aws-sdk-core", but Gemfile has "aws-sdk-sqs" in test group when using aws-sdk V3.

I think "aws-sdk-sqs" should be added as "add_dependency" in shoryuken.gemspec. 
If needed, aws-sdk-core version should be changed into `spec.add_dependency 'aws-sdk-core', '~> 3'`

What do you think?

**Comment by phstc** [comment]
@muryoimpl IIRC this was just for keeping Shoryuken compatible with AWS SDK 2 and 3. If a project is using AWS SDK 2 already (i.e. from other gems), this project wouldn't need to require `aws-sdk-sqs`, since `aws-sdk-core` V2 includes it. If we force AWS SDK 3, projects using other gems requiring AWS SDK 2 would be compatible with Shoryuken.

**Comment by muryoimpl** [comment]
@phstc 
I think that it's more user-friendly to support only one version because user doesn't need to add "aws-sdk-sqs" to Gemfile and now aws-sdk-ruby V3 is installed when installing Shoryuken.

Please consider supported version of "aws-sdk-core" for next release.

**Comment by phstc** [comment]
@muryoimpl I know, but that would drop compatibility with V2, and there are some gems still referencing it.

**Comment by phstc** [comment]
@muryoimpl wait, just read your last message again. Shoryuken does not add `aws-sdk-ruby`, Shoryuken only adds `aws-sdk-core` which for V2 includes SQS, and for V3 it does not.

**Comment by muryoimpl** [comment]
@phstc 
> I know, but that would drop compatibility with V2, and there are some gems still referencing it.

I've understood your consideration.

> Shoryuken does not add aws-sdk-ruby, Shoryuken only adds aws-sdk-core which for V2 includes SQS, and for V3 it does not.

I used "aws-sdk-ruby" as https://github.com/aws/aws-sdk-ruby repository, the breaking change, for V3, is not only for `aws-sdk-core`. I'm sorry if I might give you a misunderstanding.

**Comment by phstc** [comment]
@muryoimpl Thanks for the follow up 🍻  I will definitely consider restricting to >= V3 for a future major release. Meanwhile, I added [these instructions](https://github.com/phstc/shoryuken#installation) in the README.

**Comment by muryoimpl** [comment]
Good instruction!
