### ISSUE TITLE
Does Shoryuken have any hooks to set 'sqs_client_receive_message_opts' ?

### ISSUE THREAD

**Issue by muryoimpl** [phstc/shoryuken#465]
I'll run Shoryuken by `bundle exec shoryuken -C shoryuken.yml -r ./xxxx_worker.rb` and use Long Polling for fetching messages from queue. 

On this case, it's not Rails app and it doesn't have config/initializers or like the mechanism.  Shoryuken seems not to have the way to set `sqs_client_receive_message_opts` like from YAML and command line.

Does Shoryuken have any reasons not to set `sqs_client_receive_message_opts` from YAML or command line?

**Comment by phstc** [comment]
> Does Shoryuken have any reasons not to set sqs_client_receive_message_opts from YAML or command line?

@muryoimpl there's not a really big reason, it's just for simplicity purposes, like a single way of setting it. Keeping the YAML config restricted to the most used options.

You can add the `sqs_client_receive_message_opts` on the top of your `xxxx_worker.rb` or create a `workers.rb` file, which would require your workers and also initializers (on top of the file).

**Comment by muryoimpl** [comment]
@phstc Thank you for your quick replying!

> You can add the sqs_client_receive_message_opts on the top of your xxxx_worker.rb or create a workers.rb file, which would require your workers and also initializers (on top of the file).

Yes, I was going to add `Shoryuken.sqs_client_receive_message_opts = {wait_time_seconds: 20}` on top of  xxx_worker.rb or require a file which is written above on top of xxx_worker.rb as initializer. 

But `sqs_client_receive_message_opts` is a option for queue ( or group?) and it should not be written in xxxx_worker.rb, I think.  So, I've confirmed where the other way is.

**Comment by phstc** [comment]
> But sqs_client_receive_message_opts is a option for queue ( or group?)

@muryoimpl It can be per queue or group:

https://github.com/phstc/shoryuken/blob/4e380a4ec7ee7565a8d0df93298de28ffcd0a12f/lib/shoryuken/fetcher.rb#L64-L65
