### ISSUE TITLE
wait_time_seconds example should be to 20

### ISSUE THREAD

**Issue by muryoimpl** [phstc/shoryuken#471]
According to https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-long-polling.html#sqs-short-long-polling-differences ,

> For the WaitTimeSeconds parameter of ReceiveMessage, a value set between 1 and 20 has priority over any value set for the queue attribute ReceiveMessageWaitTimeSeconds.

so I think that [Long-Polling](https://github.com/phstc/shoryuken/wiki/Long-Polling) example should be  to 20.

What do you think?

**Comment by phstc** [comment]
Hi @muryoimpl 

Great catch, I've just updated it.

**Comment by muryoimpl** [comment]
Thank you!
