### ISSUE TITLE
Shoryuken 3.2.0 does not start simple Rails 5.1.4 app

### ISSUE THREAD

**Issue by jsteer** [phstc/shoryuken#472]
I am trying to create a Rails app that exposes a REST service and also consumes SQS messages.
I have several other successful stand-alone shoryuken apps. This is the first mixed modal app.

**Environment**
- Host - Mac OS El Capitan
- Ruby 2.3.1
- Rails 5.1.4
- Shoryuken 3.2.0
- AWS V3

To reproduce
  1. Create a hello world rails app 
```
rails new helloworld
```
 2. Add simple shoryuken worker in workers directory
```
class TestWorker
  include Shoryuken::Worker
  shoryuken_options queue: 'myqueue', auto_delete: true

  def initialize
  end
 def perform(sqs_msg,body)
    puts "Hello, #{body}"
  end
end
```
 3. Start Rails app with
```
 bundle exec shoryuken -v --rails -q my_queue -C config/shoryuken.yml
```
in the -v tracing, the queue is polled, but rails is never started.

The shoryuken.yml file is
```
rails: true
aws:
  region: 'us-east-1'
concurrency: 1  # The number of allocated threads to process messages. Default 25
delay: 0         # The delay in seconds to pause empty queues. Default 0
queues:
  - 'myqueue'
```

**Comment by phstc** [comment]
Hi @jsteer 

Is it working?

There's another issue related to Rails 5 #467, is it related to yours?
