### ISSUE TITLE
bundle exec shoryuken ls shows queue, but getting The specified queue(s) MY-QUEUE do not exist when starting it

### ISSUE THREAD

**Issue by kamok** [phstc/shoryuken#475]
I recently reinstalled my Homebrew, rvm, Ruby.

On my app, I was able to do `bundle exec shoryuken -q MY-QUEUE -r ./lib/workers/encrypt_ssn_worker.rb` to start it.

Now, I get this message: /Users/kamok/.rvm/gems/ruby-2.3.6/gems/shoryuken-3.2.0/lib/shoryuken/environment_loader.rb:165:in `validate_queues': The specified queue(s) MY-QUEUE do not exist. (ArgumentError)

Here's my `bundle exec shoryuken sqs ls`:
```
Queue                         Messages Available    Messages Inflight    Last Modified
MY-QUEUE    0                     0                    2018-01-17 16:29:18 -0500
```

`aws sqs list-queues` shows the queue url
{
    "QueueUrls": [
        "https://us-west-2.queue.amazonaws.com/1234567890/MY-QUEUE"
    ]
}

Any ideas?

**Comment by phstc** [comment]
@kamok is your Shoryuken process accessing the same region you've provisioned your queue? `us-west-2`?

**Comment by kamok** [comment]
@phstc I'm not sure what you mean. When I do `bundle exec shoryuken sqs ls`, I'm seeing the right queues. I previously switched from another aws credentials using `aws configure` (and input the correct credentials). I entered `us-west-2` on it, as that's where our queue lie.

**Comment by kamok** [comment]
I just did `be shoryuken sqs create test-queue`, and when I did `aws sqs list-queues`, I see the new queue `test-queue` correctly. Here's my trace when I start my queue:

from /Users/kamok/.rvm/gems/ruby-2.3.6/gems/shoryuken-3.2.0/lib/shoryuken/environment_loader.rb:31:in `load'
	from /Users/kamok/.rvm/gems/ruby-2.3.6/gems/shoryuken-3.2.0/lib/shoryuken/runner.rb:40:in `run'
	from /Users/kamok/.rvm/gems/ruby-2.3.6/gems/shoryuken-3.2.0/bin/shoryuken:48:in `start'
	from /Users/kamok/.rvm/gems/ruby-2.3.6/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/kamok/.rvm/gems/ruby-2.3.6/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/kamok/.rvm/gems/ruby-2.3.6/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/kamok/.rvm/gems/ruby-2.3.6/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/kamok/.rvm/gems/ruby-2.3.6/gems/shoryuken-3.2.0/bin/shoryuken:59:in `<top (required)>'
	from /Users/kamok/.rvm/gems/ruby-2.3.6/bin/shoryuken:23:in `load'
	from /Users/kamok/.rvm/gems/ruby-2.3.6/bin/shoryuken:23:in `<main>'
	from /Users/kamok/.rvm/gems/ruby-2.3.6/bin/ruby_executable_hooks:15:in `eval'
	from /Users/kamok/.rvm/gems/ruby-2.3.6/bin/ruby_executable_hooks:15:in `<main>

I even switched my queue name to using `test-queue`, same problem.

**Comment by phstc** [comment]
@kamok you need to make sure `bundle exec shoryuken` is running in the same AWS region you provisioned the queue. 

Some tests:
1. Set `Shoryuken.sqs_client = Aws::SQS::Client.new(region: 'us-west-2')` in the top of your `encrypt_ssn_worker.rb` to make sure Shoryuken is using the same region you created the queue
2. Try to `AWS_REGION=us-west-2 bundle exec shoryuken`

**Comment by kamok** [comment]
@phstc Closing issue. I had a rogue `AWS_REGION=us-east-2` in my dot env config file.

Thanks for the guidance.
