### ISSUE TITLE
Aws::Errors::MissingRegionError

### ISSUE THREAD

**Issue by mobitar** [phstc/shoryuken#477]
I'm trying to integrate with Rails 5 according to [this guide](https://github.com/phstc/shoryuken/wiki/Complete-Shoryuken-Setup-for-Rails-5-with-ActiveJob). 

When I run `bundle exec shoryuken sqs create my_queue`, I get this error:

> ~/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/plugins/regional_endpoint.rb:42:in `after_initialize': missing region; use :region option or export region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)

The guide claims it is a complete setup, but I'm seeing recommendations [here](https://github.com/phstc/shoryuken/issues/180) about what to put in the yaml file that is not in the complete setup tutorial.

Is this all that needs to be in the config file?

```
concurrency: 15
queues:
  - [name_of_your_queue_in_sqs, 1]
```

I also have the following ENV variables declared:

```
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_REGION
AWS_DEFAULT_REGION
```

**Comment by phstc** [comment]
@mobitar can you try `AWS_REGION=us-east-1 bundle exec shoryuken sqs create my_queue`, just to make sure it's getting the ENV variable?

**Comment by mobitar** [comment]
> AWS_REGION=us-east-1 bundle exec shoryuken sqs create my_queue

> ~/.rvm/gems/ruby-2.3.1/gems/aws-sdk-core-3.15.0/lib/aws-sdk-core/plugins/signature_v4.rb:72:in `sign_request': unable to sign request without credentials set (Aws::Errors::MissingCredentialsError)

I ended up just creating the queue manually on the AWS console, and the rest of the integration seems to be working now. Just the queue creation was causing problems.

**Comment by phstc** [comment]
@mobitar Shoryuken does not read `.env`, if you are using dotenv, most likely you need to `dotenv bundle exec shoryuken sqs create my_queue`.

**Comment by mobitar** [comment]
Good call, that worked. Thanks!
