### ISSUE TITLE
Example app for deploying Sinatra to AWS?

### ISSUE THREAD

**Issue by suranyami** [phstc/shoryuken#48]
I've been going around in circles with the AWS documentation for an EB Ruby web server (Sinatra) + SQS worker.

The `shoryuken` docs seem to imply that if you have a Rails app, just add config, now you have workers.

Yet, with my Sinatra app, I have to launch a separate process. I've tested that shoryuken runs and works locally and by running `eb ssh` and connecting to my EB box:

```bash
cd /var/app/current
bundle exec shoryuken -r ./config/shoryuken_init.rb -C config/shoryuken.yml
```

All works fine. But when I tried to configure the workers to be launched by a `.ebextensions/xxx.config` file, I get grief with a `AWSEBAutoscalingGroup` error.

* Should I just fork a child process in my `config.ru`?
* Do I need a separate Worker Tier application created just to run the Workers? If so, how does the webapp launch the workers?

Does anyone have a canonical app/config for deploying a PORO/Sinatra webapp to AWS/SQS?

I'm happy to provide a minimal example if none to date.

**Comment by phstc** [comment]
Hey @suranyami 

I run shoryuken in a standalone application (no Rails) with [foreman](https://github.com/ddollar/foreman):

**Procfile**
```
shoryuken: bundle exec shoryuken -C config/shoryuken.yml -r ./lib/shoryuken_init.rb
```

But I don't use it on AWS EB.

I found something for sidekiq: http://blog.noizeramp.com/2013/04/21/using-sidekiq-with-elastic-beanstalk/ shoryuken is based on sidekiq, so the same steps should work with shoryuken.

**Comment by suranyami** [comment]
Thanks. It's AWS EB in particular that's I'm struggling with.

My current workaround is to add this to `config.ru`:

```ruby
worker_cmd = 'bundle exec shoryuken -r ./config/shoryuken_init.rb -C config/shoryuken.yml'
pid = Process.spawn worker_cmd
```

It works, but my only concern is it's not being monitored by EB, so if the worker crashes it won't be automatically restarted. It'll do for the moment, but when I go to production, it's gotta be more robust than that.

**Comment by phstc** [comment]
If you create a recipe for shoryuken on EB, I would love to add to the project's wiki. :smile: 

> I'll take a look at the Sidekiq/EB article. Thanks!

Anything that works for Sidekiq, should work for Shoryuken

**Comment by CyborgMaster** [comment]
@phstc I don't mean to re-open an old issue, but I just went through this process (Getting shoryuken running on an Elastic Beanstalk Rails server), and I have a config file that you could add to the wiki.  

It's a very minor adaptation of the Sidekiq config from the blog post you linked to.  

``` yaml
# Based on http://blog.noizeramp.com/2013/04/21/using-sidekiq-with-elastic-beanstalk/.
# If we want to try to improve it, we can attempt to add some of the techniques
# included in https://gist.github.com/gcarrion-gfrmedia/11396682.

files:
  "/opt/elasticbeanstalk/hooks/appdeploy/post/50_restart_shoryuken":
    mode: "000777"
    content: |
      cd /var/app/current

      if [ -f /var/app/support/pids/shoryuken.pid ]
      then
        kill -TERM `cat /var/app/support/pids/shoryuken.pid`
        rm -rf /var/app/support/pids/shoryuken.pid
      fi

      . /opt/elasticbeanstalk/support/envvars

      sleep 10

      bundle exec shoryuken \
        -R \
        -P /var/app/support/pids/shoryuken.pid \
        -C /var/app/current/config/shoryuken.yml \
        -L /var/app/support/logs/shoryuken.log \
        -d

  "/opt/elasticbeanstalk/hooks/appdeploy/pre/03_mute_shoryuken":
    mode: "000777"
    content: |
      if [ -f /var/app/support/pids/shoryuken.pid ]
      then
        kill -USR1 `cat /var/app/support/pids/shoryuken.pid`
      fi
```

**Comment by jamilbk** [comment]
Thanks @CyborgMaster !

For anyone else coming across this script, I was getting the error `bundler: command not found: shoryuken`. Changing to this seemed to fix it:

```yaml
# Based on http://blog.noizeramp.com/2013/04/21/using-sidekiq-with-elastic-beanstalk/.
# If we want to try to improve it, we can attempt to add some of the techniques
# included in https://gist.github.com/gcarrion-gfrmedia/11396682.

files:
  "/opt/elasticbeanstalk/hooks/appdeploy/post/50_restart_shoryuken":
    mode: "000777"
    content: |
      EB_SCRIPT_DIR=$(/opt/elasticbeanstalk/bin/get-config container -k script_dir)
      EB_SUPPORT_DIR=$(/opt/elasticbeanstalk/bin/get-config container -k support_dir) 
      . $EB_SUPPORT_DIR/envvars
      . $EB_SCRIPT_DIR/use-app-ruby.sh

      mkdir -p /var/app/support/pids
      mkdir -p /var/app/support/logs

      cd /var/app/current

      if [ -f /var/app/support/pids/shoryuken.pid ]
      then
        kill -TERM `cat /var/app/support/pids/shoryuken.pid`
        rm -rf /var/app/support/pids/shoryuken.pid
      fi

      sleep 10

      bundle exec shoryuken \
        -R \
        -P /var/app/support/pids/shoryuken.pid \
        -C /var/app/current/config/shoryuken.yml \
        -L /var/app/support/logs/shoryuken.log \
        -d

  "/opt/elasticbeanstalk/hooks/appdeploy/pre/03_mute_shoryuken":
    mode: "000777"
    content: |
      if [ -f /var/app/support/pids/shoryuken.pid ]
      then
        kill -USR1 `cat /var/app/support/pids/shoryuken.pid`
      fi
```

**Comment by erwinkarim** [comment]
this is exactly what i'm looking for. should be in the documentation regrading deployment to AWS elastic beanstalk...

**Comment by phstc** [comment]
@erwinkarim good call. I added a link to this issue [here](https://github.com/phstc/shoryuken/wiki/Deployment#aws-elastic-beanstalk).

**Comment by MatayoshiMariano** [comment]
Hi guys, I have realized that for shoryuken to work in Elastic Beantalk Worker Tier, I had to stop the aws-sqsd service, do you have to do it too?

The commando: `sudo service aws-sqsd stop`

**Comment by januszm** [comment]
@MatayoshiMariano see this thread, especially the first message from @farski https://github.com/phstc/shoryuken/issues/169

and this article about ElasticBeanstalk Worker Environments http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-tiers.html

Looks like Shoryuken and the EB  Worker Environment SQS Daemon do the same job, they poll SQS queue and trigger jobs. So it seems that it makese sense to disable the aws sqs daemon in your case. But it actually makes more sense to not use Shoryuken in EB Worker Env

**Comment by MatayoshiMariano** [comment]
@januszm yes, the best solution is not to use Shoryuken service, but I am using Shoryuken to send the message to SQS. I am developing the option to use Shoryuken with EB WorkerTier

**Comment by januszm** [comment]
But stopping that daemon defeats the purpose of using EB Workers right? Perhaps you should send messages to SQS from your Web Environment?

**Comment by MatayoshiMariano** [comment]
Yes, now I am using the SQS daemon in the EB Worker tier, but I use Shoryuken to send the message to the SQS from the Web Tier. The only problem to use Shoryuken is that it send the class name in a message attribute but the Amazon SQS daemon does not retrieve any message attribute so I have to make a little tweak in the gem. 

Here is the [commit](https://github.com/MatayoshiMariano/shoryuken/commit/6f9b6d97ffdf5931083e09f2053b5a316e10e4da) in my fork.

**Comment by greggroth** [comment]
In case the pre/post deploy hooks are removed (I've heard they've been deprecated), here's a version that uses an init.d script:

```yaml
files:
  "/usr/bin/shoryuken":
    mode: "000777"
    owner: root
    group: root
    encoding: plain
    content: |
      #!/bin/bash

      cd /var/app/current

      bundle exec shoryuken \
        --rails \
        --config /var/app/current/config/shoryuken.yml \
        --log /var/log/shoryuken.log \
        --pidfile /var/app/support/pids/shoryuken.pid \
        --daemon

  "/etc/init.d/shoryuken":
    mode: "000777"
    owner: root
    group: root
    encoding: plain
    content: |
      #!/bin/bash
      #
      # chkconfig: 35 90 12
      # description: Shoryuken Worker
      #

      # Get function from functions library
      . /etc/init.d/functions

      # Start the service Shoryuken
      start() {
          if [ ! -f /var/app/support/pids/shoryuken.pid ]; then
                echo -n "Starting Shoryuken Worker: "
                /usr/bin/shoryuken &
                success $"Shoryuken Worker Startup"
                echo
          else
                echo -n "Shoryuken Worker Running"
          fi
      }

      # Restart the service Shoryuken
      stop() {
              echo -n "Stopping Shoryuken Worker: "
              killproc shoryuken
              rm -f /var/app/support/pids/shoryuken.pid
              echo
      }


      ### main logic ###
      case "$1" in
        start)
              start
              ;;
        stop)
              stop
              ;;
        status)
              status shoryuken
              ;;
        restart|reload|condrestart)
              stop
              start
              ;;
        *)
              echo $"Usage: $0 {start|stop|restart|reload|status}"
              exit 1
      esac

      exit 0
commands:
  "01":
    command: sudo touch /var/log/shoryuken.log
  "02":
    command: sudo chmod 666 /var/log/shoryuken.log
  "03":
    command: /etc/init.d/shoryuken start
```

**Comment by lpsBetty** [comment]
I was just redeploying my app with the .ebextensions config above, had anyone had this error?:

```
Return code: 1 Output: /opt/elasticbeanstalk/hooks/appdeploy/pre/03_mute_shoryuken: line 3: kill: (14036) - No such process. 
```

**Comment by tomharvey** [comment]
FYI - I've updated the config file to use AWS environment variables to dictate the location of the log, pid and working directories. Working well on `Puma with Ruby 2.5 running on 64bit Amazon Linux/2.9.1`

https://gist.github.com/tomharvey/a248800e492305bbf5ba3d56fa1e0513
