### ISSUE TITLE
Can the license be changed to MIT

### ISSUE THREAD

**Issue by sivajag** [phstc/shoryuken#481]
MIT license is better and more open compare to LGPL. It will be great if you could change to MIT. 

Thanks

**Comment by phstc** [comment]
Hi @sivajag 

Shoryuken was based on [Sidekiq](https://github.com/mperham/sidekiq). Therefore, it must be see LGPL.

Is there any specific restriction with LGPL for your use case?

See #19

**Comment by sivajag** [comment]
Our company policy does not allow to use open source projects that are LGPL. 

Great library, unfortunately we cannot use with this license.
