### ISSUE TITLE
More memory leak issues

### ISSUE THREAD

**Issue by paul** [phstc/shoryuken#482]
Hi, I'm seeing memory leak issues in the latest shoryuken 3.2.2.

![selection_020](https://user-images.githubusercontent.com/184/37415771-d3945e70-2771-11e8-8087-9d994d32aed4.png)

This Heroku dyno is running a single shoryuken worker with 5 threads on a single queue with 0 jobs.

```
$ cat Procfile | grep shoryuken
messages_worker: bin/start-pgbouncer-stunnel bundle exec shoryuken start -R -C config/shoryuken.yml
```

```
$ cat config/shoryuken.yml 
aws:
  # access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  # secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  receive_message:
    # only grab 1 message from the queue at a time
    max_number_of_messages: 1

# Number for worker threads
concurrency: 5
# If receive_message comes back empty, how long to wait before trying again
delay: 0
# When shutting down, how long to wait for a busy worker to finish before killing it
# Heroku gives us 10 seconds, so leave time to clean up
timeout: 8
queues:
  - ["messages-ingress", 1]
```

It looks like an "empty fetch" is what's leaking memory. I spun up this dyno and never put any jobs on its queue, and started getting the heroku R14 out-of-memory errors right away.

**Comment by paul** [comment]
I downgraded to 3.1.2, and memory usage is fine:

![selection_022](https://user-images.githubusercontent.com/184/37526463-0940d8a8-28f5-11e8-87e8-75da0b2f0bc9.png)

**Comment by paul** [comment]
Perhaps I spoke too soon, I've been running 3.1.2 on Heroku for awhile, it it still leaks a small amount. Interestingly, on our staging server that receives very few jobs, it looks like memory holds steady after boot with no messages, and then after a single message is processed, then the memory usage slowly grows again.

Here you can see memory growing after a restart, then holding steady overnight. Then after processing 1 message about an hour ago, memory starts growing again:
![selection_024](https://user-images.githubusercontent.com/184/37672482-b3599c4e-2c33-11e8-87d2-fcfc9b24d512.png)

This is looking back over two days, you can see the same thing happening yesterday. Memory usage remains high enough that Heroku complains about R14 (memory) errors, and then it gets restarted:
![selection_025](https://user-images.githubusercontent.com/184/37672684-1f2337dc-2c34-11e8-9154-4dc564e02d25.png)

**Comment by paul** [comment]
More investigation:

I monkeypatched `Shoryuken::Fetcher#fetch` to print out memory usage, both from the Linux `/proc/{pid}/statm` for RSS and Ruby's own `ObjectSpace.memsize_of`.

When the runner performs a fetch with no jobs on the queue, it looks like memory grows by ~100KiB on every "loop". It continues doing this "forever", until I assume some sort of memory pressure forces a GC. On Heroku, though, this doesn't happen until Heroku starts firing off "R14 low memory" alerts (It also doesn't happen on other threaded-runners, like Puma and Sidekiq).

I tried instrumenting it with the `SamSaffron/memory_profiler` gem, and it looks like there's a few "retained" objects in the shoryuken gem, but they seem to mostly be in `aws-sdk-core` or `net/http`. 

If I add an explicit `GC.start` inside the `#fetch` loop, then it seems that memory never grows at all. Is `GC` somehow explicitly disabled in the fetcher thread? Are there any costs to re-enabling it, or to adding an explicit GC.start inside the loop like I've done here in my monkeypatch? I'm not sure why GC isn't happening for these objects of the normal course of fetcher operation.

```
2018-03-20T19:36:52Z 20600 TID-gskozys8c INFO: Starting
[Fetcher] Before: 59562.27KiB
[Fetcher] After fetch: 59669.53KiB (+107.259KiB)
[Fetcher] After GC: 57572.21KiB (-1990.060KiB)

[Fetcher] Before: 58599.48KiB
[Fetcher] After fetch: 58706.70KiB (+107.220KiB)
[Fetcher] After GC: 58599.29KiB (-0.198KiB)

[Fetcher] Before: 59626.71KiB
[Fetcher] After fetch: 59733.93KiB (+107.220KiB)
[Fetcher] After GC: 59626.43KiB (-0.282KiB)

[Fetcher] Before: 60653.86KiB
[Fetcher] After fetch: 60761.08KiB (+107.220KiB)
[Fetcher] After GC: 60653.61KiB (-0.243KiB)

[Fetcher] Before: 61680.88KiB
[Fetcher] After fetch: 61788.10KiB (+107.220KiB)
[Fetcher] After GC: 61680.60KiB (-0.282KiB)

[Fetcher] Before: 62707.87KiB
[Fetcher] After fetch: 62815.09KiB (+107.220KiB)
[Fetcher] After GC: 62707.63KiB (-0.243KiB)
```

monkey-patched fetcher:

```ruby
class Shoryuken::Fetcher
  def fetch(queue, limit)
    fetch_with_auto_retry(3) do
      mem = GetProcessMem.new
      started_at = Time.now

      before = mem.bytes
      puts "[Fetcher] Before: %0.2fKiB" % (before / 1024)
      logger.debug { "Looking for new messages in #{queue}" }

      sqs_msgs = Array(receive_messages(queue, [FETCH_LIMIT, limit].min))

      logger.debug { "Found #{sqs_msgs.size} messages for #{queue.name}" } unless sqs_msgs.empty?
      logger.debug { "Fetcher for #{queue} completed in #{elapsed(started_at)} ms" }
      after = mem.bytes
      puts "[Fetcher] After fetch: %0.2fKiB (%+0.3fKiB)" % [after / 1024, (after - before) / 1024]

      GC.start
      after = mem.bytes
      puts "[Fetcher] After GC: %0.2fKiB (%+0.3fKiB)" % [after / 1024, (after - before) / 1024]
      puts

      sqs_msgs
    end
  end
end
```

memsize implementation:

```ruby
  def bytes
    memsize = 0
    ObjectSpace.each_object do |obj|
      memsize += ObjectSpace.memsize_of(obj)
    end
    memsize
  end
```

**Comment by aridlehoover** [comment]
@phstc I noticed that the OP said the memory leak was in 3.2.2. Yet, you suggest rolling back to 3.1.5 as a solution. Is that correct? Has the memory leak @paul described been fixed? I'm seeing what looks like a memory leak in both 3.2.3 and 4.0.
