### ISSUE TITLE
Not respecting active_job queue name prefix in production environments

### ISSUE THREAD

**Issue by paul** [phstc/shoryuken#483]
I seems like something is different in the load order between dev and prod rails environments. In my local dev, shoryuken correctly constructs the prefixed queue name, pulls messages of the correct queue, and sends them to the right Job class. In prod, it does not construct the correct queue name, and tries to pull messages from that non-existent queue. (I create_queue manually because I need to set attributes and subscribe it to an SNS topic). 

Local dev environment:

```
$ rails c
[textus|development|main]> MessageIngressJob.queue_name
=> "paul-messages-ingress"
[textus|development|main]> TextUs::Application.config.active_job.queue_name_prefix
=> "paul"
```

Heroku production/staging/review app:

```
irb(main):001:0> MessageIngressJob.queue_name
=> "messages-ingress"
irb(main):002:0> TextUs::Application.config.active_job.queue_name_prefix
=> "textus-staging-pr-551"
```

I am expecting the job's queue_name to be `textus-staging-pr-551-messages-ingress`.

```
$ cat config/initializers/shoryuken.rb 

TextUs::Application.configure do
  config.active_job.queue_name_prefix = ENV.fetch("HEROKU_APP_NAME", `whoami`.chomp)
  config.active_job.queue_name_delimiter = "-"
end

Shoryuken.configure_server do |config|
  config.active_job_queue_name_prefixing = true
end
```

```
$ cat config/shoryuken.yml 
aws:
  # access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  # secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  receive_message:
    # only grab 1 message from the queue at a time
    max_number_of_messages: 1

# Number for worker threads
concurrency: 5
# If receive_message comes back empty, how long to wait before trying again
delay: 0
# When shutting down, how long to wait for a busy worker to finish before killing it
# Heroku gives us 10 seconds, so leave time to clean up
timeout: 8
queues:
  - ["messages-ingress", 1]
```

If I use ERB to try and set the prefixed queue_name within the shoryuken.yml from the config, I get an error, even when using -R on the shoruken cli:

```
$ tail -3 config/shoryuken.yml
queues:
  - ["<%= TextUs::Application.config.active_job.queue_name_prefix %>-messages-ingress", 1]

$ shoryuken start -v -R -C config/shoryuken.yml
...snip...
(erb):16:in `<main>': uninitialized constant TextUs (NameError)

**Comment by phstc** [comment]
Hi @paul, I think this is similar to what @oyeanuj is raising on #487. Could you try to set `paul-messages-ingress` also in the `shoryuken.yml`?  There are some issues with loading the Rails before reading the Shoryuken, so at `shoryuken.yml` loading time, the Rails app isn't loaded, so you can't use `TextUs::Application`

You can create a helper `queue_name.rb` and load it in your  `config/initializers/shoryuken.rb` and also in your `shoryuken.yml`, so you can share the logic for getting the queue name. Other option is to use [dotenv](https://github.com/bkeepers/dotenv) for setting the queue name in development, then in development you can `dotenv shoryuken ...`

**Comment by paul** [comment]
Hi @phstc,

Sorry for the long delay in replying.

My main concern was regarding why the prefix is set as expected in dev/test mode, but not in production. I have the env var `HEROKU_APP_NAME` present, and set that as the prefix so that each review app gets its own "namespace" of queues. Locally, having the "naked" queue name in the shoryuken.yml seems to work fine, but not once it gets to "production" in a review app, it seems to drop the prefix.

**Comment by phstc** [comment]
@paul you need to set the prefix in the `shoryuken.yml`.

**Comment by paul** [comment]
@phstc hrm, ok. thanks. weird that it works fine locally then. /shrug

**Comment by JaisonBrooks** [comment]
bundle exec shoryuken -q auto_approval

lib/shoryuken/environment_loader.rb:165:in `validate_queues': The specified queue(s) auto_approval do not exist. (ArgumentError)

class AutoApprovalJob < ActiveJob::Base
  queue_as 'auto_approval'

concurrency: 10 # Number of Threads
delay: 25

Shoryuken.active_job_queue_name_prefixing = true

config.active_job.queue_adapter = :shoryuken
    config.active_job.queue_name_prefix = "svmgr_#{Rails.env}"
    config.active_job.queue_name_delimiter = '_'


Whats missing here.

**Comment by phstc** [comment]
@JaisonBrooks you need to specify the full queue name `-q svmgr_development_auto_approval`.
