### ISSUE TITLE
Dead Letter Queue documentation is gone

### ISSUE THREAD

**Issue by JoostSaanen** [phstc/shoryuken#486]
The link [https://github.com/phstc/shoryuken/wiki/Creating-a-queue#dead-letter-queue](https://github.com/phstc/shoryuken/wiki/Creating-a-queue#dead-letter-queue) on the wiki-page [https://github.com/phstc/shoryuken/wiki/Retrying-a-message](https://github.com/phstc/shoryuken/wiki/Retrying-a-message) is not working anymore. Is there a way to fix this?

**Comment by phstc** [comment]
@JoostSaanen great catch. It's updated now, thanks! 🍻
