### ISSUE TITLE
NonExistentQueue errors with fifo queues

### ISSUE THREAD

**Issue by oyeanuj** [phstc/shoryuken#487]
Hey again @phstc, I am just making the branched conversation in #484 its own thread to make sure things don't get lost in the noise.

So, to recap, here is my setup:
```rb
class TransactionalEmailsJob < ApplicationJob
  queue_as 	Proc.new { "mailer.fifo" }
  ...
end

#shoryuken.yml
queues:
  - [mailer.fifo, 1]
```
and I've set `auto_prefix: true` and therefore also created a queue called `developer_mailer.fifo` on SQS already.

Not sure if this was coming across in the previous thread, so thought I'd reframe it more clearly. Thoughts on what might be going wrong?

Thanks as always for your help!

**Comment by phstc** [comment]
@oyeanuj  in the `shoryuken.yml` you need to set the full queue name `developer_mailer.fifo`. Please, let me know if that works.

**Comment by oyeanuj** [comment]
@phstc Upgraded to the latest, and tried with your suggestion, but still the same error.

**Comment by phstc** [comment]
@oyeanuj could you paste the error log? The queue name in the `shoryuken.yml` must be set with the prefix you are using, so if your prefix is `developer_`, you must define `developer_mailer.fifo` in your `shoryuken.yml` and make sure to have that queue created in the region you are trying to access. 

Shoryuken tries to reads the queues based on the names set `shoryuken.yml` without adding any prefix, so it must be set with the final name. This setup is working, it's must be a misconfiguration. Maybe the error log can give some guidance. What you can also try, is to `shoryuken sqs ls`, so you can check if the queue name you've set in the `shoryuken.yml`, is listed via `sqs ls`.

**Comment by JaisonBrooks** [comment]
So if we have a prefix based on the environment. Do i have to list all of the "Environment_QueueName"'s in my queues section of the yml file? Do is this what folks bring up about only loading environment specific queues, hence creating different yml files based on environment

**Comment by phstc** [comment]
Hi @JaisonBrooks 

In the `shoryuken.yml` you need to specify the full queue name.
