### ISSUE TITLE
Aws::SQS::Errors::AccessDenied: Access to the resource https://sqs.eu-central-1.amazonaws.com/..... is denied.

### ISSUE THREAD

**Issue by DaddyWozBucks** [phstc/shoryuken#489]
Hey there,

I moved our project over from ActiveElasticJob as Shoryuken supports the AWS SDK v3. I have managed to get the queues running successfully on my local machine (moto & AWS SQS production queues both working fine). When I deploy to AWS things stop working. The Shoryuken server runs fine on the worker instance but the main app that posts the job to the queue returns 
"Aws::SQS::Errors::AccessDenied: Access to the resource https://sqs.eu-central-1.amazonaws.com/003688427525/excel_worker is denied."

I have the AWS creds set in the ENV variables and specified in the shoryuken.yml and shoryuken.rb initializer as laid out in the setup. My IAM user also has full access to SQS and running the local version confirms the credentials are correct.

Any idea why this isnt working?

**Comment by phstc** [comment]
@DaddyWozBucks hm it seems that your setup is right. Maybe try `bundle exec shoryuken sqs ls` to see what queues it lists for you. 

Your setup does look correct, but maybe you can review it based on these pages:

- https://github.com/phstc/shoryuken/wiki/Configure-the-AWS-Client
- https://github.com/phstc/shoryuken/wiki/Amazon-SQS-IAM-Policy-for-Shoryuken

**Comment by DaddyWozBucks** [comment]
@phstc When I run that locally all the queues show up, however when I run it while ssh'ing in to the server it returns 

> bundler: failed to load command: shoryuken (/opt/rubies/ruby-2.4.3/bin/shoryuken)
Aws::SQS::Errors::AccessDenied: Access to the resource https://sqs.eu-central-1.amazonaws.com/ is denied.

I have attached my shoryuken.yml and .rb to confirm I am not screwing this up in the config. When I try using just "excel_worker" as the queue name it cant find it but Shoryuken is designe dto take the absolute urls, right?
.yml -`
aws:
  access_key_id: <% ENV["AWS_KEY"] %>
  secret_access_key: <% ENV["AWS_SECRET"] %>
  receive_message:
    attribute_names:
      - ApproximateReceiveCount
      - SentTimestamp
  region: eu-central-1

concurrency: 25
pidfile: tmp/pids/shoryuken.pid
queues:
  - https://sqs.eu-central-1.amazonaws.com/003688427525/excel_worker
`

.rb - `
module Shoryuken
  module Middleware
    module Server
      class RavenReporter
        def call(worker_instance, queue, sqs_msg, body)
          tags = { job: body['job_class'], queue: queue }
          context = { message: body}
          Raven.capture(tags: tags, extra: context) do
            yield
          end
        end
      end
    end
  end
end
Shoryuken.configure_server do |config|
  # Replace Rails logger so messages are logged wherever Shoryuken is logging
  # Note: this entire block is only run by the processor, so we don't overwrite
  #       the logger when the app is running as usual.
  Shoryuken.sqs_client = Aws::SQS::Client.new(access_key_id: ENV['AWS_KEY'], secret_access_key: ENV['AWS_SECRET'])
  Rails.logger = Shoryuken::Logging.logger
  Rails.logger.level = Rails.application.config.log_level
  config.server_middleware do |chain|
    chain.add Shoryuken::Middleware::Server::RavenReporter
  end

  # For dynamically adding queues prefixed by Rails.env 
  # %w(queue1 queue2).each do |name|
  #   Shoryuken.add_queue("#{Rails.env}_#{name}", 1)
  # end
end
`

 I used the sample IAM policy provided and even granted blanket permissions to my server IAM user. The keys work fine for accessing S3 and the other sdk's (not to mention access from the local machine)

This is driving me a bit nuts :(

**Comment by phstc** [comment]
Hi @DaddyWozBucks 

The AWS credentials no longer work in the `shoryuken.yml`, you need to set as instructed in [here](https://github.com/phstc/shoryuken/wiki/Configure-the-AWS-Client).
