### ISSUE TITLE
How to pause/restart shoryuken?

### ISSUE THREAD

**Issue by rmharrison** [phstc/shoryuken#491]
## Context
I am using `Shoryuken::Worker.perform` to dequeue messages to a 3rd-party application.

When the 3rd party application is unavailable, swamped or otherwise "unhealthy", I'd like to pause shoryuken. When the 3rd party application becomes "healthy" again, I'd like to resume shoryuken.

So, how to a pause/restart shoryuken?

## Options
Digging through the code and wiki, I have been unable to find an implemented pause/restart. It's also unclear at which level of the application I should be pausing/restarting (launcher, manager, fetcher).

Options include:
- Custom Middleware: https://github.com/phstc/shoryuken/wiki/Middleware
- Using a life-cycle hook: https://github.com/phstc/shoryuken/wiki/Lifecycle-Events
  - Example using `:dispatch` to sleep: phstc/shoryuken#441 (comment)
- Custom polling strategy: https://github.com/phstc/shoryuken/wiki/Polling-strategies
- Writing a pause method. Unclear where though:
  * [launcher](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/launcher.rb)
    - Has `stop` method, but this shutsdown.
  * [manager](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/manager.rb)
  * [fetcher](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/fetcher.rb)

Thoughts? 

Maybe others have had this problem, and I can contribute a proper solution for posterity.

**Comment by phstc** [comment]
hi @rmharrison 

I would probably the custom polling strategy option first. You can extend an existing one, but only returning a queue `next_queue` if you have a flag set. But I'm wondering if it wouldn't be easier to just shutdown, then start when it is back.

There are also some other options, for example, if the 3rd is unavailable, you can send the messages back to the queue with a delay or move messages to another queue.

There are two options for sending messages with delay, [one is creating a new message, which supports up to 15 minutes](https://github.com/phstc/shoryuken/wiki/Sending-a-message#delaying-a-message), or just by [extending the message visibility timeout](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/middleware/server/auto_extend_visibility.rb#L37), which is up to 12 hours.

**Comment by rmharrison** [comment]
Did you have a snippet on the appropriate way to shutdown and restart shoryuken? I've read through the code and wiki, and it's unclear where/how.

**Comment by phstc** [comment]
> You can extend an existing strategy, but only returning a queue next_queue if you have a flag set. But I'm wondering if it wouldn't be better to just shutdown, then start when it is back.

@rmharrison I don't have snippet doing that, I've never had that use case. But you can try a custom pooling strategy.

How are you going to tell Shoryuken to pause?
