### ISSUE TITLE
Does not support aws-sdk 2.3.15

### ISSUE THREAD

**Issue by narutosanjiv** [phstc/shoryuken#494]
I have tried to run this application on aws-sdk 2.3.15 but i found that `Aws::Errors::NoSuchEndpointError` is missing from aws-sdk version 2.3.15

**Comment by phstc** [comment]
Hi @narutosanjiv 

Do you know what's equivalent to `Aws::Errors::NoSuchEndpointError` in 2.3.15? I tried to find when `NoSuchEndpointError` was added, but I couldn't follow it in the SDK code. 

If you remove `Aws::Errors::NoSuchEndpointError` is there anything else that does not work with 2.3.15?

**Comment by phstc** [comment]
Closing due inactivity.
