### ISSUE TITLE
LGPL-3.0 license issue

### ISSUE THREAD

**Issue by Rushyanth** [phstc/shoryuken#497]
https://spdx.org/licenses/LGPL-3.0.html
This says the LGPL - 3.0 license is deprecated.
In the latest release of shoryuken you provide this license.

**Comment by phstc** [comment]
@Rushyanth I'm not aware of LGPL-3.0 being deprecated. Shoryuken was based on Sidekiq, and it must follow Sidekiq's license. 

See #19 

cc/ @mperham

**Comment by mperham** [comment]
I don't know what that deprecated banner means.  GNU is trying to get more libraries to license under the GPL (https://www.gnu.org/licenses/why-not-lgpl.html)[https://www.gnu.org/licenses/why-not-lgpl.html] so maybe that's what they mean.  Shoryuken, being a Modified Version under the LGPL, cannot change the license except to opt into the stricter GPL, see clause 2(b).
