### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by rwadstein** [phstc/shoryuken#500]
I have a, hopefully, simple question regarding a potential issue with my company continuing to use this gem.  We have several private applications using `shoryuken`, but the LGPLv3 license is causing some concerns since our repos are private.  There is a potential implication that we would have to disclose our source code because of using `shoryuken` with the LGPLv3 license.  
Is there any specific reason you have a LGPLv3 as opposed to MIT?

**Comment by phstc** [comment]
Hi @rwadstein 

Shoryuken is based on Sidekiq, therefore it needs to use LGPLv3, see #497. 

> There is a potential implication that we would have to disclose our source code because of using shoryuken with the LGPLv3 license.

I think that is only if you are using a variation on top of Shoryuken, not for your specific business code, but It is been a while last time I check the details on LGPLv3.
