### ISSUE TITLE
Clarification on concurrency parameter

### ISSUE THREAD

**Issue by mobitar** [phstc/shoryuken#501]
Hello, I just wanted to make sure I understand the [concurrency](https://github.com/phstc/shoryuken/wiki/Shoryuken-options#concurrency) parameter correctly.

> Concurrency is the number of threads available for processing messages at time.

I'm using Rails with Passenger, and non-enterprise Passenger does not support multi-threading, so it will create a new instance of the app for every request. 

My question is, if my `concurrency` value is set to 10, is that 10 a global value for all instances of my application? Or, is that 10 per running process of the app?

I'm using capistrano/shoryuken to deploy my app, which I believe stops and starts the shoryuken process such that there is one global process running. Does this mean the value I set for `concurrency` will be the maximum number of jobs shoryuken is running at a time, regardless of how many app processes are running?

**Comment by phstc** [comment]
`concurrency` is the number of threads available for processing messages per Shoryuken process.

If you set `concurrency` to 10, it means that 10 SQS messages/jobs can be concurrently processed at a time.

> I'm using Rails with Passenger, and non-enterprise Passenger does not support multi-threading, so it will create a new instance of the app for every request.

I'm not sure if I followed this part. The Shoryuken process runs separately of the application server. 

> Does this mean the value I set for concurrency will be the maximum number of jobs shoryuken is running at a time, regardless of how many app processes are running?

If you have 10 Shoryuken processes running, each one of them configured with `concurrency` 10, it will give you 100 SQS messages/jobs concurrently processing power. 

Does that make sense?

**Comment by phstc** [comment]
@mobitar The only thing Shoryuken does with Rails, is the Active Job integration, so you can have Active Job workers, instead of standard Shoryuken workers. 

Shoryuken does not initiate any Rails instance.

**Comment by mobitar** [comment]
Got it thanks!
