### ISSUE TITLE
'should_retry?' method not found for Shoryuken::Worker

### ISSUE THREAD

**Issue by andreayng** [phstc/shoryuken#503]
Going off of this wiki page: [https://github.com/phstc/shoryuken/wiki/Retrying-a-message](https://github.com/phstc/shoryuken/wiki/Retrying-a-message), we are trying to use the should_retry? method to check whether or not the current message needs to be retried again. The should_retry? method is part of AWS::Plugins::RetryErrors and our worker is unable to find this method.

We have included Shoryuken::Worker in our worker class and set the auto_delete option to false according to the docs, is there anything else we should be doing to make this method visible to our worker?

**Comment by phstc** [comment]
Hi @andreayng 

I'm sorry for the confusion. `should_retry?` was just an example in that wiki, similar to `do_something`. I updated the wiki to avoid the confusion.

**Comment by andreayng** [comment]
Ah, okay - is there similar logic that we could use to tell if a particular message should be retried?
