### ISSUE TITLE
A very weird problem

### ISSUE THREAD

**Issue by makoton** [phstc/shoryuken#504]
Hi, first of all I wanted to thank you for this awesome gem :D 

I have a weird problem when a worker that raises an exception triggers something that re-sends the message to SQS, here's an example of what happens:
- my application enqueues an operation 
- shoryuken sends the message to sqs
- shoryuken reads from the queue and processes the message through my worker
- the process ends and I didn't delete the message from sqs (I'm not using `auto_delete`)
- shoryuken then sends the message again to sqs!!, so now I have 1 message that's not visible and a new one that now gets processed and fails

so this keeps happening and from one action I got a couple thousand messages on sqs.

Some background on my setup:
ApplicationWorker

```
class ApplicationWorker
  include Shoryuken::Worker

  shoryuken_options queue: ENV['sqs_queue'], auto_visibility_timeout: true

  def perform(sqs_msg, params)
    @sqs_message = sqs_msg
    work(params)
  end

  def work(params)
    # Abstract method. Not Implemented
  end

  def delete_sqs_message!
    @sqs_message.delete
  end
end
```
I'm not using auto_delete because I'm managing retries based on status of completion, so a failed job gets to be reprocessed unit it lands on the dead letter queue, and a completed process gets its sqs message deleted through the `delete_sqs_message` method.

```
class BackgroundJobsWorker < ApplicationWorker

  def work(message)
    Rails.logger.debug "[BackgroundJobsWorker] Started. Background job received: #{message.inspect}"

    background_job = BackgroundJobs::BackgroundJob.where(
        id: message[:background_job_id].to_i,
        status: [
            BackgroundJobs::BackgroundJob::STATUS[:pending],
            BackgroundJobs::BackgroundJob::STATUS[:failed],
            BackgroundJobs::BackgroundJob::STATUS[:aborted]
        ]
    ).first if message[:background_job_id]

    return unless background_job
    background_job.process!

    background_job.reload

    if background_job.completed?
      delete_sqs_message!
    end

    Rails.logger.debug "[BackgroundJobsWorker] Finished"
  end
end
```

I tried this on a controlled local environment, where I was absolutely sure to just trigger one operation to be enqueued and set it up to raise an exception to test that a message would get retried and then sent to the dead letter queue.

I checked the messages that were created on my queue and all of them had the same exact body, that's what lead me to believe that shoryuken was re-sending the message.

If you need any more information please let me know, I didn't know what else to add
thank you very much for any help!!

**Comment by phstc** [comment]
hi @makoton 

Shoryuken does not enqueue messages by itself. But keep in mind you are using `auto_visibility_timeout`, which bumps the visibility timeout.

**Comment by makoton** [comment]
Hi @phstc ,thanks for your reply!
This is a little embarrassing but I discovered after some long hours of debugging that the issue was always on my side of the code 😞 but your answer gave me enough clues to find the right path, so thank you very much and I'm sorry to have wasted some of your time

thanks again!

**Comment by phstc** [comment]
Hi @makoton 

I'm happy you found it. I hear you, it can be very tricky.
