### ISSUE TITLE
Possible to accomplish effective rate limiting?

### ISSUE THREAD

**Issue by mobitar** [phstc/shoryuken#505]
I'm using AWS SES to send emails, and I have a max send rate of 28 emails per second. Each email is a job that is queued to SQS. Is my understanding correct that this would make it so that no more than 28 jobs run every second?

```
Shoryuken.sqs_client_receive_message_opts = { 
  wait_time_seconds: 1, 
  max_number_of_messages: 28 
}
```

**Comment by mobitar** [comment]
Hmm so I just tested with this:

`config/initializers/shoryuken.rb`:

```
Shoryuken.sqs_client_receive_message_opts = {
  wait_time_seconds: 5,
  max_number_of_messages: 1
}
```
However, the messages I queue all come in at once and are executed right away. Should I be configuring anything in the SQS dashboard?

I'm using Shoryuken 3.2.3. I've made sure to restart the queue as well as the application after any changes.

**Comment by phstc** [comment]
@mobitar just make sure your workers won't exceed the visibility timeout, it causes the messages to become available/visible again.
