### ISSUE TITLE
Shoryuken workers get "stuck" between finishing job and deleting from queue

### ISSUE THREAD

**Issue by paul** [phstc/shoryuken#510]
We're seeing a strange issue with Shoryuken on Heroku with ActiveJob. We have its processing a single job that pulls a message from the SQS queue and puts it onto a sidekiq queue after a small amount of manipulating the hash. The ActiveJob portion of the work seems to complete very quickly (~5ms) as expected, but then intermittently (sometimes every 10 minutes for a few hours, sometimes we go a week without seeing it at all) the shoryuken worker appears to get "stuck" for as long as several minutes, before finally deleting the message from the SQS queue.

We've tried several different settings for concurrency, and it still happens, even with concurrency=1. When concurrency is higher than that, like 10 or 25, then it happens to all workers simultaneously. That is, when concurrency=25, then all 25 workers finish the ActiveJob job in a few ms, and then they all get "stuck" together for 2-3 minutes, then all delete the message from the queue within a few 100ms of each other. 

I've attached an annotated log showing the first worker getting stuck, another worker on a different dyno grabbing the job after the visibility timeout and finishing it, and then the original worker. 

https://gist.github.com/paul/65f2ef22d365869580b34e88860c630e

I'm not sure if this is a Shoryuken problem or a concurrent-ruby thread deadlock problem or something else entirely. Has anyone seen anything like this before?

**Comment by pedros007** [comment]
I've been using Shoryuken for years in a similar paradigm. I have a Shoryuken worker on an AWS ECS cluster in us-east-1. It runs as `shoryuken start -R -r ./app/workers -C config/shoryuken.yml` and does the following:
1.  reads a message from SQS
2.  manipulates the message slightly
3.  enqueues a Delayed::Job (via ActiveJob)
4.  Delete SQS message.
This has worked great for tens of thousands of messages for several years.  4 days ago (when you opened this message) is the first time I've experienced Shoryuken worker getting stuck.  I just saw the same problem again about an hour ago.  Both instances I restart my Shroyuken Worker and everything seems to work like normal again.  The last message before getting stuck was:

> 2018-07-13T20:34:49Z 1 TID-gqytrl6s8 MyWorker/some-sqs-queue/69a579cc-ee27-493e-8bb7-b3ce1299aaf0 INFO: completed in: 36.218323 ms

Next time this happens I'll try and run `strace` on the process to try and hope for some useful message.  It's sporadic (I've seen it twice ever. Once July 11 after shoryuken was running for 7 days. Another after running for 4 days July 16).

Here's my `config/shoryuken.config`:
```
concurrency: 1
delay: 20
queues:
  - some-sqs-queue
```

Versions from Gemfile.lock:
```
    shoryuken (3.2.3)
      aws-sdk-core (3.22.1)
      concurrent-ruby (1.0.5)
      thor (0.20.0)
```

**Comment by phstc** [comment]
That's interesting. I got admit that from time to time (rarely, but it happens) I get messages in my dead letter queue without any error being logged in my error tracker, which makes me believe the timeout has expired.

☝️ for that Shoryuken setup, my Redrive Policy/Max receives is 1, meaning that, if the visibility timeout expires, the message goes to the respective DL.

I'm wondering if that's something with Shoryuken/concurrent-ruby or with the AWS/ AWS SDK holding up requests. In theory standard queues support "unlimited" scalability:

> Standard queues support a nearly unlimited number of transactions per second (TPS) per action.
> https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-limits.html

But since this happen so rarely, I wouldn't be surprised if it is something with the SDK or AWS.

**Comment by paul** [comment]
It looks like the problem is with Honeybadger, and how they handle throttling within their agent: https://github.com/honeybadger-io/honeybadger-ruby/issues/283

**Comment by phstc** [comment]
@paul great job on that 🍻
