### ISSUE TITLE
Rails is loaded after config file is parsed

### ISSUE THREAD

**Issue by adaminglehart** [phstc/shoryuken#511]
Up until recently I was using an older version of Shoryuken (2.0.11). I'm currently trying to upgrade to the latest version (3.2.3), but I've found that Rails is now being loaded **after** setting up options from a config file (when using the `--rails` and `--config=<config_file_path>` CLI options). This was not the case before, so you were able to reference things like environment variables if using a library like dotenv or Rails config from application.yml, e.g.
```
queues:
  - <%= CONFIG[:sqs_queue] %>
  - my-<%= Rails.env %>-queue
```
Looks like https://github.com/phstc/shoryuken/pull/261 is the PR where this changed. Based on https://github.com/phstc/shoryuken/pull/197 it seems like, at least at some point, Rails was intended to be loaded first, perhaps this is no longer the case? If not, any recommendations for how to accomplish this a different way? Thanks!

**Comment by phstc** [comment]
Hi @adaminglehart 

There are some problems with loading Rails first, if we do it first, there will be some issues in Shoryuken, like if we fix one, we break the other.

Some alternatives:

- a) Replace `Rails.env` with `ENV['RAILS_ENV']` in case you are setting `RAILS_ENV`
- b) Create two configs for Shoryuken, shoryuken.development.yml and shoryuken.yml

WDYT?

**Comment by adaminglehart** [comment]
@phstc Thanks for the prompt response! 

I see, that's too bad. Using `ENV['RAILS_ENV']` will work for that particular case, but for any other environment-specific configuration I'll have to go with using different Shoryuken configs per-environment. I was hoping to avoid this because I'd prefer to store things like environment-specific queues in a centralized place like application.yml, since that info also needs to be accessed in the worker class and potentially other places in the codebase, but I'll figure out a way to make it work since it sounds like that won't be an option at the moment. 

This is a total shot in the dark, but an interesting option would be if the name of the worker's queue could somehow be specified separately from the actual SQS endpoint. So, if your shoryuken.yml was just
```
queues:
  - high-priority
```
and then the worker class had `shoryuken_options queue: 'high-priority', sqs_url: CONFIG[:high_priority_queue_url]`, or if in your shoryuken initializer you could specify mappings from queue names to SQS endpoints. This would be similar to how Sidekiq works, where the name of your queues is separate from which Redis endpoint you're connecting to. I'm not familiar enough with Shoryuken's codebase to know if this is even remotely an option (I imagine it's not) but just an idea

Anyways, thank you for the help, and for providing an awesome gem!

**Comment by phstc** [comment]
@adaminglehart you could also try to add the queues at the runtime, for example using a Rails initializer. 

See [`add_queue`](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/environment_loader.rb#L120).
