### ISSUE TITLE
FIFO & Exactly Once Processing

### ISSUE THREAD

**Issue by CGDS** [phstc/shoryuken#519]
In the best practices section of the wiki and in #257, it talks about the importance of writing idempotent jobs as a consequence of SQS queues only guaranteeing at least once delivery.  Since shoryuken also supports the newer FIFO queues now though, which do support [exactly once processing](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html#FIFO-queues-exactly-once-processing), it seems like the documentation could use a little brushing up to mention the other option.  If I got that right, that is.  Mind if I open a PR?

**Comment by phstc** [comment]
> Mind if I open a PR?

@CGDS please 🙏 Actually for wiki pages, you don't need to PR, you can just update them!

Even with FIFO queues, it is still important to write idempotent workers, for example: in case a worker fails and you need to retry a partially executed message, if the visibility timeout expires etc. Besides that, FIFO only prevents dups sent [within a 5 minutes interval](http://www.pablocantero.com/blog/2017/08/06/using-ruby-and-amazon-sqs-fifo-queues/) as long as you use a valid "Message Deduplication ID".

**Comment by CGDS** [comment]
Good point(s)
Made an edit, please feel free to revert or modify as you please

**Comment by phstc** [comment]
Hi @CGDS 

Which wiki did you change? I would love to have a 👀

I couldn't find updates [here](https://github.com/phstc/shoryuken/wiki/FIFO-Queues).

**Comment by phstc** [comment]
NVM just found it https://github.com/phstc/shoryuken/wiki/Best-Practices

Thanks ❤️
