### ISSUE TITLE
Issue with shoryuken 3.0.11 and aws-sdk > 2.11.105

### ISSUE THREAD

**Issue by algorist** [phstc/shoryuken#520]
Wanted to make you aware of a problem with certain versions of shoryuken and the aws-sdk gem. We began encountering unexpectedly high concurrency in our systems, and after experimentation, we discovered that a recent bundle update had caused the aws-sdk gem to bump to 3.x. Shoryuken had stayed constant at 3.0.11, but until we locked at aws-sdk 2.11.105 or below, we were having the issue. We didn’t have time to root cause it, but we wanted to at least make you aware so you can take a look and/or add some constraints in the gemspec.

**Comment by phstc** [comment]
Hi @algorist 

What happened exactly when you bumped to 3.x? For 3.x are you requiring `gem 'aws-sdk-sqs'` or all the SDK?

**Comment by algorist** [comment]
Hey @phstc,

Thanks for following up. We did a deeper dive, and discovered the problem was caused by a very weird corner case in our build pipeline that wouldn't be relevant to others. I hope I didn't send you on a wild goose chase. If I did, I apologize.

Keep up the good work with Shoryuken--it's a core piece of our infrastructure and works great :)

Cheers,
Chris
