### ISSUE TITLE
Manual consumption of Dead Letter Queue?

### ISSUE THREAD

**Issue by tibbon** [phstc/shoryuken#522]
I've got jobs that have failed into the DLQ. 

I want to have a rake task to re-attempt them all. Yet, I'm failing to see how to do this without having a worker automatically consuming them. Any tips? I do *not* want a worker automatically retrying the DLQ items.

**Comment by phstc** [comment]
@tibbon I usually go with `shoryuken sqs mv dead-letter-queue original-queue`.

You could also `shoryuken sqs dump dead-letter-queue`, review the generated dump, then `shoryuken sqs requeue original-queue dump.jsonl`.

WDYT?

**Comment by tibbon** [comment]
Oh that's great! I assume there's also just code/classes behind the requeue command so I could do it outside the command line. 

Thanks for such quick response. I'll report back!

**Comment by phstc** [comment]
> I assume there's also just code/classes behind the requeue command so I could do it outside the command line.

In a way yes, but the implementation for those commands are coupled with Thor, it might be trick to re-use them.

https://github.com/phstc/shoryuken/blob/master/bin/cli/sqs.rb
