### ISSUE TITLE
Client#receive_message gives TypeError

### ISSUE THREAD

**Issue by Pharserror** [phstc/shoryuken#523]
aws-sdk-core 2.6.33
shoryuken 3.3.0

I'm trying to poll a queue so that I can confirm a message made it there (btw documentation was overly difficult to find for `Shoryuken::Client.queues('myQueue).receive_messages({})`) however, I am repeatedly getting the error `TypeError: no implicit conversion of Array into String` from aws-sdk-core/structure.rb:63. In this case `args` is `[[:attributes]]`. Not really sure what's going on but, it doesn't work.

Please help, cheers,
- Pharserror

**Comment by Pharserror** [comment]
Just realized this is a problem with aws-sdk-core more than Shoryuken. Maybe force a depedency version?

**Comment by Pharserror** [comment]
Actually, could this be an issue with how `Aws::SQS::Client` is called? Reopening.

**Comment by Pharserror** [comment]
OK I think I was calling this wrong. Good conversation @Pharserror 👍

**Comment by phstc** [comment]
> (btw documentation was overly difficult to find for Shoryuken::Client.queues('myQueue).receive_messages({})) 

@Pharserror for sending and receiving messages without the a Shoryuken worker and the Shoryuken processor, I would use the aws-sdk-sqs directly.

I'm glad you sorted the problem.

> Good conversation @Pharserror 👍

@Pharserror is a good pal.
