### ISSUE TITLE
Example of yml file

### ISSUE THREAD

**Issue by rept** [phstc/shoryuken#524]
Hi,

The getting started is pretty to the point but doesn't specify anywhere where to configure URLs and credentials.

For testing I created this yml file:

```ruby
aws:
  access_key_id: 'XXXXXXXXXXXX'
  region: 'eu-central-1'
  secret_access_key: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  endpoint: 'https://sqs.eu-central-1.amazonaws.com/XXXXXX/events'
concurrency: 20
delay: 5
queues:
  - ['events', 2]
```

The strange thing is, when I don't set access_key_id, region and secret_access_key as ENV variables it's not working.  Does this mean these options aren't taken into account from the YML file?

**Comment by phstc** [comment]
Hi @rept 

You need to configure the AWS SDK separately: https://github.com/phstc/shoryuken/wiki/Configure-the-AWS-Client

**Comment by rept** [comment]
Great, that works, thanks!
