### ISSUE TITLE
daemonization

### ISSUE THREAD

**Issue by robert-carroll** [phstc/shoryuken#526]
More question than issue.

I read through this, https://github.com/phstc/shoryuken/issues/320#issuecomment-282290069
But want to OS the solution not write it for just myself.
Do you forsee any issues if I write custom daemonization using Process, or gem and allow custom option arguments from the command line that then runs the bundle exec start for shoryuken?

**Comment by phstc** [comment]
Hi @robert-carroll  

I don't know if I could follow what you are trying achieve. Do you want to run `bundle exec start for shoryuken` from another process? 

>  using Process, or gem

What would `gem` be in this case?

**Comment by robert-carroll** [comment]
Thanks Pablo!

I cannot seem to start 
bundle exec shoryuken -r ./fetch.rb -C sqs/config.yml
as a background process efficiently, disconnecting it from the terminal and allowing the user to close the terminal without killing the program.

I'd also like to be able to simplify this as
service servicename start|stop|restart
and take option arguments
-e environment (test|production)
-u (utility methods)

I'm leaning toward just using Process, and making the worker part of the program instead of the main method.

gems for daemonization seem to be
https://www.ruby-toolbox.com/categories/daemonizing

If you have a better suggestion I'd appreciate your thoughts. I've tried going through the documentation, issues, and seeing how others are doing this but can't find much.

**Comment by phstc** [comment]
@robert-carroll you need `-d` to make it run in daemon mode.

```
bundle exec shoryuken -d -r ./fetch.rb -C sqs/config.yml 
```

**Comment by robert-carroll** [comment]
Tried that
[FAIL] You should set a logfile if you're going to daemonize
I have /dev/null or as an option in config.yml

What about passing arguments for the optional methods/tasks I want to run in the worker?

**Comment by phstc** [comment]
@robert-carroll why don't you only set the `--logfile` as a param?

**Comment by robert-carroll** [comment]
I'm receiving hundreds of thousands of messages a day, the verbose logging of shoryuken is great for testing, but for production I would need to truncate these logs daily or append dates and roll them over. Passing an argument to disable logging or allowing a method to change the file is useful, but I don't always need logging.

**Comment by robert-carroll** [comment]
I'd still like to be able to define what task I'd like to run. I'm guessing this would be be done by requiring different workers with -r at the cli?

**Comment by phstc** [comment]
@robert-carroll if you don't want the logging, you can just `--logfile /dev/null`.
