### ISSUE TITLE
Throttling

### ISSUE THREAD

**Issue by Yaroslav-F** [phstc/shoryuken#535]
Hello there,

Very quick question here: is there a way to throttle fetching of messages from SQS queues ? I'm looking for functionality similar to [sidekiq-throttled](https://github.com/sensortower/sidekiq-throttled#usage) here.
If throttling isn't possible just now - do you expect it to be on the roadmap at some point down the line?

Thanks!

**Comment by phstc** [comment]
Hey @Yaroslav-F 

You can limit the concurrency per queue, but there's no option for limiting the number of processed jobs per interval, like that:

```
    # Allow maximum 1K jobs being processed within one hour window.
    :threshold => { :limit => 1_000, :period => 1.hour }
```

You may need to implement your own [polling strategy](https://github.com/phstc/shoryuken/tree/master/lib/shoryuken/polling) and [this](https://github.com/phstc/shoryuken/wiki/Polling-strategies) for that. I haven't planned to implement that, but I will be happy to accept pull requests.
