### ISSUE TITLE
no worker found for queue 

### ISSUE THREAD

**Issue by nerdherdwa** [phstc/shoryuken#540]
I am having an issue trying to get the worker to process.

I have an SQS queue which im sending a manual message to.

I have set up my Shoryuken Worker as follows and it is under the app/workers path (i have tried in both locations app/workers or app/jobs

```
class CreateWorker
  
  include Shoryuken::Worker
  shoryuken_options queue: ENV["create_queue"], auto_delete: true, body_parser: JSON
  
  def perform(sqs_msg, body)
    puts sqs_msg.body
  end  
end
```
my shoryuken.yml file looks like this and is under the config path

```
#logfile: ./shoryuken.log
#pidfile: ./shoryuken.pid
#delay: 30
concurrency: 1
#polling_strategy: StrictPriority
queues:
  - dev-create
  - dev-update
```
i start up the shoryuken server using the following command
shoryuken -R -C config/shoryuken.yml

the server starts and this is when i send a manual message to SQS queue. The message goes in and then automatically switches to the Messages In Flight and the console is displaying Error: no worker found for dev-create and repeats this until i purge the SQS queue to remove the file from Messages In Flight.

Im expecting the body to pushed out to console to see if the job is working before i proceed with doing something. Im new to using the process so maybe i am missing something in the setup

**Comment by nerdherdwa** [comment]
further to this i can send the command 

shoryuken -R -C config/shoryuken.yml -r create_worker.rb

this worker now works....how do i get it to work if i have multiple workers that need to process what command can i send if i only send the flag -r without any worker file it throws an error

in `require': cannot load such file -- require (LoadError)

**Comment by phstc** [comment]
@nerdherdwa `-R` is for loading Rails, if your workers are configured in the Rails load path, they should be all loaded. Other options is to `-r workers.rb` and inside `workers.rb` require all workers you need.
