### ISSUE TITLE
SQS AccessDenied even though Listing Queues works

### ISSUE THREAD

**Issue by oyeanuj** [phstc/shoryuken#547]
Hi @phstc! Similar to #489, I'm facing SQS errors while creating or consuming a queue. 
<img width="951" alt="screen shot 2019-01-14 at 5 30 37 pm" src="https://user-images.githubusercontent.com/9633371/51152883-ad7b3b80-1822-11e9-9d96-1693279bb454.png">

In the screenshot above, you'll notice that the `sqs ls` command works but the others don't. I am using an IAM policy (below) assigned to a user. It seems that the policy works (?) since it can access the queue. 

Any ideas what might be going on? 

---
Here is my setup:

`Shoryuken: 4.0.3`
`aws-sdk-sqs: 1.10.0`
`aws-sdk-core: 3.45.0`
`Rails: 5.2.2`

The keys to the user with the IAM policy are listed in `.env` file.

#### IAM
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "sqs:DeleteMessage",
                "sqs:GetQueueUrl",
                "sqs:ChangeMessageVisibility",
                "sqs:DeleteMessageBatch",
                "sqs:SendMessageBatch",
                "sqs:ReceiveMessage",
                "sqs:SendMessage",
                "sqs:GetQueueAttributes",
                "sqs:ChangeMessageVisibilityBatch"
            ],
            "Resource": "arn:aws:sqs:us-west-2:ACCOUNT:*"
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": "sqs:ListQueues",
            "Resource": "*"
        }
    ]
}
```

```yml
# config/shoryuken.yml
aws:
  receive_message:
    attribute_names:
    - ApproximateReceiveCount
    - SentTimestamp
concurrency: 25
delay: 0
queues:
  - [mailers, 1]
```

```rb
# Rails Initializer
Shoryuken.configure_server do |config|
	# Replace Rails logger so messages are logged wherever Shoryuken is logging
	# Note: this entire block is only run by the processor, so we don't overwrite
	#       the logger when the app is running as usual.
	Rails.logger = Shoryuken::Logging.logger

	
	# config.server_middleware do |chain|
	#  chain.add Shoryuken::MyMiddleware
	# end
end

Rails.application.configure do
	config.active_job.queue_name_prefix = Rails.env
	config.active_job.queue_name_delimiter = "_"
end

Shoryuken.active_job_queue_name_prefixing = true
```

```rb
# ActiveJobs File
class TransactionalEmailsJob < ApplicationJob
	queue_as 	:mailers
	#options 	auto_delete: true

	rescue_from ActiveJob::DeserializationError do |ex|
		Shoryuken.logger.error ex
		Shoryuken.logger.error ex.backtrace.join("\n")
	end


	def perform(action_object, email_type)
          ...
        end
end
```

---

Thanks so much!

**Comment by oyeanuj** [comment]
@phstc Thank you for the super quick response (and yes, I did follow that link in the wiki)! 

Unfortunately, your suggestion didn't work.. here is the output:
<img width="914" alt="screen shot 2019-01-14 at 6 43 00 pm" src="https://user-images.githubusercontent.com/9633371/51155413-4498c100-182c-11e9-9597-46c43ec59115.png">

Thoughts?

**Comment by phstc** [comment]
@oyeanuj it is trying to find a queue named `_mailers` without the env prefix 👇 

![image](https://user-images.githubusercontent.com/105652/51178755-99baee00-1891-11e9-95ea-1b517defbe70.png)

So that means that you `RAILS_ENV` is probably not set.

You can try to default to `development` when not set:

```yaml
queues:
  - [<%= ENV.fetch('RAILS_ENV', 'development') %>_mailers, 1]
```

But make sure to have that in production you have it set to `production`, otherwise production will try to use `development`. Does that make sense?
