### ISSUE TITLE
Real-time problem

### ISSUE THREAD

**Issue by nm1l0serd0v** [phstc/shoryuken#550]
Hello, thanks for this awesome tool!
In Conectar we use SQS for the payment API and have some weird problem.
It took ~13-25 seconds to receive a message from the queue. But with this [script](https://gist.github.com/nm1l0serd0v/48b4693979a4e58a0a29b282306b0659), I receive them immediately 
There is my config [file](https://gist.github.com/nm1l0serd0v/9eacb90092c2038144ca8a38281ec4af)
What can be a problem?

**Comment by phstc** [comment]
Hi @nm1l0serd0v 

Do you have a `shoryuken.yml`? How do you start Shoryuken?

A few possible differences:

* In Shoryuken you are using `wait_time_seconds` which will make the requests to wait longer. See [`WaitTimeSeconds`](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-long-polling.html).
* `Shoryuken.add_group('default', 3)` you are setting concurrency to three, meaning that Shoryuken can only process/poll three messages at a time.

**Comment by nm1l0serd0v** [comment]
Sorry for the late answer. The problem comes from the payment API. Thank you!
