### ISSUE TITLE
ActiveJob with retry_on— retries indefinitely despite "attempts" option

### ISSUE THREAD

**Issue by alexford** [phstc/shoryuken#553]
Given the following ActiveJob class in Rails 5.2.2:

```ruby
class TestRetries < ApplicationJob
  class RetryError < StandardError; end
  retry_on RetryError, attempts: 2

  def perform
    fail RetryError
  end
end
```

I would expect the job to run in Shoryuken only twice, but it runs indefinitely, repeating at each `visibility_timeout` period. I am seeing this in the logs from ActiveJob, but the message remains in SQS:

```
Stopped retrying TestRetries due to a TestRetries::RetryError, which reoccurred on 2 attempts. The original exception was nil.
```

`discard_on` works as expected—the job is only run once.

Is there some bit of configuration I'm missing here, or is this not expected to work?

ActiveJob's docs for `retry_on`: https://api.rubyonrails.org/v5.2.2/classes/ActiveJob/Exceptions/ClassMethods.html#method-i-retry_on

**Comment by phstc** [comment]
Hi @alexford 

`retry_on` and `discard_on` are not supported in the current Shoryuken adapter (unless it is something Active Job manages without using adapters). Are they supported by the [other adapters](https://github.com/rails/rails/tree/master/activejob/lib/active_job/queue_adapters) already? These options are new to me, I don't know how they work with the adapters yet. 

For SQS, I believe that `retry_on` would be better implemented with dead letter queues.

**Comment by alexford** [comment]
Thanks for the quick reply, @phstc.

I notice that with `discard_on`, the exception is captured, so I assume Shoryuken auto-deletes as intended. That would explain why that one does work.

With `retry_on`, ActiveJob does re-raise the exception every time, even if `attempts` has passed, so Shoryuken does not delete the job from SQS. I am not sure how adapters are expected to handle this case, or how ActiveJob is keeping track of retries in the first place. I will look into it a little bit when I get some time. In the meantime I can make adjustments in my worker to account for this.

**Comment by alexford** [comment]
There is a good workaround, though: `retry_on` allows a block to be passed for handling the exception once the retry attempts have been exhausted. Rescuing the exception in this block allows Shoryuken's auto_delete to take care of the job for us.

```ruby
retry_on RetryableError, attempts: 2 do |exception|
  Raven.capture_exception(exception) # for example, if using Sentry, or log however you want
end
```

**Comment by phstc** [comment]
@alexford that's a great solution. 

The [auto delete](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/extensions/active_job_adapter.rb#L85) used for AJ, [does not delete the message if the worker raises an error](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/middleware/server/auto_delete.rb#L12).

The only way to make `retry_on` to work with Shoryuken/SQS is what you suggested.

```ruby
retry_on ErrorYourPerformMayRaise, attempts: N do |_job, _exception|
  # log error, etc.
  # do not raise the error up, otherwise Shoryuken will not auto delete the message
end
```

Another option would be:

```ruby
retry_on ErrorYourPerformMayRaise, attempts: N

rescue_from ActiveJob::DeserializationError do |_exception|
  # log error, etc.
  # do not raise the error up, otherwise Shoryuken will not auto delete the message
end
```

**Comment by jmammen** [comment]
Hi,

a) is not working for me. I configured my Dead Letter queue accordingly and set the `maxReceiveCount` to 1. My job is executed N times and then the retry_on block is executed but the job never makes it way into the Dead Letter queue. When I remove the block and basically do it like in c) its working. Is that a bug? Or do I do some mistakes? Using ActiveJob with the Shoryuken adapter.

`app/jobs/my_job.rb`
```
class MyJob < ApplicationJob
  queue_as 'my_queue'

  retry_on MyException1, MyException2, attempts: 3

  def perform(message)
    myService.perform_service(message)
  end
end
```
`config/shoryuken.yml`
```
concurrency: 15
queues:
  - [my_queue, 1]
```

**Comment by phstc** [comment]
Hi @jmammen 
For a) are you also passing a block?

You should use this

```ruby
retry_on MyException1, MyException2, attempts: 3 do |_job, _exception|
  # log error, etc.
  # do not raise the error up, otherwise, Shoryuken will not auto-delete the message
end
```

Instead of just:

```ruby
retry_on MyException1, MyException2, attempts: 3
```

Otherwise, Active Job will raise up errors and Shoryuken won't delete the messages. As pointed out by @alexford.

> With retry_on, ActiveJob does re-raise the exception every time, even if attempts has passed, so Shoryuken does not delete the job from SQS
