### ISSUE TITLE
Error: __NSPlaceholderDictionary may have been in progress in another thread when fork() was called.

### ISSUE THREAD

**Issue by luisdgutierrez05** [phstc/shoryuken#554]
I'm trying to run my worker locally `MyWorker.perform_later(params)` but I'm getting this error:

objc[35186]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
objc[35186]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug

rails 5.1.2
ruby 2.3.4
shoryuken 4.0.3
aws-sdk-sqs 1.10

I'm using OX Movaje, but I have another project with Shoryuken and it's working fine.

Regards

**Comment by phstc** [comment]
@luisdgutierrez05 that's a probably an OS X specific problem.  You may need to 

```
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```

Check [this post](https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/).

**Comment by luisdgutierrez05** [comment]
@phstc thank you for your response but I already try that and still not working. As I mentioned I have another project using Shoryuken and is working fine without that export.

Regards

**Comment by phstc** [comment]
@luisdgutierrez05 that's not specific to Shoryuken. I remember seeing this before, and I believe `OBJC_DISABLE_INITIALIZE_FORK_SAFETY` or setting something similar did the trick.

There are some steps here as well https://github.com/rtomayko/shotgun/issues/69

**Comment by luisdgutierrez05** [comment]
The issue was fixed just upgrading to ruby >= 2.4.4 without using this `OBJC_DISABLE_INITIALIZE_FORK_SAFETY`
