### ISSUE TITLE
Workers in different languages?

### ISSUE THREAD

**Issue by foucist** [phstc/shoryuken#555]
If I have programs in different languages reading/writing to SQS, is shoryuken a bad fit?

I'm getting the sense that shoryuken is meant to be the only consumer of messages, and only 1 queue per shoryuken process?  Is that correct?

Does the worker registry matter for outside workers?

**Comment by phstc** [comment]
Hey @foucist 


Shoryuken can work with any message in SQS, no matter if it was sent with Shoryuken or not. 


If the message was not sent with Shoryuken, it is likely Shoryuken will work only with queue per worker. If you send the message with Shoryuken, you can use multiple workers per queue. 

Shoryuken sets message headers to determine which worker should consume each message, if you don't send messages with Shoryuken, nor set the headers, Shoryuken can't figure out which worker to use, therefore, one worker per queue. But but you can always implement a [custom worker registry](https://github.com/phstc/shoryuken/blob/34f8ae64bbec53d7fa388540923eff938a66ff5f/lib/shoryuken/default_worker_registry.rb#L16-L27) tailored to your setup.
