### ISSUE TITLE
Question about how ExponentialBackoff and AutoDelete work 

### ISSUE THREAD

**Issue by amrocco** [phstc/shoryuken#556]
Hi, first of all thanks @phstc for this great gem! I'm trying to understand the code a little bit better, specifically some of the middleware. My question is what is preventing a message that is retried with exponential backoff from being auto deleted? If the exception is being rescued and not re-raised in the ExponentialBackoff middleware then I would think the AutoDelete middleware runs next, and deletes that. But that is not the case, so there is something I'm missing.

**Comment by phstc** [comment]
Hi @amrocco 

How are you configuring `ExponentialBackoffRetry`? Unless you use a block, [exponential backoff never stop processing](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/middleware/server/exponential_backoff_retry.rb#L39).

If you configure `retry_intervals` as a block, [it would raise an error if you proc returns `nil`](https://github.com/phstc/shoryuken/blob/34f8ae64bbec53d7fa388540923eff938a66ff5f/lib/shoryuken/middleware/server/exponential_backoff_retry.rb#L23) you could catch that and delete the message.
