### ISSUE TITLE
Add option to fail gracefully in the event of Aws::SQS::Errors::AccessDenied

### ISSUE THREAD

**Issue by PlanetEfficacy** [phstc/shoryuken#557]
First, thank you for this amazing open source tool.

I'm curious what you think about adding a rescue block in the event that a `Aws::SQS::Errors::AccessDenied` is raised? I'll give you our current use case.

We have many different Shoryuken workers reading off many different SQS queues. I recently added a new worker and new sqs queue, but our rails app does not have permission to read off the queue. For various reasons our Rails app is on a different AWS account than the one that owns the SQS queue in question. This was a bad setup issue on my part, and it led to a `Aws::SQS::Errors::AccessDenied` error:

```
[31mbundler: failed to load command: shoryuken (/home/MY_APP/.gem/ruby/2.4.0/bin/shoryuken)[0m
Aws::SQS::Errors::AccessDenied: Access to the resource https://sqs.us-east-1.amazonaws.com/403959985054/MY_INCORRECTLY_PERMISSIONED_SQS_QUEUE is denied.
  /home/MY_APP/.gem/ruby/2.4.0/gems/aws-sdk-core-2.11.146/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
  /home/MY_APP/.gem/ruby/2.4.0/gems/aws-sdk-core-2.11.146/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
  /home/MY_APP/.gem/ruby/2.4.0/gems/aws-sdk-core-2.11.146/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
  /home/MY_APP/.gem/ruby/2.4.0/gems/aws-sdk-core-2.11.146/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
  /home/MY_APP/.gem/ruby/2.4.0/gems/aws-sdk-core-2.11.146/lib/seahorse/client/plugins/response_target.rb:21:in `call'
  /home/MY_APP/.gem/ruby/2.4.0/gems/aws-sdk-core-2.11.146/lib/seahorse/client/request.rb:70:in `send_request'
  /home/MY_APP/.gem/ruby/2.4.0/gems/aws-sdk-core-2.11.146/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
  /home/MY_APP/.gem/ruby/2.4.0/gems/shoryuken-4.0.3/lib/shoryuken/queue.rb:84:in `queue_attributes'
  /home/MY_APP/.gem/ruby/2.4.0/gems/shoryuken-4.0.3/lib/shoryuken/queue.rb:53:in `fifo?'
```

Unfortunately none of our other Shoryuken workers were able to go about their business as a result of my mistake and this error. I'm curious if it makes sense to more gracefully handle these type of permission errors in the gem itself?

Maybe something in here: https://github.com/phstc/shoryuken/blob/34f8ae64bbec53d7fa388540923eff938a66ff5f/lib/shoryuken/environment_loader.rb#L153

```ruby
    def validate_queues
      return Shoryuken.logger.warn { 'No queues supplied' } if Shoryuken.ungrouped_queues.empty?

      non_existent_queues = []
      
      ##############################
      # TO ADD
      non_permissioned_queues = []
      ##############################

      Shoryuken.ungrouped_queues.uniq.each do |queue|
        begin
          Shoryuken::Client.queues(queue)
        rescue Aws::Errors::NoSuchEndpointError, Aws::SQS::Errors::NonExistentQueue
          non_existent_queues << queue

        ##############################
        # new rescue block
        rescue Rescue Aws::SQS::Errors::AccessDenied
           non_permissioned_queues << queue
        ##############################

        end
      end

      return if non_existent_queues.none?

      ##############################
      # Add code here that uses the options hash to determine whether or not to fail in the event that non_presmissioned_queues.none? is false
      return if non_permissioned_queues.present? && options[:ignore_non_permissioned_queues]
      ##############################


      fail(
        ArgumentError,
        "The specified queue(s) #{non_existent_queues.join(', ')} do not exist.\nTry 'shoryuken sqs create QUEUE-NAME' for creating a queue with default settings"
      )
    end
```

There are likely additional changes that would need to be implemented. I'd love some feedback on this and I'd be happy to work on it.

**Comment by phstc** [comment]
Hi @PlanetEfficacy 

I would guess in most cases people would want to fail sooner than later if there's an issue with permissions.

Having an option `ignore_non_permissioned_queues` seems very flexible, but I'm wondering if it is an edge case, and if we add this option, we will need to maintain it as well. 

I have mixed feelings with it.

WDYT?

**Comment by PlanetEfficacy** [comment]
Agreed this could be more of a edge case and maybe it is better to not incorporate this into the gem itself. Better system architecture on my end is likely a better solution. Thanks for getting back to me!

**Comment by phstc** [comment]
@PlanetEfficacy thanks for raising that up 🍻
