### ISSUE TITLE
Fault tolerance?

### ISSUE THREAD

**Issue by hopewise** [phstc/shoryuken#564]
Hello
I would like to ask about fault tolerance, what is the recommended way to recover the worker process in-case it was crashed for any reason?

**Comment by phstc** [comment]
Hi @hopewise 

Fault tolerance might be specific to your environment/infrastructure, for example, you could use a Fargate Cluster, with a health check, checking [`TTIN`](https://github.com/phstc/shoryuken/wiki/Signals#ttin).

You could also set CloudWatch alarms, if your inflight messages are over a threshold. That can trigger a process or at least let you know (email notification).

There's also monit, and similar supervision tools. 

How are you deploying Shoryuken?

**Comment by hopewise** [comment]
İ didn't use it yet, but I was curious to know, thanks

**Comment by phstc** [comment]
@hopewise I will be happy to give you some guidance depending on your infra choices.
