### ISSUE TITLE
Can't listen to two queues with the same prefix

### ISSUE THREAD

**Issue by mauricioszabo** [phstc/shoryuken#567]
I'm using shoryuken without Rails, and I found that one o my queues wasn't being listened. Then I found that when I send a command to `setup_options` it behaves strange on certain conditions:

```ruby
[1] pry(main)> Shoryuken::EnvironmentLoader.setup_options(queues: ['foobar', 'foowat'])
=> #<Shoryuken::EnvironmentLoader:0x000000000415c7b0 @options={:queues=>["foobar"]}>
```

```
[2] pry(main)> Shoryuken::EnvironmentLoader.setup_options(queues: ['boobar', 'foowat'])
=> #<Shoryuken::EnvironmentLoader:0x0000000004cf43e8 @options={:queues=>["foowat", "boobar"]}>
```

Why is that happening?

**Comment by phstc** [comment]
Hi @mauricioszabo 

😱 it is a bug in [here](https://github.com/phstc/shoryuken/blob/7c33d24f8d5e3112a3a67b412c8ec4c673bef715/lib/shoryuken/environment_loader.rb#L84).

For testing it locally, you can add some breakpoints in `merge_cli_defined_queues` .

```ruby
def merge_cli_defined_queues
  cli_defined_queues = options[:queues].to_a.dup

  require 'pry-byebug'; binding.pry
  cli_defined_queues.each do |cli_defined_queue|
    require 'pry-byebug'; binding.pry
    # CLI defined queues override config_file defined queues
    Shoryuken.options[:queues].delete_if { |config_file_queue| config_file_queue[0] == cli_defined_queue[0] }

    require 'pry-byebug'; binding.pry
    Shoryuken.options[:queues] << cli_defined_queue
  end
  require 'pry-byebug'; binding.pry
end
```

Then you can call `rake console` in order to debug it. I need more time, but I will be happy to debug that in case you can't. 

Is there a specific reason you are calling `setup_options` directly instead of `-q` or `shoryuken.yml`?

**Comment by mauricioszabo** [comment]
I'm not calling `setup_options`, really, I'm calling:

```ruby
  Shoryuken::Runner.instance.run(queues: Config.queues_to_listen)
```

Tracking the bug I found that the easiest way to cause the issue (and print it) was to run the code I've mentioned :)

**Comment by mauricioszabo** [comment]
The code above is in the main file of my project. I'm not using `shoryuken.yml` because I'm not using Rails and everything is being configured with environment variables (and also I need some configuration on how the project will run).

I was inspired on https://github.com/phstc/shoryuken/blob/master/bin/shoryuken#L42, so I don't think `-q` will work on this case, because it just splits the string into an array and passes it to Runner (that's exacly what I am doing).

**Comment by phstc** [comment]
@mauricioszabo you don't need Rails to use `shoryuken.yml`.

It seems to be working from the CLI:

```sh
shoryuken sqs create foobar
Queue foobar was successfully created. Queue URL https://sqs.us-east-1.amazonaws.com/376895783028/foobar/
shoryuken sqs create foowat
Queue foowat was successfully created. Queue URL https://sqs.us-east-1.amazonaws.com/376895783028/foowat


shoryuken -q foobar foowat
2019-05-27T18:32:19Z 19018 TID-ovq41upng WARN: No worker supplied for foowat
2019-05-27T18:32:19Z 19018 TID-ovq41upng WARN: No worker supplied for foobar
```

Actually, it isn't a bug, if you debug the CLI call, you will see that

```sh
    37:   # Keep compatibility with old CLI queue format
    38:   opts[:queues] = opts[:queues].reject(&:empty?).map { |q| q.split(',') } if opts[:queues]
    39:
    40:   require 'pry-byebug'; binding.pry
    41:
 => 42:   fail_task "You should set a logfile if you're going to daemonize" if opts[:daemon] && opts[:logfile].nil?
    43:
    44:   Shoryuken::Runner.instance.run(opts.freeze)
    45: end

[1] pry(#<Shoryuken::CLI::Runner>)> opts
=> {:queues=>[["foobar"], ["foowat"]]}
```

`queues` is expected to be an array of arrays. In your case, you should:

```ruby
Shoryuken::EnvironmentLoader.setup_options(queues: [['foobar'], ['foowat']])
```

For having both queues.

**Comment by mauricioszabo** [comment]
Okay, I just saw that `Runner` is not documented, so probably not a public API. Right now I'm using it so it's probably not a good idea...

Is there a "canonical way" to listen to queues without relying on `shoryuken` script to launch my project? One that I could call "listen to these queues" inside my Ruby source file?

**Comment by phstc** [comment]
@mariokostelac is the any specific reason for not calling `shoryuken`?  You can always add queues dynamically `Shoryuken.add_queue(...)`.

Also, `shoryuken.yml` is an ERB, so you can add Ruby code in there.

**Comment by mauricioszabo** [comment]
I just want to use Shoryuken as a library inside my project: want to configure some things, instantiate others (no dynamic queues creation, btw), open a console in development mode or mock some external services so I can create workers injecting the mocks instead of real service clients, and so on...

**Comment by phstc** [comment]
@mauricioszabo You should be good passing an array of arrays then.
