### ISSUE TITLE
shoryuken doesn't respect activejob queue_name_prefix

### ISSUE THREAD

**Issue by mokevnin** [phstc/shoryuken#57]
for example:

application.rb

    config.active_job.queue_name_prefix = Rails.env

shoryuken.yml

    queues:
      - [docker_runner, 6]
      - [default, 2]
      - [image_builder, 1]

got message:

`Queue 'docker_runner' does not exist`

**Comment by phstc** [comment]
@mokevnin could you add the prefix in the `queues:` too? 

```erb
queues:
  - [<%= Rails.env %>_docker_runner, 6]
  - [<%= Rails.env %>_default, 2]
  - [<%= Rails.env %>_image_builder, 1]
```

Maybe you can also access `config.active_job.queue_name_prefix` via `Rails.configuration...` if you don't want use `Rails.env`.

**Comment by mokevnin** [comment]
it doesn't work because Rails.env is not defined when config is loading. Right now i use configuration file per env.

Is it bug? What do you think?

**Comment by phstc** [comment]
Maybe you could try `ENV['RAILS_ENV']`.

> Is it bug? What do you think?

Kind of, if it doesn't support ActiveJob completely.

@leemhenson do you use `queue_name_prefix`?

**Comment by leemhenson** [comment]
I don't use ActiveJob.

**Comment by kookster** [comment]
I add my own prefix to the queue names. I am not loading rails, and the file I do load with '-r' seems to be loaded after the config file is read, so I rely on ENV variables to set the prefix:

```
<% env = ENV['APP_ENV'] || ENV['RAILS_ENV'] || 'development' %>
---
concurrency: <%= ENV['WORKER_COUNT'] || 5 %>
delay: <%= ENV['SHORYUKEN_DELAY'] || 5 %>
queues:
  - [<%= env %>_fixer_p1, 4]
  - [<%= env %>_fixer_p2, 3]
  - [<%= env %>_fixer_p3, 2]
  - [<%= env %>_fixer_p4, 1]
```

**Comment by kookster** [comment]
perhaps one fix is to change the order of the cli to load the config file after loading rails and -r required file?

**Comment by phstc** [comment]
Actually shoryuken loads rails in the beginning of the load order https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/environment_loader.rb#L19

@mokevnin are you using `-R` or `--rails`? https://github.com/phstc/shoryuken#rails-integration

**Comment by mokevnin** [comment]
@phstc you right, i forgot about `-R` flag.

**Comment by phstc** [comment]
thanks to @kookster for pointing that out :beers:
