### ISSUE TITLE
How to use different AWS credentials for different queues in Rails?

### ISSUE THREAD

**Issue by alphaone** [phstc/shoryuken#573]
In our setup we have to read from two queues that live in different AWS accounts. As I understood from reading https://github.com/phstc/shoryuken/issues/143#issuecomment-251386599, I should be able to use two workers with dedicated yml configuration to solve that problem.

But how to provide different AWS credentials for those two configs? As I understand, I can setup the AWS client in Rails' initializers. But this client would then be the same for both workers.

Can I somehow setup a dedicated client per worker?

**Comment by phstc** [comment]
Hi @alphaone 

The queues can be set with their names or their [URLs](https://github.com/phstc/shoryuken/blob/34f8ae64bbec53d7fa388540923eff938a66ff5f/spec/shoryuken/queue_spec.rb#L8).  You could use the queue URL which would include the account_id, then setup IAM permissions with access for both accounts. Would this be feasible for your setup?

**Comment by alphaone** [comment]
@phstc As I understand, having the same user/role with access to both queues is the only option. Yes, that would be feasible.

Our operations team would like to have permission strict and separated, so their ideal solution would involve two users (each has access to only one queue). But then I would have to provide two sets of credentials.

**Comment by phstc** [comment]
Hi @alphaone 

I believe the options without requiring code changes are:

* a user with access for both accounts 
* running separated Shoryuken processes per account

Configuring a SQS client per queue would require some code changes. I can give you some guidance if you are interested on sending a pull request.

**Comment by benoittgt** [comment]
> Configuring a SQS client per queue would require some code changes. 

I might be interested to submit a PR for that. Do you know already how you want to do it?

**Comment by phstc** [comment]
@benoittgt sorry for not getting back to you earlier. 

> `EventOrDefaultWorkerRegistry` 

That seems to be an interesting option. Some type of Queue registry so [this](https://github.com/ruby-shoryuken/shoryuken/blob/f94f0707c1acc8ddb772b5fc98787141a68462c8/lib/shoryuken/client.rb#L7) can be overridden. 

The good thing is that a [Queue](https://github.com/ruby-shoryuken/shoryuken/blob/f94f0707c1acc8ddb772b5fc98787141a68462c8/lib/shoryuken/queue.rb#L12) instance references a client, so once it is set with the correct client, it should work throughout. We would not need to check it in multiple places.
