### ISSUE TITLE
Is there a way to quiet workers outside of the machine that runs it?

### ISSUE THREAD

**Issue by nathanpalmer** [phstc/shoryuken#575]
Is there a way to signal to workers that they should stop accepting new jobs, finish their work and shutdown? We'd like to have a smoother flow for deployments where the workers will shut down prior to any database migrations occurring. This can be done with sidekiq using the `quiet!` method on their `ProcessSet`

```ruby
Sidekiq::ProcessSet.new.each(&:quiet!)
```

Any such option here for Shoryuken? I know you can send signals, but this won't be executed from within each machine/container.

**Comment by phstc** [comment]
> Yup! :)

Nice chat in there! 

> I have a working version using the ProcessSet for Sidekiq since you can remotely send the quiet command.

I need to learn more about `Sidekiq::ProcessSet.new.each(&:quiet!)`.  Sidekiq may be using Redis for a distributed shutdown signal. That's complicated with SQS.

Shoryuken supports some [life cycle events](https://github.com/phstc/shoryuken/wiki/Lifecycle-Events) - you could try to use one of them for looking for "distributed" commands.

Depending on how you are running your containers, you could use AWS SSM programmatically for sending signals.

**Comment by nathanpalmer** [comment]
Yeah, I'm assuming Sidekiq can more easily do that because of Redis being a central storage location. This conversation at-least gives me some ideas though.

**Comment by phstc** [comment]
Hi @nathanpalmer 

I'm closing this for now. But let me know if you come up with an idea or need help.

**Comment by nathanpalmer** [comment]
No problem. We're ended up handling it the same way that Sidekiq does by receiving signals from a redis key every 5 seconds. I have to start a thread up on boot though in order to get it to work properly since there isn't any type of heartbeat (when it's not actively checking for messages.)

**Comment by phstc** [comment]
@nathanpalmer that's pretty cool. Let me know if you make it OSS 🙏  I will be happy to reference it.
