### ISSUE TITLE
EB deployment fails: "/opt/elasticbeanstalk/hooks/appdeploy/pre/03_mute_shoryuken: line 4: kill: (14246) - No such process."

### ISSUE THREAD

**Issue by MSCAU** [phstc/shoryuken#576]
I have followed these guides:

https://github.com/phstc/shoryuken/wiki/Complete-Shoryuken-Setup-for-Rails-5-with-ActiveJob
and
https://stackoverflow.com/questions/39783398/setting-up-shoryuken-active-job-and-amazon-sqs-in-a-rails-project?rq=1

While Shoryuken works fine on localhost (connecting to SQS as expected, without any region or access_key_id or secret_access_key in shoryuken.yml) it fails when deploying with EB eventhough I have copied and pasted the code from https://github.com/phstc/shoryuken/wiki/AWS-Beanstalk-Config.

The error that I am getting is:

```
Application update failed at 2019-09-24T09:15:25Z with exit status 1 and error: Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/03_mute_shoryuken failed.

/opt/elasticbeanstalk/hooks/appdeploy/pre/03_mute_shoryuken: line 4: kill: (14246) - No such process.
```

Do you have any idea how to resolve it?

**Comment by MSCAU** [comment]
To compound things, I can now no longer revert to any other prior or new EB version as I get this error when deploying:

> During an aborted deployment, some instances may have deployed the new application version. To ensure all instances are running the same version, re-deploy the appropriate application version.

:(

**Comment by phstc** [comment]
Hi @MSCAU 

Can you get the specific Shoryuken error from the logs? 

> While Shoryuken works fine on localhost (connecting to SQS as expected, without any region or access_key_id or secret_access_key in shoryuken.yml)

Does your EB instance have access to the queues you want to consume? https://github.com/phstc/shoryuken/wiki/Configure-the-AWS-Client

**Comment by MSCAU** [comment]
Perhaps this is relevant? https://github.com/phstc/shoryuken/wiki/Amazon-SQS-IAM-Policy-for-Shoryuken

I don't know how to implement this though using AWS console.

**Comment by MSCAU** [comment]
OK thanks for the tip.

**Comment by MSCAU** [comment]
OK so it seems that deploying a different version to Elastic Beanstalk doesn't remove / replace previously deployed ebextensions. I had to manually SSH to the EC2 and remove your files:

- post/50_restart_shoryuken
- post/50_restart_shoryuken.bak
- pre/03_mute_shoryuken
- pre/03_mute_shoryuken.bak

I was then able to deploy and use an (earlier) version of the code without Shoryuken.

OK, so now that I back where I started 18 hours ago, do you know why [the ebextension you recommended](https://github.com/phstc/shoryuken/wiki/AWS-Beanstalk-Config) would be failing?

**Comment by phstc** [comment]
> OK, so now that I back where I started 18 hours ago, do you know why the ebextension you recommended would be failing?


![image](https://user-images.githubusercontent.com/105652/65540455-7264f800-ded9-11e9-8568-5678b63e3831.png)


@MSCAU the author of that page is in the issue https://github.com/phstc/shoryuken/issues/48#issuecomment-475895400. I would recommend checking that with him.

**Comment by MSCAU** [comment]
Thanks, @phstc . @tomharvey, I hope you can help?

**Comment by tomharvey** [comment]
Hi @MSCAU sorry you’ve ended up in this mess.

When the shoryuken process starts it creates a file `shoryuken.pid` which holds the process ID. When the ebextension script runs, if the .pid file exists, it tries to stop that process before continuing on to start a new process.

In your case, it looks like that .pid file exists, so the script tried to kill an old process - but that process didn’t exist and the `kill` command fails, causing the whole deployment to return a failure code.

You’ve cleaned up the extension by ssh-ing onto the server and removing the file, but you’ll want to remove this .pid file as well.

```

PID_DIR=$(/opt/elasticbeanstalk/bin/get-config container -k app_pid_dir)
rm -rf $PID_DIR/shoryuken.pid
```

That will remove the pid file, so the extension will stop trying to kill a non-existent process.

That might be enough to let you retry the deploy; and if you run into the same issue, remove the pid file.

However, the root of the problem is that the extension expects that the pid file should only exist if there is a shoryuken process running. I’ll push an updated version of the extension which will handle that more gracefully later today after I’ve tested it. 

In the meantime, can you provide any hint as to how the pid file came to exist while the shoryuken process wasn’t running? It may have simply crashed if it’s own accord.

**Comment by MSCAU** [comment]
Thanks, @tomharvey . I am just about to head out for a few hours but will try and come back to you before bedtime.

**Comment by tomharvey** [comment]
There are a lot of situations where “bad luck” will have created the .pid file when it shouldn’t be there. The only thing I’d suggest you make sure of is that the deployment isn’t copying your development environment’s pid file to production. If you’re doing that then lots of other problems will likely follow. Not sure how you deploy, so can’t provide specific hints on how to make sure you avoid this, but if you let me know your deployment process I’d be happy to help with that.

**Comment by tomharvey** [comment]
I've made a small change to the scripts in the extension so they don't fail the deployment when trying to shutdown a process which is already not running.

Instead, it will print out  "The shoryuken process was not running." and carry on regardless. This will ensure that the .pid file (which contains the process ID of the non-running process) is correctly cleaned up.

Hope this fixes it, but let me know if you run into any other trouble.

**Comment by MSCAU** [comment]
Thanks. It's actually too late to play with deployments now so I will have a look in the morning and let you know how I get on.

**Comment by MSCAU** [comment]
Hi @tomharvey - sorry where can I find your new script?

**Comment by tomharvey** [comment]
I’ve updated the wiki @MSCAU 

Just changed the lines with kill commands to print a log if they fail.

`kill -USR1 `cat $PID_DIR/shoryuken.pid` || echo "The shoryuken process was not running."`

**Comment by MSCAU** [comment]
No, I get an error at the point where the Active Job is supposed to run.

Here's what I see in the logs:

```
ArgumentError: The specified queue(s) beatjosh do not exist.
Try 'shoryuken sqs create QUEUE-NAME' for creating a queue with default settings
  /opt/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/shoryuken-5.0.1/lib/shoryuken/environment_loader.rb:168:in `validate_queues'
  /opt/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/shoryuken-5.0.1/lib/shoryuken/environment_loader.rb:31:in `load'
  /opt/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/shoryuken-5.0.1/lib/shoryuken/runner.rb:39:in `run'
  /opt/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/shoryuken-5.0.1/bin/shoryuken:42:in `start'
  /opt/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /opt/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /opt/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /opt/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /opt/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/shoryuken-5.0.1/bin/shoryuken:53:in `<top (required)>'
  /opt/rubies/ruby-2.5.5/bin/shoryuken:23:in `load'
  /opt/rubies/ruby-2.5.5/bin/shoryuken:23:in `<top (required)>'
```

And here's my YML:

```
aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  receive_message:
    attribute_names:
    - ApproximateReceiveCount
    - SentTimestamp
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: ap-southeast-2
concurrency: 15
queues:
  - beatjosh
```

I have only one queue in SQS - which I created manually - and it's called beatjosh. Any ideas?

**Comment by MSCAU** [comment]
Hi @phstc  - in your docs, due to the above error, not sure whether the queue name in the Active Job is supposed to have quotes around it? Here is what I have:

```
class CommentLiveJob < ApplicationJob
  # queue_as :default			# used this for plain Active Job
  queue_as "beatjosh"
  ...
```

**Comment by phstc** [comment]
```
aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  receive_message:
    attribute_names:
    - ApproximateReceiveCount
    - SentTimestamp
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: ap-southeast-2
```

> Does your EB instance have access to the queues you want to consume? https://github.com/phstc/shoryuken/wiki/Configure-the-AWS-Client

`aws` creds in `shoryuken.yml` is no longer supported. You need to follow [this](https://github.com/phstc/shoryuken/wiki/Configure-the-AWS-Client) for configuring your credentials. 

It is probably returning 

> ArgumentError: The specified queue(s) beatjosh do not exist.

Because the instance you are running Shoryuken does not have access to the AWS account that you created the queue.

**Comment by MSCAU** [comment]
Ah OK. Do I still need the region key?

**Comment by tomharvey** [comment]
Good to hear deployment is working.

You mentioned some confusion about the wiki article around IAM policies above.

When you give credentials to shoryuken it will authenticate itself using them. You need to make sure that processes authenticating using those credentials have access to your queue as well.

You’ll be using your admin access key and secret, so you (and probably your development environment) will have access to the queue (and EVERYTHING else on AWS).

Follow @phstc advice on how to provide credentials; but if you’re still stuck it’s likely to do with those credentials not having access to the queue. You can check that by supplying the shoryuken process with the access key and secret you use as administrator, but that’s a real bad security practise as a long term solution.

Also, might be worth a separate issue to discuss this in to help future adventurers find the problem.

**Comment by MSCAU** [comment]
I changed the permissions on the SQS queue and it now appears to work, thanks!

I'm a bit puzzled though why I can't actually see any messages in the queue when I choose Queue Action > View/Delete Messages. I was able to do this when running off localhost two days ago. Do you know why this might be?

**Comment by tomharvey** [comment]
If the shoryuken process is running, it will be consuming the job almost immediately; before you can see the job in the queue. So, unless you have a backlog of jobs, or the shoryuken has stopped you wouldn't usually be able to see jobs.

If you use the SQS console to view messages, that console may consume any messages entering the queue instead of shoryuken. Only one consumer will collect the message, so you can't both view the message and complete the job. Once you finish viewing messages in the SQS console, it will return to the queue and be picked up by shoryuken and the job will be handled.

If you want to monitor job handling, it's probably best to check the output of your shoryuken log (for me, that's in `/var/app/current/log/shoryuken.log`) to see it processing your jobs. This avoids the issue with the console collecting the job instead of shoryuken.

Are you happy to close this issue now @MSCAU ?

**Comment by MSCAU** [comment]
Yes thanks. You've both been a huge help.

**Comment by MSCAU** [comment]
Woah. Just received email from AWS saying I have already sent 850,000 messages into the queue. In actual fact I probably triggered less than 5. It's not your problem but I need to get to the bottom of it.

**Comment by MSCAU** [comment]
> Hi @MSCAU sorry you’ve ended up in this mess.
> 
> When the shoryuken process starts it creates a file `shoryuken.pid` which holds the process ID. When the ebextension script runs, if the .pid file exists, it tries to stop that process before continuing on to start a new process.
> 
> In your case, it looks like that .pid file exists, so the script tried to kill an old process - but that process didn’t exist and the `kill` command fails, causing the whole deployment to return a failure code.
> 
> You’ve cleaned up the extension by ssh-ing onto the server and removing the file, but you’ll want to remove this .pid file as well.
> 
> ```
> 
> PID_DIR=$(/opt/elasticbeanstalk/bin/get-config container -k app_pid_dir)
> rm -rf $PID_DIR/shoryuken.pid
> ```
> 
> That will remove the pid file, so the extension will stop trying to kill a non-existent process.
> 
> That might be enough to let you retry the deploy; and if you run into the same issue, remove the pid file again
> 
> However, the root of the problem is that the extension expects the pid file will only exist if there is a shoryuken process running. I’ll push an updated version of the extension to handle the error more gracefully after I’ve tested it later today.
> 
> In the meantime, can you provide any hint as to how the pid file came to exist while the shoryuken process wasn’t running? Shoryuken may have simply crashed of its own accord.

@tomharvey - I wasn't able to figure out where the PID file that you recommended I remove. Which folder is it in?

**Comment by MSCAU** [comment]
It's actually OK now. I wasn't able to get this version of **shoryuken.yml** to work on AWS:

```
concurrency: 15
queues:
- [<% if ENV['RAILS_ENV'] == "production" %>beatjosh<% else %>beatjosh-dev<% end %>, 1]
```

but I was able to get this equivalent version to run:

```
concurrency: 15
queues:
- [<%= ENV['AWS_SQS_QUEUE'] %>, 1]
```

No idea why but happy to be able to run on both dev and prod finally.

**Comment by tomharvey** [comment]
This will work, glad you found a solution. Is this issue OK to close now?

I have many queues, and separate ones for dev and prod. So, I actually have a `shoryuken.development.yml` and `shoryuken.production.yml` file which lists the queue names' without any `<% ... %>` templating in them. Then, when I start shoryuken I point to the environment specific config file with `shoryuken -C ./shoryuken.production.yml ...`

Hope this helps if your queue list grows and managing them in an ENV variable becomes problematic.

**Comment by MSCAU** [comment]
Yes thanks. Let's close this.
