### ISSUE TITLE
Please explain the YML syntax for queues

### ISSUE THREAD

**Issue by MSCAU** [phstc/shoryuken#577]
Hi @phstc , please explain the significance of the "1" in the second element of the queue key array in the YML file:

https://github.com/phstc/shoryuken/wiki/Complete-Shoryuken-Setup-for-Rails-5-with-ActiveJob

**Comment by tomharvey** [comment]
That's the "queue weight" and will help you prioritise the processing of certain job queues. Have a look at https://github.com/phstc/shoryuken/wiki/Polling-strategies

**Comment by phstc** [comment]
Thanks @tomharvey. I've also updated the wiki adding extra info.

**Comment by MSCAU** [comment]
OK thanks. Not sure that I'll be needing this feature then.
