### ISSUE TITLE
How does perform_in work?

### ISSUE THREAD

**Issue by kapso** [phstc/shoryuken#587]
I did this `MyTestWorker.perform_in(2.minutes, "test message 1")` but don't see the message in my queue in AWS console.

**Comment by kapso** [comment]
Actually never mind noticed its natively supported by SQS https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-timers.html

**Comment by phstc** [comment]
Correct! Shoryuken uses [`delay_seconds`](https://github.com/phstc/shoryuken/blob/9d20e85539756cab45890003df60ec083f769f83/lib/shoryuken/extensions/active_job_adapter.rb#L41) which can go up to 15 minutes.
