### ISSUE TITLE
Handling corrupted messages in SQS

### ISSUE THREAD

**Issue by krishnanandnb** [phstc/shoryuken#590]
How to delete corrupted messages present in SQS? when I look at the code the body_parser is raising an error if it fails to parse but the messages are not getting deleted even though auto delete is set to true 
` 
    body = get_body(worker.class, sqs_msg)
   
        worker.class.server_middleware.invoke(worker, queue, sqs_msg, body) do
          worker.perform(sqs_msg, body)
        end

        @manager.async.processor_done(queue, current_actor)`

The version of Shoryuken '2.0.4'

**Comment by phstc** [comment]
Hi @krishnanandnb 

[auto delete](https://github.com/phstc/shoryuken/blob/af6ba758767aa7e541cae0ad3e4b146ef8eb7792/lib/shoryuken/middleware/server/auto_delete.rb#L6) only gets called if the message does not raise any error.

If the corrupted messages a one-off thing, you can `shoryuken sqs dump queue-name` to download all messages, remove the bad ones, then requeue the good ones `shoryuken sqs requeue queue-name dump.jsonl`.

If these corrupted will happen on an ongoing basis,  you can change the [`body_parser`](https://github.com/phstc/shoryuken/wiki/Worker-options#body_parser) to `text` and custom handle these exceptions.

**Comment by krishnanandnb** [comment]
Thanks for the reply. 
Thining of monkey patching and deleting the message. Since we can be pretty sure that we don't need those messages. We have used body-parser as JSON in hundreds of places. Maybe a bad idea?
