### ISSUE TITLE
Comparing Sidekiq performance

### ISSUE THREAD

**Issue by kapso** [phstc/shoryuken#596]
I am really interested in using this library instead of Sidekiq (due to SQS), but I have noticed Sidekiq/Redis has significantly higher throughput. Few things I noticed -

- Writing messages to SQS is slower than writing to Redis (even when using batch). Using Sidekiq `push_bulk` I can push way more messages faster.
- When consuming messages, I am getting a lot more done when using Sidekiq workers compared to this gem.

Is there something I am doing wrong? Or maybe due to Redis, it's assumed that Sidekiq will have a better throughput, and perhaps bettering/matching Sidekiq performance is not the aim of this gem.

Thanks.

**Comment by phstc** [comment]
Hi @kapso 

Have [a blog post](http://www.pablocantero.com/blog/2015/03/14/sidekiq-redis-vs-shoryuken-aws-sqs/) that can answer some of your questions. Some details in the post may be outdated, but the overall idea still applies. 

Pushing and receiving messages is via the AWS SDK, so it is not exactly dependent on Shoryuken. Overall, Redis is faster to write and read, but there are some tradeoffs (blog post). 

Depending on your goal, I can give you some guidance. If you just want to enqueue as fast as you can, Redis (Sidekiq) could be a good fit. That really depends on your goals. 

Also, if you send and receive from the AWS network, you will get less latency compared to local tests (I don't know how you tested it).

SQS can be also used as an event source for Lambdas.

**Comment by kapso** [comment]
@phstc thanks for the response, and your work on this gem. The blog post was super helpful.

Faster writes are important for our use case, we have about 150m jobs that need to enqueued once a week and getting them processed in a timely fashion is important. Also according to your blog, Shoryuken took almost the same time as Sidekiq when consuming jobs, but this is not what we are seeing in our tests. Is there something we doing wrong? These are the settings for the queue and Shoryuken.

Queue settings - 
Default Visibility Timeout: 30s
Receive Message Wait Time: 8s

Shoryuken.sqs_client_receive_message_opts = { wait_time_seconds: 8 }

**Comment by phstc** [comment]
@kapso reading performance will depend on your [concurrency](https://github.com/phstc/shoryuken/wiki/Shoryuken-options#concurrency) (number of threads available to consume message) as well. Shoryuken will not receive more messages if all threads are busy. 

Also, your latency. Is Shoryuken running in the AWS network in the same region as your queue? 

[Shoryuken also supports batch](https://github.com/phstc/shoryuken/wiki/Worker-options#batch), which can speed up some processes depending on your use-case.

> Shoryuken.sqs_client_receive_message_opts = { wait_time_seconds: 8 }

You can try not setting `wait_time_seconds` and not having any [delay](https://github.com/phstc/shoryuken/wiki/Shoryuken-options#delay) and see how it goes. The standard settings work for most users, but if you a specific need if you need some experimentation.

**Comment by kapso** [comment]
@phstc We are running on Heroku which runs on `us-east-1` and that's where we have our SQS queue as well. And we are using the `concurrency` config.

Yes, we did try `batch: true` for write/read but it wasn't enough to speed it up.

We will experiment with reducing delay time, see if it speeds up the reads.

Thanks again.
