### ISSUE TITLE
Consume Any Queue

### ISSUE THREAD

**Issue by allcentury** [phstc/shoryuken#599]
We consume from some queue's where our application is not the producer.  For instance, some S3 events trigger an SNS publish which gets pushed to an SQS queue.  In those cases the message does not look like it was published from shoryuken but we'd love to run a worker against that queue w/ all the benefits shoryuken has.  

It seems like I need to write a custom middleware that sets some values like `shoryuken_class` https://github.com/phstc/shoryuken/blob/be59f61df31565c63b0840a4655d03ab849fcc81/lib/shoryuken/default_worker_registry.rb#L18 but I was hoping for a more exact answer as to how to fullfill this request.

**Comment by phstc** [comment]
Hi @allcentury 

If you use standard Shoryuken workers (one worker per queue), you could associate one worker to your queue https://github.com/phstc/shoryuken/wiki/Worker-options#queue


`shoryuken_class` is used when multiple workers can consume messages from the same queue.

**Comment by allcentury** [comment]
Perfect, thanks @phstc - My plan was to run some native workers and some active job workers, can those be run side-by-side or do I need to break up the processes?

**Comment by phstc** [comment]
They can run side-by-side 🚀
