### ISSUE TITLE
Documentation inaccuracy: FIFO queues

### ISSUE THREAD

**Issue by elsurudo** [phstc/shoryuken#601]
Hello!

On the [FIFO queues wiki page](https://github.com/phstc/shoryuken/wiki/FIFO-Queues), there is the following note:

> Note: If you want to make sure that messages within the same Message Group ID get processed one at time, you will need to set concurrency: 1. Processing Groups can be a good alternative for that, in case we don't want to set concurrency: 1 for all queues.

According to [AWS docs here](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html#FIFO-queues-understanding-logic), under the section "Retrying multiple times", it says:

> When you receive a message with a message group ID, no more messages for the same message group ID are returned unless you delete the message or it becomes visible.

which contradicts the note above (hence, no need to limit concurrency to 1 IMO).

I'd be glad to update the wiki myself, but I wanted to post here in case I was misunderstanding something. Thoughts?

---

On a related note, one thing I've found is that `max_number_of_messages` should be set to `1`, since (also according to that AWS page):

> It is possible to receive up to 10 messages in a single call using the MaxNumberOfMessages request parameter of the ReceiveMessage action. These messages retain their FIFO order and can have the same message group ID. Thus, if there are fewer than 10 messages available with the same message group ID, you might receive messages from another message group ID, in the same batch of 10 messages, but still in FIFO order.

Shoryuken would receive the messages (for one message group and in one fetch) in order, but due to threading, it would be impossible to have them execute in order without a mutex.

**Comment by arlandism** [comment]
I'm trying to wrap my head around this as well and think you're spot-on.

My take is you can have a scenario where:
1) Receive returns up to 10 messages from 1 or more message groups, in-order
2) Any message groups returned in (1) are now locked until the messages have been deleted or become visible again

So if concurrency is >1 when (1) occurs then your scenario of multiple consumers comes into play and in-order processing can't be guaranteed. On the flip side, if `max_number_of_messages` is set to 1 then concurrency >1 doesn't matter and you'll have in-order guarantees for each poll.

But, it seems like the best setup may be `concurrency = 1` with `max_number_of_messages = 10` so you get the benefits of batching along with in-order guarantees.  I think`concurrency > 1` and `max_number_of_messages = 1` has the same net effect but without batching. I may be missing something here as the wiki recommends capping `max_number_of_messages`.

To your second point, I think that's called out [here](https://github.com/phstc/shoryuken/wiki/FIFO-Queues#process-one-by-one).

**Comment by phstc** [comment]
> which contradicts the note above (hence, no need to limit concurrency to 1 IMO).
> I'd be glad to update the wiki myself, but I wanted to post here in case I was misunderstanding something. Thoughts?

I don't have a setup for testing it now. But IIRC since Shoryuken threads share the same AWS client, I was still getting messages.  

A testing scenario:

1. Create a FIFO queue
2. Enqueue 50 messages 
3. Set Shoryuken concurrency to 5
4. Configure the worker to consume these messages
5. In the worker body

```ruby
puts "WORKER WORKING!!! You should see five of these per minute only"
sleep(60)
```

6. Start Shoryuken and confirm you only see the message above 5 times per minute

Would you mind testing that? 
---

> On a related note, one thing I've found is that max_number_of_messages should be set to 1, since (also according to that AWS page):

That sounds right 👇 

https://github.com/phstc/shoryuken/wiki/FIFO-Queues#process-one-by-one

**Comment by elsurudo** [comment]
> But, it seems like the best setup may be `concurrency = 1` with `max_number_of_messages = 10` so you get the benefits of batching along with in-order guarantees. I think`concurrency > 1` and `max_number_of_messages = 1` has the same net effect but without batching. I may be missing something here as the wiki recommends capping `max_number_of_messages`.

Ah, but setting `concurrency = 1` has the downside of... only executing one message at a time, which isn't ideal. My thinking is that as long as your message executions take longer than SQS fetches, it is more optimal to fetch one message at a time rather than only execute one message at a time – otherwise your single execution thread is the bottleneck.

**Comment by elsurudo** [comment]
> I don't have a setup for testing it now. But IIRC since Shoryuken threads share the same AWS client, I was still getting messages.
> 
> A testing scenario:
> 
> 1. Create a FIFO queue
> 2. Enqueue 50 messages
> 3. Set Shoryuken concurrency to 5
> 4. Configure the worker to consume these messages
> 5. In the worker body
> 
> ```ruby
> puts "WORKER WORKING!!! You should see five of these per minute only"
> sleep(60)
> ```
> 
> 1. Start Shoryuken and confirm you only see the message above 5 times per minute
> 
> ## Would you mind testing that?

@phstc We are talking about messages with the same Message Group ID, so the desired functionality is in fact that only _one_ of them gets executed every 60s, no matter the concurrency. Yes, I have tested this case, and it appears to work as I am describing here.

So to be clear, _even if concurrency > 1, messages with the same Message Group ID will be executed one-at-a-time in order, as long as `max_number_of_messages == 1`_.

**Comment by phstc** [comment]
> So to be clear, even if concurrency > 1, messages with the same Message Group ID will be executed one-at-a-time in order, as long as max_number_of_messages == 1.

Old-me knew better than new-me! hehe

https://github.com/phstc/shoryuken/blob/17e9df8d80d86485c1b80ef4465350a8c40fa90d/lib/shoryuken/fetcher.rb#L62-L71

I couldn't test it yet, but since you tested it and according to that comment ☝️ I think it is safe to remove the wiki, thanks for calling it out. Would you like to update the wiki? ❤️ 

> Note: If you want to make sure that messages within the same Message Group ID get processed one at time, you will need to set concurrency: 1. Processing Groups can be a good alternative for that, in case we don't want to set concurrency: 1 for all queues.

**Comment by elsurudo** [comment]
Done! Thanks for the convo – now I will investigate the batch option, as it can help reduce AWS costs.
