### ISSUE TITLE
Cost calculation examples

### ISSUE THREAD

**Issue by truongnmt** [phstc/shoryuken#604]
I'm wondering the same thing in #304 as well, just want to have a further discussion.
Besides, it would be great if there is a Wiki summarizes some general billing calculation.

On reading the old thread, I noticed that if we have multiple workers, how many times does the request will be fired?
```
concurrency: 25 # number of available processors
delay: 0
```

As the previous OP, he has a total 35 workers.
> Each worker sends a request to SQS every second, resulting in 35 requests per second.
35 requests per second x 86,400 seconds per day = 3,024,000 requests per day => ~ 90-95 million requests per month

However as @phstc replies:
> When you start Shoryuken, it will have 25 processors available, so the fetcher will perform 3 requests to SQS (it supports up to 10 messages per request only).

This is very important information! Wished it's added to the README. I though all processors will poll the queue. The same with previous OP's thought!

So if the OP has 35 workers, it will be 4 reqs/s.
Assuming the queues is always full for the whole month, it will be:
4 reqs per second x 86,400 seconds per day = 10,368,000 request per month

Just for polling checking the queue.

Which according to [AWS Price calculator](https://calculator.aws/#/createCalculator) it will be roughly 4$!

So he did get the bill for 40$, the remain 38$ must be to interact with the queue (eg: delete message request).

---

> Each message will result in another request to SQS in order to be deleted.

I would like to confirm this as well. Does this still true?

For example, I enqueue 1000 requests and after workers finish with all that request, it will need another 1000 requests to delete those messages right. Assuming that use no batch workers and have no other request to SQS.

---

https://github.com/phstc/shoryuken/wiki/Shoryuken-options#cache_visibility_timeout

> By default, Shoryuken will make requests against SQS for getting the updated queue visibility timeout, so if you change the visibility timeout in SQS, Shoryuken will automatically update it.

I would like to ask how often does Shoryuken checking for this value? It would be nice if we can see the code too? Thanks a lot!!! @phstc 🥇

**Comment by truongnmt** [comment]
I just create a sheet to calculate the total request

https://docs.google.com/spreadsheets/d/1Q6BPLjd6d0K-M3uB4pOtjdj_KuXPGIH-_CEvcZ0RDD8/edit?usp=sharing

**Comment by phstc** [comment]
Hi @truongnmt 

Indeed, some basic cost estimation would be good. 

I usually find it hard to get the AWS pricing (not just for SQS). The easiest for me is to run it for a day/a few days and check the billing page. You can also run it in a lower capacity then just multiple for the capacity. There are a lot of nuances when calculating the pricing, that approach can cover most of them.

I understand not everybody want/can use that approach, sometimes the setup is too complex, and this calculation/estimation is prior to the setup (like evaluating the service). But if that's possible, that would be the most accurate estimation.

**Comment by truongnmt** [comment]
Yeah, I agree with you. Calculation is hard indeed. However, there is some points I would like to confirm about number of request Shoryuken makes. Can you have a look? Thanks!

**Comment by truongnmt** [comment]
Thank you!
