### ISSUE TITLE
question about processing groups

### ISSUE THREAD

**Issue by rhuang** [phstc/shoryuken#605]
In the documentation: https://github.com/phstc/shoryuken/wiki/Processing-Groups

Given:

```
concurrency: 25
queues:
  - queue1
  - queue2
  - queue3
```

> Shoryuken will fetch messages from `queue1`, then `queue2`, then `queue3`, then repeat.

Does this mean if all the workers are busy with `queue1` because `queue1` is full of messages, then it will block the workers from processing `queue2` and `queue3`?

Or does it mean the workers will fetch 1 message from `queue1`, followed by `queue2`, followed by `queue3`, and then back to `queue1`?

I'm wondering if I have 1 worker and multiple queues, is 1 queue being more busy going to block every other queue?

**Comment by phstc** [comment]
Hi @rhuang 

Check this article https://github.com/phstc/shoryuken/wiki/Polling-strategies for more details on the polling strategies.
