### ISSUE TITLE
Doubt about use the customized options with ActiveJob

### ISSUE THREAD

**Issue by andreleoni** [phstc/shoryuken#606]
Hello. 

### Introduction

I have a doubt related to ActiveJob usage.

My actual code is working fine:

```
class ApplicationJob < ActiveJob::Base
  self.queue_adapter = :shoryuken
  self.queue_name_prefix = ENV["SQS_QUEUE_PREFIX"].presence
end
```

And the job as:

```
class TestForApplicationJob < ApplicationJob
  queue_as :my_queue

  def perform(name)
    puts ["Hello, #{name}"].inspect
  end
end
```

## About the doubt

I can use customized `shoryuken_options` when using the active_job? (`shoryuken_options auto_delete: false`)

I'm questioning about it, because today, we are using Sidekiq outside from ActiveJob because of custom options. 

I'm thinking if the usage inside of ActiveJob is the best solution for our business.

_Ps: Sorry for my bad English._

**Comment by phstc** [comment]
Hi @andreleoni 

`shoryuken_options` only works when using Shoryuken Workers. You can't use it combined with Active Job.

> I'm questioning about it, because today, we are using Sidekiq outside from ActiveJob because of custom options.

It is actually an Active Job limitation, it is out of the control of the adapters (Sidekiq, Shoryuken).

If you must use Active Job, you can create your own adapter, similar to [this one](https://github.com/phstc/shoryuken/blob/3ed8eb10ff59cc0fa81389890d13c826d45ae3a4/lib/shoryuken/extensions/active_job_adapter.rb#L85).

```ruby
module ActiveJob
  module QueueAdapters
    class CustomShoryukenAdapter
# ...
      class JobWrapper #:nodoc:
        include Shoryuken::Worker

        shoryuken_options body_parser: :json, auto_delete: false

        def perform(_sqs_msg, hash)
          Base.execute hash
        end
      end 
# ...
end
# ...
```

**Comment by andreleoni** [comment]
Thank you!
