### ISSUE TITLE
Feature request: Set the queue_name_prefix prefix when not url.

### ISSUE THREAD

**Issue by andreleoni** [phstc/shoryuken#608]
Hello.

We are using the queues with name.

The active_job have a `config.active_job.queue_name_prefix = Rails.env`.

If the shoryuken queues name has the same `queue_name_prefix` we can use the queues as:

* development_default
* staging_default
* production_default

This will help us to avoid an abstract creation for this queue_names.

Does has something like this implemented?

Thank you!

**Comment by phstc** [comment]
Hi @andreleoni 

I'm not sure if I could follow it. The queue name prefix should work as you described. 

Also, `shoryuken.yml` is an ERB as well, so you can add custom ruby in there, or add queues programmatically with an initializer. 

```erb
# shoryuken.yml
queues:
  - <%= ENV['QUEUE_NAME'] %>
```

```ruby
# config/initializers/shoryuken.rb

Shoryuken.add_queue('queue', 1, 'default')
```



Thank you

**Comment by phstc** [comment]
Hi @andreleoni 

I added this wiki entry https://github.com/phstc/shoryuken/wiki/Multiple-ways-of-configuring-queues-in-Shoryuken to help with that. 

Please, let me know if that covers your use case.

**Comment by andreleoni** [comment]
I think that if I have a `queue_name_prefix` like active_job should be more useful and will avoid code duplication, for example, if I have 3 queues, will be:

```
# shoryuken.yml
queues:
  - <%= ENV['QUEUE_NAME_ENVIRONMENT_PREFIX'] %>_critical
  - <%= ENV['QUEUE_NAME_ENVIRONMENT_PREFIX'] %>_default
  - <%= ENV['QUEUE_NAME_ENVIRONMENT_PREFIX'] %>_low
```

because my prefix is my environment...

with a configuration about the prefix in all URL, should be only:

```
# shoryuken.yml
queues:
  - critical
  - default
  - low
```

I think that is a good way to configure when the team has more than one staging environment...

It is only a suggestion, should others in another format, so, like ActiveJob has this feature, I think that is a good feature to improve the `shoryuken ´gem...

It is not much problem, only a suggestion..

Thank you!

**Comment by phstc** [comment]
@andreleoni sure! Have you seen this [Active Job Queue Name Support](https://github.com/phstc/shoryuken/wiki/Rails-Integration-Active-Job#active-job-queue-name-support)? 

Is that what you are asking about?

**Comment by andreleoni** [comment]
Yes! It is about this ActiveJob queue name support...

I think that we should have this feature outside of ActiveJob because ActiveJob have no support for custom options of `shoryuken_options`... 

What do you think about it?

**Comment by phstc** [comment]
Got it. I would be open to a PR adding that support. TBH, I don't recall a request for that before, so I don't know the extension of this needed. But I'm open to evaluating pull requests. 

If you have only three queues, like in your example, I don't really see a big deal with the boilerplate code. 

```ruby
- <%= ENV['QUEUE_NAME_ENVIRONMENT_PREFIX'] %>_critical
```

Do you have more than three queues?

**Comment by andreleoni** [comment]
Thanks for the feedback!

Yes, we want to add more queues, so we only have one for now...

So, I will open a pull request to create this functionality, for now, we will add the queue prefix name

Thank you for your support!
