### ISSUE TITLE
Dynamically set concurrency in initializer

### ISSUE THREAD

**Issue by jchappelle** [phstc/shoryuken#609]
Hi. I have a rails initializer that attempts to ensure the concurrency option is equal to or less than the Rails db connection pool size. I thought it was working but recently we had an issue where the worker could not get a connection from the connection pool. I opened a rails console and found that the `Shoryuken.options[:concurrency]` was set to `25` and our connection pool was set to `4`. 

Here's my initializer.
```
# config/initializers/shoryuken.rb
Shoryuken.configure_server do |config|
  begin
    worker_concurrency = config.options[:concurrency]
    
    db_connection_pool_size = ActiveRecord::Base.connection_pool.size
    if db_connection_pool_size < worker_concurrency
      Rollbar.debug "Shoryuken Startup - Limiting worker concurrency to #{db_connection_pool_size} to match DB connection pool size."
      config.options[:concurrency] = db_connection_pool_size
    end
  rescue => e 
    Rollbar.error 'Shoryuken Startup - Failed to Get DB Connection Pool Size', error: e, worker_concurrency: worker_concurrency
  end
end
```

Here's the command we use to run the worker:
```
bundle exec shoryuken -R -q $MY_WORKER_QUEUE -r ./app/workers/my_worker.rb
```

We do NOT have a `shoryuken.yml` config file anywhere.

I looked in the shoryuken code and it looks like rails is loaded after all other options are configured which would make me think my initializer would happen last, taking precedence. But that doesn't appear to be the case.

I also tried setting a `SHORYUKEN_CONCURRENCY` environment variable. But after looking in the code I don't see where that variable is referenced. This documentation implies that it should be.
https://github.com/phstc/shoryuken/wiki/Shoryuken-options#concurrency

Is there any reason this initializer would not work? I realize I could set the concurrency on the command line but I'd rather ensure this value is at or below the connection pool size dynamically to prevent future problems if we increase the pool size.

We are using rails version `5.1.7` and shoryuken version `5.0.4`. 

Any help on this is greatly appreciated.

**Comment by phstc** [comment]
Hi @jchappelle

You can try to add processing groups dynamically with lower concurrency. Check out the links below 👇 

* https://github.com/phstc/shoryuken/wiki/Processing-Groups
* https://github.com/phstc/shoryuken/wiki/Multiple-ways-of-configuring-queues-in-Shoryuken
* https://github.com/phstc/shoryuken/blob/7ce3e7540375798866d3bde482f3869bb6eee6df/lib/shoryuken/options.rb#L37-L52 

Let me know if that works for you.

**Comment by jchappelle** [comment]
If I'm understanding this correctly then processing groups are for having different configurations for groups of queues consumed in a single process. Is that correct?

We are using separate processes for each queue. Can you explain why the `Shoryuken.configure_server` approach doesn't work in this case?

**Comment by jchappelle** [comment]
In using groups would I replace
```
config.options[:concurrency] = db_connection_pool_size
```
with this?
```
Shoryuken.add_group('main', db_connection_pool_size)
```

**Comment by phstc** [comment]
> If I'm understanding this correctly then processing groups are for having different configurations for groups of queues consumed in a single process. Is that correct?

That's correct. `Shoryuken.add_group` is something you can call dynamically, so you can create a processing group with a given concurrency on the initialization. 

> We are using separate processes for each queue. Can you explain why the Shoryuken.configure_server approach doesn't work in this case?

Sorry, that would require some debugging. I would recommend you to add some `binding.pry` around [here](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/environment_loader.rb#L26). It is been a while I don't touch that part of the code, I would need to play with it to be able to answer you properly. 

* [where Shoryuken initializes managers](https://github.com/phstc/shoryuken/blob/7c33d24f8d5e3112a3a67b412c8ec4c673bef715/lib/shoryuken/launcher.rb#L73)
* [once initialized concurrency can't be changed](https://github.com/phstc/shoryuken/blob/7ce3e7540375798866d3bde482f3869bb6eee6df/lib/shoryuken/manager.rb#L12)

> Shoryuken.add_group('main', db_connection_pool_size)

I would experiment with that, add a group `main` with the concurrency you want, then add queues to that group [`Shoryuken.add_queue`](https://github.com/phstc/shoryuken/blob/7ce3e7540375798866d3bde482f3869bb6eee6df/lib/shoryuken/options.rb#L48).

> I also tried setting a SHORYUKEN_CONCURRENCY environment variable. But after looking in the code I don't see where that variable is referenced. This documentation implies that it should be.

`SHORYUKEN_CONCURRENCY` that was just an example of ENV variable. There's no reference in the code for that ENV. I updated the wiki to make more explicit https://github.com/phstc/shoryuken/wiki/Shoryuken-options#concurrency thanks for the feedback.

There also some creatives ways to do that, for example, you can have a `./shoryuken.sh` , that executes `ActiveRecord::Base.connection_pool.size` then calls Shoryuken with the available concurrency. 

Also, how do you set the pool size? You could use the same strategy for setting the Shoryuken concurrency.

**Comment by jchappelle** [comment]
Ahh I always forget that I can put variables in the yaml files with Rails.

We use an environment variable to configure the pool size in the database.yml. So I suppose the correct way to do this is to use the same variable inside the `shoryuken.yml` file. I'll use that approach and get rid of the initializer. So simple. Thanks for the guidance!

**Comment by phstc** [comment]
@jchappelle yay awesome! I am happy to hear it will work. 

Parsing ERB, then YAML is common in Ruby.

[`result = YAML.load(ERB.new(IO.read(path)).result)`](https://github.com/phstc/shoryuken/blob/8cb18f63ea64bc9d828044c615242442047dbbf3/lib/shoryuken/environment_loader.rb#L46).

It is convenient.
