### ISSUE TITLE
[Question] Why InlineExecutor forces `#perform` method to receive two arguments?

### ISSUE THREAD

**Issue by kamillle** [phstc/shoryuken#612]
I think that `Shoryuken::Worker::InlineExecutor` forces `#perform` method to receive two arguments.
https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/worker/inline_executor.rb#L33-L34

In my case, `#perform` method receive one argument, so below error shows up.

```ruby
Failures:

  1) SampleWorker#perform
     Failure/Error:
       def perform(name)
         puts name.to_s
       end

     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # ./app/workers/sample_worker.rb:8:in `perform'
     # ./.bundle/ruby/2.6.0/gems/shoryuken-5.0.4/lib/shoryuken/worker/inline_executor.rb:35:in `call'
     # ./.bundle/ruby/2.6.0/gems/shoryuken-5.0.4/lib/shoryuken/worker/inline_executor.rb:21:in `perform_async'
     # ./.bundle/ruby/2.6.0/gems/shoryuken-5.0.4/lib/shoryuken/worker.rb:10:in `perform_async'
     # ./spec/workers/sample_worker_spec.rb:10:in `block (3 levels) in <top (required)>'
     # ./spec/workers/sample_worker_spec.rb:21:in `block (3 levels) in <top (required)>'

Finished in 2.73 seconds (files took 14.29 seconds to load)
1 example, 1 failure
```

Could you tell me why InlineExecutor forces `#perform` method to receive two arguments and intended use.

**Comment by phstc** [comment]
@kamillle the first argument is the SQS message: https://github.com/phstc/shoryuken/wiki/Getting-Started#create-a-worker. A real worker will always receive the SQS message then the parsed body. 

Are you using active job or standard Shoryuken workers?

**Comment by kamillle** [comment]
@phstc Thank you for your answer. I have a few more questions.

> the first argument is the SQS message

Sorry, I didn't know that. 🙏 

From [this doc](https://github.com/phstc/shoryuken/wiki/Getting-Started#create-a-worker), I understand when we use standard Shoryuken workers, 1st argument of `#perform` is SQS message, and when ActiveJob, we just receive SQS message as 1st argument(there are no other arguments??). Is it correct?

**Comment by phstc** [comment]
@kamillle with Active Job the SQS message is not available for the worker. You only get the payload. 

Shoryuken: `def perform(sqs_msg, name)` / Shoryuken with Active Job `def perform(name)`

**Comment by kamillle** [comment]
@phstc I understood. Thank you for your kind!!
