### ISSUE TITLE
Workers sometimes not stopping with ActiveRecord::StatementInvalid: Mysql2::Error: This connection is still waiting for a result

### ISSUE THREAD

**Issue by erickrom** [phstc/shoryuken#614]
Hi,

First of all great gem!  We are using shoryuken on an application and during deploys we've noticed sometimes that the workers won't stop.  The job seems to finish since we see a message that is logged when a job completes, but the worker fails to stop and our deploy fails.

The exception we are seeing looks like this:
```ruby
ActiveRecord::StatementInvalid: Mysql2::Error: This connection is still waiting for a result, try again once you have the result
```

We rescue StandardError and log and re-raise but as mentioned the worker doesn't stop.  Is there something we can do to 'force' the worker to shutdown?

We have a short timeout:
```ruby
Shoryuken.options[:timeout] = 2
```

and we have lifecycle setup to exit but probably isn't the right thing to do:
```ruby
config.on(:shutdown) do
  Rails.logger.info("Received shutdown callback, exiting process...")
  exit
end
```

Anyway to 'force' the worker to stop and exit on shutdown?  We've gone through great lengths to ensure our jobs are idempotent, so stopping and exiting immediately is not a concern.

Thank you!

**Comment by phstc** [comment]
You can try sending a [SIGTERM](https://github.com/phstc/shoryuken/wiki/Signals#term).

But after receiving any shutdown, no matter how it takes for stopping completely it should stop fetching messages.

**Comment by phstc** [comment]
BTW does your concurrency match with your DB pool size?

https://github.com/phstc/shoryuken/wiki/Shoryuken-options#concurrency
