### ISSUE TITLE
Can I use shoryuken to run periodic tasks?

### ISSUE THREAD

**Issue by armansa** [phstc/shoryuken#615]
I would like to use Elastic Beanstalks's periodic tasks as explained here:
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-tiers.html#worker-periodictasks

I'm not sure if shoryuken is designed to work in Elastic Beanstalk workers.

**Comment by tomharvey** [comment]
Have a look at https://rubygems.org/gems/cloudwatch_scheduler to trigger a new job which your shoryuken workers will consume. I’m using and loving it alongside shoryuken.

**Comment by phstc** [comment]
Shoryuken works specifically with SQS. It can send and receive messages from SQS. As long as the messages are in SQS, it can read them.
