### ISSUE TITLE
Sentry not reporting errors while trying to binding to non-existing SQS queue

### ISSUE THREAD

**Issue by mvpgomes** [phstc/shoryuken#622]
# Description
Hello 👋 

During Shoryuken initialization, I noticed that if an error occur when binding to a non-existing SQS queue, errors are not being reported to Sentry.

I can see by the application logs that errors are being logged:

```
$  ArgumentError: The specified queue(s) <queue-name> do not exist.
```

The application current configuration is using a middleware like the one describe in this [example](https://github.com/phstc/shoryuken/wiki/Sentry.io-Integration).

It is supposed for this middleware to handle those exceptions or I'm missing something here?

Thanks and props for this awesome lib 💪

**Comment by phstc** [comment]
Hi @mvpgomes 

The middleware is for processing messages only (around workers). That error happens during the Shoryuken initialization, which is not connected to that middleware. 

That error should prevent your Shoryuken process to start.

If you need queues with no workers, one alternative is to add queues/workers dynamically when needed. 

* https://github.com/phstc/shoryuken/blob/15923f8b02793c412dc430e16f1f4742d9e1f471/lib/shoryuken/options.rb#L48
* https://github.com/phstc/shoryuken/blob/15923f8b02793c412dc430e16f1f4742d9e1f471/lib/shoryuken/options.rb#L92
