### ISSUE TITLE
How to increase no of shoryuken processes?

### ISSUE THREAD

**Issue by PrabhuPuredla95** [phstc/shoryuken#626]
We have one shoryuken process running with concurrency 32 but the CPU and Memory is almost idle every time.

As you mentioned in this comment: https://github.com/phstc/shoryuken/issues/7#issuecomment-61634012
Can you please help me with how to do that in rails 4.1?

**Comment by phstc** [comment]
Hi @PrabhuPuredla95 

Rails doesn't run Shoryuken. Shoryuken is a separated process. For running multiple processes, it will depend on how you are currently running Shoryuken in the first place. 

If CPU and Memory are idle, but the queues are empty, there isn't much you can do it, there's no job to be done. If CPU and Memory are idle and the queues are full, you can increase concurrency, [reduce/remove delay](https://github.com/phstc/shoryuken/wiki/Shoryuken-options#delay) and also increase the number of processes. 

There's no final rule TBH, it depends on your environment and type of messages you are consuming.

**Comment by PrabhuPuredla95** [comment]
Thanks for the quick reply.

This is the configuration of shoryuken.yml.
aws:
  access_key_id: xxxx
  secret_access_key: xx
  region: xxx
  ssl_verify_peer: xxxx
concurrency: 32
queues:
  - Q1
  - Q2
  - Q3
  - Q4
We have 15 workers each associated with dedicated queue. Out of these queues, Q1 gets more number of messages relative to others.

Yes cpu and memory is almost idle when there are 6 lakhs messages in SQS.

**Comment by phstc** [comment]
You can try to increase `concurrency` and monitor.

**Comment by rrdharmesh** [comment]
@phstc We're also facing a similar problem. What are the suggested threads count we can increase in Shoryuken?

**Comment by matt-taylor** [comment]
Hey @rrdharmesh. The concurrency count is specific to each setup and dependent on if the worker is I/O bound or CPU bound. 
Can you fully describe your issue in detail and give us some addition details regarding:
- What is your current system setup
- What is your Shoryuken config
- And any APM data about the issue (if available)
