### ISSUE TITLE
Release latest version (5.0.5) to rubygems

### ISSUE THREAD

**Issue by linhdangduy** [phstc/shoryuken#631]
Dependabot on my project can not automatically update shoryuken (so I can not use ARN to define queues) because:

Latest version on shoryuken repository is [5.0.5](https://github.com/phstc/shoryuken/blob/master/CHANGELOG.md#v505---2020-02-20)
But the latest on rubygems is 5.0.4: https://rubygems.org/gems/shoryuken

**Comment by phstc** [comment]
Good catch! Done.

https://rubygems.org/gems/shoryuken

Thank you
