### ISSUE TITLE
Scheduling capability using AWS DynamoDB

### ISSUE THREAD

**Issue by joekhoobyar** [phstc/shoryuken#64]
We are using Shoryuken at my work and need the ability to schedule jobs farther into the future than the 15 minute delay limit imposed by SQS.

My idea is to use DynamoDB for this purpose - and I have created a fork of Shoryuken to work on it.  I was wondering if you were interested in such a feature and/or if you have any feedback on it.  It looked like it would be more kludgy to build this feature into a separate gem, since it would need to monkey patch Shoryuken and that might make things brittle whenever an updated Shoryuken gem is released.

**Comment by phstc** [comment]
Hi @joekhoobyar 

I would not couple Shoryuken code with something for DynamoDB as it's too specific. I believe you could do that as a plugin instead. 

If you need to delay messages up 12 hours you can still use SQS, have a look at [Delaying a message perform_in](http://www.pablocantero.com/blog/2014/11/29/sqs-to-the-rescue/).

**Comment by joekhoobyar** [comment]
We need to be able to schedule for some arbitrarily far ahead point in the future.  If I develop it as a plugin, then the shoryuken server would need the "require" option to be specified in the config file in order to pull things off of the schedule.   Just thinking out loud here, but I was thinking that the monkeypatching needed in Manager and Launcher could be ugly, potentially. Or, it would have to run as a separate daemon process - which is not as nice...

**Comment by phstc** [comment]
I wouldn't change shoryuken core for that, because you will have problems to get shoryuken updates in the future. 

I believe that a daemon to pull data from DynamoDB and send to SQS would be the safer solution.

**Comment by joekhoobyar** [comment]
Yeah, my boss and I were just discussing this very fact.  We feel that an additional daemon, though maybe not as "nice", is definitely safer for the same reasons. :-)

**Comment by joekhoobyar** [comment]
Or, maybe the AJ adapter has a _different_ name, so that we don't conflict.  :-)

**Comment by phstc** [comment]
+1 on having a custom AJ adapter

But you still need to monkey patch the worker class: https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/worker.rb#L27

```ruby
Shoryuken::Worker.class_eval do
  def perform_in_ext(interval, body, options = {})
    # save on DynamoDB
  end
end
```

And have your custom AJ calling `perform_in_ext` instead of `perform_in`. So zero conflict problems to get Shoryuken updates.

wdyt?

**Comment by joekhoobyar** [comment]
Yeah, an extension method would work well, I think.  Starting work on this today.  Right now I am consulting at Gannett, Inc.  (USA Today) so both shoryuken and this "plugin" will be running in production at a large enterprise fairly soon.  :-)

**Comment by phstc** [comment]
I'm happy to hear that.

We are using Shoryuken since the day 1 hehe - no problems so far.

@leemhenson did an awesome work updating the aws-sdk dependency. It's faster (at least on my home-made tests) than the previous SDK.

Please let me know how it goes :smile:

**Comment by joekhoobyar** [comment]
Very nice.  I will be sure to.  Can't wait until I can target master, but I have to start with Shoryuken v0.0.4 (for Ruby 1.9.3), then move on to v0.0.5, and then finally I can target master.

**Comment by joekhoobyar** [comment]
I have a first cut of this available at http://github.com/joekhoobyar/shoryuken-later

This is the first version, targetting v0.0.4 (for Ruby 1.9.3).  I wanted to get your opinion before I move on.  I'm wondering if Celluloid is overkill for such a simple task, but it may get larger in the future.  I am quite new to Celluloid so I borrowed a lot of code from Shoryuken.

**Comment by joekhoobyar** [comment]
By move on, I meant targetting v0.0.5, and then master. :-)

**Comment by joekhoobyar** [comment]
Lame, I forgot the ActiveJob adapter. :-)  Easy enough to do, though.

**Comment by phstc** [comment]
Why not just having a daemon retrieving items from DynamoDB filtered by `date <= Time.now` and enqueueing them to SQS?

1. `perform_in_ext` would save on DynamoDB.
2. Your daemon would be just a script to read from DynamoDB, send to SQS and delete the item.

**Comment by phstc** [comment]
```ruby
pending_messages_on_dynamodb.each do |msg|
  send_to_sqs(msg)
  delete_on_dynamodb(msg)
end
```

Both SQS and DynamoDB support sending and deleting in batches in case you don't want to do it one by one. 

You can use [whenever](https://github.com/javan/whenever) to run it every N seconds.

**Comment by joekhoobyar** [comment]
My employer wanted a separate daemon process

**Comment by joekhoobyar** [comment]
And a separate ActiveJob adapter

**Comment by joekhoobyar** [comment]
Really, they were hoping you would include it in Shoryuken, rather than have our own daemon.  But I know you weren't interested in that.

**Comment by phstc** [comment]
I don't think you should mix that with shoryuken, IMO it should be in a separate process.

The daemon would be "shoryuken_later.rb` called by a cronjob or similar every N seconds.

And the AJ can be part of the files you are requiring `-r` in Shoryuken, same for the `perform_in_ext` monkey patch.

**Comment by joekhoobyar** [comment]
Oh, and you can't delete *after* queuing to SQS.  That's a race condition. :-)

**Comment by joekhoobyar** [comment]
They wanted to get away from running things with cron.  It causes work to pile up.  The shoryuken-later daemon won't pile up work, because it does not poll if the poller is still busy.

**Comment by phstc** [comment]
It can be an extra gem `shoryuken-later`.

But this gem would be just a few lines of code, an AJ adapter, and instead of monkey patching Shoryuken worker you can add a new worker include:

```ruby
include ShoryukenLater::Worker
```

To add the `perform_in_ext`.

**Comment by phstc** [comment]
> They wanted to get away from running things with cron. It causes work to pile up. The shoryuken-later daemon won't pile up work, because it does not poll if the poller is still busy.

You can `limit` search results on DynamoDB.

**Comment by phstc** [comment]
> Oh, and you can't delete after queuing to SQS. That's a race condition. :-)

No race condition if you have only process/thread doing that.

**Comment by joekhoobyar** [comment]
If I was running it with cron, it would be a few lines of code.  I can't run it with cron.  That is a non-starter for my employer.  If I was monkeypatching the shoryuken daemon, it would also be a few lines of code.  I can't do that either, since it would be brittle.

**Comment by phstc** [comment]
Gotcha! Then your solution looks good! :smile:

**Comment by joekhoobyar** [comment]
> > Oh, and you can't delete after queuing to SQS. That's a race condition. :-)
> No race condition if you have only process/thread doing that.
Yeah, I know that one process/thread doesn't race with itself. :-) Now you're just teasing.  LOL

**Comment by joekhoobyar** [comment]
Truthfully, it bothers me a lot to have this whole daemon just for this simple purpose.  I would love to run it with cron.  *But*, I also got to practice with Celluloid.  So, there's always a plus side. :)

**Comment by joekhoobyar** [comment]
Any thoughts about adding hooks to the Shoryuken manager?  For plugins?  Then I could get rid of the daemon. :-)

**Comment by phstc** [comment]
hm you can start and stop your process with: https://github.com/phstc/shoryuken/blob/master/lib/shoryuken.rb#L90-L96

**Comment by joekhoobyar** [comment]
Ah!  So, in the *master* branch, I would have no need for a separate daemon anymore.  That'd be pretty cool.  Although, I was thinking of rewriting my daemon stuff using the `timers` gem. https://github.com/joekhoobyar/shoryuken-later/issues/1

**Comment by phstc** [comment]
celluloid timers?

you are already using it: https://github.com/joekhoobyar/shoryuken-later/blob/c8a0f5a2fc79a71c3bfd42a8839b42c2706eb223/lib/shoryuken/later/manager.rb#L33

**Comment by joekhoobyar** [comment]
Yeah,  but I was thinking of not even using the Celluloid gem at all.  Just the timer's gem alone.

**Comment by joekhoobyar** [comment]
Either way, when I finish the README this weekend, I will definitely give credit for all of the Shoryuken code I "borrowed" from you. ;-)

**Comment by phstc** [comment]
a big part of this code was ["borrowed" from sidekiq](https://github.com/phstc/shoryuken#credits) hehe

time gem? I thought you were talking about https://github.com/celluloid/timers

**Comment by joekhoobyar** [comment]
Yeah, that's the one I meant.  It can be used without Celluloid.  I have made that change, and removed my launcher.rb and manager.rb.  Much simpler daemon.

And.. for *normal* users (not my employer) we need to have a non-daemon option by _default_ that can used from a cron job.  Now that my boss is happy, time to make everybody else happy.

**Comment by kookster** [comment]
what about using the on_start method (https://github.com/phstc/shoryuken/pull/35) to have the poller run as a timer in the existing celluloid instance?

With that, you don't need cron, or another process, or monkeypatching.

**Comment by phstc** [comment]
hm that's a good point.

@joekhoobyar https://github.com/joekhoobyar/shoryuken-later could use `on_start` to run in the same process, wdyt?

**Comment by joekhoobyar** [comment]
Yes, I actually have a ticket for that: joekhoobyar/shoryuken-later#3

The initial motivation for this project was just to fit the needs of my employer - now I am starting a new job on Wednesday.  I have no problem with the project evolving to fit the needs of the community. :-)  I will just make sure to have the gem's minor version bump up so that my "old" employer doesn't get surprised by the changes.

**Comment by Startouf** [comment]
So what's the difference with https://github.com/farski/shoryuken-waiter ?
