### ISSUE TITLE
Setting visibility_timeout when batch is enabled

### ISSUE THREAD

**Issue by venkateshan-niladri** [phstc/shoryuken#640]
I have a shoryuken worker with `batch: true`

I want to set the `visibility_timeout` for all the messages received as an array. Is there any way I can do it at once or do I need to loop through each sqs message and set them individually?

```
def perform(sqs_msgs, args)
  begin
    sqs_msgs.each do |sqs_msg|
      sqs_msg.visibility_timeout = 10
    end
  end
end

```

**Comment by phstc** [comment]
@venkateshan-niladri you need to loop through all messages. SQS does not support AFAIK batch updating the visibility timeout.
