### ISSUE TITLE
Retrying jobs

### ISSUE THREAD

**Issue by joekhoobyar** [phstc/shoryuken#65]
I would like to work on this feature, do you have any feedback about how you would like it to work?

I figure that we would be using the `:approximate_receive_count` message attribute to drive the retrying of jobs, and then set the message's visibility timeout based on the number of retries.  Does this make sense?

Configuration for the retry could be in the shoryuken_options for the worker.  Maybe a Hash of Fixnum and/or Range keys that map to visibility timeout values?  Middleware would have to scan the Hash to find the first matching key and the assign the visibility timeout.  If the retry count is greater than all of the keys in the Hash (Range end or Fixnum), then delete the message?

Just food for thought, really I am just making a bunch of assumptions about how you would like it to work. :-)  I am open to anything.

**Comment by joekhoobyar** [comment]
FYI - I got the idea from your comment here:

https://github.com/phstc/shoryuken/blob/v0.0.4/lib/shoryuken.rb#L92

**Comment by phstc** [comment]
SQS has auto retry built in, and also dead letter queues :smile: 

That comment was to add exponential backoff, but no one asked for yet. 

Have a look at https://github.com/phstc/shoryuken/wiki/Retrying-a-message and [Auto retrying errors](https://github.com/phstc/shoryuken/wiki/Retrying-a-message).

**Comment by joekhoobyar** [comment]
I do like the exponential backoff idea, if you look at my idea above it could easily be used to implement that via configuration.

**Comment by phstc** [comment]
I like your idea, would it be something like that:

```ruby
class MyWorker
  include Shoryuken::Worker
  
  shoryuken_options retry_intervals: [10.minutes, 30.minutes, 1.hour, 6.hours, 12.hours]
end
```

The `retry_intervals` could be optional, having a reasonable default value.

I'm doing exponential backoff in my project, but I didn't extract it yet, would you like to send a PR with it as a middleware?

a snippet of what I'm doing in my project:

```ruby
def retry_intervals
  if development?
    [7.seconds, 9.seconds, 12.seconds]
  else
    [10.minutes, 30.minutes, 1.hour, 6.hours, 12.hours]
  end
end

def handler_failure(sqs_msg, e)
  attempts = sqs_msg.receive_count - 1

  interval = if attempts < retry_intervals.size
     retry_intervals[attempts]
   else
     retry_intervals.last
  end

  # timeout cannot be larger than 43200 (12.hours)
  if interval + sqs_msg.queue.visibility_timeout > 43200
    interval -= sqs_msg.queue.visibility_timeout
  end

  sqs_msg.visibility_timeout = interval
  
  info "Message #{sqs_msg.id} failed, will be retried in #{interval} seconds."

  # return the next attempt timestamp
  Time.now.utc + interval
end
```

Sidekiq reference for exponential backoff: https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry

**Comment by joekhoobyar** [comment]
This is also something that my employer is interested in as well, so it looks like I will be working on it.  I like your version of the configuration better, the Array is simpler than using a Hash with Fixnum and/or Range keys.  `:retry_intervals` makes sense as the configuration key, too.

**Comment by joekhoobyar** [comment]
To make auto-retry compatible with auto-delete, I would need to some logic to the AutoDelete middleware and the Shoryuken::Worker. Something like:

```ruby
module Shoryuken::Worker
  def will_retry?
    @will_retry
  end

  def will_retry!
    @will_retry = true
  end
end
```
This way, the AutoDelete middleware could check `will_retry?` and avoid deleting jobs that are supposed to be tried again.  Does this make sense?   It would be nice for AutoDelete and AutoRetry middlewares to not need to be mutually exclusive.

**Comment by joekhoobyar** [comment]
Heh, or we could just put the AutoDelete _before_ the AutoRetry middleware.  Umm... maybe that's the easier way. :-D

**Comment by phstc** [comment]
> Heh, or we could just put the AutoDelete *before* the AutoRetry
middleware. Umm... maybe that's the easier way. :-D

Nice!

I wouldn't call it AutoRetry, because the auto retry is something that SQS
does based on the visibility timeout. Maybe we could call it
"ExponentialRetry" or 'ExponentialBackoffRetry" wdyt?



On Wed, Mar 11, 2015 at 12:40 PM, Joe Khoobyar <notifications@github.com>
wrote:

> Heh, or we could just put the AutoDelete *before* the AutoRetry
> middleware. Umm... maybe that's the easier way. :-D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phstc/shoryuken/issues/65#issuecomment-78288739>.
>



-- 
Pablo Cantero
pablocantero.com

**Comment by joekhoobyar** [comment]
ExponentialBackoffRetry works for me.  The first one might sound scary... it exponentially retries your job more and more.. lol

I can cancel the pull request and resubmit after renaming, if you want.
