### ISSUE TITLE
Capistrano recipes

### ISSUE THREAD

**Issue by joekhoobyar** [phstc/shoryuken#66]
I have some that we are using at work, for a Rails based project.  That project is still using Capistrano 2.  Then, another project that we are about to use Shoryuken in (via ActiveJob) is using Capistrano 3.  So I will have two flavors shortly.  Right now, I have only written tasks for Capistrano 2.

Is there any interest in including Capistrano recipes into Shoryuken, or should I consider putting it into a separate gem?

**Comment by phstc** [comment]
an external gem would be great

something similar to:

https://github.com/seuros/capistrano-sidekiq
https://github.com/mperham/sidekiq/wiki/Deployment#capistrano

**Comment by joekhoobyar** [comment]
Cool.  I have started working on this.  I have the Capistrano 2 support working and tested, and I have started work on the Capistrano 3 support.  It is always nice when your employer supports open source development.  I am literally on the clock while I work on this stuff. :-)

https://github.com/joekhoobyar/capistrano-shoryuken

**Comment by joekhoobyar** [comment]
This seems to be working for us in Capistrano 3 as well as Capistrano 2.  Feel like taking a look at it?

https://github.com/joekhoobyar/capistrano-shoryuken

**Comment by phstc** [comment]
Looks good! I will create a [Deployment](https://github.com/phstc/shoryuken/wiki/Deployment) section on the wiki and it as a reference :beers:

**Comment by joekhoobyar** [comment]
@phstc - Still want to write that [Deployment](https://github.com/phstc/shoryuken/wiki/Deployment) section?

**Comment by phstc** [comment]
@joekhoobyar yes I do. Let me try this weekend, maximum next week. Thanks for reminding me that!

**Comment by phstc** [comment]
@joekhoobyar initial version done [Deployment](https://github.com/phstc/shoryuken/wiki/Deployment) - feel free to update it if you want.

Tks again for [capistrano-shoryuken](https://github.com/joekhoobyar/capistrano-shoryuken), great work! :beers:
