### ISSUE TITLE
Newer AWS SDK 2 versions incompatibility

### ISSUE THREAD

**Issue by renanmzmendes** [phstc/shoryuken#67]
If I upgrade the `aws-sdk-resources` to the latest version (`2.0.29` at this time), the tests don't pass. That happens because `Aws::SQS::Queue` and `Aws::SQS::Message` (maybe others) are not defined. I've looked through the `aws-sdk` docs and it really seems to be the case.

I don't what we should do, cause I'm not sure how one would instantiate queues and messages in this scenario. Could this be an `aws-sdk` issue?

**Comment by phstc** [comment]
That's the why pinned to aws-sdk 2.0.21, you can check more in these threads: https://github.com/phstc/shoryuken/pull/39#issuecomment-76075564 and https://forums.aws.amazon.com/thread.jspa?threadID=172341&tstart=0
 

Do you need to upgrade the `aws-sdk-resources`?
