### ISSUE TITLE
ArgumentError (expected params[:message_body] to be a string)

### ISSUE THREAD

**Issue by renanmzmendes** [phstc/shoryuken#70]
As I am testing a minor addition to `shoryuken` I've been working on, I can't make a simple test application work as expected using the master branch.

The error is due to the serialization of `job` in the queue adapter. The error is as described in the title of this issue: the `message_body` is supposed to be a string, but after inspecting, I saw that `job.serialize` turns out to be a `Hash`.

Anyone knows what's going on?

**Comment by renanmzmendes** [comment]
For the record, my job is as simple as:

```ruby
class TestJob < ActiveJob::Base
  queue_as :high_priority

  def perform(message)
  	puts message
  end
end
```

and my controller's action calling `perform_later` is as simple as this:

```ruby
class WelcomeController < ApplicationController

	def index
		TestJob.perform_later("Hello world!")
		render json: {}
	end

end
```

**Comment by phstc** [comment]
Could you update with master again?

@janpapenbrock fixed that here: https://github.com/phstc/shoryuken/pull/69

**Comment by renanmzmendes** [comment]
I have the last version on my machine, @phstc.
It doesn't seem like the problem has been addressed...

The exception is raised [here](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/extensions/active_job_adapter.rb#L23) caused by [this](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/extensions/active_job_adapter.rb#L40)

**Comment by phstc** [comment]
hm you are right, I forgot about that in the AJ adapter.

Actually I'm getting inclined to monkey patch `send_message` to `JSON.dump` when the body is a Hash to avoid these code duplication. wdyt?

**Comment by renanmzmendes** [comment]
@phstc, sorry, I actually didn't have the last version. I was working on my fork not yours. Well I did some tests and the job was performed alright.

**Comment by farski** [comment]
@phstc I'm seeing this problem; would you expect it to be working on 1.0.0? It's only happening with a very small fraction of messages for a job that otherwise works. If I jump into the SQS console, this is what is shows for the message body:

```json
{"job_class":"FeedProcessJob","job_id":"190cd37c-b53d-458f-be51-94b9842ea44b","queue_name":"development_scour-audio_process","arguments":[{"_aj_globalid":"gid://audio-scour/Feed/49847"}]}
```

which, when found, causes:

```
ERROR: Process died, reason: expected params[:message_body] to be a string
```

As compared to this message, which gets handled as expected:

```json
{"job_class":"FeedProcessJob","job_id":"ead91160-3880-4da3-b8e9-a1c8f2ac8235","queue_name":"development_scour-audio_process","arguments":[{"_aj_globalid":"gid://audio-scour/Feed/49735"}]}
```

**Comment by phstc** [comment]
hm

Shoryuken dumps Hashes (usually JSON) into strings: https://github.com/phstc/shoryuken/blob/668215cd743d13107b23519f32fb6d33fba0cc21/lib/shoryuken/worker.rb#L16-L17

Which version of shoryuken are using? This auto conversion above was added in 1.0.0.

**Comment by farski** [comment]
`shoryuken (1.0.0)`

**Comment by phstc** [comment]
hm any chance you are trying to enqueue `nil`, `FixNum` etc? aws-sdk only accepts `String`

**Comment by farski** [comment]
Everything is going through Active Job, so it's just whatever serialization is happening in there.

**Comment by farski** [comment]
`FeedProcessJob.perform_later(feed)` with `feed` being a Active Record object.

**Comment by phstc** [comment]
Can `feed` be `nil` in some cases?

**Comment by farski** [comment]
In this case that seems very unlikely, since this is how I scheduled all the jobs.

```
Feed.all.each_with_index do |feed, i|
    FeedProcessJob.perform_later(feed)
end
```

**Comment by phstc** [comment]
@farski could you use Shoryuken from master? I've just added this: https://github.com/phstc/shoryuken/commit/c0bcc6ffced5003c8e8928b53b6add15942b7987 to help with this troubleshooting.

**Comment by farski** [comment]
Okay, going to try to get it to happen again now.

**Comment by farski** [comment]
First round of testing didn't have any problems. When it happened before some of those jobs had roundtripped through Shoryuken-Later, so I'll try that. I'll let you know in about 15 minutes...

**Comment by farski** [comment]
Everything worked even with delayed messages. I'm going to run the same tests on 1.0.0 to see if something else changed on master that's preventing the problem.

**Comment by farski** [comment]
Sorry, can't get it to happen. I'll keep running master so if it does I can try to capture some more info.

**Comment by phstc** [comment]
Thanks @farski 

Please let me know if you get an exception from that.

**Comment by farski** [comment]
So actually the message that was failing before was still in the dead letter queue. I got it back into the regular queue, and it worked fine using both 1.0.0 and master. 😑Not that that helps track down the problem, but I'll keep an eye on things.
