### ISSUE TITLE
Is it possible to run "bundle exec shoryuken" for all workers?

### ISSUE THREAD

**Issue by RuslanHamidullin** [phstc/shoryuken#78]
Hey Guys,

Is it possible to run shoryuken process for all workers like for sidekiq:
```
bundle exec sidekiq # Will process all jobs
```

For example if I run:
```
bundle exec shoryuken -C config/shoryuken.yml -L log/shoryuken.log
```

then I see:
```
2015-03-16T10:51:03Z 11892 TID-agdn8 WARN: No worker supplied for 'staging_mailers'
2015-03-16T10:51:03Z 11892 TID-fyjpc INFO: Starting
```

For example, if I use ActiveJob#deliver_later! - then these jobs would not be proccessed as I'm not passing path to worker. 

Just tested: jobs are adding to SQS queue, but are not process by running:
```
bundle exec shoryuken -C config/shoryuken.yml -L log/shoryuken.log
```  
Thanks for any help :beers:

**Comment by RuslanHamidullin** [comment]
Ahh, Sorry guys.
Totally my bad.
I should use:
```
bundle exec shoryuken -R -C config/shoryuken.yml -L log/shoryuken.log
```
Closing  :shipit:

**Comment by timscott** [comment]
@rusllonrails - I must be missing something.  When I start a worker without specifying a job type (no -r switch), I get warnings for every queue of ```No worker supplied for...``` and the worker does not pick up messages in any queue. Adding ```-R``` seems to have no effect.

I'm a long-time Sidekiq user, new to Shoeyuken.

**Comment by rusllonrails** [comment]
Hey @timscott 

I think probably need to double check config files, AWS creds (probably loading of ENV variables).

Here are mine code parts from working app:

1) Gemfile
```
gem 'rails', '4.2.2'

# Background Jobs
gem "shoryuken", github: "phstc/shoryuken", branch: "master"

# Envrioment variables
gem 'dotenv-rails', '~> 1.0'
```

2) .env (file in Rails.root directory for setting env variables exposed by dotenv-rails gem)
```
AWS_ACCESS_KEY_ID=<YOUR AWS KEY>
AWS_SECRET_ACCESS_KEY=<YOUR AWS SECRET KEY>
AWS_REGION=<YOUR AWS REGION>
```

3) config/shoryuken.yml
```
aws:
  access_key_id:      <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key:  <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region:             <%= ENV['AWS_REGION'] %>
  receive_message:              
    attribute_names:
      - ApproximateReceiveCount
      - SentTimestamp
concurrency: 4,  # The number of allocated threads to process messages. Default 25
delay: 5,        # The delay in seconds to pause a queue when it's empty. Default 0
queues:
  - ["<%= Rails.env %>_mailers", 1]
  - ["<%= Rails.env %>_default", 2]
```

Note that you should set whitelist of using queues list in queues option.
I use 2 queues per environment (dev / staging/ production):
 - one for mailers
 - second for another jobs

But you can add others you need.
```
queues:
  - ["<%= Rails.env %>_mailers", 1]
  - ["<%= Rails.env %>_default", 2]
  - ["<%= Rails.env %>_custom", 3]
```

4) I use shoryuken along with active_job as it's most convenient way for me:
    config/initializers/active_job_shoryuken.rb
```
if %w{staging production}.include?(Rails.env)
  Rails.application.configure do
    config.active_job.queue_adapter = :shoryuken
    config.active_job.queue_name_prefix = Rails.env
    config.active_job.queue_name_delimiter = "_"
  end
end
```

5) Job example (app/workers/example_worker.rb):
```
class ExampleWorker
  include Shoryuken::Worker

  shoryuken_options queue: "#{Rails.env}_default", auto_delete: true

  def perform(_sqs_msg)
    # Run your code
  end
end
```

6) Run jobs:
```
bundle exec shoryuken -R -C ./config/shoryuken.yml -L ./log/worker.log
```

**Comment by gmalouf** [comment]
@rusllonrails do you run both active job and non-active job workers simultaneously?

**Comment by rusllonrails** [comment]
@gmalouf nope, I use active job only

**Comment by gmalouf** [comment]
Interesting - from your example (5) it appeared you defined a non-active job worker.  I'm having trouble getting a non-active job worker to run with active jobs enabled.

**Comment by rusllonrails** [comment]
I believe I use active job a I'm setting in Step 4
```
 Rails.application.configure do
    config.active_job.queue_adapter = :shoryuken
    ...
end
```
So I think they are delivering via Active Job too

**Comment by rusllonrails** [comment]
hmm, probably you are right. Seems they are non active job workers )

**Comment by rusllonrails** [comment]
so, non active job workers are also working for me by example above ^

**Comment by gmalouf** [comment]
So you have ones defined in app/workers as well as 'Active Job' classes under app/jobs then?
