### ISSUE TITLE
Topics

### ISSUE THREAD

**Issue by kookster** [phstc/shoryuken#80]
I see that sns topics are now supported, but I am not sure how they are intended to be used - could someone add some docs for topics?

e.g. how to configure them, how to send to a topic, what needs to be done to subscribe an sqs queue to a topic so workers receive messages

I guess I can try to read the code and come to my own conclusions, but someone else may already be ahead of my understanding.

**Comment by phstc** [comment]
> I see that sns topics are now supported, but I am not sure how they are intended to be used - could someone add some docs for topics?

Nice catch! I will work on that.

> e.g. how to configure them, how to send to a topic, what needs to be done to subscribe an sqs queue to a topic so workers receive messages

```ruby
# https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/topic.rb
Shoryuken::Client.sns.send_message(body)
```
Should work.

> how to configure them

For the SNS configuration. I'm not sure if we should explain that here or just link to http://docs.aws.amazon.com/sns/latest/dg/SendMessageToSQS.html wdyt?

@leemhenson do you have some sample code to configure SNS? For my project I did that via AWS interface.

**Comment by leemhenson** [comment]
Covers most of it: 

https://github.com/Comcast/cmb/blob/master/examples/ruby/example.rb

**Comment by phstc** [comment]
Tks @leemhenson 

I'm closing this ticket in favor of https://github.com/phstc/shoryuken/wiki/SNS-Topics
