### ISSUE TITLE
Recurring tasks?

### ISSUE THREAD

**Issue by skanderm** [phstc/shoryuken#81]
I'm a fan of the easy syntax for adding recurring tasks using https://github.com/tobiassvn/sidetiq with Sidekiq.

e.g.:

```
class MyRecurrentWorker
  include Shoryuken::Worker
  include Shoryuken::Schedulable

  recurrence { daily }

  def perform
    # do stuff ...
  end
end

```
Any plans to add something like this or would that be external to shoryuken?

**Comment by phstc** [comment]
Hi @skanderm 

hm I believe it would be probably in a external project like sidetiq. But no plans yet.

Maybe https://github.com/joekhoobyar/shoryuken-later with minor changes could do something similar as sidetiq.

@joekhoobyar could you confirm that ^^^?

**Comment by joekhoobyar** [comment]
Yeah, I'm sure that I could do something like that.  I did a pretty nice recurring events "engine" for http://groupsites.com, both in SQL and in Ruby.  This one would have to be based on DynamoDB and Ruby.

**Comment by joekhoobyar** [comment]
My current client doesn't need this (so I won't be building it on the clock), but I like the idea.  Could be a good weekend project for me.  At least not during working hours. ;-)

**Comment by phstc** [comment]
@joekhoobyar recurrence + https://github.com/joekhoobyar/shoryuken-later/issues/3 would be a win! hehe :beers:

**Comment by mm53bar** [comment]
Isn't this also something that https://github.com/tomykaira/clockwork could do?
