### ISSUE TITLE
Opsworks deployment instructions 

### ISSUE THREAD

**Issue by TangRufus** [phstc/shoryuken#82]
how should I start the shoryuken workers on AWS OpsWorks?

It would be nice including OpsWorks deployment instructions / cookbooks in the deployment section ( #66 )

Thanks

**Comment by phstc** [comment]
Hi @TangRufus 

I've never used AWS OpsWorks, so I can't help much with that. But I believe the cookbooks used for Sidekiq, would work fine for Shoryuken.

I found some resources for Sidekiq:

* http://zaman.io/running-sidekiq-on-opsworks/
* https://github.com/drakerlabs/opsworks_sidekiq
* https://github.com/brainyatom/opsworks-sidekiq

If you make it work for Sidekiq, could share a gist or GitHub project with the steps, so I can add a link in the  [Deployment](https://github.com/phstc/shoryuken/wiki/Deployment) article?

**Comment by carpet** [comment]
@phstc I've modified Brainy Atom's opsworks-sidekiq recipe to work with shoryuken - https://github.com/carpet/opsworks-shoryuken

**Comment by phstc** [comment]
@carpet :star: I added a link on the [wiki page](https://github.com/phstc/shoryuken/wiki).
