### ISSUE TITLE
Update AWS SDK version

### ISSUE THREAD

**Issue by sschepens** [phstc/shoryuken#83]
I know that amazon has removed some implementations that were crucial to shoryuken.
But, is there no way of updating the amazon sdk version? right now i have request that's failing and works with latest sdk version.
And it's just a pain to use v1.
Amazon sdk's are open source, can't you just copy the code that's missing until amazon adds support?

Thanks,
Sebastian

**Comment by phstc** [comment]
Hi @sschepens 

Shoryuken uses the aws-sdk v2: https://github.com/phstc/shoryuken/blob/master/shoryuken.gemspec#L27

**Comment by sschepens** [comment]
@phstc I think i havent made myself clear, I know Shoryuken uses v2 but its locked to version 2.0.21 and.
The problem is that for example Autoscaling::Client's method #enter_standby is not working on 2.0.21 but it's working on latest 2.0.33.
Is there no chance of updating to latest version of v2?
