### ISSUE TITLE
Timeout cannot be extended?

### ISSUE THREAD

**Issue by dteoh** [phstc/shoryuken#86]
I am getting the following error when using the auto_visibility_timeout option in my worker class:

```
ERROR: Could not auto extend the message FooWorker/non-interactive-1m/7740b3be-1e0a-4c42-ba49-da69ea1ac19b visibility timeout. Error: undefined method `visibility_timeout=' for #<Aws::SQS::Message:0x007fdf67278d20>
```
My Gemfile.lock:

```
shoryuken (1.0.0)
  aws-sdk-core (= 2.0.21)
  aws-sdk-resources (= 2.0.21.pre)
  celluloid (~> 0.16.0)
```

**Comment by leemhenson** [comment]
yeah 2.0.21 docs show that it should be a call to:

> (Object) change_visibility(options = {})
>
>Options Hash (options):
>  :visibility_timeout (Integer) — required —
>The new value (in seconds - from 0 to 43200 - maximum 12 hours) for the message's visibility timeout.

**Comment by leemhenson** [comment]
it looks like master should not have this issue any more. can you try it?

**Comment by dteoh** [comment]
Yes, master works, thanks.

Do you have any plans to cut a 1.0.1 release soon?

**Comment by phstc** [comment]
thanks @dteoh for testing that! 1.0.1 released!
