### ISSUE TITLE
API Change?

### ISSUE THREAD

**Issue by rgehring** [phstc/shoryuken#94]
Since this morning have been getting errors sending strings! My specific question, has the API changed so that message is now supposed to be a hash or something? 

```
Shoryuken::Client.queues("sds-test").send_message( "test"  )


NoMethodError: undefined method `merge' for "test":String
	from /var/app/current/vendor/bundle/gems/shoryuken-1.0.2/lib/shoryuken/queue.rb:23:in `send_message'
	from (irb):4
	from /var/app/current/vendor/bundle/gems/railties-4.1.6/lib/rails/commands/console.rb:90:in `start'
	from /var/app/current/vendor/bundle/gems/railties-4.1.6/lib/rails/commands/console.rb:9:in `start'
	from /var/app/current/vendor/bundle/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /var/app/current/vendor/bundle/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /var/app/current/vendor/bundle/gems/railties-4.1.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```

**Comment by phstc** [comment]
Hey @rgehring 

Did you upgrade from 0.x to 1.x? The 1.x version contains breaking changes.

**Comment by rgehring** [comment]
Yes, 0.0.5 to 1.0. Reverting to the old version now, you are welcome to close this issue, and thanks for the response. I suppose the docs might need to be updated to reflect whatever the new api is.

**Comment by phstc** [comment]
You are more than right! I will start a CHANGELOG, I believe it will help to keep tracking on the updates.

Just a mentioning about Shoryuken versioning, It's following http://semver.org/ so MAJOR version changes can make incompatible API changes.

**Comment by phstc** [comment]
@rgehring this https://github.com/phstc/shoryuken/commit/a0d4d2560c03e2680221216cef7ced65579b5c12 should add compatibility with older versions of Shoryuken.
