### ISSUE TITLE
Update docs for topics support

### ISSUE THREAD

**Issue by romansanchez** [phstc/shoryuken#97]
I had a use case where I wanted to publish to SNS from a worker. Knowing the worker itself already creates a SQS client, but didn't know if SNS was supported I had to look through the source. Would be nice if it's explicitly documented to show there's support to publish to SNS topic from worker using the same AWS Client. Let me know if I can help with this.

**Comment by phstc** [comment]
Hey @romansanchez 

SNS still a hidden feature for Shoryuken, as its main focus is on SQS. But you are right, if it's available, let's make it public. 

How are you using SNS with Shoryuken? Only `Shoryuken::Client.sns.publish`?

https://docs.aws.amazon.com/sdkforruby/api/Aws/SNS/Client.html

**Comment by romansanchez** [comment]
Yeah, just like that.

**Comment by phstc** [comment]
@romansanchez done https://github.com/phstc/shoryuken/wiki/SNS-Topics :smile: 

Could you review it? Please let me know if there's anything else you wanna add to it that can help other users.

**Comment by romansanchez** [comment]
Looks good, I'm sure it'll help others!
