### ISSUE TITLE
Inconsistent Log Format

### ISSUE THREAD

**Issue by zakcrawford** [phstc/shoryuken#98]
__The Use Case__
I am unifying logs from a variety of sources into a single indexed source (elasticsearch).

__The Problem__
Parsing the format of the logs from shoryuken into key value pairs is proving to be a problem.
The format of the meta-data is easy to understand and parse, but the fact that the context is optional, and when not present has no placeholder, makes the regex to parse the log a bit heavy.

###### Log Format
```Ruby
"#{time.utc.iso8601} #{Process.pid} TID-#{Thread.current.object_id.to_s(36)}#{context} #{severity}: #{message}\n"
```
###### Regex to parse messages with context
```Ruby
/^(?<time>[^ ]*) (?<pid>[^ ]*) TID-(?<thread_id>[^ ]*) (?<context>[^ ]*) (?<severity>[A-Z]*): (?<message>.*)$/
```

###### Regex to parse messages without context
```Ruby
/^(?<time>[^ ]*) (?<pid>[^ ]*) TID-(?<thread_id>[^ ]*) (?<severity>[A-Z]*): (?<message>.*)$/
```

###### Regex to handle either
```Ruby
/(?<time>[^ ]*) (?<pid>[^ ]*) TID-(?<tid>[^ ]*)( )?(?<worker_class>.*?)((/(?=[a-z]))| )(?<queue>[^/]*)(/)?(?<sqs_message_id>.*)(?<severity>(INFO|WARN|DEBUG|ERROR)): (?<message>.*)/ 
```

__A Solution__
The easy way out is to simply put a space between the TID and the context, the downside is that the there will be a double space if no context is present, the upside is that it makes it much easier to handle it being there some times and not others.

A more involved solution could be to split the manager logging (no context) from the worker logging (server timing middleware, with context) so that they could be moved to write to separate locations without altering source code.

Also, given the fact that the context is always `"ActiveJob/#{WorkerClass}/#{queue_name}/#{sqs_msg_id}"` I think it might make sense to separate these items

**Comment by phstc** [comment]
Hey @zakcrawford 

I'm in with the idea. Could you submit a PR, pls? It would help me to understand your solution.

It only appends `ActiveJob` if it's an `ActiveJob` worker: 
https://github.com/phstc/shoryuken/blob/af126a190a161aea77c9e30d1996f0796e5135d1/lib/shoryuken/util.rb#L33

**Comment by zakcrawford** [comment]
Closing this for now, the regex I wrote handles my immediate needs.
I'll come back to it when I have the time.
