### ISSUE TITLE
ElasticBeanstalk Web Server / Worker environments

### ISSUE THREAD

**Issue by ncherro** [phstc/shoryuken#99]
In an ElasticBeanstalk application, Web Server instances send messages to SQS, and Worker instances consume SQS messages and process jobs (right?)

Assuming the same codebase is deployed to both Web Server and Worker environments (like Heroku), is there a way to ensure that *only* Worker instances consume messages and process jobs?

**Comment by farski** [comment]
As long as you're not starting up the Shoryuken processor you can be sure it won't be taking anything from SQS. There are some tradeoffs if you chose the worker instance over Shoryuken for processing, though, like being able to use multiple queues with different priorities. I believe the worker instance is tied to a single queue.

**Comment by ncherro** [comment]
@farski thanks for the explanation, makes sense to only run Shoryuken on instances that should be consuming messages / processing jobs, but I'm a little confused about this:

"There are some tradeoffs if you chose the worker instance over Shoryuken for processing"

Would you recommend not using Worker instances at all - just running Shoryuken on Web Server instances?

**Comment by farski** [comment]
@ncherro It's really up to you. If you don't want to have to worry about getting the shoryuken processor running, and AWS is offering one for free, it may make sense to use the Worker Instance. If you need to utilize multiple queues or queue priorities, you'll have to run the processor. You could do that on a Web Instance, or you could use a Worker Instance and just ignore the built in functionality (give it a bogus queue to monitor); I don't know off the top of my head what kind of impact the daemon EB runs on those instances has, if they aren't actually anything. One would think it is pretty minimal.

**Comment by ncherro** [comment]
@farski great, thanks again. I think I have the info I need to move forward. :+1:
